### ISSUE TITLE
Seeing deadlock in HostInfo when node goes down

### ISSUE THREAD

**Issue by wfanzju** [gocql/gocql#1003]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[cqlsh 5.0.1 | Cassandra 3.0.14.4 | CQL spec 3.4.0 | Native protocol v4]

### What version of Gocql are you using?
- name: github.com/gocql/gocql
  version: 77431609f517cb41ee9afdcdd373561c4d935316
  subpackages:
  - internal/lru
  - internal/murmur
  - internal/streams

### What did you do?
Writes to cassandra cluster when one node goes down

### What did you expect to see?
fail fast on bad nodes

### What did you see instead?
Tens of thousands goroutines are blocked at acquiring RLock in HostInfo.State 

---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

I have put the gocql related goroutine profile in attachment.
[profile.txt](https://github.com/gocql/gocql/files/1416612/profile.txt)

**Comment by Zariel** [comment]
this is fixed in https://github.com/gocql/gocql/commit/605a5e0a265c95891d9159dae6030ea195b4a3bd
