### ISSUE TITLE
gocql no longer recovers session

### ISSUE THREAD

**Issue by nlacey** [gocql/gocql#1005]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11

### What version of Gocql are you using?
latest

### What did you do?
stopped cassandra, and restarted cassandra

### What did you expect to see?
I expected the session to start working, as soon as cassandra was available
This was the case with code built on Monday

The problem started when pulling newest changes today

### What did you see instead?
The session never became usable
error
no hosts available in the pool
---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

single node cassandra

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by nejordan15** [comment]
I am going to be updating the version of gocql that is being used in our app. Currently using:
```
"revision": "77431609f517cb41ee9afdcdd373561c4d935316",
"revisionTime": "2017-08-05T14:11:44Z"
```
I have a cass cluster running with 4 data centers and for the apps, I have the gocql client configured with a data center filter, to be the local dc to the running app.
I have seen issues where the client hangs on all calls (seemingly forever) when a node in the data center goes down and/or is restarted.  Only and every app with a gocql client configured to talk to the dc that had a node go down was hanging (for over a day). Restarting the apps with the same config resolved the problem (so likely just creating a new session). I have only seen this issue a couple times, so I am trying to narrow down the problem.
I haven't seen an issue that describes my problem exactly, so was wondering if/how the issue I am describing was resolved. Could have been with #1006
