### ISSUE TITLE
Non-default port on clusterConfig.Hosts is ignored

### ISSUE THREAD

**Issue by calvn** [gocql/gocql#1007]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
From cqlsh: [cqlsh 5.0.1 | Cassandra 3.10 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
(7fabcab850b7eade1d0e0ac5ac0b6b66d6801a75) and (afe4fee3ded9a8e20b174f88e3d9b6ed30ad4d66)

### What did you do?
Attempt to create a new session to a Cassandra host with a non-default port

### What did you expect to see?
Successful call on `cluster.CreateSession()`

### What did you see instead?
`no connections were made when creating the session`

---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

Single node, so system.peers is empty. This is the info from system.local:

```
cassandra@cqlsh> SELECT listen_address, rpc_address, broadcast_address FROM system.local;

 listen_address | rpc_address | broadcast_address
----------------+-------------+-------------------
     172.17.0.2 |     0.0.0.0 |         127.0.0.1
```

#### Failure case:
```go
package main

import (
	"fmt"

	"github.com/gocql/gocql"
)

func main() {
	clusterConfig := gocql.NewCluster("127.0.0.1:32794")
	clusterConfig.Authenticator = gocql.PasswordAuthenticator{
		Username: "cassandra",
		Password: "cassandra",
	}
	clusterConfig.ProtoVersion = 4

	fmt.Printf("cluster config: %+v\n", clusterConfig)

	_, err := clusterConfig.CreateSession()
	if err != nil {
		panic(err)
	}

	fmt.Println("cassandra init done")
}
```

Output:
```
go run main.go
cluster config: &{Hosts:[127.0.0.1:32794] CQLVersion:3.0.0 ProtoVersion:4 Timeout:600ms ConnectTimeout:600ms Port:9042 Keyspace: NumConns:2 Consistency:QUORUM Compressor:<nil> Authenticator:{Username:cassandra Password:cassandra} RetryPolicy:<nil> SocketKeepalive:0s MaxPreparedStmts:1000 MaxRoutingKeyInfo:1000 PageSize:5000 SerialConsistency:UNKNOWN_SERIAL_CONS_0x0 SslOpts:<nil> DefaultTimestamp:true PoolConfig:{HostSelectionPolicy:<nil>} ReconnectInterval:1m0s MaxWaitSchemaAgreement:1m0s HostFilter:<nil> AddressTranslator:<nil> IgnorePeerAddr:false DisableInitialHostLookup:false Events:{DisableNodeStatusEvents:false DisableTopologyEvents:false DisableSchemaEvents:false} DisableSkipMetadata:false disableControlConn:false}
panic: no connections were made when creating the session

goroutine 1 [running]:
main.main()
	/Users/cleung/code/cassandra-gocql/main.go:21 +0x237
exit status 2
```

#### Success case:
```go
package main

import (
	"fmt"

	"github.com/gocql/gocql"
)

func main() {
	clusterConfig := gocql.NewCluster("127.0.0.1:32794")
	clusterConfig.Authenticator = gocql.PasswordAuthenticator{
		Username: "cassandra",
		Password: "cassandra",
	}
	clusterConfig.ProtoVersion = 4
	clusterConfig.Port = 32794

	fmt.Printf("cluster config: %+v\n", clusterConfig)

	_, err := clusterConfig.CreateSession()
	if err != nil {
		panic(err)
	}

	fmt.Println("cassandra init done")
}
```

Output:
```
go run main.go
cluster config: &{Hosts:[127.0.0.1] CQLVersion:3.0.0 ProtoVersion:4 Timeout:600ms ConnectTimeout:600ms Port:32794 Keyspace: NumConns:2 Consistency:QUORUM Compressor:<nil> Authenticator:{Username:cassandra Password:cassandra} RetryPolicy:<nil> SocketKeepalive:0s MaxPreparedStmts:1000 MaxRoutingKeyInfo:1000 PageSize:5000 SerialConsistency:UNKNOWN_SERIAL_CONS_0x0 SslOpts:<nil> DefaultTimestamp:true PoolConfig:{HostSelectionPolicy:<nil>} ReconnectInterval:1m0s MaxWaitSchemaAgreement:1m0s HostFilter:<nil> AddressTranslator:<nil> IgnorePeerAddr:false DisableInitialHostLookup:false Events:{DisableNodeStatusEvents:false DisableTopologyEvents:false DisableSchemaEvents:false} DisableSkipMetadata:false disableControlConn:false}
cassandra init done
```

Note that on the failure case, `clusterConfig.Port = 9042`. Even though a non-default is provided a part of host, the session creation does not seem to use the value from `address:port` in `clusterConfig.Hosts`. Older revisions (e.g. f8b6dca), however, did correctly set `clusterConfig.Port` to the port of that was provided as part of the host, if `clusterConfig.Port` was not explicitly set. 

### Docker instance
```
$ docker run --name some-cassandra -d -P -e CASSANDRA_BROADCAST_ADDRESS=127.0.0.1 cassandra
6d3b72d19ce0b3467e38b5bfff1b59fb2a33b566638d7ecc318b520b06a7e90b

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS              PORTS                                                                                                                         NAMES
6d3b72d19ce0        cassandra           "/docker-entrypoin..."   Less than a second ago   Up 3 seconds        0.0.0.0:32797->7000/tcp, 0.0.0.0:32796->7001/tcp, 0.0.0.0:32795->7199/tcp, 0.0.0.0:32794->9042/tcp, 0.0.0.0:32793->9160/tcp   some-cassandra
```

The `` `pwd`/cassandra/cassandra.yaml`` file that gets mounted is simply a standard config that ensures the authenticator is set to `PasswordAuthenticator` to avoid the `You have to be logged in and not anonymous to perform this request` error.

### Related references
https://github.com/gocql/gocql/issues/946
https://github.com/hashicorp/vault/issues/3467

**Comment by Zariel** [comment]
The issue here is that the HostInfo is updated from the cassandra table and needs a default port which we set to the one supplied in the config, even if the control connection was created by parsing the addr string which extracts a correct port.
