### ISSUE TITLE
NewSession() error due to missing datacenter info

### ISSUE THREAD

**Issue by wfanzju** [gocql/gocql#1011]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[cqlsh 5.0.1 | Cassandra 3.0.14.4 | CQL spec 3.4.0 | Native protocol v4]

### What version of Gocql are you using?
f5cee644705e9593c342bfabe667720580a5289f

### What did you do?
Trying to connect to cassandra cluster with DataCentreHostFilter setup.

### What did you expect to see?
Should succeed

### What did you see instead?
Got error "gocql: unable to create session: control: no endpoints specified"

From session.go line 158
addrsToHosts only fills in HostInfo with ip and port number. 
However, in line 168, no hosts will be able to pass DataCentreHostFilter since there's no DC info been set yet.

```
func (s *Session) init() error {
	hosts, err := addrsToHosts(s.cfg.Hosts, s.cfg.Port)
	if err != nil {
		return err
	}
	allHosts := hosts
	hosts = hosts[:0]
	hostMap := make(map[string]*HostInfo, len(allHosts))
	for _, host := range allHosts {
		if !s.cfg.filterHost(host) {
			hosts = append(hosts, host)
			hostMap[host.ConnectAddress().String()] = host
		}
	}
	s.ring.endpoints = hosts
	if !s.cfg.disableControlConn {
		s.control = createControlConn(s)
		...
		if err := s.control.connect(hosts); err != nil {
			return err
		}
        }
}
```

---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by palaiyacw** [comment]
@wfanzju I am also getting the same issue. Any updates on it?
