### ISSUE TITLE
NullPointerException when querying a table with a previous state

### ISSUE THREAD

**Issue by eyeofthefrog** [gocql/gocql#1017]
I'm getting an NPE from Cassandra. I've opened the following bug for them to fix that:
https://issues.apache.org/jira/browse/CASSANDRA-13991

They seem to think it's due to gocql sending a null state during the query. The following project can be used to recreate the issue:
https://github.com/eyeofthefrog/CASSANDRA-13991

### What version of Cassandra are you using?
3.11.1

### What version of Gocql are you using?
93711fb9002b469d61ae13ed615441c5e57c1da1

### What did you do?
* With a table of 12 entries, read all rows.
* Set the page size to 1 and read the first row. Save the query state.
* Read all the rows again.
* Set the page size to 5 and the page state to the previous state. (This is where the NPE occurs).

### What did you expect to see?
5 results

### What did you see instead?
NPE from Cassandra, and no results.

**Comment by eyeofthefrog** [comment]
Thanks, that fixed my issue.

**Comment by eyeofthefrog** [comment]
Thanks, this fixed it for me.

**Comment by Zariel** [comment]
Thanks for the report and repro!
