### ISSUE TITLE
Storing a map of type map[string]interface{} as one field

### ISSUE THREAD

**Issue by rajibmaitra** [gocql/gocql#1019]
I am new to golang and cassandra. I am trying to store a 'map' in cassandra as a single entity. 

I have a Table defined as:

CREATE TABLE keysp.maptable (
                id timeUUID,
                col2 text,
                mapfld map<varchar,varchar>,
                PRIMARY KEY(id, col2) );

If I define the function as below and pass a map of 'string and []byte' then it works.

func updateCassandraDB(mapblob map[string]map[string][]byte, pkey string) error {
                //define host, keyspace, cluster
                pkey := "1234560002C"
                 //insert the map
                if err := session.Query("INSERT INTO keysp.maptable(id,mapfld, col2) VALUES (?, ?, ?)", gocql.TimeUUID(), mapblob, pkey).Exec(); err != nil {
                                log.Fatal(err)
                }

However, I need to store a map, where key is string and value will be any type. SO I redefined the first parameter of the function to map[string]interface{}

(as below) and passed the mapblob, which is a map of 200 key-value pair and the values are of different types like integer, string etc.

func updateCassandraDB(mapblob map[string]interface{}, keyStr string) error {

Then inserting the mapblob is failing as :  can not marshal int into varchar

I think I have defined the mapfld as map<varchar, varchar> and I have an integer, it is failing. But How do I solve this issue?

Is there anyway to store the entire map as one field, where the map is map[string]interface{} ?

**Comment by Zariel** [comment]
Why dont you make the map `map[string]string` and convert the int to a string?

**Comment by rajibmaitra** [comment]
Oh, I thought about that but problem is I have 1000 of fields and different types of types.
What I did, I marshaled to JSON, and converred JSON to string. Then saved as VARCHAR (text).
I really don’t want too much overhead of processing just to store it in to the database.

Thanks for your input though.
