### ISSUE TITLE
Wrong implementation of HostPoolHostPolicy

### ISSUE THREAD

**Issue by JerryKwan** [gocql/gocql#1021]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[cqlsh 5.0.1 | Cassandra 3.11.0 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
The most recent checked out from this repository

### What did you do?
When i use HostPoolHostPolicy to restrict which hosts will be used for the following operations not all of the nodes in the cluster, because there was some bad network issues for some nodes , the following is the snippets i used
cluster.PoolConfig.HostSelectionPolicy = gocql.HostPoolHostPolicy(hostpool.New([]string{ "192.168.1.1", "192.168.1.2"}))
and suppose there was some more nodes in the cluster, such as "192.168.1.3", "192.168.1.4"

### What did you expect to see?
supposed the gocql will select nodes in the hostpool specified, which will be some one in  "192.168.1.1", "192.168.1.2" at most of the time , and if "192.168.1.1", "192.168.1.2" all lost connection, try to use the other nodes (such as "192.168.1.3", "192.168.1.4" ). Maybe we should remember which hosts are passed by HostPoolHostPolicy and which are nodes found in the cluster, just like DCAwareRoundRobinPolicy to remember locolhosts and remoteHosts

### What did you see instead?
seems like gocql only use the hosts specified in HostPoolHostPolicy at the first time when refreshRing() in host_source.go, and all of the nodes have been replaces by the hosts from " SELECT * FROM system.peers", that is to say all of the nodes, and then select host in a roundrobin manner
---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
As stated in the docs the HostPool will be populated by all hosts which are discovered by Gocql, 

> When creating the host pool that is passed to the policy use an empty slice of hosts as the hostpool will be populated later by gocql.

To limit which hosts are added use a HostFilter https://godoc.org/github.com/gocql/gocql#HostFilter

**Comment by JerryKwan** [comment]
@Zariel Yes, we can use HostFilter to do some validation, but that is just a whitelist or blacklist operation.
The main problem with HostPoolHostPolicy is that it does not work as expected, it will populate the hosts not matter we pass an empty list or not. As the snippets demonstrated we passed a non-empty list, but it still used the hosted collected by gocql itself. 
I think it will appropriate if it works as the following:
1, remember the hosted passed by HostPoolHostPolicy in a variable such as hosts
2, remember all of the hosted in the cluster except the passed hosts in a variable such as peers
3, try to used the host in hosts, if none of them works, then degrade to use the host in peers
To be honest, the current implementation of HostPoolHostPolicy  is useless
