### ISSUE TITLE
Allow for treating initial startup the same as a disconnection/outage of Cassandra post-startup

### ISSUE THREAD

**Issue by rbtcollins** [gocql/gocql#1027]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3

### What version of Gocql are you using?
4d2d1ac71932f7c4a6c7feb0d654462e4116c58b

### What did you do?
Tried to start a jaegertracing collector when Cassandra happened to be transiently unavailable.

### What did you expect to see?
the collector startup 

### What did you see instead?
the collector fail to startup and its pod go into a hard Error state.

See https://github.com/jaegertracing/jaeger/issues/562 where I was pointed at gocql as being the limit in fixing this known issue.
---

If you are having connectivy related issues please share the following additional information
`###                               ^ you have a typo in your template, the word 'connectivity'`

**Comment by fastest963** [comment]
This seems similar to https://github.com/gocql/gocql/issues/1365. With the changes in https://github.com/gocql/gocql/pull/1369 you'll be able to customize (with a `ReadyPolicy`) when you want to consider the session "ready" which can be with 1 host or no hosts or any number of hosts.

**Comment by martin-sucha** [comment]
It indeed seems that this is the same issue as #1365 and it should be possible to implement the desired behavior with a ReadyPolicy. Closing. Please reopen if there is any issue with using the ReadyPolicy.
