### ISSUE TITLE
New Feature: support password protected PEM files

### ISSUE THREAD

**Issue by mildebrandt** [gocql/gocql#1028]
Create a new member of the SslOptions struct to provide a password for the PEM file.

**Comment by martin-sucha** [comment]
Users can already provide custom [tls.Config](https://pkg.go.dev/crypto/tls#Config), so keys/certificates can be provided from any source the user wants. There is no need to add more wrappers for building `tls.Config` to gocql, that is outside the scope of gocql and can be implemented in an external package.
