### ISSUE TITLE
Column types returned by KeyspaceMetadata are always of Type: (gocql.NativeType)

### ISSUE THREAD

**Issue by enjoylife** [gocql/gocql#1030]
I was trying to leverage the `UDTTypeInfo` for each of my user defined types, but to my surprise all columns types come across as the generic `NativeType`.
Is this expected? Anyone run across or solved something similar?

### What version of Cassandra are you using?
3.4.4

### What version of Gocql are you using?
master

### What did you do?
```
md, err := s.KeyspaceMetadata(keySpace)
	if err != nil {
		fmt.Errorf("keyspace metadata error", err)
		return
	}


	for _, table := range md.Tables {
		for _, col := range table.Columns {
			spew.Dump(col)
		}
	}
```

### What did you expect to see?
Expected to see column types vary based on their actual types

### What did you see instead?
`Type: (gocql.NativeType)` across all columns

**Comment by carebdayrvis** [comment]
From looking through the source, each returned column type is wrapped in NativeType. That struct has a Type method to get the underlying type.

**Comment by Zariel** [comment]
I've got a fix for this just need to write some tests to cover it.
