### ISSUE TITLE
Query from queryPool never put back.

### ISSUE THREAD

**Issue by Rcio** [gocql/gocql#1038]
Every time query with a session, it will get a Query object from a global queryPool, but I can't find where it will be put back. Is that a leak?

```golang
func (s *Session) Query(stmt string, values ...interface{}) *Query {
	s.mu.RLock()
	qry := queryPool.Get().(*Query)
```

**Comment by nussjustin** [comment]
The query is returned to the pool when you call Release: https://github.com/gocql/gocql/blob/master/session.go#L1017

You can use [Sourcegraph](https://sourcegraph.com/github.com/gocql/gocql@59441a623b364472525164bb62b6da9d552eb2ca/-/blob/session.go#L308:9$references) to see all references to the pool.

**Comment by Rcio** [comment]
@nussjustin thank you for reply.

Yes, I saw that. So I need to call Release on a query object by self?
The example in readme page uses query directly with a Exec or Iter function, like this:

```golang
if err = session.Query("use example2").Exec(); err != nil {
	log.Fatal(err)
}
```

Seems no need to release it, and it will leak.

**Comment by nussjustin** [comment]
Yes and no. You should call Release each time you are done with a query, but you don't have to. Since a query holds no resources, calling Release is just an optimization to avoid allocations.

**Comment by Zariel** [comment]
As @nussjustin this is an optimisation incase the allocations of Query affect the performance of your application, using release will reuse Query structs between GC cycles.
