### ISSUE TITLE
Session Pool vs. Connection Pool? Keep sessions open -> pool -> reuse? 

### ISSUE THREAD

**Issue by hartmut-co-uk** [gocql/gocql#1048]
### What version of Cassandra are you using?
> cqlsh> show VERSION
> [cqlsh 5.0.1 | Cassandra 3.11.1 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
> [[projects]]
>   branch = "master"
>   name = "github.com/gocql/gocql"
>   packages = [".","internal/lru","internal/murmur","internal/streams"]
>   revision = "6c01199a66689472d8fab787edda1edefc0f4a79"

### What did you do?
Follow example, look into connectionpool

### What did you expect to see?
Example / documentation on how open sessions can/should be kept in a pool - so not creating sessions for each request - which seems too much overhead and way to slow to me?
```
	session, _ := cqlcluster.CreateSession()
	defer session.Close()
```

### What did you see instead?
New session created/closed for each operation.

What's the general usage strategy / any recommendations?

**Comment by Zariel** [comment]
The session maintains connection pools to each host in the Cassandra cluster so you only need one session per application/

**Comment by hartmut-co-uk** [comment]
Perfect, that wasn't quite clear.. Many thanks!

**Comment by hobbs** [comment]
is it thread safe to share the same session among threads?

**Comment by Zariel** [comment]
Yes

**Comment by kokizzu** [comment]
i think this should be on `README.md` :3
