### ISSUE TITLE
when add a column, select * got some empty value

### ISSUE THREAD

**Issue by btfak** [gocql/gocql#1056]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.9 

### What version of Gocql are you using?
https://github.com/gocql/gocql/tree/1762cce65eafd098045e30ef2b7df2c289740971

What did you do?
add a column to a table, this table has 100* 1000 * 1000 records on 5 nodes.

I use select * in my code.

```
iter := Cassandra.Query("SELECT * FROM message WHERE id IN ?", messageIDs).Iter()
	for {
		row := make(map[string]interface{})
		if !iter.MapScan(row) {
			break
		}
       }
```

### What did you expect to see?
select correct value.

### What did you see instead?
some fields value is empty (0 for int, "" for string).
I guess the  root cause is "select * "
this table's column like this
A B C D
when add a column X between A and B
A X B C D
I can got correct A , but B / C / D's value is empty.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
Does it reproduce on latest master?

**Comment by btfak** [comment]
not yet reproduce on latest master.
rarely happen, only when  a column is adding to a big table, just a few second. I have some guess:
```
func Unmarshal(info TypeInfo, data []byte, value interface{}) error
```
the first info param hold the original table info, but data point to new added field, so can't unmarshal corect, just get empty value.
![image](https://user-images.githubusercontent.com/2741940/35777030-b7b6486a-09e1-11e8-8d93-07f8a3a86592.png)


also can explain drop column case.
![image](https://user-images.githubusercontent.com/2741940/35777034-be765f14-09e1-11e8-8ab1-3fc1f36b3f1a.png)

does is reasonable?

**Comment by Zariel** [comment]
The TypeInfo is parsed from the response, but the driver is caching the result metadata from the prepare call. Because the query doesn't change the underlying columns do the wrong result metadata is used. I'm not sure what we can do in this case, really Cassandra should either invalidate the prepared statement when the underlying schema changes for a query so that we get the same value. 

We could also flush the prepared metadata cache when we get schema change events which would prevent this from occurring, or at least reduce its likelihood of doing so.

**Comment by btfak** [comment]
thanks Zariel, on production environment we never drop column. But we will add column, I want to make sure it , if we specify columns , not using `select *`, use 
```
select A,B,C,D from message ...
```
even if we add a column X , I believe this sql still work correct, am I right ?

**Comment by Zariel** [comment]
Yep that will solve it, you can also use the wildcard select and enable `NoSkipMetadata` on the query https://github.com/gocql/gocql/blob/dd47639f787e8583e1a13e17e20a9f6c4332bc29/session.go#L941
