### ISSUE TITLE
date type causing panic in MapSelect call

### ISSUE THREAD

**Issue by stevef1uk** [gocql/gocql#1057]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.1

### What version of Gocql are you using?
? How does one build this repo from github? I used go get github.com/gocql/gocql today

### What did you do?
I am trying to work out what type I need to reflect data types so wrote a test programme 

My simple schema for the test

        CREATE TYPE city (
            id int,
            citycode text,
            cityname text
        );

        CREATE TABLE employee (
            id int PRIMARY KEY,
            name text,
            mydate date,
            address_set frozen<set<frozen<city>>>

    The select is:
rawResult := map[string]interface{}{}
        err := session.Query(`SELECT id, name, mydate,  address_set FROM employee WHERE id = ?`, id).MapScan(rawResult)

### What did you expect to see?
Not a panic . I wanted to know the type that came back if the date field was included. There is no panic if I exclude the date column

### What did you see instead?
```
panic: reflect: New(nil)

goroutine 1 [running]:
reflect.New(0x0, 0x0, 0x0, 0x0, 0xc4200bda08)
	/usr/local/go/src/reflect/value.go:2148 +0xde
github.com/gocql/gocql.NativeType.New(0xc4200bda04, 0x11, 0x0, 0x0, 0xc420102220, 0xc420100070)
	/Users/stevef1/Source_Code/go/src/github.com/gocql/gocql/marshal.go:1803 +0x92
github.com/gocql/gocql.(*NativeType).New(0xc420102140, 0xc420100060, 0x1)
	<autogenerated>:1 +0x56
github.com/gocql/gocql.(*Iter).RowData(0xc420126120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200bdd10, 0x1209531)
	/Users/stevef1/Source_Code/go/src/github.com/gocql/gocql/helpers.go:218 +0x561
github.com/gocql/gocql.(*Iter).MapScan(0xc420126120, 0xc420082ff0, 0xc4200d6b00)
	/Users/stevef1/Source_Code/go/src/github.com/gocql/gocql/helpers.go:259 +0x6e
github.com/gocql/gocql.(*Query).MapScan(0xc4200d6b00, 0xc420082ff0, 0x40, 0xc42007eb60)
	/Users/stevef1/Source_Code/go/src/github.com/gocql/gocql/session.go:931 +0x71
main.main()
	/Users/stevef1/Source_Code/go/src/github.com/stevef1uk/cassandragenrest-Data-Test/data/main5.go:58 +0x1f3
```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
can you update to the latest master version and test again please

**Comment by stevef1uk** [comment]
Yes, if you can tell me how to build the latest version from the github repo? I have cloned it but don't know how to build it ;-)

**Comment by Zariel** [comment]
go get -u github.com/gocql/gocql

**Comment by stevef1uk** [comment]
Thanks. Fixed
