### ISSUE TITLE
iter.NumRows() and iter.MapScan(m) have different counts

### ISSUE THREAD

**Issue by prats226** [gocql/gocql#1059]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[cqlsh 5.0.1 | Cassandra 3.10 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
``` json
{
	"ImportPath": "github.com/gocql/gocql",
	"Comment": "pre-node-events-568-gaa93acc",
	"Rev": "aa93acc8f067e9233982b9a7de370e4d64b9c33e"
}
```

### What did you do?
```go
a = make([]A, iter.NumRows())
var i := 0
for iter.MapScan(m) {
    j, err := json.Marshal(m)
    err = json.Unmarshal(j, &a[i])
    i++
}
```

### What did you expect to see?
Code should not panic since number of rows should be equal to number of elements in mapscan

### What did you see instead?
Panic
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
That row count is the number of rows in the current frame

**Comment by martin-sucha** [comment]
We already have

```go
// NumRows returns the number of rows in this pagination, it will update when new
// pages are fetched, it is not the value of the total number of rows this iter
// will return unless there is only a single page returned.
```

as docs for `*Iter.NumRows`. I don't see what else should we change in the documentation.
