### ISSUE TITLE
no response received from cassandra within timeout period When a node goes down.

### ISSUE THREAD

**Issue by shreyasns** [gocql/gocql#1067]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11

### What version of Gocql are you using?
commit hash 33a5f3c1bcc2c421b3221c5858312afb141bf605

### What did you do?
I was testing how the application behaves when a cassandra node goes down.

### What did you expect to see?
I expected it to handle the broken connections gracefully

### What did you see instead?
It was timing out requests.
---

It looks like when a host goes down it's not detecting that the host is down and timing out. I did this 3 times and during all the times I exactly got 23 timeouts. Not sure if I'm interpreting something wrongly.

**Comment by Zariel** [comment]
please test on the latest master
