### ISSUE TITLE
Support of downgrading consistency retry policy

### ISSUE THREAD

**Issue by changliuau** [gocql/gocql#1070]
Hi there - I am new to the community and trying to contribute to the project. 

We are looking into adding 'downgrading consistency policy' as a new `RetryPolicy`. It is already implemented in the Python driver and Java driver for Cassandra. The core algorithm in Python driver's implementation looks like this: (http://datastax.github.io/python-driver/api/cassandra/policies.html#cassandra.policies.DowngradingConsistencyRetryPolicy)

```
    def _pick_consistency(self, num_responses):
        if num_responses >= 3:
            return self.RETRY, ConsistencyLevel.THREE
        elif num_responses >= 2:
            return self.RETRY, ConsistencyLevel.TWO
        elif num_responses >= 1:
            return self.RETRY, ConsistencyLevel.ONE
        else:
            return self.RETHROW, None
```

although they do slightly different things for `read_timeout`, `write_timeout` and `unavailable`, essentially it will get the number of replicas returned from the failed response, and adjust the consistency level for the retry based on this number.

Another way of doing it is to based on the current consistency level of the query, e.g., if the consistency level is `QUROM` and the query failed, try `LOCAL QUROM` in the next retry, and then `THREE` etc. The code change could be a lot smaller this way as there is already a function `GetConsistency()` in `RetryableQuery` interface.

So the questions I have are:

1. In the first way (ie the one similar to Python/Java driver), we will need to get the number of replicas returned from a query and therefore analyse the query failure response. Is there a easy way of doing that in `gocql`? Looks like it is not used in `policies.go` at this point. 
2. Which of the 2 ways do you guys think is better?

Note: it's a bit controversial whether the driver should be handling something like this. In Java driver it's deprecated and going to be removed in the next major version -- because people think this is something that should be handled by the application rather than the driver. The commit has just been made yesterday.  https://github.com/datastax/java-driver/commit/f5d44d3fea093a5c28d59ba0f587e9044e161813

Thanks in advance for any input.

Regards,
Chang

**Comment by kgreav** [comment]
@robusto This always made more sense to me. I'm not surprised the java driver has deprecated it, because frankly the implementation is a bit useless. Especially when you consider cases of RF=5. I'd be in favour of the user being able to select what consistency they downgrade to, it also makes much more sense in the case of multiple DC's. 

EG: 2 DC's (A and B) RF 3 in both DC's. B goes offline and you configure your application to automatically downgrade from QUORUM to LOCAL_QUORUM (at the moment you'd have to do some extra work to change the DC w.r.t load balancing). Downgrading from QUORUM to ONE or TWO in this case doesn't make sense at all.

This implementation would also be much more straightforward too.

**Comment by robusto** [comment]
The RetryableQuery interface doesn't have the ability to signal the ExecutableQuery to change its CL; it can only retrieve CL. We need the retry process to support changing the CL of the query called in the retry loop of the query executor which means this will require changing the query execution path.

Interesting @kgreav Did not know it was being deprecated.

**Comment by shettyh** [comment]
Is there something still pending for this enhancement ? or This feature can be used already ?

**Comment by alourie** [comment]
@shettyh seems pretty ready to me. Is there anything specific you miss in the implementation?

**Comment by alourie** [comment]
I'm actually closing this. Will reopen if needed.
