### ISSUE TITLE
Keep timezone

### ISSUE THREAD

**Issue by diegobernardes** [gocql/gocql#1071]
### What version of Cassandra are you using?
3.11.1

### What version of Gocql are you using?
2e9f2912ba58e37f34af3554659b576eac655760

### What did you do?
Insert a `time.Time` on a column that is a `timestamp`.

### What did you expect to see?
The timezone.

### What did you see instead?
UTC timezone.

I took a look at the source code and the conversion to UTC is fixed: https://github.com/gocql/gocql/blob/1303a32993a1242a6fb58dc497a3b8a54ffd257d/marshal.go#L1151

**Comment by annybs** [comment]
We've just run into this as well. The current code appears to still enforce conversion to UTC: https://github.com/gocql/gocql/blob/87a5d7a5ff74ffa9eb716f05f6e26191836bf03d/marshal.go#L1329-L1371

For the time being we may just work around it by storing the timezone in a separate column and converting it clientside. Just wanted to add a +1 to this issue. Thanks!

**Comment by martin-sucha** [comment]
Cassandra does not store timezone information for a `timestamp` data type, so there is nothing we can do on gocql side. See [Working with timestamps](https://cassandra.apache.org/doc/latest/cql/types.html#working-with-timestamps) in Cassandra documentation or [timestamp](https://github.com/apache/cassandra/blob/3bcab600edcd8428f19b89f10d48a09f447e6715/doc/native_protocol_v4.spec#L946-L950) type description in CQL protocol specification for more details.

For example:

```
cqlsh> CREATE KEYSPACE cycling
   ...   WITH REPLICATION = { 
   ...    'class' : 'SimpleStrategy', 
   ...    'replication_factor' : 1 
   ...   };
cqlsh> use cycling;
cqlsh:cycling> create table finish_time (name text, t timestamp, PRIMARY KEY(name));
cqlsh:cycling> update finish_time set t='2021-04-24T01:02:03-0600' where name='John Doe';
cqlsh:cycling> select * from finish_time;

 name     | t
----------+---------------------------------
 John Doe | 2021-04-24 07:02:03.000000+0000

(1 rows)
```

As you said, you can store the timezone name in a separate column.
