### ISSUE TITLE
TCP Write I/O Timeout

### ISSUE THREAD

**Issue by ankit2806** [gocql/gocql#1073]
What version of Cassandra are you using?
5.0

What version of Gocql are you using?
Latest master Repo

What did you do?
I am executing the parameterized query to insert a new row in the table. The column datatype is TEXT. When the size of the value of column is upto 65535, the record is inserted but when the size is increased I get the error:
**tcp write HOST_IP >> CASS_IP i/o timeout**

Actions Taken:
1) Increased the batch size in cassandra.yaml
2) Increased the tcp rmem.max and wmem.max values to 8 MB.

These changes did not affect the functionality. Is there any other change required?

Thanks
Ankit

**Comment by Zariel** [comment]
Have you tried increasing the gocql timeout?

**Comment by ankit2806** [comment]
Yeah, that worked. Thanks.
