### ISSUE TITLE
Difference between a null column (does not exist) and a column containing an empty string

### ISSUE THREAD

**Issue by rgcooper53** [gocql/gocql#1074]
Please answer these questions before submitting your issue. Thanks!

### What did you see instead? as stated in "what did you do?" section. 

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
Does using a double pointer work?

**Comment by martin-sucha** [comment]
We have this documented at https://pkg.go.dev/github.com/gocql/gocql#hdr-Nulls . Closing.
