### ISSUE TITLE
Speculative query execution

### ISSUE THREAD

**Issue by rdelval** [gocql/gocql#1083]
Sorry if this has been discussed before, I looked through the code, previous issues, and PRs but didn't find anything related.

We're looking to leverage speculative query execution (https://docs.datastax.com/en/developer/java-driver/3.4/manual/speculative_execution/)

Is there a way of achieving the same behavior with with gocql?

**Comment by alourie** [comment]
So to be able to implement this feature, we first need to implement [Query Idempotancy](https://docs.datastax.com/en/developer/java-driver/3.4/manual/idempotence/). I've created a new ticket for it at #1087 and started working on this feature.
