### ISSUE TITLE
Implement Query Idempotancy

### ISSUE THREAD

**Issue by alourie** [gocql/gocql#1087]
In order to be able to approach the implementation of the #1083, we need to first implement [Query Idempotancy](https://docs.datastax.com/en/developer/java-driver/3.4/manual/idempotence/), so that the driver will know when it is allowed to perform Speculative queries.

This ticket is the placeholder for this work.

**Comment by alourie** [comment]
I am working on this ticket and will update when there's any progress.

**Comment by alourie** [comment]
@Zariel Just in case you're looking into this, here are my findings:

It is possible to add a field on Cluster and Query that would keep "idempotence" value. This would allow client applications to manually set the value during either query creation or cluster config.

In addition, we could try and write an automatic query parser that would try to detect whether the query is idempotent or not; unfortunately, that would be quite a hard of a task of parsing queries strings, so maybe try it out with super simple use-cases

Alternatively, gocqlx is a good candidate for utilising this work. The Java driver, for example, implements some heuristics in Query Builder, which gocql doesn't have, but gocqlx does. On that note, I was wondering whether the inclusion of gocqlx's Builders in the gocql code would make any sense. If not, and we only implement manual setting/simplistic automated parser here, and then make it work for #1083, I will be able to expand on this work in gocqlx and add the Java-like heuristics there.

**Comment by Zariel** [comment]
I think the driver should just have a flag for idempotency then users can either set it or helper funcs can set it, we would need a query parser or builder to do it ourselves.

**Comment by alourie** [comment]
@Zariel Thanks for the response. I'll then start with just having a flag that users can set. I'll create a separate issue for building query parser, as it's a bit more complex work.

I'll then proceed to work on #1083 to start using the flag itself for Speculative queries and then get back to helper parser. We might benefit from doing both the parser _and_ the Builder, but that's yet to be determined :-)

**Comment by alourie** [comment]
This is already implemented and merged. Closing.
