### ISSUE TITLE
Inserts silently fail when cluster overwhelmed

### ISSUE THREAD

**Issue by hobbs** [gocql/gocql#1091]
### What version of Cassandra are you using?
3.4, official docker image.

### What version of Gocql are you using?
master

### What did you do?
Created a very simple keyspace and table, and then inserted into it very quickly.

### What did you expect to see?
I expected each insert to either succeed or fail, and in the case of failures, I was expecting an `error` returned from Query.Exec().

### What did you see instead?
I got no errors returned from Query.Exec(), however, many inserts failed. In this script it does 50 parallel inserts, I only see 2-5 rows in the table after it completes. If I make it single threaded, I see all 50. I can understand that this single node is overwhelmed, but I'd like to understand how to use gocql/cassandra in a way that will alert me of insert problems.

### Describe your Cassandra cluster
Single node, via `docker run -it -p 9042:9042 cassandra:3.4`

`nodetool status`
Datacenter: datacenter1
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  172.17.0.2  104.42 KB  256          100.0%            382b0294-931d-42be-8327-24d6f505354a  rack1

Here is the code I used for this:
```go

import (
	"fmt"
	"time"

	"github.com/gocql/gocql"
)

/*
create keyspace test with replication = {
'class' : 'SimpleStrategy',
'replication_factor' : 1
};

create table test ( f1 text, f2 text, f3 text, primary key (f1,f2) );
*/

func main() {

	cluster := gocql.NewCluster("localhost:9042")
	cluster.Keyspace = "test"
	cluster.DisableInitialHostLookup = true
	cluster.RetryPolicy = &gocql.ExponentialBackoffRetryPolicy{
		NumRetries: 3,
		Min:        time.Millisecond * 10,
		Max:        time.Second,
	}

	session, err := cluster.CreateSession()
	if err != nil {
		panic(err)
	}

	for i := 0; i < 50; i++ {
		go func() {
			q := session.Query("INSERT INTO test (f1, f2, f3) VALUES (?, ?, ?)",
				"testitem", "f1"+string(i), "f2"+string(i))
			err = q.Exec()
			fmt.Println("Executed, attempts: ", q.Attempts(), ". Errors:", err)
			if err != nil {
				panic(err)
			}
		}()
	}

	time.Sleep(5 * time.Second)

}
```

**Comment by Zariel** [comment]
This is because the goroutine is not capturing the value correctly.

https://play.golang.org/p/bX7bEld5bF5

**Comment by hobbs** [comment]
Thanks @Zariel, pretty obvious in hindsight :)

great job on this project.
