### ISSUE TITLE
connection reset error 

### ISSUE THREAD

**Issue by kkrishna** [gocql/gocql#1102]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
 Cassandra 3.11.1.2130 | DSE 5.1.7 |

### What version of Gocql are you using?
https://github.com/gocql/gocql/commit/fa516cf7b8863ae9110072ca4368f6b1693e03c2

I create a session and use that for all queries.  session works fine but after a while, on query, returns "connection reset error" while while session.Closed api returns false.  Error message from api below:
```
read tcp 10.160.105.22:34614->10.146.86.33:9042: read: connection reset by peer
```
can anybody point me to code logic that re-establishes session? Any pointers on handling this scenario is appreciated.  thanks..

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by kkrishna** [comment]
got some clarity on this..  connections are getting reset by firewall; control connection is fine due to periodic heartbeats.. I'm exploring ways to re-establish session object periodically.. looking forward to suggestions/code pointers..  @Zariel thanks.

**Comment by openmohan** [comment]
@kkrishna  Probably the session timed out and the connection had to reset.

You can try:
1.) Increase the `Timeout` (default: 600ms)
2.) Use the retry mechanism 
`cfg := gocql.NewCluster(Nodes...)
cfg.RetryPolicy = &gocql.SimpleRetryPolicy{NumRetries: 3}`
[Doc here](https://github.com/gocql/gocql/blob/master/policies.go#L151)

**Comment by kkrishna** [comment]
setting keepAlive worked

**Comment by Anshumakkar** [comment]
@kkrishna : What is the value you have set for keepAlive

**Comment by kkrishna** [comment]
you could try setting [SocketKeepAlive](https://github.com/gocql/gocql/blob/master/cluster.go#L60) to 60sec. @Anshumakkar
