### ISSUE TITLE
DATA RACE observed while performing insert/select/delete in a for loop.

### ISSUE THREAD

**Issue by krk-krk** [gocql/gocql#1103]
While using gocql package, ran into a DATA RACE condition in one of the applications. Then I tried to reproduce the race condition with a simpler unit test. Attached the code and output from golang race detector.

[data-race-out.txt](https://github.com/gocql/gocql/files/1972975/data-race-out.txt)
[gocql_test_go.txt](https://github.com/gocql/gocql/files/1972976/gocql_test_go.txt)

Please let me know if any other information would be useful in debugging this issue.

### What version of Cassandra are you using?
3.10

### What version of Gocql are you using?
revision = "2e9f2912ba58e37f34af3554659b576eac655760"

### What did you do?
Ran unit test using 'go test -race ...'.
The unit test performs the following operations:
- create keyspace
- create table (two columns: ID and Name)
- create view (by Name)
- add object1 
- in a for loop
-- add object2 (both object1 and object2 have same name but different ID).
-- run query on the view (by Name) and scan the results. close the query iterator.
-- delete object2

### What did you expect to see?
Test should complete without any failure.

### What did you see instead?
DATA RACE reported.
Unit test code and logs are attached.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by krk-krk** [comment]
Additional info:  DATA RACE is not observed when the number of connections is 1.

**Comment by Zariel** [comment]
hm, looks like something is reusing a framer, which is bad

**Comment by nightlyone** [comment]
@Zariel / @krk-krk  could you confirm that this issue is solved now? From the actions taken it looks like it.

**Comment by Zariel** [comment]
yep this is now resolved

**Comment by krk-krk** [comment]
Thanks @Zariel. Data race is not seen with latest master hash: `2b46f6`.
