### ISSUE TITLE
No easy way to obtain statement from Query.

### ISSUE THREAD

**Issue by gbbr** [gocql/gocql#1108]
At Datadog, we have a Cassandra integration which uses [`Query.String()`](https://github.com/DataDog/dd-trace-go/blob/9e8fbae/contrib/gocql/gocql/gocql.go#L45) to obtain the statement and augment it with tracing.

This is rather inefficient in a high-traffic environment. I would like to suggest (if it makes sense) that the String() method returns only the statement. If that is not possible and the rest of the string is of interest anywhere else other than tests, what would be the best approach here?

`ObservedQuery` looks very interesting but it doesn't provide enough information to server as a drop-in replacement.

I've also experimented with improving the performance of String() but while the CPU speed can be increased by 40% using `copy` instead of `fmt.Sprintf`, the memory usage goes up - so it doesn't make sense.

**Comment by gbbr** [comment]
I'd suggest to call the method `Stmt() string`, what do you think?

**Comment by Zariel** [comment]
Would rather it be called statement rather than the short version

**Comment by gbbr** [comment]
SGTM
