### ISSUE TITLE
approvedAuthenticators - hard coded list blocks use of custom authenticator functions.

### ISSUE THREAD

**Issue by gruffner** [gocql/gocql#1109]
Please answer these questions before submitting your issue. Thanks!

### What did you do? I'm trying to utilize a different authenticator routine and am getting an error - my authenticator is not one of the following:
	approvedAuthenticators = [...]string{
		"org.apache.cassandra.auth.PasswordAuthenticator",
		"com.instaclustr.cassandra.auth.SharedSecretAuthenticator",
		"com.datastax.bdp.cassandra.auth.DseAuthenticator",

### What did you see instead?  Error - unexpected authenticator

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
Maybe we can have add a function which overrides the use of the hardcoded authenticators and allows a user to say if we should authenticate?

**Comment by gruffner** [comment]
That would be fabulous.  For now, I have updated the code in my local env
to bypass this edit, but it would be really great if I didn't need to do
that.

Thanks,
Glenn

**Comment by gruffner** [comment]
Is there any update to this?  We don't use one of the 'approved' authenticators so we are not currently able to use gocql without customizing the code.  Could you please consider allowing the user to bypass this edit?

**Comment by alourie** [comment]
possibly #1242 fixes this.

**Comment by gruffner** [comment]
Thanks for letting me know, I'll try it out as soon as possible.

Glenn

**Comment by alourie** [comment]
@gruffner You'll basically need to:

a) create a new AuthProvider function that returns an Authenticator object.
b) create a new cluster as per usual
c) set  the provider function on the cluster as:
`cluster.AuthProvider = <provider function>`

d) continue to creating a session, etc.

Hope it works for you.
