### ISSUE TITLE
can not unmarshal int into *float32

### ISSUE THREAD

**Issue by wubo0067** [gocql/gocql#1114]
Please answer these questions before submitting your issue. Thanks!
CREATE TABLE IF NOT EXISTS tbl_DailyRevenue (
    Date VARCHAR,
    ChannelID VARCHAR,                      /
    Platform VARCHAR,                       
    TotalRevenue FLOAT,                     
    TotalRechargeCount INT, 				
    VersionID BIGINT,                       
    PRIMARY KEY (Date, ChannelID, Platform)    
) WITH COMMENT='tbl_DailyRevenue'
AND gc_grace_seconds = 604800;

	cqlInsertDailyRevenue := fmt.Sprintf("INSERT INTO tbl_DailyRevenue(Date, ChannelID, Platform, TotalRevenue, TotalRechargeCount, VersionID) VALUES('%s', '%s', '%s', %f, 1, 1) IF NOT EXISTS",
		date, req.ChannelID, req.PlatForm, req.RechargeAmount)

	var casDate string
	var casChannelID string
	var casPlatform string
	var casTotalRevenue float32
	var casTotalRechargeCount int
	var casVersionID int

	applied, err := session.Query(cqlInsertDailyRevenue).ScanCAS(&casDate, &casChannelID, &casPlatform, &casTotalRevenue,
		&casTotalRechargeCount, &casVersionID)

failed! reason[can not unmarshal int into *float32]

### What version of Cassandra are you using?
cassandra-3.11.2

### What did you see instead?

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
This is most likely due to the cas return column order being the
alphabetical order of the columns in the schema, not the order in the
query.

**Comment by wubo0067** [comment]
Thanks so much @Zariel
