### ISSUE TITLE
Rare problem, not even sure if this is gocql problem

### ISSUE THREAD

**Issue by didip** [gocql/gocql#1129]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Open Source Cassandra 3.7

### What version of Gocql are you using?
```
// From govendor
{
    "checksumSHA1": "iBzdEM6uMy+X/08m67iiBRNvcdk=",
    "path": "github.com/gocql/gocql",
    "revision": "ca7d33956650d92d29e6db7fe901e23d0f0e3359",
    "revisionTime": "2017-06-15T07:58:21Z"
}
```

### What did you do?
Go daemon is co-located with Cassandra itself. During server reboot, both are coming up at the same time. If the Go daemon is up first, on a rare occasion, Cassandra will fail to start because port 7199 is already in-use. See error below:

```
Errors in file - cassandra.log: 8 Ignored Errors: 0
--------------------------------------------------------------------------------
ERROR 2018-05-24 17:43:59,968 [main] [CassandraDaemon] [line 731] Port already in use: 7199; nested exception is: 
	java.net.BindException: Address already in use (Bind failed) 
	java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[na:1.8.0_131]
	at java.net.ServerSocket.bind(ServerSocket.java:375) ~[na:1.8.0_131]
	at java.net.ServerSocket.<init>(ServerSocket.java:237) ~[na:1.8.0_131]
	at javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231) ~[na:1.8.0_131]
	at org.apache.cassandra.utils.RMIServerSocketFactoryImpl.createServerSocket(RMIServerSocketFactoryImpl.java:21) ~[apache-cassandra-3.7.jar:3.7]
```

Linux version from uname: `Linux 2.6.32-642.13.1.el6.x86_64`

I have to kill the Go daemon first, and then start Cassandra to recover from this problem.

### What did you expect to see?

I expected that both daemons can go up and down without interrupting each other.

### What did you see instead?

Cassandra did not start correctly. I have to kill the Go daemon first, and then start Cassandra. Once again, this does not happen frequently.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by robusto** [comment]
This doesn't seem like a GoCQL problem. Port 7199 is the default JMX port for Cassandra which you need this if you expect to pull metrics out of the cluster or use Cassandra administration tools. Your Go "daemon" process should not use this port.
