### ISSUE TITLE
Query.IsIdempotent has no effect

### ISSUE THREAD

**Issue by jalan** [gocql/gocql#1153]
### What version of Cassandra are you using?
3.11.1.2323

### What version of Gocql are you using?
master (045d8d6abc70b5bd02bb18b8fdb05ee54d8c87aa)

### What did you do?
I played around with the included retry policies and query idempotence.

### What did you expect to see?
I expected to see some relationship between query idempotence and retries, as in the java library: [idempotence](https://docs.datastax.com/en/developer/java-driver/3.4/manual/idempotence/), [retries](https://docs.datastax.com/en/developer/java-driver/3.4/manual/retries/)

### What did you see instead?
Query idempotence seems to have no effect on retries.

---

Is this the expect behavior? I'm seeing unsafe queries getting retried.

**Comment by alourie** [comment]
@jalan you are correct that at the moment idempotence has no effect. It is just a basis for the continuing work with speculative queries (working on it right now as #1083 ), and possibly retry policies.

I hope to land this work very soon, will link it here as well.

**Comment by jalan** [comment]
@alourie Thanks for the quick reply!

Is there work in progress on speculative queries only, or on the retry policies as well? If the work happens to take longer than you hope, some doc updates would go a long way in avoiding confusion. I'm willing to do a doc update PR if it would help.

**Comment by alourie** [comment]
@jalan atm I'm working on speculative execution. I had a look yesterday what might require acknowledging idempotence in retry policies, and it's not simple. So I'm going to open a separate ticket for that work, and it's going to be independent of #1083.

That being said, I think that a doc addition could help if it had mentioned that he Idempotence flag doesn't have any effect at the moment.

**Comment by alourie** [comment]
Opened a ticket #1154 to track the work for the policies

**Comment by alourie** [comment]
The work for Speculative Queries is merged with #1178, so Idempotence is now used. Closing.
