### ISSUE TITLE
Supported version of Go 1.8 to 1.9

### ISSUE THREAD

**Issue by jonasantonelli** [gocql/gocql#1171]
Please answer these questions before submitting your issue. Thanks!

The commit 78e324ac30b063dd807a762d981486bf2ba9b8d6 has added in file marshal.go the dependency of "math/bits" that is not available in Go 1.8.

### What did you see instead?

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

>

**Comment by nussjustin** [comment]
Go 1.8 was released in early 2017 and is neither supported by the Go team nor gocql anymore.

gocql follows the [Go release policy](https://golang.org/doc/devel/release.html#policy) of supporting the current and previous Go release, as explained under [Sunsetting Model](https://github.com/gocql/gocql#sunsetting-model) in the README.

Supporting old Go releases means extra work and has a relatively small benefit, given that new Go are mostly dropin and breaking changes are rare.

The current Go release is 1.11, which means that 1.11 and 1.10 should work. Travis currently still tests Go [1.10 and 1.9](https://github.com/gocql/gocql/blob/7e0c1ee23124298e68324967df4df870f9cfef7f/.travis.yml#L32-L33),  which should be changed to at least test 1.11 and 1.10.
