### ISSUE TITLE
I think TokenAwareHostPolicy never works on my use-case

### ISSUE THREAD

**Issue by didip** [gocql/gocql#1177]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Cassandra 3.7

### What version of Gocql are you using?
Latest from `go get`

### What did you do?
I put a bunch of logger to determine if I am actually using TokenAware policy or not.

### What did you expect to see?
I expect the app to utilize `TokenAwareHostPolicy`.

### What did you see instead?
Actually, I always ended up using the fallback: `DCAwareRoundRobinPolicy` because I always hit this if block: `} else if routingKey == nil {` https://github.com/gocql/gocql/blob/master/policies.go#L528.

Further logging reveals that I am hitting this block on boot: `info.request.colCount == 0` https://github.com/gocql/gocql/blob/master/session.go#L495

On subsequent queries, I am always hitting this block: `routingKeyInfo.indexes[keyIndex] == -1` https://github.com/gocql/gocql/blob/master/session.go#L560

Finally, that's because the partition key column name is never equal to bound column name: https://github.com/gocql/gocql/blob/master/session.go#L552.

`partitionKey[0]` is correctly pointing to `metric` column while `info.request.columns` has 2 items and both of them are the same thing: `[time, time]`, shouldn't it be `[metric, time]`?

See my create table below: 

```
CREATE TABLE mykeyspace.mytable (
    metric text,
    time bigint,
    value double,
    PRIMARY KEY (metric, time)
) WITH CLUSTERING ORDER BY (time ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'NONE', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'com.jeffjirsa.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '15', 'compaction_window_unit': 'DAYS', 'max_threshold': '32', 'min_sstable_size': '134217728', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 0.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```

```
// initialization code. cassandraConf is config struct.
cluster := gocql.NewCluster(cassandraConf.Clusters...)
cluster.Keyspace = cassandraConf.Keyspace
cluster.Port = cassandraConf.CQLPort
cluster.ProtoVersion = cassandraConf.ProtoVersion
cluster.NumConns = cassandraConf.NumConns
cluster.Timeout = cassandraConf.GetTimeout()
cluster.PageSize = cassandraConf.PageSize
cluster.RetryPolicy = &gocql.SimpleRetryPolicy{NumRetries: cassandraConf.MaxRetries}
cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())

// If DC is defined, apply DataCentreHostFilter
if cassandraConf.DC != "" {
    cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.DCAwareRoundRobinPolicy(cassandraConf.DC))
    cluster.HostFilter = gocql.DataCentreHostFilter(cassandraConf.DC)
}
```

The Cassandra is on 2 DCs.

The table has 2 Replication Factor on each DC.

The SELECT query I am running is using `LOCAL_QUORUM`.
```
SELECT * FROM mykeyspace.mytable where metric IN (?) AND time >= ? AND time <= ?

// first ? value is a slice of string.
```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by beltran** [comment]
> Further logging reveals that I am hitting this block on boot: info.request.colCount == 0

That can would happen if the query is for example `session.Query("INSERT INTO test.mytable (metric, time, value) VALUES ('1', 1, 2.0)")`, without any columns to be bounded (as opposed to `session.Query("INSERT INTO test.mytable (metric, time, value) VALUES (?, ?, ?)", "1", 1, 1.0)`).

> Finally, that's because the key column name is never equal to bound column name

What's the query that's producing this? I'm not sure in what scenario [this loop](https://github.com/gocql/gocql/blob/master/session.go#L546) would come into play, but if the query has a partition key as a bound column it would exist [here](https://github.com/gocql/gocql/blob/master/session.go#L500). Maybe in your query the partition columns is set and won't be bounded?

> info.request.columns has 2 items and both of them are the same thing

That's weird, what's the query producing this?

**Comment by didip** [comment]
Hi @beltran , the query is fairly straight forward:

```
SELECT * FROM mykeyspace.mytable where metric = ? AND time >= ? AND time <= ?
```

**Comment by didip** [comment]
@beltran Your comment actually gave me a clue. 

The `metric IN (...)` values are actually interpolated in, and not bounded with `?`! Could that be the problem?

**Comment by beltran** [comment]
hmm I'm getting `len(info.request.pkeyColumns) > 0` with that query. Here's my code:

```
func TestIssue1177(t *testing.T) {
	// initialization code. cassandraConf is config struct.
	cluster := NewCluster("127.0.0.1","127.0.0.2")
	cluster.ProtoVersion = 4
	cluster.NumConns = 1
	// cluster.Timeout = cassandraConf.GetTimeout()
	// cluster.PageSize = cassandraConf.PageSize
	cluster.RetryPolicy = &SimpleRetryPolicy{NumRetries: 5}
	cluster.PoolConfig.HostSelectionPolicy = TokenAwareHostPolicy(RoundRobinHostPolicy())

	// If DC is defined, apply DataCentreHostFilter
	cluster.PoolConfig.HostSelectionPolicy = TokenAwareHostPolicy(DCAwareRoundRobinPolicy("datacenter1"))
	cluster.HostFilter = DataCentreHostFilter("datacenter1")

	session, err := cluster.CreateSession()

	if err != nil {
		panic(err)
	}

	fmt.Println("Droping keyspace")
	if err := session.Query(`DROP KEYSPACE IF EXISTS mykeyspace`).Exec(); err != nil {
		log.Fatal(err)
	}

	fmt.Println("Creating keyspace")
	if err := session.Query(`CREATE KEYSPACE mykeyspace WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': '3' }`).Exec(); err != nil {
		log.Fatal(err)
	}

	fmt.Println("Creating table")
	if err := session.Query(`CREATE TABLE mykeyspace.mytable (
		metric text,
		time bigint,
		value double,
		PRIMARY KEY (metric, time)
	) WITH CLUSTERING ORDER BY (time ASC)
		AND bloom_filter_fp_chance = 0.01
		AND caching = {'keys': 'NONE', 'rows_per_partition': 'NONE'}
		AND comment = ''
		AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
		AND crc_check_chance = 0.0
		AND dclocal_read_repair_chance = 0.0
		AND default_time_to_live = 0
		AND gc_grace_seconds = 0
		AND max_index_interval = 2048
		AND memtable_flush_period_in_ms = 0
		AND min_index_interval = 128
		AND read_repair_chance = 0.0
		AND speculative_retry = '99PERCENTILE';`).Exec(); err != nil {
		log.Fatal(err)
	}

	fmt.Println("Select query")
	if err := session.Query(`SELECT * FROM mykeyspace.mytable where metric IN (?) AND time >= ? AND time <= ?`, "1", 1, 1).Exec(); err != nil {
		log.Fatalf("%s, %T", err.Error(), err)
	}
}
```

`info.requests.columns` is populated [here](https://github.com/gocql/gocql/blob/master/frame.go#L983), with the response from Cassandra.

**Comment by beltran** [comment]
I'm testing against 3.11 and information comes from Cassandra. I'll try later against 3.7.

**Comment by didip** [comment]
After updating my query with the actual: `SELECT * FROM mykeyspace.mytable WHERE metric IN ? AND time >= ? AND time <= ?`, I am getting `Bound column[0]: in(metric)`.

But that's still not equal to `metric`, so I am still falling back to DCAware. See my logging output below:

```
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Looping info.request.columns"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Partition key[0]: metric"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Bound column[0]: in(metric)"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Is partition key == bound column?: false"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Partition key[0]: metric"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Bound column[1]: time"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Is partition key == bound column?: false"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Partition key[0]: metric"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Bound column[2]: time"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Is partition key == bound column?: false"
INFO 2018-09-08T18:29:40Z msg="session.routingKeyInfo(): Missing a routing key column mapping"
```

**Comment by didip** [comment]
Just checked my logger again, I am not hitting this block:

```
	if len(info.request.pkeyColumns) > 0 {
		if gocqlDebug {
                         // This is my logger
			Logger.Printf("session.routingKeyInfo(): Routing info primary key columns: %v", info.request.pkeyColumns)
		}

		// proto v4 dont need to calculate primary key columns
		types := make([]TypeInfo, len(info.request.pkeyColumns))
		for i, col := range info.request.pkeyColumns {
			types[i] = info.request.columns[col].TypeInfo
		}

		routingKeyInfo := &routingKeyInfo{
			indexes: info.request.pkeyColumns,
			types:   types,
		}

		inflight.value = routingKeyInfo
		return routingKeyInfo, nil
	}
```

**Comment by Zariel** [comment]
I'm not going to support this because fundamentally this is a bad idea to do.

1. This is could open you up to SQL injection attacks
2. This is require preparing every query for every request regardless of the input params.
3. This would require parsing the input query which is non trivial.

I suggest you change your code to using bound params with `?` instead.

**Comment by didip** [comment]
@zariel, just to be clear, do you propose creating the query like this:

where metric in (?, ?, ?, ?)

instead of

where metric in ?

Just to be clear, I am still constructing the select query with bound marker. No sql injection here.

**Comment by Zariel** [comment]
Using IN like that the query can never be sent to the node which owns the token because the token is either TOKEN(1) or TOKEN(2) or TOKEN(3).. etc so if this is causing you perf problems then either make all the queries concurrently using a an equal clause or change your schema to not require the IN query.

**Comment by didip** [comment]
I see what you mean, If I replace with individual `= ?` then I will hit the data nodes directly but the app daemon is the one that has to merge and sort the results.

So quick question @Zariel , then why can't gocql simply choose one of the TOKEN(1) or TOKEN(2) or TOKEN(3)?

**Comment by Zariel** [comment]
Because that would require parsing the query and making sense of it, in the
end it would require significant complexity to save 1 hop out of N hopes
from the coordinator.

If the coordinator needs to make 5 requires to other nodes does it matter
if it only has to make 4?
