### ISSUE TITLE
ExecuteBatch leading to deadlock when the writes are sequential

### ISSUE THREAD

**Issue by siva0chain** [gocql/gocql#1200]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
 Cassandra 3.11.2 

### What version of Gocql are you using?
Latest from master branch

### What did you do?
I write multiple records in batches using ExecuteBatch. Only after the ExecuteBatch is completed successfully the next set of records are again written. So, if the first call doesn't return then no more writes will happen.

### What did you expect to see?
I expect the ExecuteBatch to complete.

### What did you see instead?
Sometimes it's not returning. Below is the stack trace of the two stuck threads.

\#	0x45065a	sync.runtime_notifyListWait+0x10a				/usr/local/go/src/runtime/sema.go:510
\#	0x47f49f	sync.(*Cond).Wait+0x7f						/usr/local/go/src/sync/cond.go:56
\#	0x9126d9	github.com/gocql/gocql.(*writeCoalescer).Write+0xe9		/go/src/github.com/gocql/gocql/conn.go:660
\#	0x910081	github.com/gocql/gocql.(*Conn).Write+0x51			/go/src/github.com/gocql/gocql/conn.go:283
\#	0x921e27	github.com/gocql/gocql.(*framer).finishWrite+0x257		/go/src/github.com/gocql/gocql/frame.go:782
\#	0x92b4a0	github.com/gocql/gocql.(*framer).writeBatchFrame+0x1380		/go/src/github.com/gocql/gocql/frame.go:1730
\#	0x92a0f7	github.com/gocql/gocql.(*writeBatchFrame).writeFrame+0x47	/go/src/github.com/gocql/gocql/frame.go:1653
\#	0x912cc9	github.com/gocql/gocql.(*Conn).exec+0x229			/go/src/github.com/gocql/gocql/conn.go:734
\#	0x9162ec	github.com/gocql/gocql.(*Conn).executeBatch+0xa2c		/go/src/github.com/gocql/gocql/conn.go:1181
\#	0x95f184	github.com/gocql/gocql.(*Batch).execute+0x34			/go/src/github.com/gocql/gocql/session.go:574
\#	0x95aa3c	github.com/gocql/gocql.(*queryExecutor).attemptQuery+0x6c	/go/src/github.com/gocql/gocql/query_executor.go:24
\#	0x95ac90	github.com/gocql/gocql.(*queryExecutor).executeQuery+0x190	/go/src/github.com/gocql/gocql/query_executor.go:53
\#	0x95f261	github.com/gocql/gocql.(*Session).executeBatch+0xc1		/go/src/github.com/gocql/gocql/session.go:590
\#	0x95f388	github.com/gocql/gocql.(*Session).ExecuteBatch+0x38		/go/src/github.com/gocql/gocql/session.go:601

\#	0x45065a	sync.runtime_notifyListWait+0x10a				/usr/local/go/src/runtime/sema.go:510
\#	0x47f49f	sync.(*Cond).Wait+0x7f						/usr/local/go/src/sync/cond.go:56
\#	0x9128d8	github.com/gocql/gocql.(*writeCoalescer).writeFlusher+0xc8	/go/src/github.com/gocql/gocql/conn.go:685

It seems like writeFlusher is waiting on fcond and write is waiting on cond. But as I don't have any other writes happening till my call for ExecuteBatch is returned, seems like it's deadlocked.

**Comment by alourie** [comment]
@siva0chain yep, we've noticed this already: https://github.com/gocql/gocql/pull/1194/files/d845a0e2eba7b867634c207bb8f7b84343540fd6#r219705159
There's a PR to fix this #1198, hopefully will land soon enough.

**Comment by AlexisMontagne** [comment]
@alourie i don't think #1198 will help out in this case.

**Comment by AlexisMontagne** [comment]
I have an idea from where it could come from. 

We unlock the fcond lock [here](https://github.com/gocql/gocql/blob/master/conn.go#L700) and relock it  [here](https://github.com/gocql/gocql/blob/master/conn.go#L683) 

If: 
* writeFlusher is unlocked ( after L700, before L683 )
* Write gets [here](https://github.com/gocql/gocql/blob/master/conn.go#L653) and Broacast

It creates a deadlock

Two resolve this, we could move the `w.fcond.Wait()` in the locked section L696-L700 (and also wait before entering the `for` loop)

cc. @alourie @Zariel

**Comment by alourie** [comment]
@AlexisMontagne If `Write` entered the lock after L700 and broadcast it means it has set `running` to true and released the fcond lock; it means that writeFlusher is not even supposed to get to that wait() call. Maybe what happens is:
1) Write gets into fcond lock _before_ writeFlusher gets its second one on line 696; running is still `true` so the Writer doesn't broadcast, and releases the lock
2)  writeFlusher acquires the lock, flushes and immediately sets `running` to false on [L699](https://github.com/gocql/gocql/blob/master/conn.go#L699)
3) Writer gets to its own `wait()` on [L660](https://github.com/gocql/gocql/blob/master/conn.go#L660) and deadlocks as there are no cond lock broadcasts
4) writeFlusher is reentering the for loop and its `wait()` call on [L685](https://github.com/gocql/gocql/blob/master/conn.go#L685) and deadlocks as there are no fcond lock broadcasts

Not only this creates the deadlocks, if `running` is set to true/false intermittently like that, we might miss flush cycles. To fix this, we can do something like the following:

1. Implement atomic boolean calls on `running` field in `writeCoalescer` (we could turn running into int and do atomic operations):
    * running(bool) -> this will set the int to 1 and call the broadcast if the bool is true, or set to 0 if bool is false
    * isRunning() bool -> this will return true if int is 1, false otherwise
    * waitToRun() -> will wait on fcond for the broadcast until isRunning() is true

2. Then Write() can be something like:
```golang
...
        w.cond.L.Lock()
        w.running(true)
	w.buffers = append(w.buffers, p)
	for len(w.buffers) != 0 {
		w.cond.Wait()
	}
...
```

3. Then writeFlusher can be something like:
```golang
....
for {
		
                // wait for a write to start the flush loop
		w.waitToRun()
	        
                timer.Reset(interval)
		select {
		case <-quit:
			return
		case <-timer.C:
		}	
                w.flush()
		w.running(false)
}
...
```
This way the marking of the loop run is closer to actual write/flush operations, which helps to avoid other possible order-related deadlocks, and then the writeFlush is free to do things in its own cycle. Also, we can even provide `waitToRun` the quit channel, so it can do a select on it and return and not wait forever if the connection is closed (addressing the issue that [1198](https://github.com/gocql/gocql/pull/1198#discussion-diff-220369375R683) is trying to address in a separate goroutine)

cc @Zariel

**Comment by ericrenard** [comment]
I have also experienced this issue in production in a simple Execute, not a batch one. It doesn't happen very often but it's a serious problem

**Comment by alourie** [comment]
@siva0chain @ericrenard the #1208 is supposed to fix the coordination for the flush loop and Write loop. Would you mind running your stuff again with the latest master to see if fixed? Thanks!

**Comment by alourie** [comment]
Closing, please reopen if the issue returns.
