### ISSUE TITLE
scylladb  - query fails for secondary index keys with "varchar" types

### ISSUE THREAD

**Issue by senthilrag** [gocql/gocql#1207]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
cqlsh> SHOW VERSION
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]

### What version of Gocql are you using?
Latest from the github. Did a go get on github path.

### What did you do?
Create secondary index table of which one key is "varchar".

### What did you expect to see?
Select to go through

### What did you see instead?
&{{{132 0 192 0 344 []} 0 marshaling error: read_simple_exactly - size mismatch (expected 8, got 12) Backtrace:   0x7a31e8
  0x13463e4
  0x1346f20
  0x223ca29
  0x25f6958
  0x2601d1f
  0x25efad1
  0x1eb666c
  0x1ee5f19
  0x5873a6
  0x587561
  0x652447
  0x673fc2
  0x72f96d
  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9
  /lib/x86_64-linux-gnu/libc.so.6+0x10741c
} 0 {0 [] [] 0 0} 0 <nil> 0xc42029c160 0xc420212420 0}
running query...
panic: failed to load block
---

### Describe your Cassandra cluster
3 node single datacenter cluster

please provide the following information

- output of `nodetool status`
ubuntu@labs39:~$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  172.25.236.37  752.13 KB  256          ?       1d289622-eada-4869-9bcf-77612d33eac6  rack1
UN  172.25.236.39  3.35 MB    256          ?       dffa2d47-0ca3-4dd1-938e-82bc7360669b  rack1
UN  172.25.236.38  688.93 KB  256          ?       69732bae-5305-4bbe-afd0-e5e149544e7b  rack1

- output of `SELECT peer, rpc_address FROM system.peers`
172.25.236.39
cqlsh> SELECT peer, rpc_address FROM system.peers
   ... ;

 peer          | rpc_address
---------------+---------------
 172.25.236.38 | 172.25.236.38
 172.25.236.37 | 172.25.236.37

(2 rows)
cqlsh>

- rebuild your application with the `gocql_debug` tag and post the output
[scylla_sec_idx.txt](https://github.com/gocql/gocql/files/2451890/scylla_sec_idx.txt)

**Comment by senthilrag** [comment]
notice if clustering key(in attached scylla_sec_idx.txt/go file) limited from 
PRIMARY KEY (mkey,mid, mhash)
to
PRIMARY KEY (mkey, mhash)
the problem goes away. just thought to share in case it helps.

**Comment by Zariel** [comment]
this looks like a bug in scylla and that looks like a C backtace to me?

**Comment by mmatczuk** [comment]
@senthilrag please post the bug to https://github.com/scylladb/scylla

**Comment by senthilrag** [comment]
just did, thanks
