### ISSUE TITLE
Memory leak in context.WithCancel

### ISSUE THREAD

**Issue by apetruhin** [gocql/gocql#1224]
### What version of Cassandra are you using?
2.2.12

### What version of Gocql are you using?
https://github.com/gocql/gocql/commit/22229812a83e

Commit https://github.com/gocql/gocql/commit/08a3a27c42ccc63167b9d470472b85983e17e0e2 introduced memory leak.
![image](https://user-images.githubusercontent.com/199054/47344714-c7890000-d6b1-11e8-9d3e-e06c9790bf75.png)
Rollback to previous version fixes issue.

From https://golang.org/pkg/context/#WithCancel:
_Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete._
So `cancelQuery` should be called after query execution?

**Comment by nightlyone** [comment]
I agree with you that this is not correctly implemented. Cancellation of contexts is a concept used by the callers, exposing the cancellation seems wrong and backwards to me. 

The Go stdlib is controlling lifetimes and operation cancellations now exclusively with contexts provided by the user, various packages there regretted adding an alternative cancellation concept. If anything, there should be a way to pass on contexts deeper to deeper layers, if there is such a use case.

We successfully control all lifetimes with query.WithContext and this works beautifully as is. See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/internal/gax/invoke.go#L80 for a good example of a control loop only with a context. 

So @Zariel, please reconsider this design.

**Comment by Zariel** [comment]
Agreed, will fix

**Comment by Zariel** [comment]
thanks for the report & memory profile debugging, fixed via #1228
