### ISSUE TITLE
SslOptions when EnableHostVerification requires certificates with IP SANs

### ISSUE THREAD

**Issue by projetdb0101** [gocql/gocql#1232]
Hi,

I have question regarding the implementation of the EnableHostVerification with SSL/TLS: not sure if this is a bug or a design choice.

### What version of Cassandra are you using?

Not related. Go only.

### What version of Gocql are you using?

The latest version at the time (Oct, 25, 271c061)

### What did you do?

I attempt to connect to a cluster using SSL/TLS with EnableHostVerification set to true. 

I connect to the cluster using a local FQDN. This FQDN is referenced in the CN field of the certificate.

### What did you expect to see?

No connection error as the CA that generated the cluster certificates is provided in the SslOption.

### What did you see instead?

Upon creating the session, i received the following error:

> gocql: unable to create session: control: unable to connect to initial hosts: x509: cannot validate certificate for 192.168.3.10 because it doesn't contain any IP SANs

Digging in the code of the conn.go file, I found the following:

```go
// TODO(zariel): handle ipv6 zone
addr := (&net.TCPAddr{IP: ip, Port: port}).String()

if cfg.tlsConfig != nil {
    // the TLS config is safe to be reused by connections but it must not
    // be modified after being used.
    conn, err = tls.DialWithDialer(dialer, "tcp", addr, cfg.tlsConfig)
```
Based on the previous code, the "error" I receive is to be expected as tls.DialWithDialer uses explicitly IP addresses and not the provided FQDN.

I don't know if it is a design choice or a bug, but currently we cannot use wildcard certificates as we should then include all potential IP SANs.

**Comment by alourie** [comment]
@projetdb0101 I've created the patch for it, please try #1310 if you can in your environment. It's quite basic, but what I'm worried about is that it won't work properly if you have new nodes added, so if you could try that scenario as well, that would be awesome.
