### ISSUE TITLE
Support zero parameters to ScanCAS

### ISSUE THREAD

**Issue by JensRantil** [gocql/gocql#1235]
I am executing

    applied, err := session.Query(`INSERT INTO my_table (key, data) VALUES (?, ?) IF NOT EXISTS`, key, data).ScanCAS(&keyCAS, &dataCAS)

but really I'm just interested in `err != nil` and `applied == true`, not the value of `keyCAS` nor `dataCAS`.

**Expected:** That I can skip the parameters to `ScanCAS` and simply execute

    applied, err := session.Query(`INSERT INTO my_table (key, data) VALUES (?, ?) IF NOT EXISTS`, key, data).ScanCAS()

**What happens:** If I skip the parameters I get an error something like:

    gocql: not enough columns to scan into: have 1 want 3

**Comment by JensRantil** [comment]
https://github.com/gocql/gocql/pull/95 might also be relevant here don't know.

**Comment by alourie** [comment]
@JensRantil can you please try #1237? It's a small change I just made to allow this (even though you just may want to use `ScanCAS(nil, nil)`)

**Comment by alourie** [comment]
Agreed with @Zariel. Even in the original #95 it's been suggested to use something like ```ScanCAS(nil, nil)``` when you don't care about storing of the results.

**Comment by JensRantil** [comment]
I'm find with using `nil` parameters, but believe that should be documented in `ScanCAS` in that case (and possibly have a test case for it, if it doesn't exist).

**Comment by JensRantil** [comment]
Looks like `Session.ScanCAS(nil, nil)` is already tested in https://github.com/gocql/gocql/blob/master/cassandra_test.go#L1082.
