### ISSUE TITLE
Authenticator per Host

### ISSUE THREAD

**Issue by magaldima** [gocql/gocql#1238]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
v2.2.1

### What version of Gocql are you using?
latest master

### What did you do?
Attempt to connect to a series of hosts in primary DC. The default cluster settings, `NumConns = 2` and `DisableInitialHostLookup = false` means that each one of the 3 hosts in this DC attempt to authorize my connection. The `Authenticator` interface only allows for setting one global authenticator per cluster while I need a separate authenticator per host since each host's challenge + response will depend on the given hostname (using PKI authentication).

### What did you expect to see?
I'd expect to be able to authenticate per host in the cluster with a unique challenge response.

### What did you see instead?
I'm getting WRONG_TARGET error when responding to the second host with the same response I was successfully able to connect to with the first host. 

I'm was currently able to bypass this problem by setting `NumConns = 1` and `DisableInitialHostLookup = true`.. however this is not a long-term solution as it limits the cluster pool connections. 

I see 2 potential solutions to this issue:
1. Don't change the `gocql` library and build an `Authenticator` that is also implements the `HostSelectionPolicy` interface so I'm able to extract the context of which host is currently active or attempting to authorize.
2. Change the `gocql` library to allow setting an `AuthProvider` with the following spec:
```
AuthProvider func(hostname string) (Authenticator, error)
```
This would possibly replace or augment the default authenticator and be called internally when each host is attempting to authenticate. I'm following examples from the JAVA CQL implementation.

**Comment by alourie** [comment]
I'll try to take a look at this a bit later this week.

**Comment by Zariel** [comment]
Cassandra stores IP addresses, I don't see how we can store DNS names for hosts if C* doesn't, how can we map the supplied DNS name to a host being down in Cassandra?
