### ISSUE TITLE
What do you guys think of versioning?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#1239]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

* Version: 3.11.2. Cassandra is setup on 2 DC. 

* Cassandra logger is configured to debug and we don't see any meaningful errors.

* Insert is done using LOCAL_ONE consistency.

* gocql uses HostFilter to get local Cassandra nodes.

### What version of Gocql are you using?

Latest from master

### What did you do?

We upgraded and we now see high number of INSERT failures after prolong use.

### What did you expect to see?

Upgrade can be done somewhat safely.

### What did you see instead?

Increase number of INSERT errors after running our daemon for about 24 hours.

We have high number of inserts, low millions per minute and we are seeing about 9000 insert errors per minute.

After rolling back on a few hosts, we stopped seeing INSERT failures on those hosts.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by beltran** [comment]
What's the error for the insert? Is it something in the driver or a Cassandra returned error? That'd help narrow the issue.

**Comment by didip** [comment]
@beltran Unfortunately our logs are quickly rotated already.

The symptoms look like blocked data structure/channel because number of net/http goroutines spiked very high when number of insert errors spiked as well.

**Comment by alourie** [comment]
So it might be still relating to the write coalescing work we've done recently. @didip what version are you running at the moment that seems to be ok?

Additionally, having at least some information about the system would help. Were there CPU spikes? Memory/IO spikes? Was there anything out of ordinary with your application (like sudden spikes in writes/reads)?

And we'd have an actual error, that would be great.
