### ISSUE TITLE
Can't connect to Cassandra 2.1.0

### ISSUE THREAD

**Issue by davidlusg** [gocql/gocql#1251]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
2.1.0

### What version of Gocql are you using?
go version go1.11.4 darwin/amd64

### What did you do?
 ```
func init() {

	var err error

	// cluster := gocql.NewCluster("localhost", "127.0.0.2", "127.0.0.3")
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Keyspace = "user_settings"
	cluster.ProtoVersion = 2
	Session, err = cluster.CreateSession()
	if err != nil {
		fmt.Printf("err is %v\n", err)
		panic(err)
	}
	fmt.Println("cassandra init done")
 }
```

### What did you expect to see?
A successful connection message

### What did you see instead?
```
panic: no valid connect address for host: 
[HostInfo connectAddress="<nil>" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="0.0.0.0" connect_addr_source="invalid" port=9042 data_centre="datacenter1" rack="rack1" host_id="265e9938-2e6b-4320-8438-9fcfb5b97a81" version="v2.1.0" state=UP num_tokens=1]. Is your cluster configured correctly?
```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
```
ccm status
Cluster: 'test'
---------------
node1: UP
node2: UP
node3: UP
```

- output of `SELECT peer, rpc_address FROM system.peers`
```
ccm node1 cqlsh
Connected to test at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.0 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> SELECT peer, rpc_address FROM system.peers;

 peer      | rpc_address
-----------+-------------
 127.0.0.3 |   127.0.0.3
 127.0.0.2 |   127.0.0.2

(2 rows)
```
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by davidlusg** [comment]
It looks like gocql is picking up the port, data_centre, rack, host_id but can't find the connect_address.  Is there something about ccm running on my local mac that is not configured properly?

**Comment by drcforbin** [comment]
If you take a look at the call stack in the panic, it references `(*Conn).localHostInfo`, which selects from `system.local`, rather than `system.peers` and feeds the result to `hostInfoFromMap`. At least in mine, that row doesn't include any IP addresses, causing the failure and panic in `(*HostInfo).ConnectAddress`

**Comment by alourie** [comment]
@drcforbin is right, the `system.local` doesn't include any IP in Cassandra 2.1 and hence the driver doesn't find an address to connect with.

I've created a small update to the `localInfoFromMap` call to work with Cassandra 2.1.

**Comment by alourie** [comment]
@drcforbin done, should be all good now.
