### ISSUE TITLE
Add session-specific logger

### ISSUE THREAD

**Issue by NWilson** [gocql/gocql#1257]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

N/A

### What version of Gocql are you using?

Commit 70385f88b28b (released 2018-11-24 15:14:48)

### What did you do?

Gocql exposes the `gocql.StdLogger` object, which is a package-global logger.

### What did you expect to see?

I expected to be able to set the logger on the `Cluster` or `Session` objects. I would like to be able to have multiple Cassandra sessions in my application, and handle the logging separately for each session.

Gocql should fall back to the using the package-global StdLogger only if a session-specific logger is not provided.

### What did you see instead?

Gocql has its logging configuring using a global :(

**Comment by alourie** [comment]
I've looked at this once, could give it another go (pun intended)

**Comment by martin-sucha** [comment]
Fixed with #1553
