### ISSUE TITLE
tokenAwareHostPolicy selects wrong replicas

### ISSUE THREAD

**Issue by mmatczuk** [gocql/gocql#1262]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

Scylla 2.3 - does not matter

### What version of Gocql are you using?

8516aabb0f993b6c0d88b66d46e54a90d622671d

### What did you do?

Using `TokenAwareHostPolicy` backed by `DCAwareRoundRobinPolicy` or `RoundRobinHostPolicy`

```
package main

import (
	"encoding/hex"
	"log"
	"os"
	"time"

	"github.com/gocql/gocql"
)

type Config struct {
	IPs               []string
	Connections       int
	Datacenter        string
	KeySpace          string
	Timeout           time.Duration
	KeepaliveInterval time.Duration
}

func main() {
	var ProtoVersion byte = 4

	config := Config{
		IPs:               []string{"192.168.100.21"},
		Connections:       100,
		Datacenter:        "dc1",
		KeySpace:          "kiwi1",
		Timeout:           250 * time.Second,
		KeepaliveInterval: 5 * time.Second,
	}

	configuration := gocql.NewCluster(config.IPs...)
	configuration.NumConns = config.Connections
	configuration.Compressor = &gocql.SnappyCompressor{}
	configuration.ReconnectInterval = 5 * time.Second
	configuration.Consistency = gocql.LocalOne
	configuration.Keyspace = config.KeySpace
	configuration.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(
		gocql.DCAwareRoundRobinPolicy(config.Datacenter),
	)
	configuration.ProtoVersion = int(ProtoVersion)
	configuration.RetryPolicy = &gocql.ExponentialBackoffRetryPolicy{
		NumRetries: 3,
		Min:        10 * time.Millisecond,
		Max:        100 * time.Millisecond,
	}
	configuration.Timeout = config.Timeout
	configuration.SocketKeepalive = config.KeepaliveInterval

	session, err := configuration.CreateSession()
	if err != nil {
		log.Fatal(err)
	}

	b, _ := hex.DecodeString("383436354c5038373430") // token 8280534492184117680

	session.SetTrace(gocql.NewTraceWriter(session, os.Stdout))

	const stmt = "SELECT * from standard1 where key = ?"
	q0 := session.Query(stmt)
	q0.Bind(b)
	q0.Consistency(gocql.LocalOne)

	if err := q0.MapScan(map[string]interface{}{}); err != nil {
		log.Fatal(err)
	}

	time.Sleep(time.Second)
}
```

### What did you expect to see?

```
2019/02/04 13:01:03.556135: read_data: querying locally (source: 192.168.100.11, elapsed: 161)
```

### What did you see instead?

```
2019/02/04 13:17:12.76912: read_data: sending a message to /192.168.100.11 (source: 192.168.100.13, elapsed: 120)
2019/02/04 13:17:12.769426: read_data: message received from /192.168.100.13 (source: 192.168.100.11, elapsed: 5)
2019/02/04 13:17:12.769476: read_data handling is done, sending a response to /192.168.100.13 (source: 192.168.100.11, elapsed: 55)
2019/02/04 13:17:12.769617: read_data: got response from /192.168.100.11 (source: 192.168.100.13, elapsed: 617)
```

---

I did code analyses, tests and experiments, there is a number of issues with tokenAwareHostPolicy when it comes to replica selection:

* in `tokenAwareHostPolicy::getReplicas` func `tokenAwareHostPolicy::meta` is always nil unless a keyspace changed event it received
* even when metadata is available it uses the calculated token value of a partition key to find replicas, however, the replicas are stored in a map where the key is the primary replica token aka the end_token (nodetool describering)
* when a node is added or removed replicas are not updated

Please find fixes in PR https://github.com/gocql/gocql/pull/1261.

**Comment by Zariel** [comment]
Thanks for investigating this and reporting it. Looking at it the token aware policy just feels plain wrong, and the abstractions we have for picking hosts down the policies is also not sufficient.

We also make the replica finding method far too complicates, when in reality we just need to walk around the ring until we have the target RF.

I'll put together a PR to rewrite the host selection and make another issue to improve the host selection policies, fundamentally it feels like the token aware policy should also be DC aware, in that a user should be able to say, use DC1 then fallback to DC2 then DC3.

**Comment by didip** [comment]
Thumbs up on this: `it feels like the token aware policy should also be DC aware, in that a user should be able to say, use DC1 then fallback to DC2 then DC3`

We are using extra `HostFilter` as a work around for it.

**Comment by mmatczuk** [comment]
Fundamentally it feels like token + DC aware host selection policy should be the default.

**Comment by mmatczuk** [comment]
@Zariel shall we close this ticket since #1261 is merged?

**Comment by alourie** [comment]
@mmatczuk I'll close this ticket for now and we can reopen/create a new one if we see an issue with the `tokenAwareHostPolicy`.
