### ISSUE TITLE
CreateSession not finding other nodes in cluster

### ISSUE THREAD

**Issue by huttotw** [gocql/gocql#1266]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.3

### What version of Gocql are you using?
master

### What did you do?
Noticed in our metrics that 2 of our 5 nodes were not handling any writes or reads.
Here is a [graph](https://ibb.co/3yGJRPJ).

### What did you expect to see?

I expect to see reads/writes hitting every node.

### What did you see instead?

Reads/writes are only hitting the 3 nodes that were given as seeds to gocql.ClusterConfig.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
Here is my [nodetool status](https://ibb.co/fNW77Q1)

- output of `SELECT peer, rpc_address FROM system.peers`
Here is my query [peer and rpc_address](https://ibb.co/4S4677D)

- rebuild your application with the `gocql_debug` tag and post the output

**Comment by huttotw** [comment]
I have confirmed that for some reason we are not discovering non-seed nodes. When we specify every node as a seed, it works as intended.

Furthermore, using the Cassandra stress test tool, load is distributed across all nodes evenly? What difference is there in the discovery logic of this package? Any ideas?

**Comment by alourie** [comment]
@huttotw just out of curiosity, would simple python client work? Basically, Cassandra supplies the list of the other nodes, so it should work fine...

**Comment by huttotw** [comment]
@alourie this turned out to be an issue with the `rpc_address`, it was pointing to the Docker ip rather than the EC2's IP address. Once I changed that, discovery worked as intended.
