### ISSUE TITLE
proposal: add RouteTable translator

### ISSUE THREAD

**Issue by rjeczalik** [gocql/gocql#1267]
Hey!

I'd want to propose adding new API to gocql package - a RouteTable type, which would be responsible for translating addresses basing on a static list of routes.

The motivation behind the proposal is to ease the effort required to setup a gocql driver to work with e.g. Cassandra clusters which use broadcasting over a private network. While translating addresses basing on a static routing table might seem like a common use-case (like mapping public to private addresses in EC2 environment), currently each gocql user needs to roll out their own solution.

Following the `gocql.IdentityTranslator()` example I propose adding a new function:

```go
func RouteTranslator(destination, target []net.IP) AddressTranslator
```

Wdyt?

**Comment by alourie** [comment]
I'm pretty sure you can implement the AddressTranslator interface having `Translate` do what you need. I don't really see the benefit of adding another function like the above.

We could implement it in the driver with something like `StaticAddressTranslator`, which might be a bit more appropriate implementation. I'm not yet completely sold on having it in the driver though, as there are multiple legitimate ways to implement it.

**Comment by martin-sucha** [comment]
This can be easily implemented outside of gocql package. The mapping will likely be different for each cluster and you can already implement AddressTranslator as needed. Closing.
