### ISSUE TITLE
Cannot update, "bind variables are not supported inside collection literals" of type list<frozen<type>>

### ISSUE THREAD

**Issue by leofabri** [gocql/gocql#1268]
### What version of Cassandra are you using?
I'm using Scylla 3.0.3

### What did you do?
I'm trying to update a row in my table with the following structure:
```
CREATE TYPE name.sub_topic(
    level int,
    id text,
    url text,
    title text,
    date timestamp,
);
CREATE TABLE name.test (
    id text,
    date timestamp,
    sub_topics list<FROZEN<sub_topic>>,
    PRIMARY KEY (id, date)
) WITH CLUSTERING ORDER BY (date desc);
```
#### My model
```
Topic struct {
        // Other stuff...
	SubTopics       []SubTopic   `json:"sub_topics"`
}

SubTopic struct {
	Level int       `json:"level"`
	ID    string    `json:"id"`
	URL   string    `json:"url"`
	Title string    `json:"title"`
	Date  time.Time `json:"date"`
}
```

#### The query in question:
```
data := models.SubTopic{
	Level: 1,
	ID:    "1234",
	URL:   "/some/url",
	Title: "This is a test",
	Date:  previously read timestamp,        // Type time.Time
}

q := db.Conn.Query("UPDATE table.name SET sub_topic = sub_topic + [?] WHERE id=? and date=?", data, ID, date)
```

### What did you expect to see?

I would expect to see the data to be appended to the existing list.
```
[{level: 0, id: 'abcd', url: '/existing/url', title: 'existing data', date: 2019-02-31 .... }, 
{level: 1, id: '1234', url: '/some/url', title: 'This is a test', date: 2019-02-32 ....}]

```

### What did you see instead?
I get an error telling me that I cannot bind the list.
```
Invalid list literal for sub_topics: bind variables are not supported inside collection literals
```

---
I googled for a possible solution but I didn't find much ([even though this seems quite similar](https://stackoverflow.com/questions/32405114/what-is-the-proper-way-to-add-a-udt-element-to-a-list-collection-in-cassandra-us)).

Thank you in advance for your support

**Comment by alourie** [comment]
@leofabri have you tried to use an actual list/slice instead of a single object for `data`? That's what the linked example shows to have worked.

**Comment by martin-sucha** [comment]
`Invalid list literal for sub_topics: bind variables are not supported inside collection literals` is an error message from the server.

The following should work:

```go
q := db.Conn.Query("UPDATE table.name SET sub_topic = sub_topic + ? WHERE id=? and date=?", []models.SubTopic{data}, ID, date)
```

We have since added an example https://pkg.go.dev/github.com/gocql/gocql#example-package-Set demonstrating how to add to a set, this is similar.

There wasn't any activity in this issue since 2019, so closing.
