### ISSUE TITLE
CreateSession always take a lot CPU

### ISSUE THREAD

**Issue by ccmcpp** [gocql/gocql#1275]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.3

### What version of Gocql are you using?
master

### What did you do?
	cluster := cql.NewCluster(host)
	cluster.Keyspace = space
	cluster.Consistency = cql.Quorum
	cluster.NumConns = 2
	session, err = cluster.CreateSession()
        
I use CreateSession and want to use the session to query always util the service close.
But I will take a lot cpu(30%) even I do nothing.  
It is the right way to use is CreateSession new every time to query?

 

 
 ### What did you expect to see?
        It take 0 cpu.

### What did you see instead?
         It take 0 cpu.
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by alourie** [comment]
@ccmcpp would you mind elaborating a bit? This is a pretty basic code that you're using there, what exactly happens when you do it? Do you create a query? Or just waiting in the client doing nothing?

Running profile might also help to look into this.

Thanks!

**Comment by alourie** [comment]
@ccmcpp is this still relevant? Thanks!

**Comment by ccmcpp** [comment]
Sorry for reply later.
`cluster := cql.NewCluster(host)
cluster.Keyspace = space
cluster.Consistency = cql.Quorum
cluster.NumConns = 2
session, err = cluster.CreateSession()`

And just waiting in the client doing nothing. But I not close the Session. 
It takes a lots of CPU.
Sorry for reply later again.

**Comment by alourie** [comment]
@ccmcpp I just ran this on my local laptop running Cassandra 3.11.3 under ccm. This code takes at most about 6% when starting and then drops to an insignificant number.

Any more information that you could provide about your specific case? It's really strange that it would consume this much resources, this code doesn't really do anything to justify that.

**Comment by alourie** [comment]
@ccmcpp I'm closing this for now for the lack of the widespread problem. Please let me know if it needs to be reopened.
