### ISSUE TITLE
Update with clause 'if' is not returning proper error

### ISSUE THREAD

**Issue by prishabh** [gocql/gocql#1277]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
cqlsh:testkeyspace> show version
[cqlsh 5.0.1 | Cassandra 3.6 | CQL spec 3.4.2 | Native protocol v4]

### What did you do?
1. Inserted a row with version field
2. Deleted a row
3. Trying to update a deleted row with if clause on version

### What did you expect to see?
gocql is not giving any error but
output of cqlsh:
In case of successful update (case: row exists)
![image](https://user-images.githubusercontent.com/25919671/54103088-0c0f0100-43f1-11e9-948f-ff10ba8d1717.png)

In case of update failed (case: row is deleted)
![image](https://user-images.githubusercontent.com/25919671/54103118-2ba62980-43f1-11e9-8e8a-0e288752fdaf.png)

### What did you see instead?

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by zed-rishabh** [comment]
Please closing this issue, I found API i.e MapScanCAS and ScanCAS in order to get desired result. Thanks!

**Comment by alourie** [comment]
@zed-rishabh can you please give usage examples so that next person stumbling here knows what to do? Thanks!

**Comment by zed-rishabh** [comment]
@alourie Okay, will add.

**Comment by alourie** [comment]
thanks!

**Comment by alourie** [comment]
@zed-rishabh just a check if you could add more examples, thanks!

**Comment by rivelles** [comment]
> @zed-rishabh just a check if you could add more examples, thanks!

In case someone needs examples, I went through the same issue and found this thread. I was able to make it work using `MapScanCAS`. Here is some basic code snippet that can be used:

```
m := make(map[string]interface{})
applied, _ := s.session.Query("your query").MapScanCAS(m)
if !applied {
    // A conflict happened
} else {
    // Update succeeded
}
```
