### ISSUE TITLE
Helpers function goType lacks TypeTime support

### ISSUE THREAD

**Issue by dahankzter** [gocql/gocql#1284]
### What version of Gocql are you using?
Latest.

### What did you do?
Inserting and reading from a table containing "time" columns.

### What did you expect to see?
A proper time being read.

### What did you see instead?
panic as seen in #1283

**Comment by alourie** [comment]
@dahankzter is this solved by #1286 ?

**Comment by dahankzter** [comment]
It is indeed @alourie , closing.

**Comment by alourie** [comment]
:+1:
