### ISSUE TITLE
Invalid peers should be ignored when checking for schema agreement

### ISSUE THREAD

**Issue by tobgu** [gocql/gocql#1298]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11

### What version of Gocql are you using?
0.0.0-20181117210152-33c0e89ca93a

### What did you do?
Ran migrations through gocqlx

### What did you expect to see?
Migrations finish successfully and quickly.

### What did you see instead?
Migrations take 60 seconds (The timeout to wait for schema agreement)

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
Cassandra is running as statefulset within kubernetes. Whenever a cassandra POD is recreated it will receive a new IP address. The old peers will remain in the peers table for some time though.

During initial connection gocql will handle this gracefully and ignore the peers that are not valid with an error message such as the below:
```
2019/04/10 14:20:16 Found invalid peer '[HostInfo connectAddress="10.42.1.7" peer="10.42.1.7" rpc_address="<nil>" broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="10.42.1.7" connect_addr_source="connect_address" port=9042 data_centre="" rack="" host_id="a9bae1a8-379f-488e-a5f3-35e836b1d730" version="v0.0.0" state=UP num_tokens=0]' Likely due to a gossip or snitch issue, this host will be ignored
```

When executing queries that affect the schema version of the cluster no such check is done though. This means that `awaitSchemaAgreement` will wait until timeout for the schema versions to match, even though the cluster is fine.

`awaitSchemaAgreement` should make use of `isValidPeer` or similar and only consider valid peers when checking of schema agreements.

```
cqlsh> select peer, rpc_address from system.peers;

 peer       | rpc_address
------------+-------------
 10.42.6.23 |        null
  10.42.1.3 |   10.42.1.3
 10.42.6.10 |  10.42.6.10
 10.42.6.16 |  10.42.6.16
```

**Comment by alourie** [comment]
@tobgu please check #1300

**Comment by tobgu** [comment]
@alourie Cool, looks great! Thanks!
