### ISSUE TITLE
Consider exposing awaitSchemaAgreement

### ISSUE THREAD

**Issue by muirdm** [gocql/gocql#1301]
Wanted to see what others thought about adding `func (*Session).AwaitSchemaAgreement() error` as a public method.

I'm running schema changes from gocql and I want to make sure the schema is in agreement after every schema change. gocql has built-in calls to awaitSchemaAgreement, but it doesn't propagate an error. I could query system.peers myself, but you also need to query the coordinator's system.local to get the full list. gocql doesn't really provide a way to query a specific node (that I know of) short of making a second cluster with host limiting config. It would be convenient if I could just depend on gocql's already implemented logic to check the entire ring's schema version.

**Comment by alourie** [comment]
@Zariel your opinion? I can make the change as a part of #1300

**Comment by annismckenzie** [comment]
I added this in #1395 – I'd like to use it in gocqlx's issue https://github.com/scylladb/gocqlx/issues/106 to await schema agreement before applying each statement in a migration. Thoughts?

**Comment by annismckenzie** [comment]
This was added in #1395. Close this issue?

**Comment by alourie** [comment]
@annismckenzie Please do :-) Thanks!

**Comment by annismckenzie** [comment]
I can't! :D

**Comment by alourie** [comment]
haha, fine :-)
