### ISSUE TITLE
Can't unmarshal date

### ISSUE THREAD

**Issue by ndjordjevic** [gocql/gocql#1302]
Hi,

To what golang datatype I should unmarshal cassandra date?

```
	var expirationDate string
	iter := session.Query(`SELECT market, isin, currency, short_name, long_name, status, expiration_date FROM instruments`).Iter()
	for iter.Scan(&market, &isin, &currency, &shortName, &longName, &status, &expirationDate) {
		log.Println("Instrument:", market, isin, currency, shortName, longName, status, expirationDate)
	}

```
To a string doesn't work.

**Comment by ndjordjevic** [comment]
I guess it does unmarshal it to time.Time

**Comment by alourie** [comment]
@ndjordjevic yes it does. But also, with #1276 you should be able to unmarshal to string as well, so please try the latest master.

**Comment by alourie** [comment]
@ndjordjevic any updates on this?

**Comment by ndjordjevic** [comment]
Unmarshaling to time.Time worked for me perfectly... Haven't tried https://github.com/gocql/gocql/pull/1276... So I guess u can close it

**Comment by alourie** [comment]
@ndjordjevic Thanks!
