### ISSUE TITLE
Is it a bad thing that developers can configure DisableSchemaEvents? 

### ISSUE THREAD

**Issue by guanw** [gocql/gocql#1303]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.0.14

### What version of Gocql are you using?
181004e14a3fb735efcc826a4256369d0c96747b

### What did you do?
As developers we can easily set the `DisableSchemaEvents` to true which would disable keyspace updates as well as meta data changes that could affect how policy select host(At least what I understand from the code?) Isn't this a bad thing? Why was this being exposed at the first place. If a developer set it to true wouldn't that just cause driver to have stale data?

Are there scenarios where it's correct to set it to true?  We have applications that was using this tokenAwarePolicy but was thinking to replace it with `DCAwareRoundRobinPolicy ` but just want to ask this question first. Thanks in advance.

### What did you expect to see?
Not applicable

### What did you see instead?
Not applicable

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by alourie** [comment]
@guanw in other drivers you would have similar facilities. For example in Java driver, you can create an event listener that you then register for the schema updates.

I don't see anything specifically bad with it. I can think of short-burst scenarios, where the client would create/kill short-lived connections to the cluster without keeping any traces. In these scenarios, you might not care for the schema changes and hence use this option.
