### ISSUE TITLE
Having problems with gocql for INSERTS

### ISSUE THREAD

**Issue by stevef1uk** [gocql/gocql#1304]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.2

### What version of Gocql are you using?
commit 2e9f2912ba58e37f34af3554659b576eac655760
Author: Zhixin Wen <john.wenzhixin@hotmail.com>
Date:   Sat Feb 24 01:24:22 2018 -0800

### What did you do?
Hi, I have written a tool using go-swagger & gocql to generate RESTful services to Read and Insert data into a Cassandra table using it's definition as input. See: https://github.com/stevef1uk/cassuservice for more details

I have managed to generate code that uses gocql to handle most table types I have created, including ones that use UDTs, so that is all looking good :-)

For the new code I have added to generate table inserts (using POST service) I am having a number of challenges and would appreciate some advice.

### What did you see instead?
1. I have been unable to use curl to insert a timeuuid field. 
2. I have been unable to use curl to create a decimal value. 
2. I have found that UDTs are not populated by the data passed

**Comment by alourie** [comment]
@stevef1uk I don't see how is that related to gocql specifically, but could you elaborate on what "unable to curl" or "UDTs are not populated" mean in your case?

**Comment by stevef1uk** [comment]
Alex, you probably need to try my tool to understand this. Basically, I create a swagger specification from the Cassandra DDL and then use go-swagger to provide a framework for the gocql handler logic that I generate. I this have two different data models in play, that used by go-swagger and that required by gocql. I use curl to access the service via go-swagger, which then forwards it to my handler and thus to gocql. 

The problem I have with the data conversions is in going from the go-swagger type to the go-cql type. In one case, Decimal when go-cql uses the gopkg.in/inf.v0 package I can't see anyway to create a Dec type with anything but a string representing an integer!

**Comment by alourie** [comment]
@stevef1uk could you provide a couple of specific examples, like in the generated code, what is received by go-swagger and what is expected by gocql?

**Comment by Zariel** [comment]
fundamentally as @alourie this is not related to gocql

**Comment by stevef1uk** [comment]
I disagreed. I think a number of issues are gocql related. I will raise individual issues.

**Comment by Zariel** [comment]
I am not going to debug programs that use gocql, if you can create a reproducible case that shows an error in what gocql is doing then fine, but something being broken between a web frontend and gocql is not a problem with the driver. On the other hand if you want to create inf.Dec some other way then create a feature request with that project.

**Comment by stevef1uk** [comment]
I understand & accept your position. The type inf.NewDec is one used by your driver. Unless I have completely lost the plot? 

I was looking at the cassandra_test.go file for how to generate inserts. Line 915 has:
m["testdecimal"] = inf.NewDec(100, 0)

Not sure how I could populate decimal fields without using integers ?

The code I have generated from a very simple table example:

CREATE TABLE demo.Decimal (
    id int PRIMARY KEY,
    dec decimal,
);


is:
// GENERATED FILE so do not edit or will be overwritten upon next generate
package data

import (
    "github.com/stevef1uk/test4/models"
    "github.com/stevef1uk/test4/restapi/operations"
    middleware "github.com/go-openapi/runtime/middleware"
    "github.com/gocql/gocql"
    "os"
    "log"
	"gopkg.in/inf.v0"
	"strconv"
	
    "github.com/stevef1uk/test4/restapi/operations/decimal"
     
)


var cassuservice_session *gocql.Session

func SetUp() {
  var err error
  log.Println("Tring to connect to Cassandra database using ", os.Getenv("CASSANDRA_SERVICE_HOST"))
  cluster := gocql.NewCluster(os.Getenv("CASSANDRA_SERVICE_HOST"))
  cluster.Keyspace = "demo"
  cluster.Consistency = gocql.One
  cassuservice_session, err = cluster.CreateSession()
  if ( err != nil ) {
    log.Fatal("Have you remembered to set the env var $CASSANDRA_SERVICE_HOST as connection to Cannandra failed with error = ", err)
  } else {
    log.Println("Yay! Connection to Cannandra established")
  }
}

func Stop() {
    log.Println("Shutting down the service handler")
  cassuservice_session.Close()
}

func Search(params operations.GetDecimalParams) middleware.Responder {

    var ID int64
    _ = ID
    var Dec *inf.Dec
    _ = Dec
    _ = models.Decimal{}

    codeGenRawTableResult := map[string]interface{}{}

    if err := cassuservice_session.Query(` SELECT id, dec FROM decimal WHERE id = ? `,params.ID).Consistency(gocql.One).MapScan(codeGenRawTableResult); err != nil {
      log.Println("No data? ", err)
      return operations.NewGetDecimalBadRequest()
    }
    payLoad := operations.NewGetDecimalOK()
    payLoad.Payload = make([]*operations.GetDecimalOKBodyItems0,1)
    payLoad.Payload[0] = new(operations.GetDecimalOKBodyItems0)
    retParams := payLoad.Payload[0]
    tmp_ID_0 := codeGenRawTableResult["id"].(int)
    ID = int64(tmp_ID_0)
    retParams.ID = &ID
    Dec = codeGenRawTableResult["dec"].(*inf.Dec)
    tmp_Dec_1,_ := strconv.ParseFloat(Dec.String(), 64 )
    retParams.Dec = &tmp_Dec_1
    return operations.NewGetDecimalOK().WithPayload( payLoad.Payload)
    }

func Insert(params decimal.AddDecimalParams) middleware.Responder {

    m := make(map[string]interface{})
    
    
    m["id"] = params.Body.ID
    m["dec"] = params.Body.Dec
    if err := cassuservice_session.Query(` INSERT INTO decimal(id, dec) VALUES (?,?)`,m["id"],m["dec"]).Consistency(gocql.One).Exec(); err != nil {
      return decimal.NewAddDecimalMethodNotAllowed()
    }
    return decimal.NewAddDecimalCreated()

Having inserted a simple row in I get:
$curl -X GET "http://127.0.0.1:5000/v1/decimal?id=1"
[{"dec":1.23456,"id":1}]

which is fine.

However, if I try to insert using:
$curl -d '{"id": 2, "dec":3.456}' -H "Content-Type: application/json" -v -X POST http://localhost:5000/v1/decimal

I get:
error: can not marshal float64 into decimal

Now, I accept that the float64 is coming from go-swagger, but I need to work out how I can convert to the type supported by gocql.
