### ISSUE TITLE
Cassandra returns error but operation succeeds

### ISSUE THREAD

**Issue by longquanzheng** [gocql/gocql#1308]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Cassandra 3.100.14.514

### What version of Gocql are you using?
https://github.com/gocql/gocql/commit/70385f88b28b43805bd83d212169ab2d38810b15

### What did you do?

We found that Cassandra can return timeout error but the actual operation succeeded. https://github.com/gocql/gocql/blob/master/conn.go#L1441

Is there a way to know all those errs of this kind?

Here is the background why we need this: We are using two phase commit:
```
1) append data to tableA
2) execute LWT on tableB
3) So if 2) fails we need to clean up the data written into tableA. 

Otherwise we lost data.
```
Previously we always clean up in 3) if we got any error from 2), which is wrong for ErrorTimeoutNoReponse. This error simply means the result is unknown. So we should whitelist this error. But we don't know what are the other errors that should also be whitelisted.

Alternative: What we can also do is instead of whitelisting, we do backlisting. We only clean up in 3) for certain error that we know that 2) doesn't succeed. But from the gocql code, I don't know how to find all of them. If we don't clean up correctly in those case, we may leak some data that will never be deleted.

**Comment by alourie** [comment]
@longquanzheng what seems to be happening here is phase 2 takes longer than the gocql's default timeout for waiting for the response. You can try to set it for longer and see if it helps.

You should definitely not whitelist/backlist the error, as it may appear in any other scenario, and it should be properly handled and not ignored. This error is not specific, it just means that the driver doesn't know the result of the last command as it didn't get the reply in time.

**Comment by longquanzheng** [comment]
@alourie thanks for your response. I found an article for this topic. 
https://www.datastax.com/dev/blog/how-cassandra-deals-with-replica-failure
And we finally decided to assume  two types of errors as potential succeeds:
https://github.com/uber/cadence/blob/master/common/persistence/cassandra/cassandraPersistence.go#L4390
