### ISSUE TITLE
Add the ecAudit plugin for username/password auth

### ISSUE THREAD

**Issue by CH-JosephBironas** [gocql/gocql#1320]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11 + the ecAudit plugin

### What version of Gocql are you using?
multiple

### What did you do?
Tried to implement two monitoring systems that use gocql as a connector to a backend cassandra cluster with compliance requirements for audit logging.

### What did you expect to see?
I expect username/password auth to not be blocked by a whitelist of allowed plugins.

### What did you see instead?

2019/06/11 17:41:06 gocql: unable to dial control conn <redacted>: unexpected authenticator "com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator"                                {"level":"fatal","ts":1560274866.5549803,"caller":"collector/main.go:87","msg":"Failed to init storage factory","error":"gocql: unable to create session: control: unable to connect to initial hosts: unexpected authenticator \"com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator\"","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:87\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:177\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}

---

Please add "com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator" plugin to the whitelist of acceptable plugins maintained here:
https://github.com/gocql/gocql/blob/master/conn.go#L27

This plugin is a drop in replacement for username/password auth that provides compliant audit logging. An alternative would be to remove the whitelist, but that might not be desirable for some reasons I haven't thought of.

**Comment by martin-sucha** [comment]
Closing as this seems to be solved with #1321 .
