### ISSUE TITLE
Export gocql.errSyntax & friends

### ISSUE THREAD

**Issue by kostja** [gocql/gocql#1335]
I am writing a general purpose CQL console and need to produce a nice, informative output for any kind of server error. gocql returns a distinct type for some server codes, and a generic RequestError for remaining codes.

There is even a TODO in the source code: 
https://github.com/gocql/gocql/blob/master/frame.go#L705
    // TODO(zariel): we should have some distinct types for these errors

Thanks to lack of the aforementioned distinct types, and lack of export for err* codes, I now have to copy-paste the const error codes array into my application and add some nice mapping for them. I guess whoever wants to know the detailed error code has to do the same, since there is no export even for a syntax error (errSyntax), which is very common for console tools.

I can submit a patch.

**Comment by alourie** [comment]
@kostja if you submit a patch, I promise to promptly review it ;-)

Otherwise, we might get to it ourselves when the time allows.

Thanks!
