### ISSUE TITLE
cancellation of a single query affects multiple queries in the same session

### ISSUE THREAD

**Issue by nightlyone** [gocql/gocql#1341]
### What version of Cassandra are you using?
3.4.0
### What version of Gocql are you using?
latest master at https://github.com/gocql/gocql/commit/df4b9cc330307b4a196f255fc0d1e8a53cabfbcd
### What did you do?
- start a new cassandra session
- run a statement in multiple queries multiple times concurrently in multiple Go routines each.
- statements created with `session.Query(selectStatement, x).WithContext(ctx)`
- each statement gets a different `ctx`
- one of thoese `ctx` variables is an already canceled context
### What did you expect to see?
Only the statement with the canceled context should receive the cancellation error.
### What did you see instead?
All statements running concurrently with the cancelled statement get cancelled.

**Comment by nightlyone** [comment]
Observation: 
```diff
diff --git a/conn.go b/conn.go
index 553292a..6acf627 100644
--- a/conn.go
+++ b/conn.go
@@ -835,6 +835,11 @@ func (c *Conn) exec(ctx context.Context, req frameWriter, tracer Tracer) (*frame
        if !ok {
                return nil, ErrNoStreams
        }
+       if ctx != nil {
+               if ctxErr := ctx.Err(); ctxErr != nil {
+                       return nil, ctx.Err()
+               }
+       }
 
        // resp is basically a waiting semaphore protecting the framer
        framer := newFramer(c, c, c.compressor, c.version)
```
seems to either fix or at least workaround this issue. But I am not very confident that this is the right fix.

**Comment by alourie** [comment]
@nightlyone Just out of curiosity, why is one of the `ctx`es is cancelled?

In any case, I would place this check in the `WithContext` call on Query rather than on `conn`. If the context is cancelled during that `conn` call, it would quickly get to https://github.com/gocql/gocql/blob/master/conn.go#L921 with the result as above in your example.

**Comment by martin-sucha** [comment]
I did not notice this issue before. Please check if https://github.com/gocql/gocql/pull/1352 fixes your issue as well.

**Comment by nightlyone** [comment]
Just confirming that this issue has been resolved with Zariels changes. The session.Close issues (not reported but discussed) as well as the cancellation issue reported here. So thank you @Zariel and @martin-sucha for the great work.
