### ISSUE TITLE
Connection pool in cql session

### ISSUE THREAD

**Issue by mjmanav4** [gocql/gocql#1346]
ClusterConfig has many parameters that can be tuned according to requirement

```
NumConns           int  
SocketKeepalive    time.Duration  
PoolConfig PoolConfig
```
```
	cluster = gocql.NewCluster(strings.Split(hosts ",")...)
	cluster.Port = 9042
cluster.Consistency = gocql.One
	cluster.Keyspace = "abc"
	cluster.NumConns = 5
	cluster.Timeout = 200 * time.Millisecond```

how to config poolConfig for cql cluster

**Comment by alourie** [comment]
`PoolConfig` is an object that wraps around the `HostSelectionPolicy` interface. The default is RoundRobin policy, which is good enough for many cases, but if you look into `policy.go`, there is a TokenAwarePolicy as well implemented. To "set" it manually you simply use `cluster.PoolConfig.HostSelectionPolicy = ...` and use either a function call that returns the policy (i.e. `RoundRobinHostPolicy()` or the actual policy object.
