### ISSUE TITLE
Upgrade gocql version causes for loop iter.Scan() to mess up slice 

### ISSUE THREAD

**Issue by Tommy-42** [gocql/gocql#1348]
### What version of Cassandra are you using?
3.11.4

### What version of Gocql are you using?
3540fc649cd7fc57cef5612b7bacac7a4fc443d6
16cf9ea1b3e28090d416d36528f304e4553e6b56

### What did you do?
I upgraded gocql from 3540fc6 to 16cf9ea

It appears that the code below doesn't works well anymore
```
var keys []models.Key
var key models.Key

for iter.Scan(&key.X, &key.Y, &key.Z) {
    keys = append(keys, key)
}
```

where :
X is `string`
Y is `[]byte`
Z is `[]byte`

### What did you expect to see?
---->
X: private
Y: foo
Z: bar
---->
X: public
Y: fuzz
Z: buzz

### What did you see instead?
---->
X: private
Y: fuzz
Z: buzz
---->
X: public
Y: fuzz
Z: buzz

---

for instance it was run & tested on go 1.10.8 on OSX

Everything works well with 3540fc6 but when updated to 16cf9ea the data got messed up somehow :(

Do you have any Idea why it could happen ?

To reproduce that I just need to upgrade the glide and fetch one of the version listed above.

**Comment by Tommy-42** [comment]
I've manage to make it work by reseting the `key` value to default value

```
var keys []models.Key
var key models.Key

for iter.Scan(&key.X, &key.Y, &key.Z) {
    keys = append(keys, key)
    key = models.Key{} // fix here
}
```

I still don't know why it work without it with the old version ...

**Comment by omosu** [comment]
Hi @Tommy-42, I have found changes in `Unmarshal` func.

https://github.com/gocql/gocql/commit/f596bd36e19ecaa7a9be478cf137fedc75036b02#diff-984b621d683cf81bbf404d291c4802a8R235

But for me is unclear what behavior should be: clean after append or gocql lib should copy values to the new array.

**Comment by Tommy-42** [comment]
Yep, 
I don't mind cleaning it after or the lib doing it but either way it should be documented somewhere :D 
especially in the example in the readme

**Comment by Zariel** [comment]
As far as I am aware this is behaving as expected, the address of `key.X` is the same for each iteration, the value is copied into the slice which has its own memory but the pointer to the slice is the same. See https://play.golang.org/p/ayzN8-UzASS

The interface for reading from the iter doesn't help this, use `iter.Scanner()` instead then it is more obviously correct.

**Comment by jeffwidman** [comment]
Yes, it's behaving as expected, but it's also confusing... especially given that the readme example promotes falling into this trap.
