### ISSUE TITLE
panic: first replica is not the primary replica for the token

### ISSUE THREAD

**Issue by guo0693** [gocql/gocql#1349]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

[cqlsh 5.0.1 | Cassandra 3.0.14.32 | CQL spec 3.4.0 | Native protocol v4]

keyspace replica: replication = {'class': 'NetworkTopologyStrategy', 'dca1': '2'}

### What version of Gocql are you using?

revision = "16cf9ea1b3e28090d416d36528f304e4553e6b56"

### What did you do?

Change DCAwareRoundRobinPolicy to TokenAwareHostPolicy(DCAwareRoundRobinPolicy)

### What did you expect to see?
Correctly initialized session for read/write

### What did you see instead?

This is different from the similar issue I found from this repo, there is no node add/remove, when we deploy the change and try to create session, the exception was thrown.

panic: first replica is not the primary replica for the token

goroutine 971 [running]:
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.(*networkTopology).replicaMap(0xc01c5445b8, 0xc010df5b00, 0x83, 0x83, 0xc030916000, 0x8300, 0x9d55, 0xc000bf2000)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/topology.go:203 +0x1366
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc00257e000, 0xc002862310, 0xc0015a2320, 0xe)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/policies.go:468 +0x2b9
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc00257e000, 0xc0015a2320, 0xe, 0x0, 0x0)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/policies.go:452 +0x9a
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.(*Session).init(0xc008536e00, 0xc00257e070, 0x0)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/session.go:256 +0x3cb
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.NewSession(0xc00274f000, 0x41, 0x80, 0x167581a, 0x5, 0x4, 0x2540be400, 0x0, 0x6b4c, 0xc0015a2320, ...)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/session.go:161 +0x824
code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
	code.uber.internal/infra/jaeger/vendor/github.com/gocql/gocql/cluster.go:185
code.uber.internal/infra/jaeger/cmd/ingester/app/cassandra.NewSession.func1(0xc0000d3f80, 0x16b4879, 0x2e, 0x0)
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by funny-falcon** [comment]
I have similar issue but with two DC and keyspace with replication only on single DC:
For example:
```go
package main

import (
	"log"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("127.0.1.1")
	cluster.Keyspace = "testkv"
	rr := gocql.DCAwareRoundRobinPolicy("dc1")
	cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(rr)
	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}
	defer session.Close()
}
```

With two DC running on localhost (of cause I have an issue in production. But it is easily reproduced in such simple local setup).
```
$ nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.1.1  179,66 KiB  256          100,0%            5ff09954-d433-462e-9c00-98a07868142d  rack1
Datacenter: dc2
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.1.2  189,7 KiB  256          0,0%              49614024-f089-40b0-88ab-104ebab706d4  rack1
```

And keyspace:
```
cqlsh> describe testkv;             
                                                         
CREATE KEYSPACE testkv WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': '1'}  AND durable_writes = true;
```

And panic stacktrace is same to above:
```
panic: first replica is not the primary replica for the token: expected 127.0.1.1 got 127.0.1.2

goroutine 1 [running]:
github.com/gocql/gocql.(*networkTopology).replicaMap(0xc000196078, 0xc000096380, 0xc000196078, 0x0, 0x0)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/topology.go:261 +0x17d1
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc0001383f0, 0xc000012b80, 0x706d53, 0x6)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/policies.go:449 +0x25f
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc0001383f0, 0x706d53, 0x6, 0x0, 0x0)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/policies.go:434 +0x99
github.com/gocql/gocql.(*Session).init(0xc000122380, 0xc000142180, 0x0)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/session.go:280 +0x5ca
github.com/gocql/gocql.NewSession(0xc000012960, 0x1, 0x1, 0x706956, 0x5, 0x0, 0x23c34600, 0x23c34600, 0x2352, 0x706d53, ...)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/session.go:166 +0x809
github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
        /home/yura/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200228163523-cd4b606dd2fb/cluster.go:194
main.main()
        /home/archive/cassandra_cluster/test_app/main.go:14 +0x2aa
```
As you can see in stack trace folders, gocql is the latest commit (but from 20190927095247-bd5f930c6137 fails in similar way).

When keyspace replication is set to both DC (i.e. with `{'class': 'NetworkTopologyStrategy', 'dc1': '1', 'dc2': '1'}`), it doesn't fail. Unfortunatelly there is no way to add DC in production without being in situation when replication is set to single DC.

**Comment by funny-falcon** [comment]
It could be fixed with following simple patch in topology.go:
```diff
@@ -180,4 +180,7 @@
 
        for i, th := range tokenRing.tokens {
+               if rf := n.dcs[th.host.DataCenter()]; rf == 0 {
+                       continue
+               }
                for k, v := range skipped {
                        skipped[k] = v[:0]
```
Though I'm not sure if this patch fully correct.
