### ISSUE TITLE
Create session blocked until connection to every peer is established

### ISSUE THREAD

**Issue by jameshartig** [gocql/gocql#1365]
### What version of Cassandra are you using?
Yugabyte 2.0.1

### What version of Gocql are you using?
master (07ace3bab0f84bb88477bab5d79ba1f7e1da0169)

### What did you do?
When creating a session without `DisableInitialHostLookup` then the session will not be blocked from being created if ANY of the peers are down until the reconnect policy fails. Instead, there should be an option to do the initial host lookup but only connect to other hosts asynchronously.

### What did you expect to see?
I expected the session to be created and asynchronously connect to other peers.

### What did you see instead?
Instead CreateSession is blocked until a connection to all peers is established.

---
Logs with `gocql_debug`:
2019/10/22 16:03:25 gocql: Session.handleNodeUp: 10.142.0.175:9042
2019/10/22 16:03:31 connection failed "10.142.0.174": gocql: no response to connection startup within timeout, reconnecting with *gocql.ConstantReconnectionPolicy

The downside of setting `DisableInitialHostLookup` is that it won't discover any peers until a topology event. I'd like to try to connect to the peers discovered originally but not make them block. At the risk of making yet another flag, I'd like to propose adding `DisableInitialSyncPeerConnect`. If that is set to true, then after getting the peers they're connected to asynchronously and Session.init would return once one is connected. Alternatively we could call the option `RequireSinglePeer` or something.

**Comment by fastest963** [comment]
Here's what I was proposing: https://github.com/fastest963/gocql/commit/async

I thought I'd discuss it via an issue before making a PR.

**Comment by GingerMoon** [comment]
Hi @fastest963 , I created another similar (maybe) PR #1429 for the purpose of speeding up session's initialization by making filling connection pools asynchronously. I would appreciate if you could share some insights.

**Comment by martin-sucha** [comment]
Referencing my comment https://github.com/gocql/gocql/pull/1429#issuecomment-613293650 here since it is relevant to this issue in general (should have posted it here probably).

**Comment by fastest963** [comment]
I think it should be configurable and the default behavior shouldn't change. There could be people relying on it connecting to all hosts in init which is why I make it configurable. We've been using this PR in production for months now without issue.

**Comment by fastest963** [comment]
@martin-sucha I'd be fine adding a method to session instead but I would think we'd need to add a configuration knob to session in order to keep the default behavior and @Zariel was against that https://github.com/gocql/gocql/pull/1369#issuecomment-549753165.

I was adding it to the `HostSelectionPolicy` so someone could override that policy and do something custom if they wanted, or they could just leave the defaults and there'd be no introduced behavior changes by default.
