### ISSUE TITLE
Multiple statements in a single s.Query() call (for counters)

### ISSUE THREAD

**Issue by gronka** [gocql/gocql#1366]
I would like to return the value of a CQL counter immediately before (or after) I increment the counter. For the most accurate counter result, I'd like to increment the counter as close as possible to the statement in which I'm grabbing the value. Something such as:
`stmt := 'SELECT msg_id FROM convo_counters WHERE convo_uuid = ?; UPDATE convo_counters SET msg_id = msg_id + 1 WHERE convo_uuid = ?'`
or such as:
`stmt := 'UPDATE convo_counters SET msg_id = msg_id + 1 WHERE convo_uuid = ?; SELECT msg_id FROM convo_counters WHERE convo_uuid = ?'`

`msg_id` is of `counter` type

I wasn't expecting this to work, but perhaps it could be a feature request - I think the use case makes sense. If two goroutines are making separate calls to SELECT and increment the `counter`, then it's possible I end up with 2 messages with the same ID. For my use case, this is okay, but it would be nice to avoid.

I'm also open to suggestions of other ways to achieve this. It appears as though batch queries don't allow `SELECT` statements.

Note: I'm not looking for perfect atomicity. My goals: 1) minimize latency, 2) avoid silly logic loops of tracking/retrying statements.

### What version of Cassandra are you using?
3.11.4

### What version of Gocql are you using?
20190915

### What did you do?
For both of the example statements above, I tried to extract the msg_id with the following:
```
var msg_id int
iter := s.Query(stmt, payload.ConvoUuid, payload.ConvoUuid).Iter()
iter.Scan(&msg_id)
log.Info(msg_id)
```

### What did you expect to see?
I was hoping to get the value `2` after 2 messages were sent, and then to have the value in the Cassandra table be 3. If I execute simple the SELECT statement `'SELECT msg_id FROM convo_counters WHERE convo_uuid = ?'` then I get the value `2`.

### What did you see instead?
`msg_uuid` is always `0`, which I assume is simply because this is the initial value of an `int` in go.

**Comment by martin-sucha** [comment]
CQL protocol does not support running multiple queries by a single command, see https://github.com/datastax/native-protocol/blob/f025b9f4a7b5d7c724714254fa48a902386c4212/src/main/resources/native_protocol_v3.spec#L285-L342

If you want to generate unique IDs, you could just assign every instance of your application a unique instance id (for example generate a uuid on startup) and keep counter in your app. The unique message ID would then be a tuple (instance id, counter value). That way you don't need to do a query to database for every id and can ensure the ids are unique (as long as instance id is unique and counter does not overflow).

**Comment by Zariel** [comment]
This is a cassandra limitation.
