### ISSUE TITLE
Comment inside CQL always give error: Invalid amount of bind variables

### ISSUE THREAD

**Issue by kokizzu** [gocql/gocql#1386]
### What version of Cassandra are you using?
Scylla 3.x

### What version of Gocql are you using?
latest master (from gocqlx)

### What did you do?
querying with comment, this query works normally:
```
SELECT * FROM test1 WHERE id = ?; 
```

This query always error: `Invalid amount of bind variables`
```
-- test 123
SELECT * FROM test1 WHERE id = ?; 

// test 123
SELECT * FROM test1 WHERE id = ?; 

/* test 123 */
SELECT * FROM test1 WHERE id = ?; 
```

### What did you expect to see?
it should work normally

### What did you see instead?
Error: Invalid amount of bind variables

### Why is this important?
I need comments because I have a code that make debugging easier (printing file name and line number inside the CQL as comment, so I can know which CQL causes the error on runtime/debug mode.

Gocqlx said this is gocql's problem https://github.com/scylladb/gocqlx/issues/127

**Comment by Zariel** [comment]
This is cassandra reporting the error and nothing to do with the driver, you must strip out comments and split statements on ; yourself
