### ISSUE TITLE
roundRobinHostPolicy uses lots of resources for every query

### ISSUE THREAD

**Issue by muirdm** [gocql/gocql#1401]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.5

### What version of Gocql are you using?
1982a06ad6b987c24beec15336019914d71b2e31

### What did you do?
Due to #1400 we were accidentally using the round robin host selection policy for every query.

### What did you expect to see?
I expected to see normal client side performance.

### What did you see instead?
I did CPU profile and noticed 10% CPU used by `rand.NewSource`. In addition, it allocates a lot, taking up ~30% CPU via GC.

**Comment by AlexeyUzhva** [comment]
Just faced same issue.

Confirming that it happens due to excessive memory allocations.

![image_2020_02_02T09_41_25_771Z](https://user-images.githubusercontent.com/1519328/73606418-16169100-45bb-11ea-9ee7-95aa1fcb8443.png)

**Comment by AlexeyUzhva** [comment]
Submitted merge request for that. Please review. It's not only memory efficient, and also faster :)

**Comment by Zariel** [comment]
can we just pool rands?

**Comment by AlexeyUzhva** [comment]
Already attached MR which eliminates random and array copying. It just uses single atomic counter which is interpreted of start offset for host selection.

So, no copying at all, and no expensive random calls. Saves 60% of allocations of entire library!...

**Comment by AlexeyUzhva** [comment]
@Zariel why do we need to have random at all? Random is slow, and also requires array copying.

In our project we use high throughput submission something around 300k queries per second. It means 300k arrays allocations per second, 300k shuffles per second.

This is considerable GC overhead just to make a copy of it.

While it's not necessary at all. It's enough just to loop array from incremental offset without any copies of it.

**Comment by nightlyone** [comment]
@Zariel / @AlexeyUzhva I am not sure doing this completely without randomness is a good idea. If you have N machines accessing the same set of M Cassandra hosts and all N start talking to machine node X, overloading it and iterating all the way through the M Cassandra hosts. 

Would you mind randomizing at least the start of that iteration on session creation and maybe also when changing the set of hosts?

**Comment by AlexeyUzhva** [comment]
Hi, randomising initial list of hosts sounds like a good idea. May add so.

**Comment by AlexeyUzhva** [comment]
@nightlyone I've added to the MR randomising of initial offset. Now every client start counting from different (random) position. And it's still allocation free.
