### ISSUE TITLE
To many goroutine create when `Iter.Scan` very fast

### ISSUE THREAD

**Issue by Sasasu** [gocql/gocql#1411]
### What version of Cassandra are you using?
Any

### What version of Gocql are you using?
master

### What did you do?
Do query

### What did you expect to see?
Good performance

### What did you see instead?
Bad performance

https://github.com/gocql/gocql/blob/9b1842907e238671a483cc064a3a6cdd92ae6c53/session.go#L1408-L1410

![image](https://user-images.githubusercontent.com/12945182/75519046-4f68e200-5a3d-11ea-953f-dcfa5ecd7077.png)

page size is the default value (5000), prefetch = 0.25

my code cost 50ns for each row (`memcopy` workload). Cassandra spends 15ms on each page.

gocql will create `5000*0.25 = 1250` goroutine for each page, all block in one mutex lock (`once.Do`).

In the flamegraph
  > ` 5.28%` `runtime.newproc`
  > `10.49%` `sync.(*Mutex).Lock`
  > ` 4.75%` `sync.(*Mutex).UnLock` 
  > ` 3.02%` `runtime.goexit0`    
  > ` 3.02%` `runtime.park_m`

**Comment by Zariel** [comment]
we should use a single goroutine to do the paging and pass results on a channel back to the iter, then if reading is too slow the user can increase the prefetch rate.

**Comment by Sasasu** [comment]
`Iter.Scan` contain `iter.pos++` which is thread-unsafe. means `Iter.Sacn` is thread-unsafe.

How about just add `hasPrefetched` on `Iter`?

**Comment by hummerd** [comment]
We have same problem. ~800 reading routines created about 2Mi (~1800000) fetching routines. I've created PR #1496 with proposal to fix that.

**Comment by martin-sucha** [comment]
Now that #1496 has been merged, this issue can be closed.
