### ISSUE TITLE
AWS MCS cannot handle Any Consistency

### ISSUE THREAD

**Issue by mattmassicotte** [gocql/gocql#1420]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Amazon AWS MCS

### What version of Gocql are you using?
v0.0.0-20200203083758-81b8263d9fe5

### What did you do?
Attempted to connect MCS with a cluster Keyspace specified.

### What did you expect to see?
No issues.

### What did you see instead?
Recently, MCS began denying queries that use the ANY consistency level. This is definitely a bug in MCS. However, gocql will unconditionally use ANY when setting a keyspace on a session.

```
failed to connect to 3.83.170.141:9142 due to error: Consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
```

As a workaround, you can just not specify a keyspace in your `ClusterConfig`. Or, you can make a change to conn.go's UseKeyspace, to use a consistency level MCS does support. While it makes far more sense for MCS to support ANY as well, I figured I'd open an issue just in case.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

```
 peer         | data_center | host_id                              | preferred_ip | rack      | release_version | rpc_address  | schema_version                       | tokens
--------------+-------------+--------------------------------------+--------------+-----------+-----------------+--------------+--------------------------------------+---------------------------------------------
 3.83.171.140 |   us-east-1 | 6d916d92-3bd6-37c6-9c2e-888c93da51a5 | 3.83.171.140 | us-east-1 |          3.11.2 | 3.83.171.140 | 05deae2d-6405-494d-a965-c0e5836bcb3c |  {'37809151880104273718152734159085356828'}
 3.83.170.141 |   us-east-1 | c7322060-65ca-3bf1-a844-e9836ab89f9a | 3.83.170.141 | us-east-1 |          3.11.2 | 3.83.170.141 | 05deae2d-6405-494d-a965-c0e5836bcb3c |  {'75618303760208547436305468318170713656'}
 3.83.168.141 |   us-east-1 | d4ddea0e-245a-3204-bbd6-079f60d5a51c | 3.83.168.141 | us-east-1 |          3.11.2 | 3.83.168.141 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'113427455640312821154458202477256070484'}
 3.83.171.152 |   us-east-1 | e189316b-b453-320b-a934-d8c08812cc32 | 3.83.171.152 | us-east-1 |          3.11.2 | 3.83.171.152 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'151236607520417094872610936636341427312'}
 3.83.170.153 |   us-east-1 | 98a9b954-f8f5-33b4-9bf9-25e7978a5def | 3.83.170.153 | us-east-1 |          3.11.2 | 3.83.170.153 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'189045759400521368590763670795426784140'}
 3.83.168.153 |   us-east-1 | 731d1d59-af51-32ff-80d1-3d1c2a768d59 | 3.83.168.153 | us-east-1 |          3.11.2 | 3.83.168.153 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'226854911280625642308916404954512140968'}
 3.83.169.143 |   us-east-1 | 982e0bb8-57e6-3c03-b8ad-6cba28147d0f | 3.83.169.143 | us-east-1 |          3.11.2 | 3.83.169.143 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'264664063160729916027069139113597497796'}
 3.83.168.151 |   us-east-1 | a5e96481-95f8-3224-a516-5ff5f156a294 | 3.83.168.151 | us-east-1 |          3.11.2 | 3.83.168.151 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'302473215040834189745221873272682854624'}
 3.83.170.143 |   us-east-1 | a77b5d20-7bb8-31c3-8485-f89cf3d3ea80 | 3.83.170.143 | us-east-1 |          3.11.2 | 3.83.170.143 | 05deae2d-6405-494d-a965-c0e5836bcb3c | {'340282366920938463463374607431768211452'}
```

**Comment by mattmassicotte** [comment]
@danilop another one you might be interested in. Appears this is a recent change in behavior on the MCS side.

**Comment by Zariel** [comment]
Can we please not report upstream issues here. This issue tracker for issues with gocql itself, not Cassandra, MCS, Scylla or any other upstream system.

@danilop is there any where users/we can report issues with MCS upstream?

**Comment by mattmassicotte** [comment]
@Zariel sorry about this - this is my fault. For normal MCS weirdness, I wouldn't have opened an issue here. Of course, this is not your responsibility. Thanks for looking at it so quickly, anyways.

This was a case where I wanted to offer the team a chance to look, and see if adding the ability to influence the consistency level used for UseKeyspace made sense. I worded the report very poorly. 

Regardless, I have a feeling this is something that, if just left as-is, will eventually disappear, even if it doesn't affect other drivers.

**Comment by danilop** [comment]
Thank you for letting us know!

All writes in Amazon MCS are stored durably and replicated three times across multiple AWS Availability Zones using LOCAL_QUORUM consistency. To help customers optimize performance and consistency, reads can be executed using either ONE, LOCAL_ONE or LOCAL_QUORUM consistency. Early in the preview, MCS would map unsupported consistency levels to supported levels to help customers migrate workloads without minimal changes to their source code. In this case, ANY was mapped to LOCAL_QUORUM. However, based on customer feedback, we have adjusted MCS to explicitly reject unsupported consistency levels to ensure there is no confusion about the consistency level being used.

**Comment by danilop** [comment]
For posting feedback on Amazon MCS, you can this section of the AWS Forums that is monitored by the product team:

https://forums.aws.amazon.com/forum.jspa?forumID=357

**Comment by allamand** [comment]
thanks @mattmassicotte for the tips, I wouldn't have found it myself! I struggled 4 hours on it yesterday..

**Comment by mattmassicotte** [comment]
@allamand you are very welcome! Sorry to hear you had trouble.

Unfortunately, it's now clear that MCS is intentionally not supporting the Any consistency level. I haven't tried it, but another, possibly much better workaround is to manually issue the "use" directive, so the session will use the consistency level you configure.

**Comment by allamand** [comment]
@songyanho just make a fix in this problem : https://github.com/gocql/gocql/pull/1422 thanks to him :)
