### ISSUE TITLE
gocql connection error to AWS mcs cluster

### ISSUE THREAD

**Issue by allamand** [gocql/gocql#1421]
Hi,

I add a program that was properly connecting to an AWS mcs cluster last week, but now it refuse to connect with this error : 

```
2020/03/23 23:22:53 error: failed to connect to 3.83.168.151:9142 due to error: Consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
```

in my code, I specify the consistency level to `	cluster.Consistency = gocql.One` 

### What version of Cassandra are you using?

AWS MCS

### What version of Gocql are you using?

github.com/gocql/gocql v0.0.0-20200226121155-e5c8c1f505c5

### What did you do?

just try to connect

### What did you expect to see?

connected

### What did you see instead?

```
2020/03/23 23:22:53 error: failed to connect to 3.83.168.151:9142 due to error: Consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
```

**Comment by Zariel** [comment]
see #1420
