### ISSUE TITLE
How to detect failed queries when executing with Iter()?

### ISSUE THREAD

**Issue by erikbos** [gocql/gocql#1426]
I'd like to check for a failed query vs. a query with 0 row result set. 

The example code from https://godoc.org/github.com/gocql/gocql#Iter.MapScan suggests:

```
iter := session.Query(`SELECT * FROM mytable`).Iter()
for {
	// New map each iteration
	row = make(map[string]interface{})
	if !iter.MapScan(row) {
		break
	}
	// Do things with row
	if fullname, ok := row["fullname"]; ok {
		fmt.Printf("Full Name: %s\n", fullname)
	}
}
```

This does not allow me to detect the difference between a failed query and result set with 0 rows. What is the best way to check for that? (Returned type Iter does have field err..)

**Comment by martin-sucha** [comment]
Calling [Iter.Close](https://godoc.org/github.com/gocql/gocql#Iter.Close) after the for loop should get you the error (and close the iterator).

```go
iter := session.Query(`SELECT * FROM mytable`).Iter()
for {
	// New map each iteration
	row = make(map[string]interface{})
	if !iter.MapScan(row) {
		break
	}
	// Do things with row
	if fullname, ok := row["fullname"]; ok {
		fmt.Printf("Full Name: %s\n", fullname)
	}
}
if err := iter.Close(); err != nil {
	return err
}
```

**Comment by erikbos** [comment]
Ah, I wrongly expected close() to report on just the act of closing and not on the previously executed query. thx!
