### ISSUE TITLE
gocql.createSession: Consistency level ANY is not supported for this operation

### ISSUE THREAD

**Issue by Pinank** [gocql/gocql#1428]
Getting following error while trying to create session from cql,

```
Error: 
Consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
```

I've used **Amazon Managed Apache Cassandra Service**

Following is the code for creating session

```
clusterConfig := gocql.NewCluster("<HOST:PORT>")
clusterConfig.Authenticator = gocql.PasswordAuthenticator{Username: "Username", Password: "Password"}
clusterConfig.SslOpts = &gocql.SslOptions{
CaPath: "./AmazonRootCA1.pem",
}
clusterConfig.Consistency = gocql.LocalQuorum
clusterConfig.ConnectTimeout = time.Second * 10
clusterConfig.ProtoVersion = 3
clusterConfig.DisableInitialHostLookup = true
clusterConfig.Keyspace = "TestDB"
clusterConfig.NumConns = 3
session, err := clusterConfig.CreateSession()
if err != nil {
fmt.Println("err>", err)
}
return session
```

I am setting consistency level to **LocalQuorum** but still its giving above mentioned error. If anybody knows how to resolve please help us out

**Comment by martin-sucha** [comment]
@Pinank which version of gocql are you using? It seems that you might be hitting an issue that was recently fixed: https://github.com/gocql/gocql/pull/1422

**Comment by Pinank** [comment]
@martin-sucha Version upgrade worked for me. Thanks
