### ISSUE TITLE
[product behavior discussion] Do we really need to wait for connections to the specified hosts to be ready? 

### ISSUE THREAD

**Issue by GingerMoon** [gocql/gocql#1432]
Quoted from @martin-sucha  in #1429 , 

> Waiting for connection to all nodes (the current state) in the cluster is not ideal, since a single database node that is down will force you to wait the entire timeout period (and currently addHost are called serially, which adds the startup latency). We definitely want to connect to database nodes concurrently.

> Some programs don't care about the connections as long as the queries can be executed (for example command-line utilities, long-running jobs, etc.).

> In some cases like API servers, you might want to be able to wait until the driver established connection to all the peers that it usually sends queries to. Queries should work even with just a single connection to the cluster as the coordinator node will then forward them to the correct node. However, this incurs latency costs for the **hop** (which might add up when you issue a lot of queries to your service). When doing rolling release/restarting your service, you might want to wait for all connections to be established before starting routing requests to the newly spawned instance so that you don't impact your service's latency during normal operations (when the database cluster is healthy).

My question is, after it's warmed up totally after a while (maybe longer), all the connections, which are supposed to be workable, are workable, we don't have this extra "hop" expense.

@martin-sucha @fastest963 
Any more insights would be appreciated!

**Comment by martin-sucha** [comment]
Users can implement a ReadyPolicy since #1365, so it is possible to specify the waiting behavior during startup. Closing this issue. Please reopen if you think there is still something missing.

> My question is, after it's warmed up totally after a while (maybe longer), all the connections, which are supposed to be workable, are workable, we don't have this extra "hop" expense.

Indeed. If you have ready connections to all nodes and are using token aware host selection policy, then there won't be any extra network hops as the driver will connect to a replica holding the requested data.
