### ISSUE TITLE
Add new ecAudit plugin - com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator for username/password auth

### ISSUE THREAD

**Issue by rsbala** [gocql/gocql#1440]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11 + the ecAudit plugin

### What version of Gocql are you using?
latest

### What did you do?
Have been using gocql to connect to Cassandra. Trying to use ecaudit to generate audit logs.

### What did you expect to see?
I expect username/password auth to not be blocked by a whitelist of allowed plugins.

### What did you see instead?
2020/05/15 10:24:27 gocql: unable to dial control conn : unexpected authenticator "com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator"
2020/05/15 10:24:27 error in session create gocql: unable to create session: control: unable to connect to initial hosts: unexpected authenticator "com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator"

Please add "com.ericsson.bss.cassandra.ecaudit.auth.AuditAuthenticator" plugin to the whitelist of acceptable plugins maintained here:
https://github.com/gocql/gocql/blob/master/conn.go#L27. "com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator" was already added (https://github.com/gocql/gocql/pull/1321), unfortunately AuditPasswordAuthenticator is deprecated and have been recommended to use AuditAuthenticator instead as mentioned in https://github.com/Ericsson/ecaudit/blob/6e3b0d90cb811ddbcb5abcb81d2eabda35231a63/UPGRADING.md.

This plugin is a drop in replacement for username/password auth that provides compliant audit logging. This change will be a huge help to unblock the issue and move forward. Thanks much.

**Comment by rsbala** [comment]
Created a PR https://github.com/gocql/gocql/pull/1441 to add AuditAuthenticator to the whitelist in the similar way it was done earlier. Can someone please review ?

**Comment by alourie** [comment]
closed via https://github.com/gocql/gocql/pull/1441

**Comment by rsbala** [comment]
Thanks @alourie. I have created a ticket https://github.com/gocql/gocql/issues/1442 as suggested.
