### ISSUE TITLE
How to get the number of rows returned by a query using gocql ?

### ISSUE THREAD

**Issue by kool927** [gocql/gocql#1468]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
latest as of today

### What version of Gocql are you using?
latest as of today
### What did you do?
```
var count string
	iter := Session.Query(`SELECT count(*) FROM code.dd`).Iter()
	for iter.Scan(&count) {
		print(count)
	}
```
### What did you get?
`the total number is %!(EXTRA int=2)2`
### What did you expect to see?
Just an int value like `2`
### Question
**How to get the number of rows returned by a query using gocql?** please answer this question on StackOverflow or here
https://stackoverflow.com/questions/37800892/how-to-get-the-number-of-rows-returned-by-a-query-using-gocql

**Comment by Zariel** [comment]
The code posted will work if count is changed to an int, can be shorted to

```go
var count int
err := Session.Query(`SELECT count(*) FROM code.dd`).Scan(&count)
if err != nil {
    panic(err)
}
```
