### ISSUE TITLE
Query isn't well formed in the log using ObserveQuery interface

### ISSUE THREAD

**Issue by tushardas** [gocql/gocql#1497]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.8

### What did you do?
I'm implementing the QueryObserver interface as below, for logging the query
```go
type queryLogger struct {
	Logger log.Logger
}

func (q queryLogger) ObserveQuery(ctx context.Context, o gocql.ObservedQuery) {
	q.Logger.Debugf("[CQL] query: %v %vms", o.Statement, o.End.Sub(o.Start).Milliseconds())
}
```

And below is the query which I'm using
```go
query := "INSERT INTO students (id, name, marks) VALUES (?, ?, ?)"
cassandra.Session.Query(query, 1, "Tushar",95).Exec()
```
### What did you expect to see?
[CQL] INSERT INTO students (id, name, marks) VALUES (1, "Tushar", 95)

### What did you see instead?
[CQL] INSERT INTO students (id, name, marks) VALUES (?,?,?)

---

**Comment by tushardas** [comment]
Found that the issue is at https://github.com/gocql/gocql/blob/master/session.go#L1004

The receiver `q` contains a field `values` which stores the args passed in Query().

**Comment by martin-sucha** [comment]
gocql does not substitute bound values in the query, those are [passed separately in cql protocol](https://github.com/datastax/native-protocol/blob/82b12f3892aeb360b3acefe2f915449698764251/src/main/resources/native_protocol_v4.spec#L302), so rendering 
```
[CQL] INSERT INTO students (id, name, marks) VALUES (1, "Tushar", 95)
```
is out of scope.

I guess we could add something like `Values []interface{}` field to ObservedQuery and set it to `Query.values`, so that you can log the values separately.

**Comment by tushardas** [comment]
@martin-sucha  
That would help. 

I would like to work on these changes and submit a PR.

For the `ObserveBatch`, would it be good to have a `map[string][]interface{}`, where the key would be the statement and value would be the corresponding bound values?

**Comment by martin-sucha** [comment]
> I would like to work on these changes and submit a PR.

Nice :+1: 

> For the `ObserveBatch`, would it be good to have a `map[string][]interface{}`, where the key would be the statement and value would be the corresponding bound values? In order for backward compatible changes, we can create a new field `Entries`, maybe?

We can't use the statement as key as there could be the same statement executed multiple sets of bound values. For example adding multiple records to the same partition. Consider the following batch:

```
statement: INSERT INTO table (a, b, c) VALUES (?, ?, ?);
values: {"key1", "key2", "value1"}

statement: INSERT INTO table (a, b, c) VALUES (?, ?, ?);
values: {"key1", "key2", "value2"}
```

Also a map is a little more complex structure than just plain slice, we are executing this on every query so we should try to use as lightweight operations here as possible.

ObservedBatch has
```go
Statements []string
```

so I would go with just adding a new field

```go
// Values holds a slice of bound values for each statement.
// Values[i] corresponds to Statements[i].
Values [][]interface{}
```

**Comment by tushardas** [comment]
When can we expect this change to be released?
