### ISSUE TITLE
Panic of gocql with TokenAwareHostPolicy during the creation of a partial keyspace

### ISSUE THREAD

**Issue by antonio-tringali** [gocql/gocql#1500]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Cassandra version 3.11.4

### What version of Gocql are you using?
v0.0.0-20200131111108-92af2e088537

### What did you do?
The test cluster is made up of three datacenters with three nodes each. Let's call them DC1, DC2 and DC3.

With an active client, connected to the cluster via TokenAwareHostPolicy, I created a new keyspace with:

`CREATE KEYSPACE test_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3', 'DC2': '3'}  AND durable_writes = true;
`

i.e., keyspace DC3 is not mentioned. The application panics with the following stacktrace:

```
github.com/gocql/gocql.(*networkTopology).replicaMap at topology.go:265
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas at policies.go:458
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged at policies.go:443
github.com/gocql/gocql.(*Session).handleKeyspaceChange at events.go:127
github.com/gocql/gocql.(*Session).handleSchemaEvent at events.go:112
github.com/gocql/gocql.(*Session).handleSchemaEvent-fm at events.go:106
runtime.go_exit at asm_amd64.s:1374

```

### What did you expect to see?
It should not panic and handle the schema change with grace.

### What did you see instead?
It panics.

The application does NOT panic with DCAwareHostPolicy.

No other change causes panic, for example the drop of this "partial" keyspace. Or creating, dropping and altering tables inside the keyspace.

But altering the keyspace such as:

`CREATE KEYSPACE test_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'}  AND durable_writes = true;
`

or:

`CREATE KEYSPACE test_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3', 'DC2': '3', 'DC3': '3'}  AND durable_writes = true;
`

from the definition with two datacenters it panics.

It seems gocql always expects a number of replica hosts equal to the number of nodes in the cluster.
 
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by antonio-tringali** [comment]
It also happens when starting a connection.

**Comment by funny-falcon-at-joomcode** [comment]
Your version is old. Fix were merged at 20 March 2020, and yours is of 31 January 2020.
bdeb4c9
Update, please.

**Comment by martin-sucha** [comment]
Closing as this should work in the latest version (@funny-falcon-at-joomcode thanks!). @antonio-tringali Please reopen in case you can reproduce with latest master.
