### ISSUE TITLE
Connection issues with multiple hosts

### ISSUE THREAD

**Issue by TomL-dev** [gocql/gocql#1509]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

[cqlsh 5.0.1 | Cassandra 3.11.3.5117 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?

not sure where to find this.
copied from go.mod file:

`require github.com/gocql/gocql v0.0.0-20201024154641-5913df4d474e`

### What did you do?

I tried to connect a small go program to cassandra. 

### What did you expect to see?

the same result when executing the program with only 1 host and with multiple comma-separated hosts

### What did you see instead?

The program was able to connect to the cassandra cluster when providing only 1 host, However it throws an error when i supply multiple hosts

```
panic: gocql: unable to create session: failed to resolve any of the provided hostnames
```

note that it could connect to host1, and when adding another host, it can't. see full program below

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`

not sure how to do this. i don't own/run the cassandra instances myself. connecting to already deployed cluster

- output of `SELECT peer, rpc_address FROM system.peers`

gives a table(9 rows) of ip addresses which are the same left and right

- rebuild your application with the `gocql_debug` tag and post the output

main.go file:

```Golang
func main() {
	// connect to the cluster
	cluster := gocql.NewCluster("host1, host2")
	// cluster := gocql.NewCluster("host1")
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: "my_username",
		Password: "my_password",
	}
	ks := "keyspace_name"

	cluster.Keyspace = ks
	cluster.Consistency = gocql.LocalQuorum
	session, conErr := cluster.CreateSession()

	if conErr != nil {
		fmt.Println("couldn't get session")
		panic(conErr)
	}

	defer session.Close()
	fmt.Printf("\nCLUSTER\n%#v\n\n", cluster)
	fmt.Printf("\nSESSION\n%#v\n\n", session)

	keyspaceMetadata, err := session.KeyspaceMetadata(ks)
	fmt.Printf("\nKeySpaceMETA\n%#v\n\n", keyspaceMetadata)

	if err != nil {
		panic(err)
	}

	for _, table := range keyspaceMetadata.Tables {
		fmt.Println(table.Name)
	}
}
```

**Comment by martin-sucha** [comment]
Hi @TomL-dev , `NewCluster` takes a variable list of arguments, each one is a hostname.

Instead of `gocql.NewCluster("host1, host2")` you should use `gocql.NewCluster("host1", "host2")`.

**Comment by TomL-dev** [comment]
sorry about that, seems in my example i missed the extra quotes. i'm using `gocql.NewCluster(strings.Split(cfg.Addresses, ",")...)`

**Comment by megadeezl** [comment]
I know this is closed, but in case anyone else has this issue I go the following to work:

cluster := gocql.NewCluster(strings.Split(cfg.ClusterHosts, ",")...) //https://golangdocs.com/variadic-functions-in-golang
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: cfg.DBUsername,
		Password: cfg.DBPassword,
	}
	cluster.Keyspace = cfg.Keyspace
	Session, err = cluster.CreateSession()
	if err != nil {
		panic(err)
	}
