### ISSUE TITLE
Getting a specific page of the results

### ISSUE THREAD

**Issue by kszmigiel** [gocql/gocql#1512]
Hello!

Let's say I have such piece of code:

```
query := "SELECT id, something FROM messages WHERE something = ? ALLOW FILTERING"
iter := db.Session.Query(query, something).PageSize(10).Iter()
```

How can I get the results from, let's say, 2'nd page (results no. 11-20), without iterating over the results with iterator? I know it's pretty lame question, but I failed to find anything about this in the docs.

**Comment by martin-sucha** [comment]
Hello!

You can get the paging state from query result by calling [Iter.PageState](https://godoc.org/github.com/gocql/gocql#Iter.PageState) (this will return `nil` if there aren't more pages) and later you can query the next page by setting the previously obtained page state in the query with [Query.PageState](https://godoc.org/github.com/gocql/gocql#Query.PageState).

To get just the first page, call `PageState(nil)` on the query to disable auto paging for the iterator.

For example, you could do:

```go
query := "SELECT id, something FROM messages WHERE something = ? ALLOW FILTERING"

firstPageIter := db.Session.Query(query, something).PageSize(10).PageState(nil).Iter()
// process rows here
if err := firstPageIter.Close(); err != nil {
    return err
}
pagingState := firstPageIter.PageState()

secondPageIter := db.Session.Query(query, something).PageSize(10).PageState(pagingState).Iter()
// process rows here
if err := secondPageIter.Close(); err != nil {
    return err
}
pagingState2 := secondPageIter.PageState()

// ...
```

Paging state data could be stored in the user's session, or (encrypted/signed as needed) in a URL, etc if the second page needs to be queried some time later.

**Comment by kszmigiel** [comment]
@martin-sucha all clear, thank you! closing :)

**Comment by martin-sucha** [comment]
Actually when there are no more pages, `PageState()` returns zero-length slice now, not `nil` as I wrote previously (because internally copyBytes converts the `nil` to non-nil zero-length slice when copying the data), so it's best to check with `len(pageState) == 0`.

**Comment by martin-sucha** [comment]
Hmm, I'm learning new things every day. The page state is specific to the cql version used, so storing it in external places can have implications for operations when updating to a newer CQL protocol version. More details here:

https://github.com/apache/cassandra/blob/acf8de28ce2f2871e30e4a55086a38d850470f3e/doc/native_protocol_v5.spec#L1054-L1088
