### ISSUE TITLE
Many different queries = prepared statement evicted from cache -> error

### ISSUE THREAD

**Issue by mihasya** [gocql/gocql#152]
### Context
We have long running services that use old-style batches `BEGIN BATCH ... APPLY BATCH` to insert data. The inserts can vary in number, thus producing a number of different resulting queries. We had until recently been using gocql incorrectly, creating and destroying sessions all over the place. After fixing that issue, we came back on Monday to find a new error:

```
Prepared query with ID bf03ecbca870fb358e2ef4673f307ca3 not found (either the query was not prepared on this host (maybe the host has been restarted?) or you have prepared too many queries and it has been evicted from the internal cache)
```

This error is actually coming back from Cassandra, and it means that either the statement had not been prepared, or it had been prepared, but has since fallen out of cache due to many other queries having been prepared.

The query that was failing was a read that gets executed on the very first load of our app. Restarting the offending service made the exact same query succeed, so I'm guessing the issue is the latter case. The cache is defined here with a limited memory: https://github.com/apache/cassandra/blob/cassandra-1.2.11/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L60

I can't easily come up with an easy way to reproduce this, but my hypothesis is that the chain of events was as follows:

1. Query was successfully prepared and executed immediately after the process was last started sometime on Sunday morning
1. Process ran for a long time, accepting inserts from background processes which all generated slightly different `BATCH` queries.
1. no one looked at the UI after ~2pm Sunday until Monday morning, so that read had not been occurring
1. By monday morning, the various batch queries had pushed the query out of cassandra's cache, causing the failure.

I'm guessing we never encountered this before because we were recreating sessions so much.

Just filing this in case I get distracted, but going to look at the code now and see if I can't come up with a patch.

**Comment by 0x6e6562** [comment]
@mihasya Do you think it is still worth keeping this issue open?

**Comment by Zariel** [comment]
As there has been no update no this im going to close it, if is still applicable please reopen.
