### ISSUE TITLE
Reusing of loop variable while compiling metadata in function compileMetadata causing loss of metadata

### ISSUE THREAD

**Issue by Felix-Raj** [gocql/gocql#1524]
### What version of Cassandra are you using?
4.0.0.6.77

### What version of Gocql are you using?
v0.0.0-20210125064827-43a8f9bf6605

### What version of Go are you using?
go1.15

### What did you do?
Fetch materialized view metadata using `KeyspaceMetadata.MaterializedViews`

There are 3 views - view1, view2, view3. I am fetching metadata of each using something like - 
```
viewMeta := KeyspaceMetadata.MaterializedViews
fmt.Printf("view meta %+v", viewMeta)
```

### What did you expect to see?
Metadata of each of the view corresponding to `view_name` above. As each view are different I expected to see different values for each of the keys. Something like

```
view meta map[view2:0xc00019e3c0 view1:0xc00019e4b0 view3:0xc00019e5a0]
```
See the value of each map entry

### What did you see instead?
Metadata on each key are duplicate.
```
map[view2:0xc00028e3c0 view1:0xc00028e3c0 view3:0xc00028e3c0]
```
See the value of each map entry

This is because the loop variable is being reused in the compileMetadata function ([this lines](https://github.com/gocql/gocql/blob/master/metadata.go#L350-L353)), which is like:
```
    for _, materializedView := range materializedViews {
        materializedView.BaseTable = keyspace.Tables[materializedView.baseTableName]
        keyspace.MaterializedViews[materializedView.Name] = &materializedView
    }
```
Only the last metadata entry in `materializedViews` will be available. For any key, we will get the same value.

**Comment by beltran** [comment]
This is probably happening in other places as well, like here for the aggregates: https://github.com/gocql/gocql/blame/master/metadata.go#L327-L331

**Comment by Felix-Raj** [comment]
The PR fixes the issue, closing the issue. Thanks @beltran .

**Comment by martin-sucha** [comment]
I have opened a separate issue for the aggregates: https://github.com/gocql/gocql/issues/1526

**Comment by Felix-Raj** [comment]
Keeping this open until PR get's merged.
