### ISSUE TITLE
Reused loop variables

### ISSUE THREAD

**Issue by martin-sucha** [gocql/gocql#1526]
Loop variable is reused at:

https://github.com/gocql/gocql/blob/43a8f9bf6605c25fcaa921fb7c9f8b3d6024f05d/metadata.go#L327-L331

Probably in different places as well.

https://github.com/gocql/gocql/issues/1524#issuecomment-766865202

**Comment by beltran** [comment]
I believe this is the only place where it's happening, in the other places we seem to be using an index and `&array[i]`, which prevents the bug

**Comment by martin-sucha** [comment]
Yep, seems to be the only case. I have executed scopelint linter (from golangci-lint) and it found:

```
internal/murmur/murmur_test.go:28:17: Using the variable on range scope `test` in function literal (scopelint)
			if v := rotl(test.in, uint8(test.rotate)); v != test.exp {
			             ^
internal/murmur/murmur_test.go:29:36: Using the variable on range scope `test` in function literal (scopelint)
				t.Fatalf("expected %d got %d", test.exp, v)
				                               ^
internal/murmur/murmur_test.go:48:17: Using the variable on range scope `test` in function literal (scopelint)
			if v := fmix(test.in); v != test.exp {
			             ^
metadata.go:330:42: Using a reference for the variable on range scope `aggregate` (scopelint)
		keyspace.Aggregates[aggregate.Name] = &aggregate
		                                       ^
```

The cases in murmur_test.go are false positives because of the table tests.
