### ISSUE TITLE
Cassandra 4 beta4: received unexpected frame on stream 0

### ISSUE THREAD

**Issue by nathandragun** [gocql/gocql#1532]
4.0 support seems to be broken with the latest pull:

> 2021/01/31 17:50:30 gocql: unable to dial control conn xx.xx.xx.xx:9042: gocql: received unexpected frame on stream 0: [header 
version=[version=4 direction=RESP] flags=0x0 stream=0 op=SUPPORTED length=96]

> 2021/01/31 17:50:30 gocql: unable to create session: control: unable to connect to initial hosts: gocql: received unexpected frame on stream 0: [header version=[version=4 direction=RESP] flags=0x0 stream=0 op=SUPPORTED length=96]

simple connection init using:

```
cluster := gocql.NewCluster("xx.xx.xx.xx")
cluster.Keyspace = "mykeyspace"
session, err := cluster.CreateSession()
if err != nil {
	log.Println(err)
	return
}
```

Requested additional environment information:
Cassandra version: 4.0
Cassandra repo: deb http://www.apache.org/dist/cassandra/debian 40x main
Cassandra package info: cassandra_4.0~beta4_all.deb
Cassandra package MD5sum: 556a3490ec69834111904a98e3e9f620
OS: Ubuntu 20.04.2 LTS
Gocql: github.com/gocql/gocql v0.0.0-20210129204804-4364a4b9cfdd h1:j0VZcDIpU6sLBMNFUEvuwP4FdmEXbmaEq6qufApwbbo=
GO: 1.14.6

nodetool status output:

=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load        Tokens  Owns (effective)  Host ID                               Rack
UN  xx.xx.xx.xx  230.45 KiB  16      ?                 b9f4ece9-351a-4fe9-a90b-f25b3f85edff  rack1

peer information:
cqlsh> SELECT peer, rpc_address FROM system.peers;

 peer | rpc_address
------+-------------

(0 rows)

output with gocql_debug tag compile unchanged

**Comment by Zariel** [comment]
Gocql does not send frames on stream 0 to avoid a bug where errors can come back in the wrong stream. This is likely a protocol violation in Cassandra.

**Comment by jhekau** [comment]
OS: Debian 10
`Linux cassandra 5.4.73-1-pve #1 SMP PVE 5.4.73-1 (Mon, 16 Nov 2020 10:52:16 +0100) x86_64 GNU/Linux`

Repo: 
`http://downloads.apache.org/cassandra/debian 40x main`

dpkg -s cassandra
```
Package: cassandra
Status: install ok half-configured
Priority: extra
Section: misc
Installed-Size: 53145
Maintainer: Eric Evans <eevans@apache.org>
Architecture: all
Version: 4.0~beta4
Replaces: apache-cassandra1
Depends: openjdk-8-jre-headless | java8-runtime, adduser, python (>= 2.7)
Recommends: ntp | time-daemon
Suggests: cassandra-tools
Conflicts: apache-cassandra1
Conffiles:
 /etc/cassandra/cassandra-env.sh bf3ccc99e67b3dff26957995cdfb00f9
 /etc/cassandra/cassandra-rackdc.properties 3ab4cb3f784e659058f67a6045a6e33f
 /etc/cassandra/cassandra-topology.properties 5f10b88bcaa0593900d83aa769645af9
 /etc/cassandra/cassandra.yaml 45ffdaad4c2d5d1cb957edad7b29ec13
 /etc/cassandra/commitlog_archiving.properties 844cc7ba84c53ac4ae20103df4450dc8
 /etc/cassandra/hotspot_compiler cec4cf0d941891aa4a85384d53e88edd
 /etc/cassandra/jvm-clients.options 653d97ef01d25aa7b898707374b118e2
 /etc/cassandra/jvm-server.options 4ea4912d8bfe88dbbde3dd12cf5851d3
 /etc/cassandra/jvm11-clients.options 139b04c58c898f3c396375f7969e6876
 /etc/cassandra/jvm11-server.options 246916325e3a0629eb64db27e79a85c0
 /etc/cassandra/jvm8-clients.options e5acc7088c463f7746beb8fb7f7214e5
 /etc/cassandra/jvm8-server.options 247b576856d2623f6189efc5e651ca71
 /etc/cassandra/logback-tools.xml 0e90ef9829edf69960ba890be7f72862
 /etc/cassandra/logback.xml eebc5423243eca76fd9ff6fe57d12be3
 /etc/cassandra/triggers/README.txt 3ab8b4b7503a307349813a3a969fc4f1
 /etc/default/cassandra 98a0a8e9283cc085b8eddee9da28f778
 /etc/init.d/cassandra 2f3e07e00dad4d1bfe0738c06fa59740
 /etc/security/limits.d/cassandra.conf 816e1a79629c0491f93e2caad5bb9827
 /etc/sysctl.d/cassandra.conf 7fabde6fe4a64f152fad7e61b1c6434d
Description: distributed storage system for structured data
 Cassandra is a distributed (peer-to-peer) system for the management
 and storage of structured data.
Homepage: http://cassandra.apache.org
```

go version: 
`1.15.7`

gocql
`current version`

connect: 
```
cluster := gocql.NewCluster("10.100.0.1", "10.100.0.2")
cluster.ProtoVersion = 4
cluster.CQLVersion = "3.4.5"
cluster.Port = 9042
cassandra, err := cluster.CreateSession()
```

log error: 
```
gocql: unable to dial control conn 10.100.0.1:9042: gocql: received unexpected frame on stream 0: [header version=[version=4 direction=RESP] flags=0x0 stream=0 op=SUPPORTED length=96]
gocql: unable to dial control conn 10.100.0.2:9042: gocql: received unexpected frame on stream 0: [header version=[version=4 direction=RESP] flags=0x0 stream=0 op=SUPPORTED length=96]
```

**Comment by Zariel** [comment]
Can you please tcp dump and check what the outgoing stream the frame is using please.

**Comment by martin-sucha** [comment]
I can indeed reproduce with Cassandra 4 beta 4. And I can confirm that gocql sends the `OPTIONS` frame on stream 1 and the server sends back `SUPPORTED` frame on stream 0. So this is a bug in Cassandra.

[cassandra4beta4.pcapng.gz](https://github.com/gocql/gocql/files/5928228/cassandra4beta4.pcapng.gz)

**Comment by Zariel** [comment]
Great thanks Martin! I explicitly prevented gocql from using frame 0 for the exact purpose and is not the first bug we have found! Can you report it upstream?

**Comment by nathandragun** [comment]
Thank you for jumping on this so quickly.  I'm just diving into Cassandra so I'm not yet familiar with the inner workings.

What surprises me about this being a Cassandra issue is that cqlsh doesn't freak out when communicating under this same configuration.

What 4.0 build do you currently recommend?

**Comment by martin-sucha** [comment]
Reported here: https://issues.apache.org/jira/browse/CASSANDRA-16424

**Comment by martin-sucha** [comment]
> What surprises me about this being a Cassandra issue is that cqlsh doesn't freak out when communicating under this same configuration.

cqlsh sends the `OPTIONS` frame on stream 0, so if the server always responds with 0, cqlsh does not notice that server uses 0 wrongly all the time.
gocql sends the `OPTIONS` frame on stream 1, so if the server sends response on stream 0, gocql detects protocol error.

> What 4.0 build do you currently recommend?

Cassandra 4.0 beta3 works.

**Comment by martin-sucha** [comment]
Ah, should already be fixed in Cassandra trunk, and will work in Cassandra 4.0.0-beta5 (see [comment](https://issues.apache.org/jira/browse/CASSANDRA-16424?focusedCommentId=17279621&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17279621))
