### ISSUE TITLE
Query.PageState like method for the "previous page" feature

### ISSUE THREAD

**Issue by BentCoder** [gocql/gocql#1533]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra&Gocql are you using?
`[cqlsh 5.0.1 | Cassandra 3.11.9 | CQL spec 3.4.4 | Native protocol v4]`

### What version of Go are you using?
`go version go1.15.3 darwin/amd64`

### What did you do?

I am able to paginate result and work out the "next page" after following the links below which were very useful.

- https://github.com/gocql/gocql/blob/4364a4b9cfdd5b806725cc7d2e9abf3bdf461166/example_paging_test.go#L12
- https://github.com/gocql/gocql/blob/f242734b1558a112c9268e4f84d4d292ac87e2fa/cassandra_test.go#L2741
- https://github.com/gocql/gocql/blob/4364a4b9cfdd5b806725cc7d2e9abf3bdf461166/doc.go#L199-L202

```go
func List(ctx context.Context, limit int, self []byte /* xyz123 */) (.....) {
     iter := Session.Query(`SELECT * FROM logs`).WithContext(ctx).PageSize(limit).PageState(self).Iter()
     defer iter.Close()

     next := iter.PageState() // abc987
     ...
     prev := ?????
}
```

However, what I also want to find out is, if there is a possibility to work out what would be the "previous page" so that I can respond to a request like shown below?

Thanks

```json
{
   "prev": "????",
   "self": "?cursor=xyz123",
   "next": "?cursor=abc987",
}
```

**Comment by martin-sucha** [comment]
No, this is not supported by CQL protocol. If you want to iterate backwards, you need to [implement paging manually with range queries](https://stackoverflow.com/a/34751910)
