### ISSUE TITLE
Invalid or unsupported protocol version (4); supported versions are (3/v3, 4/v4, 5/v5-beta)

### ISSUE THREAD

**Issue by ninetyone** [gocql/gocql#1537]
Please answer these questions before submitting your issue. Thanks!
### What version of Cassandra are you using?
3.11.6
### What version of Gocql are you using?
[cqlsh 5.0.1 | Cassandra 3.11.6 | CQL spec 3.4.4 | Native protocol v4]
1982a06ad6b9
See
https://github.com/uber/cadence/blob/ea35743c913ed582d4a6357507e168bc24826305/go.mod#L22
### What did you do?
Run Cadence service in a testing env, and see error:
```
2021/02/26 00:45:19 error: failed to connect to 10.24.12.108:9042 due to error: Invalid or unsupported protocol version (4); supported versions are (3/v3, 4/v4, 5/v5-beta)
```
It keeps going throughout the test. 
### What did you expect to see?
No such error. 
### What did you see instead?
---
If you are having connectivity related issues please share the following additional information
### Describe your Cassandra cluster
please provide the following information
- output of `nodetool status`
```
UN  10.24.11.171  9.27 GiB   256          ?       92c6bd30-8278-4bf5-b0c3-39ca1dc5f0a6  rack1
UN  10.24.12.108  9.02 GiB   256          ?       ac3efee5-dda6-4788-9a83-0e672199516e  rack1
UN  10.24.7.141   8.22 GiB   256          ?       f274df82-e6fe-48c7-a27f-5c636e8d1f09  rack1
UN  10.24.26.116  9.18 GiB   256          ?       3d114ff5-9fd5-42e9-9dfe-2fe8b8c38530  rack1
UN  10.24.9.86    10.05 GiB  256          ?       7e1b3612-0995-41d3-a3ed-dbbc181cd7b9  rack1
```

- output of `SELECT peer, rpc_address FROM system.peers`
```
 peer         | rpc_address
--------------+--------------
 10.24.11.171 | 10.24.11.171
 10.24.12.108 | 10.24.12.108
 10.24.26.116 | 10.24.26.116
  10.24.7.141 |  10.24.7.141
 10.24.25.137 | 10.24.25.137
 ```
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
This seems to be related to https://github.com/gocql/gocql/issues/1536.

The `Invalid or unsupported protocol version (4); supported versions are (3/v3, 4/v4, 5/v5-beta)` part of the error comes from the server. Do you see anything related in server logs? Could you please attach a network capture of the TCP stream where `Invalid or unsupported protocol version (4); supported versions are (3/v3, 4/v4, 5/v5-beta)` is returned from the server? What is printed if you build with `gocql_debug` tag?

**Comment by ninetyone** [comment]
I was running a 5 nodes cluster. On 1 of the node the Native protocol was v3 and on the rest it was v4. Used nodetool to remove this node. That fixed the issue
