### ISSUE TITLE
go get failing due to undefined struct field error

### ISSUE THREAD

**Issue by anirudhgupta22** [gocql/gocql#1545]
The PR https://github.com/gocql/gocql/pull/1504 removed the `timeouts` field from the connection struct but failed to remove the [usage](https://github.com/gocql/gocql/blob/master/conn.go#L722)
https://github.com/gocql/gocql/pull/1504/files#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654L180

This is leading to build failure
![Screenshot 2021-03-10 at 1 51 20 PM](https://user-images.githubusercontent.com/6864996/110598403-b6b88680-81a7-11eb-8b15-6dea1e516bbe.png)

**Comment by martin-sucha** [comment]
Should be fixed in https://github.com/gocql/gocql/commit/1418e1105e720e09744dd50f9b21aed3911bf434
