### ISSUE TITLE
go get -u github.com/gocql/gocql failing

### ISSUE THREAD

**Issue by kitz99** [gocql/gocql#1546]
```go get -u github.com/gocql/gocql
github.com/gocql/gocql
../gocql/gocql/conn.go:722:43: c.timeouts undefined (type *Conn has no field or method timeouts)```

go version: go version go1.14.2 darwin/amd64

**Comment by abesheknarayan** [comment]
@martin-sucha requesting you to look at your latest commit, you removed a line (in Conn.go file line number 180) which is causing this error! Thanks

**Comment by ionutvilie** [comment]
No worries, just a bug, the best day to use `go mod`. 

I confirm it is working now.

**Comment by kitz99** [comment]
Thanks for the support, @martin-sucha! I confirm everything is working just fine
