### ISSUE TITLE
Allow setting preferred data centre

### ISSUE THREAD

**Issue by zaddok** [gocql/gocql#1557]
I would like app servers to have a preferred data centre, so they talk within the same local network when possible, but failover to an external data centre in emergencies.

I see we have a helpful `DataCentreHostFilter` option which would allow limiting to one single data centre, but I can't see an option to set things up to "break out of the filter if needed". So I think this is  a feature request. Unless I am missing something?

```
func DataCentreHostFilter(dataCentre string) HostFilter {
	return HostFilterFunc(func(host *HostInfo) bool {
		return host.DataCenter() == dataCentre
	})
}
```

**Comment by zaddok** [comment]
I think I might have found what I was trying to describe, the `DCAwareRoundRobinPolicy`, I wonder if there could be some info added to the README.md with some common examples to save having to dig through the source code?

**Comment by martin-sucha** [comment]
You might want to use [TokenAwareHostPolicy](https://github.com/gocql/gocql/blob/558dfae50b5d/policies.go#L354) in combination with the `DCAwareRoundRobinPolicy` like `TokenAwareHostPolicy(DCAwareRoundRobinPolicy(localDC))`. That way requests will go to replicas based on partition key first. Also check out possible options for the `TokenAwareHostPolicy`: [ShuffleReplicas](https://pkg.go.dev/github.com/gocql/gocql#ShuffleReplicas), [NonLocalReplicasFallback](https://pkg.go.dev/github.com/gocql/gocql#NonLocalReplicasFallback)
