### ISSUE TITLE
Updating Query Logger

### ISSUE THREAD

**Issue by royprotim** [gocql/gocql#1568]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.10

### What version of Go are you using?
1.16

### What did you do?
```go
cluster.QueryObserver = &QueryLogger{Hosts: cassandraCfg.Hosts, Logger: logger, Query: make([]string, 1)}
cluster.BatchObserver = &QueryLogger{Hosts: cassandraCfg.Hosts, Logger: logger, Query: make([]string, 1)}
```
We set up Query and Batch Observer as above. Then creating a session with the cluster above. 

```go
session, err := cluster.CreateSession()
```
### What did you expect to see? 

We need to update the logger for every request because of some extra data we need our logger to print. 

### What did you see instead?

We are not able to update the logger unless we create new session for every request

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
Hello @royprotim. You can use [Query.Observer](https://pkg.go.dev/github.com/gocql/gocql#Query.Observer) and [Batch.Observer](https://pkg.go.dev/github.com/gocql/gocql#Batch.Observer) to set the observer per query/batch execution.

**Comment by royprotim** [comment]
Hi @martin-sucha ,

We don't want to set it per query/batch but per session. The QueryObserver works for a specific session as of now. Even if we update the `cluster.QueryObserver`, we still have to create a new session in order for it to reflect the changes.

**Comment by martin-sucha** [comment]
> We don't want to set it per query/batch but per session. 

It is still not clear to me what exactly you want to achieve.

You are correct that you cannot change the Session's observer once the session is created. This is by design and we won't change it. However, you should never need to change the observer of the session anyway:

* If you want to report some per-request (as in HTTP request) value, you can set the value in the request context and retrieve it from the context in your query observer.

* Or you can set a different Observer every time you execute a Query.

* If you want to change some settings of your query observer on the fly, you can implement the change inside your observer type directly. If you are sure that you want to change whole observer in the session, you can swap it in your implementation of the observer instead (but I can't imagine a use case where this is useful):

```go
type ObserverSwapper struct {
    mu sync.RWMutex
    observer gocql.QueryObserver
}

func (os *ObserverSwapper) ObserveQuery(ctx context.Context, q gocql.ObservedQuery) {
    os.mu.RLock()
    defer os.mu.RUnlock()
    os.observer.ObserveQuery(ctx, q)
}

func (os *ObserverSwapper) Swap(observer gocql.QueryObserver) {
    os.mu.Lock()
    defer os.mu.Unlock()
    os.observer = observer
}
```

If you show a snippet of code that you have I might be able to provide a better answer.

**Comment by royprotim** [comment]
This is the struct I have which is commonly used accross different data bases.
```go
type QueryLogger struct {
	Hosts     string     `json:"host,omitempty"`
	Query     []string   `json:"query"`
	Duration  int64      `json:"duration"`
	StartTime time.Time  `json:"-"`
	Logger    log.Logger `json:"-"`
	DataStore string     `json:"datastore"`
}
```

This is the implementation of the interfaces required for Query Observer. 
```go
func (l QueryLogger) ObserveQuery(ctx context.Context, o gocql.ObservedQuery) {
	duration := o.End.Sub(o.Start)
	l.Query[0] = o.Statement
	l.Duration = duration.Microseconds()
	l.DataStore = pkg.Cassandra

	l.Logger.Debug(l)
	l.monitorQuery(o.Keyspace, duration.Seconds())
}

func (l QueryLogger) ObserveBatch(ctx context.Context, b gocql.ObservedBatch) {
	duration := b.End.Sub(b.Start)
	temp := strings.Join(b.Statements, ", ")
	l.Query[0] = temp
	l.Duration = duration.Microseconds()
	l.DataStore = pkg.Cassandra

	l.Logger.Debug(l)
	l.monitorQuery(b.Keyspace, duration.Seconds())
}

func (l *QueryLogger) monitorQuery(keyspace string, duration float64) {
	// push stats to prometheus
	cqlStats.WithLabelValues(checkQueryOperation(l.Query[0]), l.Hosts, keyspace).Observe(duration)
}
```

Now there is something called correlationID we have in the `Logger` struct above. That is request specific.

`cluster.QueryObserver ` is an interface right? so even if I add any new method, I will not be able to call it. Observe the screenshot below. 

<img width="869" alt="Screenshot 2021-07-01 at 12 43 21 PM" src="https://user-images.githubusercontent.com/18380085/124082097-f31b3580-da69-11eb-81df-e85cbce6980c.png">

**Comment by martin-sucha** [comment]
I see that you store query information in fields of `QueryLogger` struct. Note that the query observer can be called from multiple goroutines. Make sure it is safe to call your ObserveQuery / ObserveBatch concurrently from multiple goroutines. So you should probably just log and update metrics in the ObserveQuery/ObserveBatch method to avoid race conditions.

<hr />

For using the `correlationID`, as I wrote previously, you can put `correlationID` into the request context and retrieve `correlationID` from the context in the observer. For example:

```go
type correlationIDKey struct{}

func correlationIDFromContext(ctx context.Context) string {
	if v := ctx.Value(k); v != nil {
		return v.(string)
	}
	return ""
}

func myHTTPHandlerFunc(w http.ResponseWriter, r *http.Request) {
	ctx := context.WithValue(r.Context(), correlationIDKey{}, "some value here")
	// some more code here
	query := session.Query("INSERT INTO example(col1) VALUES ('test')").WithContext(ctx)
	err := query.Exec()
        // ...
}
```
```go
func (l QueryLogger) ObserveQuery(ctx context.Context, o gocql.ObservedQuery) {
	duration := o.End.Sub(o.Start)
	l.Logger.Debug(LogEntry{
		Query: o.Statement,
		Duration: duration.Microseconds(),
		CorrelationID: correlationIDFromContext(ctx),
	})
	cqlStats.WithLabelValues(checkQueryOperation(o.Statement), l.Hosts, o.Keyspace).Observe(duration.Seconds())
}
```

I hope this helps.

**Comment by royprotim** [comment]
@martin-sucha Thanks for your responses. I was able to figure out a very simple solution to my problem.

```go
type CassandraSession struct {
	*gocql.Session
	Logger QueryLogger
}

func (c *CassandraSession) Query(stmt string, values ...interface{}) *gocql.Query {
	return c.Session.Query(stmt, values...).Observer(&c.Logger)
}

func (c *CassandraSession) NewBatch(typ gocql.BatchType) *gocql.Batch {
	return c.Session.NewBatch(typ).Observer(&c.Logger)
}
```

I believe Keeping It Simple is the best approach 😊
