### ISSUE TITLE
Doesn't work through proxy

### ISSUE THREAD

**Issue by sir-farfan** [gocql/gocql#1579]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[ycqlsh 5.0.1 | Cassandra 3.11.3.5122 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
require github.com/gocql/gocql v0.0.0-20210817081954-bc256bbb90d

### What version of Go are you using?
go version go1.15.5 linux/amd64

### What did you do?
This is the setup I've been using for the last year with Firefox, kubectl and a bunch of things:
Workstation -> host with VPN and proxy -> internal network -> Cassandra
export HTTPS_PROXY=http://192.168.x.y:z // and its env siblings on various casings

Connecting with the DNS name tries to resolve using localhost instead of the proxy server
1 `cluster := gocql.NewCluster("cassandra.company.com")`

Using the IP directly doesn't seem to go through the proxy either.
2 `cluster := gocql.NewCluster("10.x.y.z")`

### What did you expect to see?
A connection like the one I get when running the same thing directly from the "host with VPN"

GoLang stuff I've written, for REST calls at least, automatically picks the proxy environment variables.

### What did you see instead?
1 `gocql: dns error: lookup cassandra.company.com on 127.0.0.1:53: no such host`
2 `gocql: unable to create session: unable to discover protocol version: dial tcp 10.x.y.z:9042: i/o timeout`

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
Hello,

gocql uses the `net.Dialer` by default to establish connections. Also note that the client discovers IP addresses of all database nodes, so it will try to connect to the IP addresses configured on the server side (broadcast_address).

You can implement [gocql.Dialer](https://pkg.go.dev/github.com/gocql/gocql#Dialer) interface and configure it in [ClusterConfig](https://pkg.go.dev/github.com/gocql/gocql#ClusterConfig) to use custom logic for establishing connections, like connecting through a proxy.

If you need to remap the IP addresses you can implement [gocql.AddressTranslator](https://pkg.go.dev/github.com/gocql/gocql#AddressTranslator).

**Comment by martin-sucha** [comment]
Closing as it should be possible to provide custom gocql.Dialer or the newly added gocql.HostDialer to connect through any kind of proxy. It seems that gocql should not use HTTPS_PROXY environment variable as gocql does not use HTTPS.
