### ISSUE TITLE
Getting row's timestamp (writetime) and TTL

### ISSUE THREAD

**Issue by sir-farfan** [gocql/gocql#1580]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
[ycqlsh 5.0.1 | Cassandra 3.11.3.5122 | CQL spec 3.4.4 | Native protocol v4]

### What version of Gocql are you using?
require github.com/gocql/gocql v0.0.0-20210817081954-bc256bbb90de

### What version of Go are you using?
go version go1.16.3 darwin/amd64

### What did you do?
A SELECT query.
Get the iterator and see it's contents.

### What did you expect to see?
When I execute a SELECT statement from DataStax Studio, I also get the Time To Live and TimeStamp (write time) for free for each individual returned (row, col) cell.
How can I get that data using gocql?

### What did you see instead?
No cell metadata at all.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
Hello!

Similar to when you execute a query in `cqlsh`, you can `SELECT` the data in your query. You can use writetime and ttl functions in the select clause to get the data:
* [WRITETIME and TTL function](https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#writetime-and-ttl-function)
* [Returning the write time](https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useWritetime.html)

`SELECT mycolumn, writetime(mycolumn), ttl(mycolumn) FROM mytable WHERE ...`

**Comment by sir-farfan** [comment]
Thanks, that will do, I wish our ninja DBAs knew how the DB works 🤦
