### ISSUE TITLE
LWT query showing default consistency of QUORUM in query

### ISSUE THREAD

**Issue by danthegoodman1** [gocql/gocql#1588]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
ScyllaDB 4.4.4-0.20210801.69daa9fd0

### What version of Gocql are you using?
v0.0.0-20200131111108-92af2e088537 (indirect dep of gocqlx v2.4.0) 

### What version of Go are you using?
go version go1.17 darwin/amd64

### What did you do?

Attempted the following query builder query:
```go
// Insert if not exists
q := qb.Insert(db.IdentityMetadata.Name).
	Columns(db.IdentityMetadata.Columns...).
	Unique(). // IF NOT EXISTS
	Query(*db.DBSession).
	SerialConsistency(gocql.Serial).
	BindMap(map[string]interface{}{
		"namespace":   namespaceID,
		"id":          identityID,
		"password_id": "crap",
		"auth_method": "email",
		"created_at":  time.Now(),
		"updated_at":  time.Now(),
		"verified":    false,
		"active":      true,
		"traits":      "blah",
		"credentials": "kreuighr",
	})

applied, err := q.ExecCASRelease()
```

WIth the following output:
```
[query statement="INSERT INTO identities (namespace,id,password_id,traits,created_at,updated_at,active,verified,credentials,auth_method) VALUES (?,?,?,?,?,?,?,?,?,?) IF NOT EXISTS " values=[ex_id i-20HwL4ZTlq9PqtSGgnPYPr0Qdyz crap blah 2021-10-31 17:12:41.756966 -0400 EDT m=+2.704511886 2021-10-31 17:12:41.756966 -0400 EDT m=+2.704512123 true false kreuighr email] consistency=QUORUM]
```

### What did you expect to see?

I would expect `SERIAL` consistency

### What did you see instead?

The following result showed a consistency of `QUORUM`

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster

ScyllaDB running locally in docker container on laptop.

**Edit:**

I will add that it seems to be doing a transaction still, at least `IF EXISTS` and `IF NOT EXISTS` still seem to be respected, but I can't determine whether this is actually happening in a transaaction due to the shown consistency level.

**Comment by danthegoodman1** [comment]
I've also found that if I do a `q.SetConsistency(gocql.Consistency(gocql.Serial))` I get the following:
```
consistency=UNKNOWN_CONS_0x8
```

**Comment by danthegoodman1** [comment]
Another thing I have noticed is the docs say:
> This option will be ignored for anything else that a conditional update/insert.

However doing a `IF EXISTS` on a delete query and using the serial consistency seems to work.

**Comment by danthegoodman1** [comment]
This is how I am connecting:
```
func DBConnect() {
	var cluster *gocql.ClusterConfig
	scyllaHost := os.Getenv("SCYLLA_HOST")
	if scyllaHost == "" {
		cluster = gocql.NewCluster("localhost:9042")
	} else {
		cluster = gocql.NewCluster(scyllaHost)
	}
	cluster.Keyspace = "identity_ksp"

	session, err := gocqlx.WrapSession(cluster.CreateSession())
	utils.HandleError(err)

	DBSession = &session
}
```

**Comment by danthegoodman1** [comment]
I think the following might explain where I am mistaken: https://docs.datastax.com/en/dse/6.0/cql/cql/cql_reference/cqlsh_commands/cqlshConsistency.html#:~:text=A%20LWT%20is,CONSISTENCY%0A%20%20%20%20%20%20%20%20SERIAL%20fail%3A

**Comment by martin-sucha** [comment]
Indeed, [consistency](https://github.com/apache/cassandra/blob/d21e0dd8461e7ab9ce41ad4ee58e75134dc918ab/doc/native_protocol_v4.spec#L345) and [serial consistency](https://github.com/apache/cassandra/blob/d21e0dd8461e7ab9ce41ad4ee58e75134dc918ab/doc/native_protocol_v4.spec#L367-L372) are two different things.
