### ISSUE TITLE
How can I optimize this query?

### ISSUE THREAD

**Issue by delgec** [gocql/gocql#1595]
Hello everyone 

I need a bit help. 

### What version of Cassandra are you using?
4.0.1

### What version of Gocql are you using?
v0.0.0-20211222173705-d73e6b1002a7

### What version of Go are you using?
1.17.6

### Table name
countries

### Problem 1
The table named in the following query is incorrect. The query should throw an error. How can I catch the error message?

### Problem 2
The iterable is closeable. Should this iterable must be close? I've never seen it in the articles I've read

```

func (s *CountryStore) GetCountriesByIds(ctx context.Context, ids []int) []*model.Country {
	var list []*model.Country
	m := map[string]interface{}{}

	iterable := s.session.Query("SELECT * FROM wrong_table_name WHERE id IN ?", ids).WithContext(ctx).Iter()
        defer iterable.Close() **// Is it necessary? I've never seen it in the articles I've read**

	for iterable.MapScan(m) {
		var item = mapToCountry(m)
		list = append(list, item)
		m = map[string]interface{}{}
	}

	return list
}
```

Thanks.

**Comment by martin-sucha** [comment]
Hello,

> The table named in the following query is incorrect. The query should throw an error. How can I catch the error message?
> The iterable is closeable. Should this iterable must be close?

Yes, you need to close the `Iter` with [Iter.Close](https://pkg.go.dev/github.com/gocql/gocql#Iter.Close). That will release resources and also give you the error if there was one:

```go
func (s *CountryStore) GetCountriesByIds(ctx context.Context, ids []int) ([]*model.Country, error) {
	var list []*model.Country
	m := map[string]interface{}{}

	iterable := s.session.Query("SELECT * FROM wrong_table_name WHERE id IN ?", ids).WithContext(ctx).Iter()
	for iterable.MapScan(m) {
		var item = mapToCountry(m)
		list = append(list, item)
		m = map[string]interface{}{}
	}
	err := iter.Close()

	return list, err
}
```

Also note that MapScan will update the map and reuse any pointers that are in the map already, that's why we recommend using a new map each time MapScan is called: https://pkg.go.dev/github.com/gocql/gocql#Iter.MapScan

There is also https://github.com/scylladb/gocqlx that could help you with converting a result set into a list of structs.

> I've never seen it in the articles I've read

Which articles? If these are in gocql repository, we could update them.

**Comment by delgec** [comment]
> Hello,
> 
> > The table named in the following query is incorrect. The query should throw an error. How can I catch the error message?
> > The iterable is closeable. Should this iterable must be close?
> 
> Yes, you need to close the `Iter` with [Iter.Close](https://pkg.go.dev/github.com/gocql/gocql#Iter.Close). That will release resources and also give you the error if there was one:
> 
> ```go
> func (s *CountryStore) GetCountriesByIds(ctx context.Context, ids []int) ([]*model.Country, error) {
> 	var list []*model.Country
> 	m := map[string]interface{}{}
> 
> 	iterable := s.session.Query("SELECT * FROM wrong_table_name WHERE id IN ?", ids).WithContext(ctx).Iter()
> 	for iterable.MapScan(m) {
> 		var item = mapToCountry(m)
> 		list = append(list, item)
> 		m = map[string]interface{}{}
> 	}
> 	err := iter.Close()
> 
> 	return list, err
> }
> ```
> 
> Also note that MapScan will update the map and reuse any pointers that are in the map already, that's why we recommend using a new map each time MapScan is called: https://pkg.go.dev/github.com/gocql/gocql#Iter.MapScan
> 
> There is also https://github.com/scylladb/gocqlx that could help you with converting a result set into a list of structs.
> 
> > I've never seen it in the articles I've read
> 
> Which articles? If these are in gocql repository, we could update them.

Thank you very much.
