### ISSUE TITLE
Type Assertion Nil pointer problem

### ISSUE THREAD

**Issue by delgec** [gocql/gocql#1610]
Hello everyone

I can't use the nil pointer in the iterable mapscan.

If i am using this it gives error
`TimestampField:    m["like_count"].(*time.Time),`

If I use the if check, the result filling empty time value. 0001-01-01 00:00:00 +0000 UTC
```
if m["timestamp_field"] != nil {
    timestampField := m["timestamp_field"].(time.Time)
    item.TimestampField = &timestampField
} 
```

How can I fix it?

Thanks

```
func (s *ViewerStore) GetViewers(ctx context.Context) ([]*model.Viewer, error) {
	var list []*model.Viewer
	m := map[string]interface{}{}

	iterable := s.session.Query("SELECT * FROM viewers").WithContext(ctx).Iter()
	for iterable.MapScan(m) {
		item := &model.Viewer{
			NewsId:       m["news_id"].(gocql.UUID),
			ViewCount:    m["view_count"].(int64),
			TimestampField:    m["like_count"].(*time.Time), // ERROR
		}

		if m["timestamp_field"] != nil {
			timestampField := m["timestamp_field"].(time.Time)
			item.TimestampField = &timestampField
		} // OUTPUT: "0001-01-01 00:00:00 +0000 UTC"

		list = append(list, item)
		m = map[string]interface{}{}
	}
	if err := iterable.Close(); err != nil {
		return nil, errors.WithStack(err)
	}
	return list, nil
}
```

**Comment by martin-sucha** [comment]
Hello,

> If i am using this it gives error `TimestampField: m["like_count"].(*time.Time),`

Are you sure `like_count` is pointer to time.Time? Based on the name, it seems like like_count would be int.

> ```go
> if m["timestamp_field"] != nil {
>     timestampField := m["timestamp_field"].(time.Time)
>     item.TimestampField = &timestampField
> } 

MapScan stores the zero value in case there is null in the database, so you will get the zero time.
If you want to handle distinguish null and zero time stored in the database with MapScan, you'd need to set the key in the map first, so that gocql uses `*time.Time`. Something like this could work:

```go
m["timestamp_field"] = (*time.Time)(nil)
iter.MapScan(m)
```

If not, providing a custom unmarshaler should definitely work:

```go
type myUnmarshaler struct {
    var t *time.Time
}

func (u *myUnmarshaler) UnmarshalCQL(info gocql.TypeInfo, data []byte) error {
    return gocql.Unmarshal(info, data, &u.t)
}
```

But if you want a `[]*model.Viewer`,  you could use gocqlx.Select to scan directly to your structs: https://pkg.go.dev/github.com/scylladb/gocqlx#section-readme

**Comment by delgec** [comment]
```
m["timestamp_field"] = (*time.Time)(nil)
iter.MapScan(m)
```

that's worked. thank you.
