### ISSUE TITLE
Cassandra HealthCheck

### ISSUE THREAD

**Issue by CarloDeVita** [gocql/gocql#1619]
Please answer these questions before submitting your issue. Thanks!

Feature request: 

It would be nice to have some function to check cassandra liveness (session.Ping() as an example).
If I am not wrong, it still does not exist for gocql. Am I missing something?
What do you think about adding this feature? 
I thought about it, and maybe it would be simply implemented adding something like:
session.Query("SELECT release_version FROM system.local").Exec() and check if there is an error.
I think this feature is very useful in a microservices application, since usually a microservice can be set to NotReady if the underlying DB is unavailable for some reasons. 
In my use case, I used this query in my cassandra interfaces: SELECT release_version FROM system.local. But I think it could be nice to have a gocql.Session method (session.Ping()) which simply executes this health check. 
What do you think? If you agree, I will be very happy to contribute to the project.
Thanks,
Carlo

### What version of Cassandra are you using?
3.11

### What version of Gocql are you using?
latest

### What version of Go are you using?
1.17

---

**Comment by martin-sucha** [comment]
I don't think a method like `Session.Ping()` would be useful. Cassandra cluster can have many nodes, so it would not be clear on which node you want to execute the ping. Also, the node where the driver sends the request is selected based on the query. If one of the nodes is down, gocql automatically connects to some other replica holding the same token range (if there is one). If a query cannot be executed, you get an error from executing the query. gocql maintains connection pool internally and does healthchecks for each database node separately. Certainly you wouldn't want to mark your service as non-ready if only one of the nodes in the database cluster is down and it would be possible to service the query from another database node.

**Comment by martin-sucha** [comment]
I think that for this use case, you can just execute the query you proposed in your microservice directly. It seems that a different user would have different criteria as to what a method like Ping should do because they would have a different cluster topology than you have. Some users want to fallback to a remote DC if nodes in local DC are not available, for example.

**Comment by CarloDeVita** [comment]
Ok Martin, thank you very much for the quick responses. I think we can close this "issue".
