### ISSUE TITLE
impl of a custom address translator sometimes gets default port to translate

### ISSUE THREAD

**Issue by smiklosovic** [gocql/gocql#1634]
### What version of Cassandra are you using?

4.1-alpha1-SNAPSHOT (I am building that from sources but it actually does not matter, any 4.x will do).

### What version of Gocql are you using?

1.1.0

### What version of Go are you using?

1.18

### What did you do?

Because reasons, our Cassandra cluster is consisting of nodes where each node listens on a different CQL port. Lets say I have nodes running at `10.0.0.1:6001` and `10.0.0.2:6002`. These nodes are behind a proxy / LB with dns name `myproxy.com`, so I setup the seeds to be like "myproxy.com:6001,myproxy.com:6002". The proxy takes this and it re-routes it to `10.0.0.1:6001` and `10.0.0.1:6002` respectively. But, I need to have my own translator for this, because nodes return their internal addresses which are unreachable from application so my translator is supposed to translate `10.0.0.1:6001` to `myproxy.com:6001` and `10.0.0.2:6002` to `myproxy.com:6002`

I implemented my own translator which returns always the same IP no matter what IP I give to it. However, and this is super strange, for the nodes to be translated, the log message is like:

````
translating address '10.0.0.1:9042' to 'ip-of-my-proxy-dot-com:9042'
````

In other words, translator gets default 9042 port.

HOWEVER, sometimes it _does_ get the port. Sometimes, what it does, is that it is going to translate the IP of the proxy itself. In this case, it contains right address. The logs I see are:

````
2022/06/24 16:52:44 gocql: translating address '10.0.143.162:6001' to '10.0.143.162:6001'
2022/06/24 16:52:44 gocql: translating address '10.0.6.3:9042' to '10.0.143.162:9042'
2022/06/24 16:52:45 gocql: translating address '10.0.143.162:6002' to '10.0.143.162:6002'
2022/06/24 16:52:45 gocql: translating address '10.0.13.68:9042' to '10.0.143.162:9042'
````

13.68 and 6.3 are internal IPs of the nodes, 143.162 is IP of the proxy.

The translator:

````
       resolvedIp := ip-of-my-proxy-dot-com
	return gocql.AddressTranslatorFunc(func(addr net.IP, port int) (net.IP, int) {
		log.Printf("gocql: translating address '%v:%d' to '%v:%d'", addr, port, resolvedIp, port)
		return resolvedIp, port
	})
````

### What did you expect to see?

What I expect to see is that I will see log:

````
2022/06/24 16:52:44 gocql: translating address '10.0.6.3:6001' to '10.0.143.162:6001'
2022/06/24 16:52:45 gocql: translating address '10.0.13.68:6002' to '10.0.143.162:6002'
````

### What did you see instead?

Already described above.

What I should say is that the application _works as expected_. It just works. It connects and stuff. But it is mindbogling why it works when translator gets different ports.

**Comment by martin-sucha** [comment]
Hello! Thanks for the report!

gocql initially discovers peers by selecting from `system.peers` table. However, there is no port column in `system.peers` table, so the default port is probably used. Please confirm that if you do `SELECT * FROM system.peers` that the port is not listed anywhere in the result (if it were, we could change the code to read it, but I think it's not there). See comment here:

https://github.com/gocql/gocql/blob/473180d4afd379efd8f069edf4389bf2c0b7c96a/host_source.go#L511-L512

The topology events contain ip address and port, so when a host goes up/down or is added/removed to the cluster, it should be registered automatically.

So the address translator should probably replace the default port with the correct one.
We can at least update the docs if it won't be possible to get the port number from `system.peers`.

As for why the app works - it may be the case that it connects only to seeds which then forward the queries to correct nodes. Does ConnectObserver report any errors when dialing?

**Comment by martin-sucha** [comment]
> The topology events contain ip address and port, so when a host goes up/down or is added/removed to the cluster, it should be registered automatically.

Actually it seems gocql only reads the IP address, not the port.

**Comment by smiklosovic** [comment]
We have implemented same address translator for Datastax Java driver, here is PR, it was already accepted by the community and it gets the right port so I am not sure why gocql can not do it same when Java driver does it just fine.

I will try to investigate what Java driver is doing differently from gocql in this regard.

(1) https://github.com/datastax/java-driver/pull/1597

**Comment by smiklosovic** [comment]
@martin-sucha You can see the logic in the driver here, it is rather verbose as it needs to cover different Cassandra versions but it seems to me port is parsable just fine (1). Then it gets to (2) and finally to (3). I think it is only matter of how you parsing what Cassandra has to offer.
 
(1) https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultTopologyMonitor.java#L128
(2) https://github.com/datastax/java-driver/blob/a76d38e4ec86c18850381ed4c01afd21e3bd1e6e/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultTopologyMonitor.java#L272
(3) https://github.com/datastax/java-driver/blob/a76d38e4ec86c18850381ed4c01afd21e3bd1e6e/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultTopologyMonitor.java#L509

**Comment by smiklosovic** [comment]
Native port is here, this is for Cassandra 4.x though. There is no peers_v2 table in Cassandra 3.x.

````
cqlsh> DESCRIBE TABLE system.peers_v2;

CREATE TABLE system.peers_v2 (
    peer inet,
    peer_port int,
    data_center text,
    host_id uuid,
    native_address inet,
    native_port int, <<<<<<<<<<<<<<<
    preferred_ip inet,
    preferred_port int,
    rack text,
    release_version text,
    schema_version uuid,
    tokens set<text>,
    PRIMARY KEY (peer, peer_port)
) WITH CLUSTERING ORDER BY (peer_port ASC)

````

For Cassandra 4.x, there is also "rpc_port" in system.local.

For Cassandra 3.x, the driver is doing this https://github.com/datastax/java-driver/blob/a76d38e4ec86c18850381ed4c01afd21e3bd1e6e/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultTopologyMonitor.java#L468-L478

**Comment by smiklosovic** [comment]
Thanks @martin-sucha for the merge. When do you think there will be 1.2.0 release of this library? We are going to depend on this in some other open source project on GitHub.

**Comment by martin-sucha** [comment]
@smiklosovic I think I can release it on Wednesday or Thursday. I'd like to merge https://github.com/gocql/gocql/pull/1639 before cutting the release.

**Comment by martin-sucha** [comment]
@smiklosovic [v1.2.0](https://github.com/gocql/gocql/releases/tag/v1.2.0) is released  :tada:
