### ISSUE TITLE
No proper way of checking if a query is valid (without panicking)

### ISSUE THREAD

**Issue by xrahoo** [gocql/gocql#1658]
### What version of Cassandra are you using?
Cassandra 3.11.11

### What version of Gocql are you using?
v0.0.0-20210707082121-9a3953d1826d
(copied from go mod)

### What version of Go are you using?
1.18

### What did you do?
        q := sg.Connection.Cassandra.Session.Query("select * from non_existent")

        defer q.Release()

        c1 := map[string]interface{}{}

        iter := q.Iter() // The line that gets panicked

        count := 0
        for iter.MapScan(row) {
	        // Do things with row
	        c1 = map[string]interface{}{}
        }
        if err := iter.Close(); err != nil {
	        // handle err
	        fmt.Println(err)
        }

### What did you expect to see?
I am deliberately failing the query with a fictional table, but really this happens with every miss I have with my query.
No panic, instead a detailed matching error in the `err` variable
Would idealy wish to see the same error I am getting with a simple cli client:
`InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table non_existent"`

### What did you see instead?
The program panics with the following message:
`ERROR : panic: runtime error: invalid memory address or nil pointer dereference`

________________

Really sorry if this isn't the place for this and I am just missing something.
Thanks in advance.

**Comment by martin-sucha** [comment]
Hi!

It is not clear from your post on which line do you get the panic, could you add more information about the error?

In any case:

* `q.Exec()` returns only one value, not two, so the above would probably not compile
* Calling both `q.Exec()` and `q.Iter()` would execute the query twice (once in Exec, once in Iter) and reusing the query would distort the attempt count metrics at least.
* `q.Release` does not work properly in case you use gocql's speculative execution (https://github.com/gocql/gocql/issues/1315).
* Use `Iter.Close()` to get the error.

Please see also [Executing queries](https://pkg.go.dev/github.com/gocql/gocql#hdr-Executing_queries), [MapScan](https://pkg.go.dev/github.com/gocql/gocql#Iter.MapScan) example and other examples in the documentation.

So, something like the following should work for the above code:

```go
q := sg.Connection.Cassandra.Session.Query("select * from non_existent")
defer q.Release()

c1 := map[string]interface{}{}
iter := q.Iter()

count := 0
for iter.MapScan(row) {
	// Do things with row
	count++
	if count == 2 {
		break
	}
	c1 = map[string]interface{}{}
}
if err := iter.Close(); err != nil {
	// handle err
	fmt.Println(err)
}
```

**Comment by xrahoo** [comment]
> Hi!
> 
> It is not clear from your post on which line do you get the panic, could you add more information about the error?
> 
> In any case:
> 
> * `q.Exec()` returns only one value, not two, so the above would probably not compile
> * Calling both `q.Exec()` and `q.Iter()` would execute the query twice (once in Exec, once in Iter) and reusing the query would distort the attempt count metrics at least.
> * `q.Release` does not work properly in case you use gocql's speculative execution ([Data race in Query #1315](https://github.com/gocql/gocql/issues/1315)).
> * Use `Iter.Close()` to get the error.
> 
> Please see also [Executing queries](https://pkg.go.dev/github.com/gocql/gocql#hdr-Executing_queries), [MapScan](https://pkg.go.dev/github.com/gocql/gocql#Iter.MapScan) example and other examples in the documentation.
> 
> So, something like the following should work for the above code:
> 
> ```go
> q := sg.Connection.Cassandra.Session.Query("select * from non_existent")
> defer q.Release()
> 
> c1 := map[string]interface{}{}
> iter := q.Iter()
> 
> count := 0
> for iter.MapScan(row) {
> 	// Do things with row
> 	count++
> 	if count == 2 {
> 		break
> 	}
> 	c1 = map[string]interface{}{}
> }
> if err := iter.Close(); err != nil {
> 	// handle err
> 	fmt.Println(err)
> }
> ```

Thanks Martin, I updated the sample like you wrote it.
Unfortunately I still get the same panic described above. With the message:
` panic: runtime error: invalid memory address or nil pointer dereference`

The panic itself happens in q.Iter()

**Comment by martin-sucha** [comment]
Could you please post the whole stack trace of the panic so that it's clear where exactly it is happening? Also please try with the latest gocql version.

**Comment by xrahoo** [comment]
Hi, stack trace attached below.
The following was produced using the latest version of gocql (changed in go.mod to `latest` and then did go mod tidy).

Heres is also a code im using to intiate Cassandra - maybe its related too:

    func NewCassandra(hosts []string, keyspace string) (*Cassandra, error) {    
    	cluster := gocql.NewCluster(hosts...)
    	cluster.Keyspace = keyspace
    	cluster.Timeout = time.Minute
    	cluster.NumConns = 10
    
    	observer := apmgocql.NewObserver()
    	cluster.QueryObserver = observer
    	cluster.BatchObserver = observer
    
    	session, err := cluster.CreateSession()
    	if err != nil {
    		return nil, err
    	}
    
    	return &Cassandra{
    		cluster,
    		session,
    	}, nil
    }


> Exception has occurred: panic
"runtime error: invalid memory address or nil pointer dereference"
Stack:
	 4  0x0000000000a36afc in go.elastic.co/apm/module/apmgocql.(*Observer).ObserveQuery
	     at /home/user/.go/pkg/mod/go.elastic.co/apm/module/apmgocql@v1.8.0/observer.go:100
	 5  0x0000000000a210b5 in github.com/gocql/gocql.(*Query).attempt
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/session.go:994
	 6  0x0000000000a1a09b in github.com/gocql/gocql.(*queryExecutor).attemptQuery
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/query_executor.go:32
	 7  0x0000000000a1b167 in github.com/gocql/gocql.(*queryExecutor).do
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/query_executor.go:112
	 8  0x0000000000a1a8b3 in github.com/gocql/gocql.(*queryExecutor).executeQuery
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/query_executor.go:60
	 9  0x0000000000a1f8d4 in github.com/gocql/gocql.(*Session).executeQuery
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/session.go:446
	10  0x0000000000a21cce in github.com/gocql/gocql.(*Query).Iter
	     at /home/user/.go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200526081602-cd04bd7f22a7/session.go:1167
	11  0x0000000000a37e4e in careboxhealth.com/serviceName/internal/data.NewConnection
	     at /home/user/Documents/Projects/service-name/internal/data/connection.go:27
	12  0x0000000000ae5445 in main.run
	     at /home/user/Documents/Projects/service-name/cmd/api/main.go:44
	13  0x0000000000ae50ab in main.main
	     at /home/user/Documents/Projects/service-name/cmd/api/main.go:21

>

**Comment by xrahoo** [comment]
Update: with dropping the Observer from ClusterConfig the panic does not happen.

to clarify:

`func NewCassandra(hosts []string, keyspace string) (*Cassandra, error) {    
	cluster := gocql.NewCluster(hosts...)
	cluster.Keyspace = keyspace
	cluster.Timeout = time.Minute
	cluster.NumConns = 10

	//observer := apmgocql.NewObserver()
	//cluster.QueryObserver = observer
	//cluster.BatchObserver = observer

	session, err := cluster.CreateSession()
	if err != nil {
		return nil, err
	}

	return &Cassandra{
		cluster,
		session,
	}, nil
}`

**Comment by xrahoo** [comment]
OK I figured out this was purely an `apmgocql` issue, that was resolved in newer versions, so I updated and the issue resolved.
Closing this.. if you have anymore questions open.
