### ISSUE TITLE
Allow passing struct's into Query.Scan()

### ISSUE THREAD

**Issue by ajsharp** [gocql/gocql#167]
Instead of needing to pass individual fields into `Scan` like this:

``` go
iter := cqlSession.Query(`SELECT * FROM Events WHERE id=?`, id).Iter()

var fieldOne string
var fieldTwo int

for iter.Scan(&fieldOne, &fieldTwo) {
  // ...
}
```

It would be nice to be able to do this, and have the fields returned mapped to the object:

``` go
iter := cqlSession.Query(`SELECT * FROM Events WHERE id=?`, id).Iter()

var event Event

for iter.Scan(&event) {
  // ...
}
```

Presumably such functionality would be enabled by tags:

``` go
type struct Event {
  Id   gocql.UUID `cql:"id" json:"id"`
  Name string     `cql:"name" json:"name"`
}
```

Has this been proposed before? Are you open to it, or do you feel this is better-suited to a higher level library?

**Comment by mmatczuk** [comment]
Hi,
I'm going back to this old issue as we at Scylla have put up a new tool that is fast, flexible and complete. Please take a look if you are interested: https://github.com/scylladb/gocqlx
