### ISSUE TITLE
Confusing documentation of timeouts

### ISSUE THREAD

**Issue by lcosmin** [gocql/gocql#1671]
### What version of Cassandra are you using?
n/a

### What version of Gocql are you using?
master branch @ [66ec152](https://github.com/gocql/gocql/commit/66ec1520631c9e3b9b40777d2febd537e09ddaaa)

### What version of Go are you using?
n/a

### What did you do?
n/a

### What did you expect to see?
n/a

### What did you see instead?
The documentation for [Timeout](https://github.com/gocql/gocql/blob/master/cluster.go#L55) is confusing, as it mentions `ConnectionTimeout`. It doesn't say what `Timeout` actually does.

**Comment by martin-sucha** [comment]
Thanks for the report! Indeed the docs don't specify when exactly the timeouts apply.
