### ISSUE TITLE
gocql driver cannot be used with com.scylladb.auth.TransitionalAuthenticator

### ISSUE THREAD

**Issue by tarzanek** [gocql/gocql#1703]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Scylla, any version that has  com.scylladb.auth.TransitionalAuthenticator  (so basically all of them since 1.6)

### What version of Gocql are you using?
1.4.0

### What version of Go are you using?
go1.20.4

### What did you do?
trying to access Scylla with com.scylladb.auth.TransitionalAuthenticator  
https://docs.scylladb.com/stable/operating-scylla/security/runtime-authentication.html

### What did you expect to see?
just connect while providing dummy password (as does python (cqlsh) or java driver)

### What did you see instead?
```
ERROR: gocql: unable to create session: unable to discover protocol version: unexpected authenticator "com.scylladb.auth.TransitionalAuthenticator"
```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

the only thing needed is to enable in `scylla.yaml` and restart node:
```
authenticator: com.scylladb.auth.TransitionalAuthenticator
```

- while other drivers are OK with above and just login, it seems gocql is too strict here and fails, can this be relaxed pretty please?

**Comment by tarzanek** [comment]
this breaks the functionality of transparently enabling roles/users in Scylla
the only workaround is to temporarily enable on one node full auth and quickly create expected users/roles the client use to minimize the impact

**Comment by martin-sucha** [comment]
Related to https://github.com/gocql/gocql/issues/529

**Comment by martin-sucha** [comment]
It seems to me that the allowlist causes more trouble than we get benefits from it, so we could perhaps change the default. Users could still use PasswordAuthenticator.AllowedAuthenticators if they need the allowlist. @Zariel @jameshartig what do you think, should we change the default (empty AllowedAuthenticators) to accept all authenticator class names or do you think it is more a breaking change?

**Comment by jameshartig** [comment]
@martin-sucha strictly speaking, I think it is a breaking change but I'm not sure if it will materially break anything. The fix for users is just to add this custom one to the list, right? So it's not like any user is stuck, they just need to add a line of code to define this one. Assuming that's true, I don't know if its worth making the change yet but can be added to a list of things to add to a larger breaking change release.

**Comment by martin-sucha** [comment]
> The fix for users is just to add this custom one to the list, right?

Yes. However, some users that can't do that easily if they are not using gocql directly, but rather some product that embeds it which does not expose the option. For example: Hashicorp Vault

There are many requests to add various authenticator classes. See also #1711 .

All right, let's at least add the `com.scylladb.auth.TransitionalAuthenticator` to the default approved list.
