### ISSUE TITLE
Reconnect control using initial hosts

### ISSUE THREAD

**Issue by Bolodya1997** [gocql/gocql#1713]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
`4.1.0`

### What version of Gocql are you using?
`1.5.2`

### What version of Go are you using?
`1.19`

### What did you do?
1. Cassandra cluster is created as a StatefulSet in k8s cluster.
2. `hosts` for the `gocql.NewCluster()` are hostnames made upon headless service (`cassandra-0.cassandra.default.svc`, ..., `cassandra-n.cassandra.default.svc`).
3. At some time, all nodes restarts simultaneously (without losing data), so all of them go down and after start with different IP addresses.

### What did you expect to see?
I expect that `gocql` should be able to use initial `hosts` to reconnect existing `gocql.Session` or at least have some option to enable such behavior.

### What did you see instead?
`gocql` continues using last resolved IP addresses to reconnect the control and so it keeps failing, even when Cassandra cluster is actually ready and operating.
```
2023/07/10 12:25:35 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:35 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:35 gocql: control unable to register events: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:39 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:39 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:39 gocql: control unable to register events: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:40 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:40 gocql: unable to dial control conn 10.244.1.59:9042: dial tcp 10.244.1.59:9042: connect: connection refused
2023/07/10 12:25:40 gocql: control unable to register events: dial tcp 10.244.1.59:9042: connect: connection refused
```

**Comment by martin-sucha** [comment]
Hi!

https://github.com/gocql/gocql/pull/1708 should fix this. The pull request is already merged into master, but a new version is not released yet.

**Comment by Bolodya1997** [comment]
@martin-sucha
Thank you, it works!
