### ISSUE TITLE
otelgocql deprecation

### ISSUE THREAD

**Issue by pellared** [gocql/gocql#1718]
I am creating this issue to inform you that we (OpenTelemetry contributors) are planning to deprecate https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/gocql/gocql/otelgocql.

You can consider copying the OpenTelemetry instrumentation to this repository or organization. You can even consider instrumenting with OpenTelemetry "natively" (without requiring the users to use an instrumentation library). You can also check for more information [here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#new-instrumentation).

**Comment by martin-sucha** [comment]
Thank you for the notification!

gocql/gocql has interfaces that allow observing queries/batches, which the otelgocql package already uses.
There are many things that can be tracked about queries and there are different tradeoffs for tracking different subsets of data, so it seems to be better to leave what should be tracked to the users.
If there are any users of the otelgocql package, they could maintain it in some external repository.
