### ISSUE TITLE
Tuple type (2.1)

### ISSUE THREAD

**Issue by al3xdm** [gocql/gocql#177]
Final new 2.1 feature that we're looking at (https://issues.apache.org/jira/browse/CASSANDRA-6875) requires the new CQL tuple type: https://issues.apache.org/jira/browse/CASSANDRA-7248

**Comment by 0x6e6562** [comment]
What's required roadmap-wise to turn this into a pull request?

**Comment by Zariel** [comment]
I based it on my frame-refactor branch which is #339

**Comment by 0x6e6562** [comment]
Ah, so the two patches need to be separated first?

**Comment by Zariel** [comment]
Ideally #339 would be merged then it will apply cleanly over the top, but if thats not the case then I can rebase it onto current master.

**Comment by 0x6e6562** [comment]
OK, let's look at trying to land #339.

**Comment by cellofellow** [comment]
I know that this issue is closed, but I don't see any way in which to marshal a tuple. Am I missing something?
