### ISSUE TITLE
CASSGO-28 Retry type Ignore is not different from Rethrow (error is still returned)

### ISSUE THREAD

**Issue by Rikkuru** [gocql/gocql#1808]
### What version of Cassandra are you using?
Scylla Enterprise 2024.1.8 or scylla 5.1 

### What version of Gocql are you using?
github.com/gocql/gocql v1.6.0

### What version of Go are you using?
go 1.21.11

### What did you do?
used RetryType Ignore (https://pkg.go.dev/github.com/gocql/gocql#RetryType) on write query 

### What did you expect to see?
I expected that query.Exec() would not return error  

### What did you see instead?
the error is returned.

---

Maybe the documentation is not clear on how Ignore and Rethrow are different? 

I thought Ignore would make it so that Exec does not return error ? Maybe this would be strange on read ops but it can be used on writes (in Downgrading CL retry policy for example ). But they both return error and I don't see any difference between those retry types 

Is there any difference in Rethrow and Ignore retry types  ?

**Comment by Rikkuru** [comment]
Example (on empty cluster , keyspace error is ok for our test )

MyRetryPolicy can return Ignore or Rethrow - it changes nothing 

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/gocql/gocql"
)

type MyRetryPolicy struct {
}

func (*MyRetryPolicy) Attempt(q gocql.RetryableQuery) bool {
	if q.Attempts() > 2 {
		return false
	}
	return true
}

func (*MyRetryPolicy) GetRetryType(error) gocql.RetryType {
	return gocql.Ignore
}

type LoggingObserver struct{}

func (*LoggingObserver) ObserveQuery(ctx context.Context, q gocql.ObservedQuery) {
	fmt.Printf("observer attempt: %d err: %s\n", q.Attempt, q.Err)
}

func main() {
	cluster := gocql.NewCluster("node-1")
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: "scylla",
		Password: "***",
	}

	s, err := gocql.NewSession(*cluster)
	if err != nil {
		fmt.Printf("session err: %s\n", err)
	}
	defer s.Close()

	q := s.Query("INSERT INTO  my.events(event_id, time, args) VALUES (?,?,?)", 1, gocql.UUIDFromTime(time.Now()), "test")

	q.RetryPolicy(&MyRetryPolicy{})
	q.Observer(&LoggingObserver{})

	fmt.Printf("QUERY IsIdempotent: %v\n", q.IsIdempotent())

	err = q.Exec()
	if err != nil {
		fmt.Printf("exec err: %s\n", err)
	}

}

```

Output
```
➜  test go run main.go
QUERY IsIdempotent: false
observer attempt: 0 err: Keyspace my does not exist
exec err: Keyspace my does not exist
```

**Comment by Rikkuru** [comment]
need to add ignored error in ObserverdQuery too

**Comment by joao-r-reis** [comment]
I honestly don't see a use case for `Ignore`, we should probably just deprecate it.

**Comment by joao-r-reis** [comment]
Hmm other drivers also have `Ignore` so we can probably keep it as well but we need to fix the behavior and add tests to ensure it's properly fixed and there's no regressions in the future.

**Comment by joao-r-reis** [comment]
v2.0.0-rc1 with the fix for this has been released, it would be great if users could try it out and provide feedback on it before 2.0.0 GA
