### ISSUE TITLE
"no viable alternative at input" error on ALTER TABLE IF EXISTS

### ISSUE THREAD

**Issue by ebilling** [gocql/gocql#1841]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
4.1.0

### What version of Gocql are you using?
1.7.0

### What version of Go are you using?
1.23.2

### What did you do?
We constructed the following query: `ALTER TABLE IF EXISTS foo.bar ADD IF NOT EXISTS column_name BLOB`
This was sent via:

```
q := c.Session.Query(ctx, "ALTER TABLE IF EXISTS foo.bar ADD IF NOT EXISTS column_name BLOB")
return q.Consistency(gocql.LocalQuorum).Exec()
```

### What did you expect to see?
Based on documentation, and sending the same query via cqlsh this should succeed.

### What did you see instead?
`line 1:12 no viable alternative at input 'IF' (ALTER TABLE [IF]...)`

**Comment by joao-r-reis** [comment]
That is not valid CQL as far as I'm aware, there's no "IF EXISTS" for "ALTER TABLE". It's an error that is returned by the server not the driver.

**Comment by yifan-c** [comment]
`IF EXISTS` in the context of alter table is available since 4.1. https://issues.apache.org/jira/browse/CASSANDRA-16916

**Comment by joao-r-reis** [comment]
I stand corrected, hmm I can try to investigate this but the error does seem like a server error

**Comment by joao-r-reis** [comment]
I can't reproduce, that query works fine on my test project (tested with C* 4.1.0 on Docker). Make sure you're connecting to the correct C* cluster.

**Comment by ebilling** [comment]
Thanks.  We'll verify that all instances are current.
