### ISSUE TITLE
Question: `describe keyspaces` query

### ISSUE THREAD

**Issue by xbeta** [gocql/gocql#193]
Hello all,

Forgive my bad knowledge of Cassandra and Golang, but I'm trying to learn here by picking up this library.

I would like to get myself start to simply running `describe keyspaces;` query to Cassandra, and this is the code snippet I have so far:

``` go
  cluster := gocql.NewCluster("localhost")
  session, err := cluster.CreateSession()
  defer session.Close()
  iter := session.Query(`DESCRIBE KEYSPACE`).Iter()
```

But the result is nothing.  So I would like to know what else I did wrong at my calls.

Thanks

**Comment by wedneyyuri** [comment]
> [This is an example](https://github.com/relops/cqlc/blob/master/generator/schema.go#L114) of how to use gocql to query the system keyspace.

(sorry for bringing this thread again, but this page is still relevant to google)

There is a easier way to describe a Keyspace or describe tables:

```go
session, err := r.r.createSession(KeyspaceName)
if err != nil {
	return nil, errors.Wrap(err, "create session")
}
defer session.Close()

keyspaceMetadata, err := session.KeyspaceMetadata(KeyspaceName)
if err != nil {
	return nil, err
}

for _, table := range keyspaceMetadata.Tables {
	fmt.Println(table.Name)
}
```

https://godoc.org/github.com/gocql/gocql#Session.KeyspaceMetadata
