### ISSUE TITLE
Support client side timestamps

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#265]
Currently the client can send many requests which can arrive out of order at Cassandra, where by default it uses the timestamp when a query arrives at the coordinator to decide the last write wins for inserts which can cause issues in high load time sensitive applications as in #264.

To work around this in protocol V2 and V1 queries can append `USING TIMESTAMP ?` to the query to specify the client timestamp to maintain the outgoing order.

V3 of the binary protcol allows the driver to send the timestamp as part of the query which we should enable by default for V3 protocol [0].

[0] https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec#L322

**Comment by xueyouchao** [comment]
@Zariel 
I have a question. It seems to me there is a confliction here.

https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlInsert.html
Cassandra mentioned :
Restriction: INSERT does not support IF NOT EXISTS and USING TIMESTAMP in the same statement.

My question is if I sent lots of IF NOT EXISTS insertion using gocql against Cassandra 3.0+, 
does gocql internally append USING TIMESTAMP to Cassandra?

If yes, it will get false result back. (I can't post the result here. But I do see MapScanCAS returns false but still the insertion is successful in our ENV.) My guess is sending insertion cmd with USING TIMESTAMP to replace server side TIMESTAMP will potentially break Cassandra light weight transaction's Paxos protocol for IF NOT EXISTS checking.

If not, then this bug will still exists when sending lots of IF NOT EXISTS  in high load time sensitive applications.

**Comment by Zariel** [comment]
there isn't a way for the client to know that a query is doing a LWT unless it parses it, surely Cassandra should be ignore the client sent timestamp as it knows its doing the LWT?

**Comment by xueyouchao** [comment]
Even they ignore , that means they will still use server side timestamp which means this bug may still open in that case.

**Comment by Zariel** [comment]
yes but that doesn't need to be set as it defaults, I guess we could be disabling it in *CAS methods though

**Comment by xueyouchao** [comment]
If you can do that, hopefully CAS will work correctly without bug #264 re-surfacing.

**Comment by Zariel** [comment]
Can you link me to any documentation/cassandra issue which mentions that the client sending the timestamp in the query frame can be harmful when executing LWTs as I can't find anything. #264 is a different issue. The driver is not changing the outgoing query it instead sets the flag in the query frame that sends the timestamp see here https://github.com/apache/cassandra/blob/2ecadc88e4407ebd4b3325f42e0296e1e1dc8944/doc/native_protocol_v5.spec#L335

**Comment by xueyouchao** [comment]
@Zariel 
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlInsert.html

TIMESTAMP epoch_in_microseconds 
Marks inserted data (write time) with TIMESTAMP. Enter the time since epoch (January 1, 1970) in microseconds. By default, Cassandra uses the actual time of write.

Restriction: INSERT does not support IF NOT EXISTS and USING TIMESTAMP in the same statement.

**Comment by xueyouchao** [comment]
My understanding is  IF NOT EXISTS (not sure about the other IF clause check) strictly requires server side timestamp to ensure the correctness of linearizable consistency.

I saw another issue where they mentioned (without client side timestamp) even mixing non-LWT and LWT will cause issues.
https://issues.apache.org/jira/browse/CASSANDRA-13767
