### ISSUE TITLE
Unable to Install gocql

### ISSUE THREAD

**Issue by BorderlessNomad** [gocql/gocql#267]
Hi Guys,

I am receiving following error while executing `go get github.com/gocql/gocql`

```
mayur@eantrix:~# go get github.com/gocql/gocql
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /home/ubuntu/gocode/src/speter.net/go/exp/math/dec/inf
Cloning into '/home/ubuntu/gocode/src/speter.net/go/exp/math/dec/inf'...
fatal: unable to access 'https://code.google.com/p/go-decimal-inf.exp/': Failed to connect to code.google.com port 443: No route to host
package speter.net/go/exp/math/dec/inf: exit status 128
```

I've already checked my internet connection (both local & server), Go installation is working fine in fact it complies other projects where gocql is not required and imported. I've started noticing the problem since yesterday.

**Comment by rubycut** [comment]
Again same issue.

**Comment by rubycut** [comment]
```
 go get speter.net/go/exp/math/dec/inf
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /home/sysmon/go/src/speter.net/go/exp/math/dec/inf
Cloning into '/home/sysmon/go/src/speter.net/go/exp/math/dec/inf'...
fatal: repository 'https://code.google.com/p/go-decimal-inf.exp/' not found
package speter.net/go/exp/math/dec/inf: exit status 128
```

**Comment by rubycut** [comment]
https://github.com/kubernetes/kubernetes/issues/23529

**Comment by rubycut** [comment]
From the issue above, it seems package moved to: http://gopkg.in/inf.v0

Can we update gocql to use this new location?

**Comment by nemothekid** [comment]
gocql *does* use this new location, the google code repo has been down for months:

https://github.com/gocql/gocql/blob/master/marshal.go#L20

Check if you are using the most up to date code?

**Comment by rubycut** [comment]
Yes, you are correct, I had old code.

**Comment by zhangguanzhang** [comment]
same issue, go mod is a subgroup module. 

```
fatal: unable to connect to xxx.xxx.net:
	xxx.xxx.net[0: 10.xx.x.xx]: errno=No route to host
```

but work for me:
```
git config --global url."git@xxx.xxx.net:".insteadof "https://xxx.xxx.net/"
go build
```
