### ISSUE TITLE
Decide on the future of the mock test server

### ISSUE THREAD

**Issue by 0x6e6562** [gocql/gocql#279]
#275 demonstrated that the mock test server may actually be costing us more in terms of maintenance and build failures than we are getting benefit from it. So this ticket has been created to address the issue and take the according action.

**Comment by Zariel** [comment]
Over the weekend I was refactoring the frame handling code, in in doing so removed most of the code for creating frames which are not supposed to come from the client.

As such the TestServer is now pretty broken.

**Comment by 0x6e6562** [comment]
OK - as stated in other threads, I would be happy to see the test server get EOL'ed, so if the test server stands in the way of some other change down the line, then here's my pre-vote of approval to get rid of it :-)
