### ISSUE TITLE
Intermittent ring discovery test failure

### ISSUE THREAD

**Issue by 0x6e6562** [gocql/gocql#280]
The ring discovery test appears to intermittently only discover 2 out 3 nodes in the ccm cluster on Travis. As part of #275, bb7e0323136df4f93d8fe8bb88efb29f22c41b7f made the executive decision to log this occurrence rather than failing the build. It doesn't appear that there is any issue with the ccm cluster. So basically we have a silent bug in the test suite that we're consciously allowing to get through.

**Comment by Zariel** [comment]
The only way I could reproduce this locally on my laptop was by removing the sleep, I wonder if there is a potentially slow query which causes this?

**Comment by Zariel** [comment]
This is fixed now
