### ISSUE TITLE
Proposal: Clarify when error messages originate from the server

### ISSUE THREAD

**Issue by JensRantil** [gocql/gocql#281]
Right now, when gocql receives an error from the server, it unhelpfully outputs the verbatim of the error message without indicating to the user that this error originated on the server side. For example:

```
Operation timed out - received only 0 responses
```

It would be much clearer from a debugging perspective if this log output were somehow denoted clearly as a being a server side issue.

See [this related discussion](https://github.com/gocql/gocql/issues/34#issuecomment-61239855) for some background.

**Comment by let4be** [comment]
Any update on this, is this library even being maintained?...

**Comment by Zariel** [comment]
You are welcome to contribute

**Comment by JensRantil** [comment]
> Any update on this, is this library even being maintained?...

@let4be The repository code was updated 5 days ago, so definitely actively maintained.

**Comment by Zariel** [comment]
also errors which originated from Cassandra are available via types in https://github.com/gocql/gocql/blob/master/errors.go

Closing this and future issues can be about improving this user experience or for gaps in the implementation.
