### ISSUE TITLE
Implementing Marshaler with a pointer receiver no longer works.

### ISSUE THREAD

**Issue by james-maloney** [gocql/gocql#290]
[This](https://github.com/gocql/gocql/commit/8eb8ccf7f39d72c0e29959edf5f63c9015c2cf96#diff-984b621d683cf81bbf404d291c4802a8R43) addition seems to be the problem. 

Seems like:

    if v, ok := value.(Marshaler); ok {
        return v.MarshalCQL(info)
    }

Should be called before the pointer check.

**Comment by 0x6e6562** [comment]
Considering that this was addressed in #291, should this particular ticket not get closed (even if #287, which is ongoing, is tangential to this issue)?
