### ISSUE TITLE
SliceMap doesn't return all rows

### ISSUE THREAD

**Issue by julienfouilhe** [gocql/gocql#310]
I have a bug and I don't know where exactly it comes from, but whenever I add a column to a table using

```cal
ALTER TABLE "tablename" ADD "new_column" int;
```
(request made directly from `cqlsh` though.

And that I request then (after restarting my program):

```go
params := ...
stmt := `SELECT * FROM "tablename" WHERE ...`
res, err := session.Query(stmt, params...).Iter().SliceMap()
```

I get my results without the new column added (other columns are there). The column is present when I do the same request using **cqlsh**

**Comment by 0x6e6562** [comment]
If you can provide an easy way to reproduce this bug (i.e. a simple runnable example together with schema definitions), then I will run it locally and have at look it. Otherwise it will take me longer to look into this.

**Comment by julienfouilhe** [comment]
Just found out it is actually a known bug in Cassandra and that it will be resolved in 2.1.3.

https://issues.apache.org/jira/browse/CASSANDRA-7910

**Comment by 0x6e6562** [comment]
OK, good to know, thanks for the heads up. Can we close this issue now or do you need to keep it open?

**Comment by julienfouilhe** [comment]
Since it is an issue related to Cassandra and not to the library itself, I think it would be better to close it.
