### ISSUE TITLE
Enable execution of unprepared queries?

### ISSUE THREAD

**Issue by hbcheng** [gocql/gocql#313]
Hello,

Thanks for all the awesome work on this driver.

Currently, our application uses a number of conditional update statements of the type "IF col = foo". These statements as far as I understand cannot be parametrized (http://www.datastax.com/documentation/cql/3.1/cql/cql_reference/prepared_stmt_c.html), so the value of the IF statement (foo) must be in the query statement string. By my understanding of the gocql code, this UPDATE statement will be prepared and added to the prepared statement LRU cache, which runs the risk of generating a large amount of prepared statements where the only difference is the conditional IF statement.

Is there any way to execute a query without preparing it? If not, and this is something that makes sense for the project, I could take a crack at a patch to allow a Query object to indicate that it should not be prepared, and make a pull request.

Thanks!

**Comment by 0x6e6562** [comment]
We have a couple of test cases that do parameterize the CAS condition, e.g.

https://github.com/gocql/gocql/blob/master/cassandra_test.go#L289

Do you have an example that is not working for you? If so, maybe we can look into why that is not working.

**Comment by hbcheng** [comment]
Well in that case consider me incorrect.

I was going off of the Datastax documentation for CQL 3.1 (linked above), which seems to indicate that the target of "IF col =" statements were not on the list of parameterizable statements. This may be a documentation issue on their end, then. Sorry for the noise.

**Comment by 0x6e6562** [comment]
No worries at all :-)

The DataStax documentation is generally authoritative, but there are still bugs (or just ambiguous stuff) in it that require cleaning as well - I'm not sure whether an issue should be raised with them about these individual items.

But at least they do actually document stuff, which is better than gocql :-)

If you do find an example that is not working for you, do let us know.

**Comment by 0x6e6562** [comment]
Note to google: Right now, the gocql API does not let you manually disable the statement cache. That is not to say that this will never happen, it is just that for every example that we've come across thus far where people have wanted to disable the cache, it has turned out that there was a way to avoid the problem in the first case. But this might not always be the case.
