### ISSUE TITLE
Add support for named param binding

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#323]
In protocol v3 we can bind params in queries using names instead of ?

**Comment by Zariel** [comment]
@0x6e6562 how would this interact with the current query binding? Could we replace the current logic in v3 with this?

**Comment by Zariel** [comment]
This ties into #175 as they both require params to have names

**Comment by Zariel** [comment]
Im not entirely sure this is worth adding to be honest

**Comment by 0x6e6562** [comment]
Do you think you state why not (for the sake of posterity when somebody is asking for this in the future)?

**Comment by Zariel** [comment]
As we always prepare statements we get back the arguments in the correct order from the PREPARE call which means we wont need to send the value names.

It will complicate the API as we go from having a query interface by positional arguments to one which is identified by named values, which i'm not too keen on.

The spec has this to say about it as well,

`Note that this is only useful for
              QUERY requests where named bind markers are used; for EXECUTE statements,
              since the names for the expected values was returned during preparation,
              a client can always provide values in the right order without any names
              and using this flag, while supported, is almost surely inefficient.`

So unless someone comes up with a use case and a good API I don't think this is worth adding.

**Comment by 0x6e6562** [comment]
Fair enough, let's close this issue then.
