### ISSUE TITLE
RFC: Dont export Conn, Connect and ConnectionPool

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#326]
Im not sure why the Conn struct and the Connect function are exported, it makes me warey of changing the API, for instance changing it to take a dialer.

The rationale for not exporting the ConnectionPool is that once we have a host based connection pool it doesnt make sense for it to be replaceable, and will allow the driver to make more specific assumptions about the features of the pool and will simplify the code once we need to do things like token aware host selection. Instead we should expose the host selection policy for a query so that the host selector can be replaced.

**Comment by Zariel** [comment]
So whilst playing with implementing a control connection which receives events and can query system  tables it becomes really hard to do this in a way without having access to the connection pool, as such making it a a concrete type which can not be changed makes this much easier.

@0x6e6562 @justinretailnext thoughts?

Given #356 I think we should make the underlying pool unchangeable and only allow the policies to be changed.

**Comment by 0x6e6562** [comment]
I think it's too early to tell whether this is a good idea or not - i would suggest we let other things mature around this until making this decision.
