### ISSUE TITLE
runtime/cgo: pthread_create failed: Resource temporarily unavailable in travis

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#330]
`=== RUN TestRingDiscovery
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fd28bdbe445`

https://travis-ci.org/gocql/gocql/jobs/54245096

**Comment by Zariel** [comment]
I wonder if this is related to #332 ?

**Comment by 0x6e6562** [comment]
Good point - let's try to get that merged so we can see what effect it may have.

**Comment by Zariel** [comment]
I guess not

**Comment by Zariel** [comment]
I think this is related to #324 but it happens during when Go is creating its threads.

**Comment by Zariel** [comment]
This could be fixed by #334

**Comment by Zariel** [comment]
Think this was fixed by #334, closing until it happens again.

**Comment by justinwhite** [comment]
For anyone else.. build was running out of memory and throwing this error. Fixed with a larger droplet on Digital Ocean.

**Comment by Zariel** [comment]
I think this was caused by exhausting virtual memory in the VM when we were running in travis.
