### ISSUE TITLE
Lock upgrades whilst refilling a connection pool 

### ISSUE THREAD

**Issue by 0x6e6562** [gocql/gocql#370]
[As discussed](https://github.com/gocql/gocql/pull/348#discussion-diff-28655667) during the review of #348, we should revisit lock upgrades during a connection pool refill.

**Comment by nemothekid** [comment]
Is there any reason why we should with @Zariel proposed solution? Its small enough that I can write it this weekend, and if the implementation is the same, the current tests should suffice?

**Comment by 0x6e6562** [comment]
>Is there any reason why we should with @Zariel proposed solution?

Did you mean to say "should not go with"?

If so, then I think it is fine to try that out - after all it would be a small patch, so feel free to contribute it.
