### ISSUE TITLE
Ease the creating of IN queries

### ISSUE THREAD

**Issue by henrikbjorn** [gocql/gocql#372]
Currently it is not possible to write a query like:

```
SELECT * FROM my_column_family WHERE my_column IN (?)
```

It would be great if the marshaller supported this, and would make it much easier if you use a secondary column_family as a index.

**Comment by 0x6e6562** [comment]
I've noticed that we don't have test coverage for `WHERE .. IN`, so I added this in #373.

However, I don't fully understand your question - are you saying that gocql does not allow to submit a query like this, or that you can't bind the response?

**Comment by henrikbjorn** [comment]
@0x6e6562 seems like my testing of this was premature, as normally drivers requres the question mark to be encapsulated in `()`.

But you are correct, this is supported and works as in the test.

**Comment by 0x6e6562** [comment]
BTW and FWIW `WHERE ... IN` clauses have been [supported in cqlc](http://www.relops.com/cqlc/predicates/) for a while now.
