### ISSUE TITLE
Allow setting Nagle's algorithm on server connections

### ISSUE THREAD

**Issue by abustany** [gocql/gocql#383]
For workloads with lots of small inserts, we've seen a small performance boost when enabling Nagle's algorithm (net.TcpConn.SetNoDelay) on the Cassandra socket. It's probably not a good idea to have this enabled by default, however we could add an option in the ConnConfig struct for that. If you think it makes sense, I'll send a PR.

**Comment by Zariel** [comment]
Ive been thinking about how we handle connection level things such as heartbeats, dial timeouts and various other things which can be set on a per tcp level socket.

There are a set of options which can be setup by passing a dialler to use, but another is to provide a function to setup a connection before it is used in gocql, such as

```go
func setupConn(conn net.Conn) error {
    // conn is what will be used by the underlying connection, return a error to indicate a failure
    // set heartbeat, nagles, tune window sizes etc
}
```

**Comment by abustany** [comment]
I was initally expecting to be able to do that by writing a "NagleConnectionPool" wrapper, that would just take whatever was picked by the underlying pool implementation and set the options there, but you only get a gocql.Conn, without access to the underlying net.Conn. Also, I assume Pick() can return the same connection many times, so setting the options each time would be silly.

Regarding your proposal, I'd probably lean towards being able to give a Dialer in... But there might be cases which I haven't thought about.

**Comment by matope** [comment]
Hmm, I think Nagle's algorithm for net.TCPConn is enabled in default by Go.
So, IMHO you don't need to wrap it.

> SetNoDelay controls whether the operating system should delay packet transmission in hopes of sending fewer packets (Nagle's algorithm). The default is true (no delay), meaning that data is sent as soon as possible after a Write.
http://golang.org/pkg/net/#TCPConn.SetNoDelay

**Comment by abustany** [comment]
"No delay" means "no Nagle" basically, since Nagle's algorithm is about coalescing small packets together. The issue is about setting Nagle algorithm on, ie. NO_DELAY = off, so that many small inserts get grouped into bigger TCP packets.

**Comment by matope** [comment]
Oh, Sorry, I had a misunderstanding about the effect of the method.
Thank you for your correction:)

**Comment by 0x6e6562** [comment]
I'm sitting on the fence as to whether a dialer is passed in or whether you can make settings during a callback. What are the advantages of passing in a dialer over the callback? In any case, the solution would need to work for TLS as well.
