### ISSUE TITLE
Conn.exec potentially blocks forever

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#388]
I'm looking through the protocol to see why this might happen, but `Conn.exec` can block potentially forever if, for whatever reason, a request to cassandra fails.

I have processes that can get blocked on [conn.exec:368](https://github.com/gocql/gocql/blob/5e2ead955768693323babcbc4daa624b110159d2/conn.go#L368) for as long as 20 hours.

I haven't debugged it fully yet but it seems the `Conn.recv()` never gets any more data on that stream.

**Comment by nemothekid** [comment]
My initial thoughts is doing something like this
```
select {
    case err = <-call.resp:
	if err != nil {
		return nil, err
	}
    case <-time.NewTimer(someTimeout).C:
       return nil, errTimeout
}
```

However I'm still not 100% sure why the stream is being dropped - the downside to something like this is if the stream was slow and the timeout is too aggressive, I think if that stream is reused, the new stream can get old data.

**Comment by Zariel** [comment]
Yeah ive considered doing what you suggest with the timer and think its a pretty good idea, but unsure if it should close the connection.

Do you have heartbeats enabled on the connection? It should keep the connection open, we could also look into adding a heartbeater back in which sends an options frame every X seconds to detect dead connections.

It seems odd that this has been dead for so long, what version of Cassandra is this against?

**Comment by nemothekid** [comment]
This is current stable - `2.0.14` and driver version 5e2ead9557 (25 commits behind)

You could even allocate the Timer when you create the `callReq` to prevent the `NewTimer` allocation at the exec level.

Does the driver support cassandra-specific heartbeats? Or are you talking about KeepAlives? Can't see anything in the code about it. I don't have KeepAlive's enabled, so I will try enabling that, but if the connection closes, the application should be notified of that right?

It seems Cassandra should always respond, and it doesn't look like there are any race conditions that would cause corruption here.

**Comment by Zariel** [comment]
There was a bug that I fixed (CASSANDRA-8848) which meant that Cassandra would send back protocol errors back to the client on stream 0 regardless of what the request stream was. So this could be a protocol frame error, or it could be another error in Cassandra which caused it to return on stream 0.

I guess this is pretty hard (or impossible) to reproduce?

**Comment by nemothekid** [comment]
[CASSANDRA-8848](https://issues.apache.org/jira/browse/CASSANDRA-8848) landed in 2.0.13.

I will try the keep-alive (I'm actually seeing the error regularly) and pray that works, my hunch is however like you said, that there is some protocol error/corruption, on the same level as [CASSANDRA-8848](https://issues.apache.org/jira/browse/CASSANDRA-8848), that is causing the driver to deadlock.

I'll likely know in 24 hours if that helps at all. 

OTOH - with just using timeouts, I think the entire connection should be closed. If its the case that the timeout is too aggressive, and the stream response takes too long, if that stream is recycled the next guy to read the stream will read data intended for someone else. Secondly, I'm seeing this issue tie up the entire application - `ringDescriber.GetHosts` is even blocked on this so keeping the connection open doesn't seem wise.

**Comment by Zariel** [comment]
It's very strange that you are seeing it regularly, is there any other strange things going on TCP wise on the boxes?

To debug if there are errors coming back on frame 0 which shouldn't be you can try making it so the driver wont use stream 0 for requests then have something check in `readFrame` for stream 0 and log out what the frame response is. If it is the case that there is an error in the protocol or such then I would expect there to also be an error in Cassandra's log.

Closing the connection seems like the correct thing to do in this situation.

**Comment by 0x6e6562** [comment]
As a complete aside: Not that it helps solve this issue per se, but this reminds me some of a discussion I had with one of the Cassandra developers about how the protocol could be revised to do TX/RX over different TCP connections and the flow control benefits that might have.

**Comment by Zariel** [comment]
I wonder if not using stream 0 and only check it for frame errors

**Comment by Zariel** [comment]
Sorry didnt mean to do that

**Comment by nemothekid** [comment]
I do see it regularly, but it is very difficult to reproduce. I feel its related to some batch queries I run that read potentially a lot of data.

Now that I'm thinking about it - I'm also looking into how paging is handled.

**Comment by nemothekid** [comment]
So I have a node that is currently deadlocked and poking around I think I'll check for errors coming back on frame 0.

* KeepAlive didn't work
* The faulty session has 80 active connections to Cassandra, and strangely they have all been blocked for ~400m. (This is really weird because 1 session does heavy usage which is blocked, the other doesn't hardly does any, is also blocked for ~400m, (this other session a new session with the exact same settings as the heavy session) and then there are 2 other sessions which see almost 0 usage, but their connections have sub-10m IO wait times. - so not only is my app blocked, but so is `ringDescriber`)[1]

I'm now assuming that an invalid frame is sent on an invalid stream, like @Zariel suggested, as I'm not sure what else could be going on. 

[1]
```
goroutine 172 [IO wait, 412 minutes]:
net.(*pollDesc).Wait(0xc2081053a0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081053a0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208105340, 0xc20830e000, 0x1000, 0x1000, 0x0, 0x7ff44b101f70, 0xc208370040)
	/usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c470, 0xc20830e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20830d920)
	/usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20830d920, 0xc208308f28, 0x8, 0x8, 0xc20832c8a0, 0x0, 0x0)
	/usr/src/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7ff44b102650, 0xc20830d920, 0xc208308f28, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/src/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff44b102650, 0xc20830d920, 0xc208308f28, 0x8, 0x8, 0xc8d0a0, 0x0, 0x0)
	/usr/src/go/src/io/io.go:316 +0x6d
github.com/channelmeter/gocql.readHeader(0x7ff44b102650, 0xc20830d920, 0xc208308f28, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/channelmeter/gocql/frame.go:302 +0x80
github.com/channelmeter/gocql.(*Conn).recv(0xc2080972b0, 0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/conn.go:318 +0x10d
github.com/channelmeter/gocql.(*Conn).serve(0xc2080972b0)
	/go/src/github.com/channelmeter/gocql/conn.go:284 +0x40
created by github.com/channelmeter/gocql.Connect
	/go/src/github.com/channelmeter/gocql/conn.go:166 +0x68e
```

**Comment by nemothekid** [comment]
Actually looks like you were right @Zariel - I have a method that almost reliably reproduces this (involves running a shitton of tasks though :/) but nonetheless -
```
2015/05/08 01:11:49 GOCQL : GOT A MESSAGE ON STREAM 0
2015/05/08 01:11:49 GOCQL : Header: [header version=[version=2 direction=RESP] flags=0x0 stream=0 op=ERROR length=50]
```

**Comment by Zariel** [comment]
Run parse frame on that to get the error, nothing in the Cassandra logs?

Or could you post the bytes ("%#+v") of that frame after it is read? Do you know what outgoing frame is being used? BATCH?

**Comment by nemothekid** [comment]
Took a couple tries : 
```
2015/05/08 01:31:01 GOCQL : GOT A MESSAGE ON STREAM 0
2015/05/08 01:31:01 GOCQL : Header: [header version=[version=2 direction=RESP] flags=0x0 stream=0 op=ERROR length=48]
2015/05/08 01:31:01 Error Code: %!(EXTRA int=10)
2015/05/08 01:31:01 Error Msg: %!(EXTRA string=Invalid or unsupported protocol version: 5)
```

Protocol Version 5? That can't be possible - but explains why its on stream 0. Secondly this process I am running does a huge number concurrent of read/writes so if I had to guess maybe we are getting a racy access somewhere that is corrupting the data?

**Comment by Zariel** [comment]
ack, that looks nasty. Is it possible to run with the race detector?

**Comment by nemothekid** [comment]
Race detector isn't helping.
```
2015/05/08 02:06:31 GOCQL : GOT A MESSAGE ON STREAM 0
2015/05/08 02:06:31 GOCQL : Header: [header version=[version=2 direction=RESP] flags=0x0 stream=0 op=ERROR length=84]
2015/05/08 02:06:31 Error Code: %!(EXTRA int=10)
2015/05/08 02:06:31 Error Msg: %!(EXTRA string=Wrong protocol direction (expected RESPONSE, got REQUEST) for opcode 0 (ERROR))
```

I noticed calls to `*Conn.Write([]byte) (int, error)` aren't synchronized. 

```go
func (c *Conn) Write(p []byte) (int, error) {
	if c.timeout > 0 {
		c.conn.SetWriteDeadline(time.Now().Add(c.timeout))
	}	
	return c.conn.Write(p)
}
```

And essentially any framer can call

```go
func (f *framer) finishWrite() error {
	if f.wbuf[1]&flagCompress == flagCompress {
		if f.compres == nil {
			panic("compress flag set with no compressor")
		}

		// TODO: only compress frames which are big enough
		compressed, err := f.compres.Encode(f.wbuf[f.headSize:])
		if err != nil {
			return err
		}

		f.wbuf = append(f.wbuf[:f.headSize], compressed...)
	}
	length := len(f.wbuf) - f.headSize
	f.setLength(length)

	_, err := f.w.Write(f.wbuf)
	if err != nil {
		return err
	}

	return nil
}
```

(`f.w` here is the `*Conn` object)

**Comment by Zariel** [comment]
As far as I am aware the underlying conn writes are synchronised at the TCP level.

If there was data corruption going on the only place I think it can happen is when appending to the buffer in frame, but as the race detector didn't find anything (ive been unable to reproduce it my side, just kills Cassandra) im leaning towards it not being driver corruption, to be sure about that we would need to look at pcaps or something to ensure that we are writing valid frames going out from gocql.

It defiantly looks like the header is becoming corrupt and its consistently messing up the version, with that being the first field in the header it makes sense as to why that is always coming back as the corrupt part of the frame.

An idea would be to add a check in the `finishWrite` method to ensure that byte 0 of the `wbuf` is always `0x02` before the call to `f.w.Write`, if it is not then there is a problem.

**Comment by nemothekid** [comment]
After a ton of debugging, I'm going to chalk this one to cloudly network conditions. If I ever come up with something reproducible I'll reopen this issue.

**Comment by 0x6e6562** [comment]
Well done for putting all the effort in to try to track this done - if this issue re-appears, then this history will serve us well. I guess that in that case some (potentially high effort) debugging steps would be to either port the critical code section to the DataStax java driver for comparison or to capture pcaps in order to replay the client driver's wire behavior.
