### ISSUE TITLE
Failed to unmarshall UserType

### ISSUE THREAD

**Issue by nguyener** [gocql/gocql#390]
I created a table which has one of the columns is User Defined Type (actually a map of User Defined Type).  Let says my table name is 'templates' and the UDT is 'File' which has two attributes: file_name and file_content (both as text).  The UDT column is defined as map[string]File
I have no problem retrieving data from this table using cqlsh.  However, when wrote some code with gocql, I got the following error:
"can not unmashal custom (org.apache.cassandra.db.marshal.UserType(.....) in to *templates.File

**Comment by Zariel** [comment]
Could you post a snippet of code which is doing the query?

**Comment by nguyener** [comment]
type File struct {
    File_name string `json: "file_name"`
    File_content string `json: "file_content"`
}


 var files = make(map[string]File)
    
get_template_str := "SELECT files FROM templates limit 1"
if err:=Conn.Query(get_template_str).Scan(&files); err != nil{
        log.Fatal(err)
}

Here is what my data look likes

cqlsh:demo> select template_name, template_hash, commit_hash, files from templates;

 template_name | template_hash                            | commit_hash                              | files
---------------+------------------------------------------+------------------------------------------+--------------------------------------------------------
    template_1 | 61d09ee12cdfe9b85003ea37dbc8c090fdb5c6f5 | 61d09ee12cdfe9b85003ea37dbc8c090fdb5c6f5 | {'file_1': {file_name: 'file_1', file_content: 'abc'}}
    template_1 | 62e0b4c4f14fea76d120c5827becdedb2a45af03 | 62e0b4c4f14fea76d120c5827becdedb2a45af03 | {'file_2': {file_name: 'file_2', file_content: 'edf'}}
    template_1 | 34e7688cda9d475056e2f206fb446317cb91167d | 34e7688cda9d475056e2f206fb446317cb91167d | {'file_3': {file_name: 'file_3', file_content: 'xyz'}}

**Comment by nguyener** [comment]
cqlsh:demo> select files from templates;

 files
--------------------------------------------------------
 {'file_1': {file_name: 'file_1', file_content: 'abc'}}
 {'file_2': {file_name: 'file_2', file_content: 'edf'}}
 {'file_3': {file_name: 'file_3', file_content: 'xyz'}}

**Comment by Zariel** [comment]
Thanks. This is because currently the UDT unmarshalling wont try to fuzzy match the field names like the json decoder does (ill look at adding that). You can get around this by adding `cql` tags to map the column names.

**Comment by nguyener** [comment]
I changed the File struct with cql tag but still get the same error
type File struct {
    File_name string `cql: "file_name"`
    File_content string `cql: "file_content"`
}
2015/05/11 14:49:28 can not unmarshal custom(org.apache.cassandra.db.marshal.UserType(demo,66696c65,66696c655f6e616d65:org.apache.cassandra.db.marshal.UTF8Type,66696c655f636f6e74656e74:org.apache.cassandra.db.marshal.UTF8Type)) into *templates.File

**Comment by Zariel** [comment]
What version of cassandra is this against? Im not sure but the `TypeInfo` looks a big strange

**Comment by nguyener** [comment]
nguyener@ubuntu-vm2:~$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.5 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.

**Comment by nemothekid** [comment]
Does the driver currently throw an error when you try to use UDT's with the v3 protocol? The `custom` identifier makes me believe its reporting type `0x00` (custom) instead of type `0x0030` (which should throw an error like `can not unmarshal unknown_type_30 into *templates.File` if it really couldn't unmarshal).

@nguyener 
Are you setting the protocol version to `3`? Currently by default the driver uses protocol version `2`, which is supported by Cassandra 2.0.x.

Ex:
```go
cluster := gocql.NewCluster("cass1", "cass2")
cluster.ProtoVersion = 3
```

**Comment by nguyener** [comment]
@nemothekid 
I added "cluster.ProtoVersion = 3 " and got different error:
2015/05/11 22:55:13 cannot unmarshal demo.file{file_name=varchar,file_content=varchar} into *templates.File

**Comment by nemothekid** [comment]
Did you post your full code earlier?

```go
var files File

get_template_str := "SELECT files FROM templates limit 1"
if err:=Conn.Query(get_template_str).Scan(&files); err != nil{
log.Fatal(err)
}
```

I think the issue is you are trying to scan into a Map.

**Comment by nguyener** [comment]
Yes, I tried to scan a Map.
My table templates has a column that stores a collection of file (File{file_name, file_content}).  My original design was using Set instead of Map.  However since Go does not suport Set, so I switched to Map.
Could you please help me to avoid the "scan in to a Map" issue? I guess since my data is a map, I have to scan it into a Map.
cqlsh:demo> select files from templates;
files

{'file_1': {file_name: 'file_1', file_content: 'abc'}}
{'file_2': {file_name: 'file_2', file_content: 'edf'}}
{'file_3': {file_name: 'file_3', file_content: 'xyz'}}

**Comment by nemothekid** [comment]
What type is `files` in the cassandra database? Is it `map<string, File>`?

**Comment by nguyener** [comment]
CREATE TYPE demo.file (
    file_name text,
    file_content text
);


CREATE TABLE demo.templates (
    template_hash text PRIMARY KEY,
    commit_hash text,
    files map<text, frozen<file>>,
    release_role text,
    template_name text
)

**Comment by nguyener** [comment]
Sorry the previous paste was cut off.

CREATE TABLE demo.templates (
    template_hash text PRIMARY KEY,
    commit_hash text,
    files map<text, frozen<file>>,
    release_role text,
    template_name text
)

**Comment by nguyener** [comment]
the files column was cut off by the editor again.
yes, it is a map from string to "frozen" file

**Comment by nemothekid** [comment]
Actually, it looks like this is a driver issue - I don't think you make this work for now. 

If you have a table in Cassandra like so:
```
  CREATE TYPE address (
      street text,
      city text,
      zip int
  );
  
  CREATE TABLE user_profiles (
      login text PRIMARY KEY,
      first_name text,
      last_name text,
      email text,
      addresses map<text, address>
  );
```

And then you try to do this:
```
type Address struct {
  Street string `cql:street`
}
addresses := make(map[string]Address)
if err := sessions.Query("SELECT addresses FROM user_profiles").Scan(&addresses); err != nil{
    log.Fatal(err)
}
```

It should fail with `can not unmarsahl`.

The issue is here - [marshal.go#L1381](https://github.com/gocql/gocql/blob/master/marshal.go#L1381)
```go
if !f.IsValid() || !f.CanAddr() {
	return unmarshalErrorf("cannot unmarshal %s into %T", info, value)
}
```

`f.CanAddr()` returns `false` because you can't take the address of an element in a map. I think the right solution here is to use `SetMapIndex()` (like the json decoder)?

**Comment by nemothekid** [comment]
Actually, after going through the code a bit more, I'm wrong --

@nguyener 
```go
type File struct {
File_name string json: "file_name"
File_content string json: "file_content"
}

var files = make(map[string]*File) // use pointer

get_template_str := "SELECT files FROM templates limit 1"
if err:=Conn.Query(get_template_str).Scan(&files); err != nil{
log.Fatal(err)
}
```

should work.

**Comment by nemothekid** [comment]
Gah 😂😂😂

Turns out I was missing the quotation marks on the struct tags.

@nguyener The following code works for me:
```go
package main

import (
	"fmt"
	"log"

	"github.com/gocql/gocql"
)

func main() {
	// connect to the cluster
	cluster := gocql.NewCluster("cass1")
	cluster.Keyspace = "gocql_test"
	cluster.Consistency = gocql.Quorum
	cluster.ProtoVersion = 3
	session, _ := cluster.CreateSession()
	defer session.Close()

	type Address struct {
		Street string `cql:"street"`
		City   string `cql:"city"`
		Zip    int    `cql:"zip"`
	}
	addresses := make(map[string]Address)
	if err := session.Query("SELECT addresses FROM user_profiles").Scan(&addresses); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%v", addresses)
}
```

With the CQL:
```
  CREATE TYPE address (
      street text,
      city text,
      zip int
  );

 
  CREATE TABLE user_profiles (
      login text PRIMARY KEY,
      first_name text,
      last_name text,
      email text,
      addresses map<text, frozen<address>>
  );
```

**Comment by Zariel** [comment]
Good spot with the v2 protocol @nemothekid I'm pretty surprised that Cassandra would even return UDT columns in protocol 2 mode.

**Comment by Zariel** [comment]
I was able to reproduce this by changing the test to run in protocol 2 mode for the UDT tests,

`=== RUN TestUDT_Reflect-4
--- FAIL: TestUDT_Reflect-4 (1.32s)
	cassandra_test.go:105: Created keyspace gocql_test
	udt_test.go:123: can not marshal gocql.horse into custom(org.apache.cassandra.db.marshal.UserType(gocql_test,686f727365,6e616d65:org.apache.cassandra.db.marshal.UTF8Type,6f776e6572:org.apache.cassandra.db.marshal.UTF8Type))`

**Comment by nguyener** [comment]
Hi guys,
Thanks very much for your help.  I have tried all suggestion and still ran in to the same error 
2015/05/12 07:30:22 cannot unmarshal demo.file{file_name=varchar,file_content=varchar} into *main.File
Here is my code:
package main

import (
    "fmt"
    "log"
    "github.com/gocql/gocql"
)

type File struct {
    File_name string `cql: "file_name"`
    File_content string `cql: "file_content"`
}

func main() {
    cluster := gocql.NewCluster("127.0.0.1")
    cluster.Keyspace = "demo"
    cluster.ProtoVersion = 3
    cluster.Consistency = gocql.Quorum
    session,_ := cluster.CreateSession()


    get_template_str := "SELECT files FROM templates limit 1"
    files := make(map[string]*File)

    if err:=session.Query(get_template_str).Scan(&files); err != nil{
        log.Fatal(err)
    }
    fmt.Println(files)

}

**Comment by Zariel** [comment]
Instead try this,

```go
package main

import (
    "fmt"
    "log"
    "github.com/gocql/gocql"
)

type File struct {
    File_name string `cql:"file_name"`
    File_content string `cql:"file_content"`
}

func main() {
    cluster := gocql.NewCluster("127.0.0.1")
    cluster.Keyspace = "demo"
    cluster.ProtoVersion = 3
    cluster.Consistency = gocql.Quorum
    session,_ := cluster.CreateSession()


    get_template_str := "SELECT files FROM templates limit 1"
    file := &File{}

    if err:=session.Query(get_template_str).Scan(file); err != nil{
        log.Fatal(err)
    }
    fmt.Println(file)
}
```

If you want to scan into a map try using `query.ScanMap` but I think that is for scanning a single row into a map.

**Comment by nemothekid** [comment]
@nguyener
Make sure there is no space between `cql:` and `"file_name"` in your strict definition.

**Comment by nguyener** [comment]
Thanks guys, I have it working  now.  The problem was that I have spaces after 'cql:.

**Comment by Zariel** [comment]
@nguyener no problem!

@nemothekid thanks for the assistance tracking this down!

**Comment by 0x6e6562** [comment]
Nice work @nemothekid :-)

**Comment by jstoup** [comment]
@nemothekid & @Zariel 

I know I'm late to the party here but I have a question. I've closely looked over the solution to this problem and attempted to implement it in my own code but I still get the following error:

`cannot marshal kleserver.FullName into kle_newdatamodel.fullname{first=varchar,last=varchar,middle=varchar,suffix=varchar,prefix=varchar}`

When I log in with cqlsh this is the version: 
`[cqlsh 5.0.1 | Cassandra 2.1.3 | CQL spec 3.2.0 | Native protocol v3]`

I've already implemented several hundred lines of go code writing to Cassandra and everything works just fine except for this. Trying to write to a UDT is the only thing causing me issues. Here is a snippet of my code, could you please tell me what I'm doing wrong?

```
...
cluster.ProtoVersion = 3
...

type FullName struct {
	FirstName  string `cql:"firstname"`
	LastName   string `cql:"lastmiddle"`
	MiddleName string `cql:"middlename"`
	Suffix     string `cql:"suffix"`
	Prefix     string `cql:"prefix"`
}

myName := &FullName{
	FirstName:  "james",
	LastName:   "stoup",
	MiddleName: "r",
	Suffix:     "I",
	Prefix:     "Mr.",
}

myerr := session.Query("INSERT INTO test_udt(id, name) VALUES (?,?)", 2, myName).Exec()

if myerr != nil {
	log.Printf("Error adding my name")
	log.Printf(myerr.Error())
	return http.StatusBadRequest, nil
} else {
	log.Printf("It worked!")
	return http.StatusOK, nil
}

```

**Comment by Zariel** [comment]
@jstoup it looks like your schema doesnt match the UDT, check that the UDT fields match the `cql` struct tag. It looks like it should be,

```go
type FullName struct {
    FirstName  string `cql:"first"`
    LastName   string `cql:"last"`
    MiddleName string `cql:"middle"`
    Suffix     string `cql:"suffix"`
    Prefix     string `cql:"prefix"`
}
```

**Comment by jstoup** [comment]
Damn, you are correct. Thanks.

**Comment by ddave09** [comment]
I am using protocol version 4. I had the same error just now where I was trying to insert a row with a UDT column


cql type:
CREATE TYPE x_y (
    a double,
    o double
);

go type:
type XY struct{
  A float64 
  O float64
}

cql column name: a_b type x_y
go column name: AB type XY

insertion to row with column AB failed silently and succeeded after I changed type XY to:
type XY struct{
  A float64 `cql:"a"`
  O float64 `cql:"o"`
}

Is the cql tag requirement going to persist? It would be helpful if go to cql mapping it is not case sensitive as first letter of member name behaves as an access modifier.
