### ISSUE TITLE
import error from code.google.com

### ISSUE THREAD

**Issue by gingerhot** [gocql/gocql#402]
I run into a error when running `go get github.com/gocql/gocql` in a Ubuntu 14.04 node, while in my Mac all is fine.

```
package github.com/gocql/gocql
        imports code.google.com/p/snappy-go/snappy: unable to detect version control system for code.google.com/ path
```

How can I fix this? 
Thanks!

**Comment by 0x6e6562** [comment]
I'm just going to re-trigger the Travis build to see if it experiences the same issue with `go get`.

**Comment by 0x6e6562** [comment]
Yes, as suspected, Travis can also no longer reference the snappy dependency, so we have an issue - from memory there was something about google code being EOL'ed in some fashion, but I might be wrong.

**Comment by gingerhot** [comment]
Thanks a lot!
