### ISSUE TITLE
unconfigured column family failure in travis

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#422]
I've seen this one itermitantly in the past, not sure what is causing it.

```
--- FAIL: TestTooManyQueryArgs-2 (1.45s)
	cassandra_test.go:520: '`SELECT * FROM too_many_query_args WHERE id = ?`, 1, 2' should return an ErrQueryArgLength, but returned: unconfigured columnfamily too_many_query_args
```

Full log is available at https://gist.github.com/Zariel/ab6ed48081e7e3ff9c80

**Comment by abustany** [comment]
If that "helps", we see that in our tests as well, seems that sometimes Cassandra takes some time before properly creating the column family.

**Comment by Zariel** [comment]
Yeah, in 2.2 it seems to completely break the test suite which is quite worrying, need to spend time to figure out why and fix it.

**Comment by abustany** [comment]
2.2 uses the world "table" in error messages, but there might be other reasons as well.

**Comment by Zariel** [comment]
I did a bit of testing and it seems that table changes are immediate for the same connection which makes the change, which I couldn't really confirm via Cassandra or the change logs.
