### ISSUE TITLE
data race closing connections

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#424]
As first reported by @xoraes there is a data race when closing connections leading to a send on a closed channel panic.

```
==================
WARNING: DATA RACE
Read by goroutine 300:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:83 +0x0
  github.com/gocql/gocql.(*Conn).closeWithError()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:326 +0x23f
  github.com/gocql/gocql.func·034()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:548 +0x146

Previous write by goroutine 270:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:257 +0x0
  github.com/gocql/gocql.(*Conn).closeWithError()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn.go:330 +0x268
  github.com/gocql/gocql.func·034()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:548 +0x146

Goroutine 300 (running) created at:
  github.com/gocql/gocql.TestCloseConnWithError()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:549 +0x631
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 270 (running) created at:
  github.com/gocql/gocql.TestCloseConnWithError()
      /Users/chris/dev/go/src/github.com/gocql/gocql/conn_test.go:549 +0x631
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133
==================
```

**Comment by xoraes** [comment]
@Zariel  sorry for the delay, but here is the stack trace of the panic I am still seeing with the new build. 

https://github.com/gocql/gocql/blob/c3e714b4b2601c134235e20707578dabad3efcd2/conn.go#L393

This is the stack trace I am seeing:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5eac21]
goroutine 1393738 [running]:
github.com/gocql/gocql.(*Conn).exec(0xc20813cb40, 0x7f4eeaf03110, 0xc2083803c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gocql/gocql/conn.go:393 +0x391
github.com/gocql/gocql.(*Conn).executeQuery(0xc20813cb40, 0xc2083fc9c0, 0x9c76e0)
        /go/src/github.com/gocql/gocql/conn.go:529 +0x5f4
github.com/gocql/gocql.(*Session).executeQuery(0xc208038820, 0xc2083fc9c0, 0x7f4650)
        /go/src/github.com/gocql/gocql/session.go:222 +0x1da
github.com/gocql/gocql.(*Query).Iter(0xc2083fc9c0, 0xc2083fc9c0)
        /go/src/github.com/gocql/gocql/session.go:613 +0x107
github.com/gocql/gocql.(*Query).Exec(0xc2083fc9c0, 0x0, 0x0)
        /go/src/github.com/gocql/gocql/session.go:603 +0x3a
