### ISSUE TITLE
Unmarshaling embedded list type fails

### ISSUE THREAD

**Issue by exu** [gocql/gocql#433]
Hi, 

I'm trying to run following code with gocql

    /* Before you execute the program, Launch `cqlsh` and execute:
    
    CREATE KEYSPACE test1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
    USE test1;
    CREATE TYPE answer_task( euid bigint, result int);
    CREATE TABLE attempt( id timeuuid, user_assignment_id int, answers list <frozen<answer_task>>, primary KEY (user_assignment_id, id) );
    INSERT INTO attempt (user_assignment_id, id, answers) VALUES (1, now(), [{euid:12,result:1}]);
    INSERT INTO attempt (user_assignment_id, id, answers) VALUES (2, now(), [{euid:1332,result:2}]);
    
    */
    package main
    
    import (
    	"fmt"
    	"github.com/gocql/gocql"
    	"log"
    )
    
    type Answer struct {
    	Euid      int `cql:"euid"`
    	Questions int `cql:"questions"`
    	Error     int `cql:"error"`
    	Result    int `cql:"result"`
    	MaxResult int `cql:"max_result"`
    }
    
    type Attempt struct {
    	Id               gocql.UUID    `cql:"id"`
    	UserAssignmentId string        `cql:"user_assignment_id"`
    	Answers          []interface{} `cql:"answers"`
    }
    
    func main() {
    
    	// connect to the cluster
    	cluster := gocql.NewCluster("localhost")
    	cluster.Keyspace = "test1"
    	cluster.Consistency = gocql.Quorum
    	session, _ := cluster.CreateSession()
    	defer session.Close()
    
    	var id gocql.UUID
    	var uaid int
    	var answer Answer
    
    	if err := session.Query(`SELECT id, user_assignment_id, answers FROM attempt`).
    		Consistency(gocql.One).
    		Scan(&id, &uaid, &answer); err != nil {
    		log.Fatal(err)
    	}
    
    	fmt.Println("a:", id, uaid, answer)
    }

when I 

    go run app.go 

I get: 

    2015/06/26 09:45:07 can not unmarshal list(custom(org.apache.cassandra.db.marshal.UserType(test1,616e737765725f7461736b,65756964:org.apache.cassandra.db.marshal.LongType,726573756c74:org.apache.cassandra.db.marshal.Int32Type))) into *main.Answer
    exit status 1

Any idea what I'm doing wrong? Or maybe some workaroung to unmarshal to embedded structs. I saw similar approach in wiki_test.go but there hashmaps are used.

**Comment by Zariel** [comment]
It looks like you are unmarshalling a list of UDT's into a single UDT, try this instead

```go
    	var id gocql.UUID
    	var uaid int
    	var answers []Answer
    
    	if err := session.Query(`SELECT id, user_assignment_id, answers FROM attempt`).
    		Consistency(gocql.One).
    		Scan(&id, &uaid, &answers); err != nil {
    		log.Fatal(err)
    	}
```

**Comment by exu** [comment]
It's working great! thanks for help, 
I've needed to add 

	cluster.ProtoVersion = 3

because of UDT error message.
