### ISSUE TITLE
Panic while executing batches (non deterministic)

### ISSUE THREAD

**Issue by liviosoares** [gocql/gocql#435]
Hi,

I started getting the following panic while executing a batch of INSERT queries. It occurs about 1/2 or 2/3 of the times we perform the batch, but is not completely deterministic.

Here's part of the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8b1973]
goroutine 23538 [running]:
github.com/gocql/gocql.(*Conn).exec(0xc208114000, 0x7f5320043580, 0xc212c171d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        go/src/github.com/gocql/gocql/conn.go:430 +0x603
github.com/gocql/gocql.(*Conn).executeBatch(0xc208114000, 0xc22263d630, 0x0, 0x0)
        go/src/github.com/gocql/gocql/conn.go:745 +0x317
github.com/gocql/gocql.(*Session).ExecuteBatch(0xc20813e000, 0xc22263d630, 0x0, 0x0)
        go/src/github.com/gocql/gocql/session.go:402 +0x1a3
```

I added a few print statements, and saw that `frame.header` is `nil` when the panic happens.
I don't know if it helps, but if I change cluster.ProtoVersion to 3, the panic goes away.

Let me know if you need further information. I would also like to know if there are contra-indications for running with ProtoVersion 3 in production.

Cassandra version information:

```
cqlsh -u xxx -p xxx
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.7 | CQL spec 3.2.0 | Native protocol v3]
```

**Comment by Zariel** [comment]
There shouldnt be any difference between using v2 and v3, v3 has more support for options when using batches. Its very odd that the panic doesnt happen with v2, are there any errors on the cassandra servers in the logs?

@nemothekid have you seen anything like this with batches?

**Comment by liviosoares** [comment]
Just to clarify, you said:

`Its very odd that the panic doesnt happen with v2`.

The panic *only* happens with v2.  I also checked the Cassandra logs, and do not see any errors when executing these batches.

**Comment by Zariel** [comment]
Sorry that was a mistake on my part.

**Comment by nemothekid** [comment]
The panics I saw weren't quite like this - what was happening is I was sending rather large batches (I didn't think they broke the frame size but it caused Cassandra to puke). When this happened Cassandra would send an error on stream 0 - which *might* have caused a panic or might have caused everything to hang.

You can try reducing the size of your batches to see if that fixes this issue however in my case changing from protocol 2 to 3 didn't fix the issue (although if you are the same problem I had, I'd check to see your program isn't dead locking)

You can always check your Cassandra logs to as that can tell you something as well. In my case I was caused an indexoutofbounds exception in Cassandra. [CASSANDRA-9341](https://issues.apache.org/jira/browse/CASSANDRA-9341)

**Comment by Zariel** [comment]
@liviosoares if this is reproducible using protocol v2 can you try running #440 which I think might fix this issue.

**Comment by Zariel** [comment]
Im going to close this, if it is still an issue please reopen.
