### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by clutchski** [gocql/gocql#444]
I'm getting this panic when using gocql:

```
goroutine 974 [running]:
github.com/gocql/gocql.(*Conn).recv(0xc223744410, 0x0, 0x0)
        /home/vagrant/code/datadog/go/src/github.com/gocql/gocql/conn.go:363 +0x39e
github.com/gocql/gocql.(*Conn).serve(0xc223744410)
        /home/vagrant/code/datadog/go/src/github.com/gocql/gocql/conn.go:339 +0x3a
created by github.com/gocql/gocql.Connect
        /home/vagrant/code/datadog/go/src/github.com/gocql/gocql/conn.go:187 +0x727
```

Our code is using the same gocql.Session to perform concurrent reads + writes, but according to the doc this should be fine, so I think we're using the code in the correct way. I'll see if I can dig in and provide more details.

Thanks very much.

**Comment by Zariel** [comment]
Now that #445 checks that the stream isnt above the limit, do you still see this? How often does it happen?

**Comment by clutchski** [comment]
will rebuild and try.

**Comment by clutchski** [comment]
Seems ok. I can let you know if it happens again.

**Comment by Zariel** [comment]
Thanks, if you see the error `gocql: frame header stream is beyond call exepected bounds` could you report it here as well? It should never happen and could indicate corruption somewhere.

Ill close this for now, if it happens again please reopen.
