### ISSUE TITLE
session: Reduce default number of streams w/ Protocol version 3

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#446]
Protocol version 3 bumps up the number of default streams from 128 and 32768, nearly eradicating the need to have have multiple connections.

Currently gocql defaults to opening the maximum number of streams (if you don't set `cluster.NumStreams`) which can really blow up the amount of memory used, and we may want to look at this tradeoff.

Currently with default settings, a bare application (creates a session and nothing else) uses around ~220MiB of resident RAM with 32768, but only 4.5MiB with 256 streams (2x the default with protocol 1, 2 connections, everything else default). Maybe others can test this, but this means to me you can't really throw a gocql app on a $5/DO box without causing some swapping.

**Comment by Zariel** [comment]
This was something I had in the back of my mind, I dont really like allocating all of the stream call handlers up front, but to do it without would require some potential locking which im not too keen to introduce into the conn layer if possible.

Maybe it might be worth adding something to the docs to mention that this can be reduced if its not needed? I wonder how many applications will really use all the v3 streams concurrently on a single conn.

**Comment by tux21b** [comment]
Since the protocol is TCP based and one slow stream or lost package will block everything else, it isn't advisable to use that many streams with one connection either.

**Comment by Zariel** [comment]
Looking at the object sizes, Conn is `200` bytes and callReq is `24`, so for v3 using all 32768 streams that gives us `786432` bytes which is `786.4KB`. I think its best to run with the max but on a case by case basis the user should change it to match their use cases. I think using all v3 streams is unlikely anyway in 99% of apps.

**Comment by thomersch** [comment]
We had a highly increased memory usage by simply switching the protocol version to 3. It jumped to 50x of the normal amount and garbage collector run times skyrocketed, which can have a critical impact on infrastructure, while it had no improvement in terms of query execution time.
I would suggest to reduce the number of streams to a more sane amount or to have some explicit note in the documentation what can happen if the user switched to proto version 3.

**Comment by Zariel** [comment]
@nemothekid I closed this due to reducing the memory per connection used by streams, if this is still an issue can you reopen please?
