### ISSUE TITLE
MapScan expecting newly initialized map[string]interface{}?

### ISSUE THREAD

**Issue by shanab** [gocql/gocql#449]
Hi,

I was working with `MapScan`, when I bumped into an unusual error. This is the code I was working on:
```go
cql := `SELECT * FROM user LIMIT 10`
res := make(map[string]interface{})
iter := session.Query(cql).Iter()
for iter.MapScan(res) {
	fmt.Println(res)
}

if err := iter.Close(); err != nil {
	panic(fmt.Sprintf("Could not close iterator query=%v: %v", cql, err.Error()))
}
```

For some reason, it worked for the first iteration, and then broke in the next one:
```
map[userid:c7303f7d-201e-4408-a85f-acb9fe1966a2 username:foobar]
panic: Could not close iterator query=SELECT * FROM user LIMIT 10: can not unmarshal X uuid into gocql.UUID
```

I tried a couple of other solutions, and this is the one that worked out:
```go
cql := `SELECT * FROM user LIMIT 10`
res := make(map[string]interface{})
iter := session.Query(cql).Iter()
for iter.MapScan(res) {
	fmt.Println(res)
	res = make(map[string]interface{})    // Reinitialize res
}

if err := iter.Close(); err != nil {
	panic(fmt.Sprintf("Could not close iterator query=%v: %v", cql, err.Error()))
}
```

By reinitializing the res variable, it worked. I'm not sure though why it won't work on an already initialized `map[string]interface{}`. Is this normal?

**Comment by Zariel** [comment]
I guess this is unexpected behaviour, will take a look

**Comment by 0x6e6562** [comment]
@shanab Would it be possible to supply us with the schema and data required to reproduce this issue?

**Comment by shanab** [comment]
@0x6e6562 yeah sure. This is the schema I was using:
```cql
CREATE TABLE user (
       userId uuid,
       username string,
       PRIMARY KEY(userId)
);
```

And for the data, I just dumped in dummy usernames and random UUIDs.

**Comment by 0x6e6562** [comment]
Thanks for your input, I've just had a look at this and I think this is probably a bug and a feature :-(

I think the underlying issue here is the potentially confusing way that the `SliceMap()/MapScan` API is designed.

So whilst your code compiles and seems intuitive enough, in reality the `MapScan()` model was only really conceived to work on a row by row basis. The intended use case is for applications to use `SliceMap()` which will return a completely populated map.

In your app, would it be practicable to do

```
res, err := session.Query(cql).Iter().SliceMap()
```

instead?

**Comment by shanab** [comment]
I was inclined to using `SliceMap` at first, but I thought it wouldn't work very well in my case.

In my case, I'm reading through millions of records, so I needed to iterate over a specific page size, save them in a file, then do the same until the dataset is finished. That's why `Iter().MapScan(...)` was better for me to use, since it will take into consideration the page size and loop accordingly.

If I understand correctly, if I use `Iter().SliceMap()`, then what I will get is a really big `[]map[string]interface{}` loaded into memory. With millions of records to read, that won't be very useful unfortunately.

**Comment by 0x6e6562** [comment]
Yes, your understanding is correct: `SliceMap()` should not be used for large data sets because it eagerly unmarshals the query result into memory. In this sense `SliceMap()` is only a convenience function that should only be used in a non-streaming fashion.

**Comment by Zariel** [comment]
Is there a reason to not use `iter.Scan`?

**Comment by shanab** [comment]
Yes there is. I was trying to develop a generic data exporter/importer that would have access to a certain host, execute a read query on it, create another schema and insert the same data into it.

**Comment by shanab** [comment]
It's working so far with this:
```go
es = make(map[string]interface{})    // Reinitialize res
```

I'm new to Go so I'm not very sure whether this will have a significant impact on the performance, but so far it's working well for small sets of data.

**Comment by 0x6e6562** [comment]
Have you seen the metadata API in gocql BTW?

**Comment by shanab** [comment]
I have, but I didn't use it yet.

**Comment by bsferrazza** [comment]
I'm having a similar issue, but receive a "can not unmarshal into non-pointer int" error. When I query a simple CF using MapScan and iterate on it, it errors out after the first iteration. The schema is about as simple as it can be.

CREATE TABLE counts (
    cnt int PRIMARY KEY,
    val int
);

```go
	row := make(map[string]interface{})

	iter := session.Query("SELECT * FROM counts").Iter()
	for iter.MapScan(row) {
		fmt.Println(row)
	}
	if err := iter.Close(); err != nil {
		log.Fatal(err)
	}

similar to the workaround from #449, if I re-initialize the map[string]interface{} each iteration, it does not throw an error.

**Comment by Zariel** [comment]
Looking it to how this is implemented the intended use case looks to be something like this.

```go
var (
	a string
	b int
)

m := map[string]interface{}{
	"a": &a,
	"b", &b,
}

for iter.Scan(m) {
	// use a and b
}
```

Which im not sure makes sense as an API use case, and it is certainly not obvious.
