### ISSUE TITLE
Batch does not correctly handle LWT response

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#453]
Currently we expect BATCH frames to only respond with RESULT VOID frames, but when a query has a LWT then it will respond with RESULT ROWS like a normal CAS will. Reported on the mailing list.

```go
CREATE KEYSPACE foo WITH replication = {
  'class': 'SimpleStrategy',
  'replication_factor': '1'
};

USE foo;

CREATE TABLE bar (
  pcol int,
  ccol int,
  col1 int,
  scol int static,
  PRIMARY KEY ((pcol), ccol)
);

the following code,

func main() {
	cluster := gocql.NewCluster("localhost")
	cluster.Keyspace = "foo"

	sess, err := cluster.CreateSession()
	if err != nil {
		log.Fatalln("Error connecting:", err)
	}

	batch := gocql.NewBatch(gocql.LoggedBatch)
	batch.Query("insert into bar (pcol, ccol, col1) values (1, 1, 1)")
	batch.Query("update bar set scol = 1 where pcol = 1 if scol = 0")

	if err := sess.ExecuteBatch(batch); err != nil {
		log.Fatalln("Error executing batch:", err)
	}
	fmt.Println("Success")
}
```

```
2015/08/18 08:16:27 Error executing batch: Unknown type in response to batch statement: [result_rows meta=[metadata flags=0x1 paging_state= columns=[[column keyspace=foo table=bar name=[applied] type=boolean] [column keyspace=foo table=bar name=pcol type=int] [column keyspace=foo table=bar name=ccol type=int] [column keyspace=foo table=bar name=scol type=int]]]]
```

**Comment by Zariel** [comment]
To fix this we probably need to change the API, or add a new method for BatchCAS which returns a list of Iters for each query or something

**Comment by 0x6e6562** [comment]
API wise it would probably need to return the `applied` flag back to the app. But what are the actual protocol semantics of CAS with batches? Is it good enough that one statement returns applied or do all PUT statements need to be get applied?

**Comment by Zariel** [comment]
Not sure, thats what I need to look at.

**Comment by tuxychandru** [comment]
In an LWT batch, either all statements are applied or none of them do.

There will be multiple rows returned, if there are multiple rows being updated in the batch and the batch was not applied. The value of `[applied]` column will be the same false for all rows in the returned result, if the batch was not applied.
