### ISSUE TITLE
Failing to use  gocql on AppEngine 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [gocql/gocql#457]
When gocql is used in an appengine project the deployment is failing with the following error 
`go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/gocql/gocql/token.go `,

**Comment by Zariel** [comment]
hm, thats frustrating. We can add a special file which is used for app engine for that function. Is there any build flags available for appengine?

**Comment by Karthic-Hackintosh** [comment]
There are build flags , but it creates runtime issues , I have to ship my code in few hours , But struggling to find a way out , is there a quick way out ?? https://sourcegraph.com/github.com/gocql/gocql@master/.tree/token.go#startline=58&endline=58 , here is the only place where unsafe is used

**Comment by Zariel** [comment]
@Karthic-Hackintosh that should fix your problem

**Comment by Karthic-Hackintosh** [comment]
@Zariel  : thank you :)
