### ISSUE TITLE
Implement write coalescing

### ISSUE THREAD

**Issue by abustany** [gocql/gocql#458]
http://www.datastax.com/dev/blog/performance-doubling-with-message-coalescing details how coalescing socket writes on client side can reduce the pressure on the network, and lead to performance improvement.

This issue is somehow related to issue #383 , except that coalescing in user space also helps reducing the syscall load (on loads with lots of small inserts, we see `syscall.Syscall` taking a significant share of CPU time).

I have some prototype code in the `perf` branch of my `abustany/gocql` fork, specifically the first two commits, this issue is more to spark discussion on whether there is interest, and how the API should look like (with my prototype, coalescing is hardcoded, but we probably want to give the users some knobs to tweak).

**Comment by Zariel** [comment]
I guess this is just as simple as adding a bufio.Writer around the connection and then having somethign which periodically flushes it

**Comment by abustany** [comment]
basically yes, except you need to start the flushing when a write comes in, and ideally stop it when it's idle. Also, errors need to be forwarded to the caller at some point. But conceptually you're right :-)

Cassandra does some slightly more complicated stuff internally (see the various policies described in the blog post), but I had quite good results already with a simple policy, which is also all that the java client has at this point.

**Comment by Zariel** [comment]
Im not sure how much benefit this will bring to be honest, and it will complicate the write path quite a bit.

**Comment by abustany** [comment]
Well, the blog post has some figures, which of course are probably "optimistic" given that they try to "sell" their feature. Still, we've seen quite a decrease on the syscall load with coalescing enabled. Note that I'm not necessarily advocating for the fancy moving average stuff, just the thing that you mentioned (bufio.Writer + periodic flushing) was enough.

The patch itself was quite simple for us, as you can see in https://github.com/abustany/gocql/commit/326016ac5075051da30205af8871cfc7c619fed9 (the batchio code could be simpler, that was a first version that was blocking for writers), the modifications to conn.go are minimal.

**Comment by Zariel** [comment]
The worrying this adding a lock in the write path, it may be necessary to enable this (and writes are already serialised at the socket side), I would be interested in seeing some numbers (or a pprof) of heavy write loads which spend lots of time in syscalls.

On an implementation side, how can errors be correctly returned to callers? Error handling in conn exec path has caused some trouble in the recent path and I would rather not complicate it too much.

**Comment by abustany** [comment]
I'll try to gather some pprof data. Note that pprof won't show the full extent of the performance improvement: by using larger packets, you improve the "packet metadata vs packet data" ratio, so you take better advantage of your bandwidth.

Regarding error reporting, it is the same as a buffering writer: write that simply append to the buffer don't error, and writes that flush it can error. The fact that errors are reported asynchronously shouldn't be too much of an issue, since requests have a timeout anyway. The implementation I linked above is loosely inspired by the Java client one: https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/transport/Message.java#L417 .

In any case, I'd make coalescing an opt-in feature, ie. we'd keep the current bare writer as a default, and only add coalescing if the user requests it (the trade-off that write errors become then asynchronous should be properly documented).

**Comment by Zariel** [comment]
I guess the only thing pprof would show would be a lot of syscalls caused by frame writes, which is what I would hope to see to support this. The general performance improvement should be from less syscalls to write to the wire, not really packet sizes.

Error handling is very precarious, relying on the timeout isnt a good idea as it will be hard for users to correlate that the write failed because it was buffered and that write failed (though it will likely fail with a timeout).
