### ISSUE TITLE
CreateSession Fails on AppEngine

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [gocql/gocql#462]
Since outbound connections have to created using appengine/socket CreateSession() fails to connect to the Remote cassandra instance , because of the above constraint on appengine it works locally but not on production .

**Comment by Zariel** [comment]
This change will require a more invasive change, which requires supporting custom dialers

**Comment by Karthic-Hackintosh** [comment]
@Zariel  : I'll start modifying the fork of this repo to make it work with App Engine , I'll get back on needing some suggestions

**Comment by Karthic-Hackintosh** [comment]
@Zariel  : I made new Implementation of the dialer and the driver works well on appengine , will push it to my forked repo in 12 more hours

**Comment by nikhilmahesh** [comment]
I am still facing this issue while deploying my code on appengine using aedeploy. Is there anything specific I need to change to make this work ?

**Comment by nikhilmahesh** [comment]
@hackintoshrao : Even, I can not see the change you were about to make in your repo.

**Comment by Zariel** [comment]
yes please
