### ISSUE TITLE
connection can run out of streams, leading to infinite waits?

### ISSUE THREAD

**Issue by ianrose14** [gocql/gocql#468]
I'd rather formulate this as a question rather than an issue but since Github doesn't really support that, here we are...

I have a relatively simple webserver that spends most of its time accepting HTTP requests and making cassandra writes in response.  I noticed today that one of these servers (a) had stopped performing any work and (b) had >10k goroutines.  Checking the stack traces, I find 12339 goroutines in the "select" state at line 447 of conn.go, which is a `select` waiting on `stream = <-c.uniq`.

Examining the conn.go code, I see that `releaseStream()` is (intentionally, it appears) *not* always called after a stream is finished.  For example, on line 471 of conn.go, if the response contains an error, the `exec()` call returns an error but never releases the stream.  So, if I understand this right, couldn't a connection run out of streams, meaning every exec() invocation would block indefinitely?

**Comment by Zariel** [comment]
Thanks for the report, conn stream handling is tricky and it indeeds looks like it was handle incorrectly in the case where recv sends an error to exec but does not close the connection. This should now be fixed, if you see this behaviour again can you please reopen.

**Comment by ianrose14** [comment]
Thanks for the quick response, Chris.  One thing for you to consider: what about adding a timeout to the stream-acquisition logic?  Right now there is:

```	select {
	case stream = <-c.uniq:
	case <-c.quit:
		return nil, ErrConnectionClosed
	}```

Just as a sensible guard against either (a) things moving really slowly, or (b) logic bugs like #469, one could do something like:

```	select {
	case stream = <-c.uniq:
	case <-c.quit:
		return nil, ErrConnectionClosed
	case <-time.After(<some sensible timeout value>):
		return nil, ErrNoStreams
	}```

Thoughts?  Of course the detail of "what is the right timeout value" could be tricky.  Off the cuff I would guess that our app would want something around 5 seconds, but I don't know about other users of gocql...

**Comment by Zariel** [comment]
Yeah at one point I had had it default out if no streams were available, but connections shouldn't be used by the connection pool if there are no streams available.

Really the conn shouldnt be used when it has no streams, how many conns and streams do you use in the config? (and cassandra nodes)

**Comment by ianrose14** [comment]
I must admit that we are using the default for both, which is probably a relatively uninformed choice on our part, but things seemed to mostly work so we haven't had reason to tweak them.  We previously had a 3 node cluster but recently added a 4th (which I now think was not necessary - I think our current issue is GC pauses, not too much load for our 3 nodes).

**Comment by mdelah** [comment]
We've started seeing this issue too, even after the patch above (we're currently building our application against gocql [3bc659a](https://github.com/brandscreen/gocql/commit/3bc659aecb321175a940135ac5f7f599f021e492), and running Cassandra 2.1.8). Scenario is basically identical to the OP. All queries start blocking indefinitely for an available stream, while each connection sits idle in readHeader(). Sample stack traces below.
```
82: select, 36 minutes [Created by main.respondWithUnique @ handlers.go:58]
    gocql   conn.go:447           (*Conn).exec(#3110, #6330, *, 0, 0, 0, 0, 0, 0)
    gocql   conn.go:629           (*Conn).executeQuery(#3110, *, 0xaf3880)
    gocql   session.go:222        (*Session).executeQuery(#600, *, *)
    gocql   session.go:634        (*Query).Iter(*, 0x960e90)
    service unique-service.go:209 (*UniqueService).GetUnique(#574, *, 0xc, *, 0, 0, 0)
    main    handlers.go:56        func·001()

230: IO wait, 29 minutes [Created by gocql.Connect @ conn.go:192]
    net     fd_poll_runtime.go:84 (*pollDesc).Wait(*, 0x72, 0, 0)
    net     fd_poll_runtime.go:89 (*pollDesc).WaitRead(*, 0, 0)
    net     fd_unix.go:242        (*netFD).Read(*, *, 0x1000, 0x1000, 0, #6321, *)
    net     net.go:121            (*conn).Read(*, *, 0x1000, 0x1000, 0, 0, 0)
    bufio   bufio.go:97           (*Reader).fill(*)
    bufio   bufio.go:174          (*Reader).Read(*, *, 0x8, 0x8, 0, 0, 0)
    io      io.go:298             ReadAtLeast(#6322, *, *, 0x8, 0x8, 0x8, 0, 0, 0)
    io      io.go:316             ReadFull(#6322, *, *, 0x8, 0x8, *, 0, 0)
    gocql   frame.go:315          readHeader(#6322, *, *, 0x8, 0x8, 0, 0, 0, 0, 0, ...)
    gocql   conn.go:363           (*Conn).recv(*, 0, 0)
    gocql   conn.go:344           (*Conn).serve(*)
```

**Comment by Zariel** [comment]
@mdelah interesting. The protocol is asynchronous so there is always 1 goroutine per connection reading headers. Were there any errors before this situation? Are there any other connections blocked elsewhere in exec? What connection pool are you using?

**Comment by mdelah** [comment]
> Were there any errors before this situation?

Nothing out of the ordinary, just the usual timeouts.

> Are there any other connections blocked elsewhere in exec?

No, all goroutines interacting with gocql end up stuck in one of the two call stacks above.

> What connection pool are you using?

SimplePool.

Thanks for the quick update. I'll rebuild with your patch above and let you know whether it reoccurs.

**Comment by mdelah** [comment]
@Zariel: Have been running with the patch above in production for a week now, and it looks like this issue has cleared up. Thanks again!

**Comment by Zariel** [comment]
@mdelah awesome thanks!
