### ISSUE TITLE
gocql can not marshal float64 into float

### ISSUE THREAD

**Issue by kelwang** [gocql/gocql#474]
ERROR: gocql can not marshal float64 into float

gocql/marshal.go

doesn't not support float64 for method: marshalFloat, unmarshalFloat

**Comment by Zariel** [comment]
This is because in Cassandra this type should be a double, a Cassandra float is a 32 bit float, which is what is expected for that column.

**Comment by kelwang** [comment]
@Zariel yep, tried to change the cassandra column type to double, works fine now. thanks

**Comment by pramanandasarkar02** [comment]
It should also be supportive for float 64, as strconv.parseFloat direct give float64.

**Comment by joao-r-reis** [comment]
> It should also be supportive for float 64, as strconv.parseFloat direct give float64.

last comment on this issue was 11 years ago, please open a new issue if you're having issues with the latest version of the driver
