### ISSUE TITLE
Runtime error using session.Bind() with TokenAwareConnectionPool

### ISSUE THREAD

**Issue by johannac** [gocql/gocql#475]
I'm getting the following error after changing my cluster config to use the token aware connection pool:
```
  Line 113: - runtime error: index out of range 
  goroutine 31 [running]:
  github.com/CrowdSurge/gocql.(*Query).GetRoutingKey(0xc20801fe10, 0x0, 0x0, 0x0, 0x0, 0x0)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/session.go:533 +0x3f4
  github.com/CrowdSurge/gocql.(*tokenAwareHostPolicy).Pick(0xc208062780, 0xc20801fe10, 0x0)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/policies.go:166 +0xce
  github.com/CrowdSurge/gocql.(*policyConnPool).Pick(0xc20805e2c0, 0xc20801fe10, 0x3)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/connectionpool.go:595 +0x55
  github.com/CrowdSurge/gocql.(*Session).executeQuery(0xc20800cd00, 0xc20801fe10, 0xc20800cd00)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/session.go:214 +0x107
  github.com/CrowdSurge/gocql.(*Query).Iter(0xc20801fe10, 0xc20801fe10)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/session.go:648 +0xce
  github.com/CrowdSurge/gocql.(*Query).Exec(0xc20801fe10, 0x0, 0x0)
  	/Users/Johanna/src/github.com/CrowdSurge/gocql/session.go:630 +0x3a
  github.com/CrowdSurge/cqlr.(*Binding).Exec(0xc208011570, 0xc20800cd00, 0x0, 0x0)
  	/Users/Johanna/src/github.com/CrowdSurge/cqlr/cqlr.go:51 +0xb0
```

I think this only occurs when using `session.Bind()`. After looking into this it appears that when using `session.Bind()` the value of `query.values` is either never set or is not set before the coordinator node gets picked, so when `query.GetRoutingKey()` references the slice it fails.

**Comment by Zariel** [comment]
Hm, I cant see a nice way to resolve this as it has a dependency as follows,

pick conn -> prepare -> bind -> exec

But for the token aware pool to work it has to go

bind -> getRoutingKey -> pick conn -> prepare -> exec

But bind depends on prepare, but we cant prepare until we have a conn.

**Comment by johannac** [comment]
If its not possible or too difficult to support the feature, perhaps we could add some error handling which prevents you from using Bind if you've got a token aware connection pool? A compile time warning would be ideal. Not super nice but would at least prevent run time errors.

**Comment by Zariel** [comment]
Ive created #477 to track fixing the underlying issue, for now the best that can be done is to not panic but to fallback to the round robin pool.
