### ISSUE TITLE
Unable to insert using 2.2 JSON format

### ISSUE THREAD

**Issue by sbowman** [gocql/gocql#484]
When I try to run this query, I'm not getting any errors, but nothing is saved to my database:

```go
    j := `{"message_id":"123456","type":"test","notified":"2015-10-06T23:56:21.351","session_id":"xyz","device_id":"abc","tracking":"abc123"}`
    if err := session.Query("INSERT INTO notifications JSON ?", j).Exec(); err != nil {
        panic(err)
    }
```

If I copy the query and paste in my value into cqlsh, the insert works just fine.

**Comment by sbowman** [comment]
I believe this has to do with the query value substitution and metadata in conn.go, in the Conn.executeQuery function.

**Comment by Zariel** [comment]
I cant reproduce this locally, as far as I can tell it is working.

**Comment by Zariel** [comment]
Are you using session.Bind or cqlc or something else ontop of gocql?

**Comment by sbowman** [comment]
I'm using straight gocql.  I'm trying the code similar to what I posted in the original ticket, except that "j" is really the doc from json.Marshal.

**Comment by sbowman** [comment]
And are you sure it's working?  I never get an error message, but when I look in Cassandra using cqlsh, the record is not there.

**Comment by Zariel** [comment]
According to #486 it appears to be working as expected, if you can provide a test case that proves otherwise or a fuller example that demonstrates the behaviour then ill be happy to fix.

**Comment by sbowman** [comment]
Your test case works fine for me too, though you may want to test all data types.  I tested some JSON using a struct that has a time.Time value that's not UTC, and Cassandra flipped out on the Go formatting of the time.  Zulu time seems to work fine.  I have not had this problem with traditional columnar inserts and updates of time.Time values.  

So, back to my case, if I run the above example now, it's working, sort of.  I think I've got something weird happening in my Cassandra instance, that somehow the JSON is "stuck".  If I run this once:

```go
	j := `{"message_id":"123","type":"test","notified":"2015-10-07T23:56:21.351Z","session_id":"xyz","device_id":"abct","tracking":"abc123"}`
	if err := session.Query("INSERT INTO notifications JSON ?", j).Exec(); err != nil {
		t.Fatalf("Failed to insert notification: %s", err)
	}
```

Then go into cqlsh, I see the record fine.  If I "delete from notifications where message_id = '123'", the message is gone from my "select" (obviously tombstoned).  Then if I change the above JSON slightly, the old record appears when I run the code again:

```go
	j := `{"message_id":"123","type":"test","notified":"2015-10-07T23:56:21.351Z","session_id":"AAA","device_id":"BBB","tracking":"CCC"}`
	if err := session.Query("INSERT INTO notifications JSON ?", j).Exec(); err != nil {
		t.Fatalf("Failed to insert notification: %s", err)
	}
```

If I query Cassandra after running the above, I see the old "session_id", "device_id", and "tracking" values from the first run!

However, if I update normally, using something like "INSERT INTO notifications (message_id, type, notified, session_id) VALUES ('123', 'test', '2015-10-07T23:56:21.351Z', 'DDD')", the notifications table gets updated with the correct "DDD" value.

I'm just going to steer clear of JSON for now...plus I figure it's probably a lot slower, both at the Go and Cassandra layers, though I haven't run any test cases.

**Comment by JCzz** [comment]
I have the same problem.

**Comment by Zariel** [comment]
I get this when encoding a time.Time using json.Marshal,

`Error decoding JSON value for value: Unable to coerce '2015-11-26T10:29:19.204499365Z' to a formatted date (long)`

Which I think is probably a bug in Cassandra

**Comment by Zariel** [comment]
Or it looks like Cassandra expects the timestamp to be encoded as a long not a string.

**Comment by Zariel** [comment]
So Cassandra expects it to either be a string or a long. The string format is hard coded to be, see https://github.com/apache/cassandra/blob/4a0d1caa262af3b6f2b6d329e45766b4df845a88/src/java/org/apache/cassandra/serializers/SimpleDateSerializer.java#L36

If you want to use JSON with Go time.Time then I would suggest raising a ticket with Cassandra

**Comment by Zariel** [comment]
Cassandra does not correctly decode blob either.
