### ISSUE TITLE
How do I use SliceMap?

### ISSUE THREAD

**Issue by gtaylor** [gocql/gocql#485]
I'm new to Go, and am completely failing at figuring out how to use SliceMap. Here's what I've got:

```go
    queryStr := fmt.Sprintf("SELECT * from %s ", tableName)
	fullQueryStr := queryStr + "WHERE locid=? AND per=?"
	iter := self.Session.Query(fullQueryStr, locId, startTime).Iter()

	for rd, err := range iter.SliceMap() {
		if err != nil {
			log.Fatal("ERR ", err)
		} else {
			fmt.Printf("RD ", rd)
		}
	}
```

Compile error ends up being:
```
../../gopath/src/bitbucket.org/aclima/sig-cassandra-extractor-go/lib/data_store/data_store.go:33: rd, err = iter.SliceMap() used as value
```

My intent is to retrieve all columns for each row in the query. I don't want to map this to a pre-determined set of variables or a struct since we don't know what the schema will be ahead of time. I'll be stuffing the values into a CSV.

Can someone point me in the correct direction?

**Comment by Zariel** [comment]
You cant use multiple return values like that in a range statement, the correct way to do this is via

```go
    queryStr := fmt.Sprintf("SELECT * from %s ", tableName)
    fullQueryStr := queryStr + "WHERE locid=? AND per=?"
    iter := self.Session.Query(fullQueryStr, locId, startTime).Iter()
    rd, err := range iter.SliceMap()
    if err != nil {
        log.Fatal("ERR ", err)
    } else {
       fmt.Printf("RD ", rd)
    }

    for row := range rd  {
        ...
    }
```

**Comment by gtaylor** [comment]
This makes perfect sense. Thanks for passing this along.
