### ISSUE TITLE
Placeholders, slices and prepared statements cache limits

### ISSUE THREAD

**Issue by crufter** [gocql/gocql#487]
Is there a way to bind slices to a single placeholder?

I am trying to fix the following issue we've found in the cassandra logs:

```
4 prepared statements discarded in the last minute because cache limit reached (14811136 bytes)
```

We are generating IN queries the following way:
```
SELECT fields FROM tablename WHERE fieldA IN (?, ?, ?) AND time >= ? AND time <= ?
```

And the values we are binding are
```
[1444302000000 1444305600000 1444309200000 2015-10-08 12:53:57.667550858 +0100 BST 2015-10-08 14:53:57.667550898 +0100 BST]
```

Obviously this means the number of placeholders is dependent on the size of the slice.
If I try to bind the slice to a single placeholder, like this:

```
SELECT fields FROM tablename WHERE fieldA IN (?) AND time >= ? AND time <= ?
```

```
[[1444302000000 1444305600000 1444309200000] 2015-10-08 12:53:57.667550858 +0100 BST 2015-10-08 14:53:57.667550898 +0100 BST]
```

The query does not return an error but returns no results.

This might be because of passing a slice to `session.Query`.

Is there a way to make this work without having to build separate statements depending on the size of the slice, thus polluting the prepared statement cache in Cassandra?

**Comment by nemothekid** [comment]
I'm not sure if I follow how the error you saw in your log is related to the way you were originally generating IN queries. Are you dynamically creating the queries with dynamic number of `?`s? If your statement always has 3 `?`, then the number of prepared statements in this case will always be the same.

**Comment by Zariel** [comment]
I'm not sure this is a particular issue with the driver. The drive can not function without knowing what the type of the column is to marshal to, otherwise it can't write out frames to send to the server.

That being said, unless this is causing problems with Cassandra beyond a log message I would think its fine. It might be worth considering not using the IN clause and instead sending one query for each of the IN elements, or using a batch.

**Comment by crufter** [comment]
@nemothekid 
> Are you dynamically creating the queries with dynamic number of ?s

Yes.
The number of `?`s is changing depending on the size of the slice, with the current way we are doing things. Each element in a size results in a `?`, thus producing a different statement, which pollutes the cache.

@Zariel 

> I'm not sure this is a particular issue with the driver. The driver can not function without knowing what the type of the column is to marshal to, otherwise it can't write out frames to send to the server.

I don't follow this. The parameters passed to an `IN` have a type of `[]type`, surely that can be recognised and marshalled? I am don't know how this works at the protocol level, however.

> It might be worth considering not using the IN clause and instead sending one query for each of the IN elements, or using a batch.

That's a very good idea and a possible solution to this problem. It would be nicer to avoid the complexity of doing this though, if we can.

> That being said, unless this is causing problems with Cassandra beyond a log message I would think its fine.

I agree, it might not have an impact.

**Comment by nemothekid** [comment]
I think this should work actually, I do it quite often - example

```go
var channels []string
var limit int
// ....
iter := c.Database.Cass.Query("SELECT created, type, args FROM channel_feeds WHERE channelid IN ? ORDER BY created DESC LIMIT ?", channels, limit).Iter()
var item feedItem
var args string
for iter.Scan(&item.Id, &item.Type, &args) {
//...
```

**Comment by crufter** [comment]
@nemothekid That actually works. The problem was the parens in the statements I generate. My fault.

Thanks, @nemothekid, @Zariel
