### ISSUE TITLE
Detect host failure in connection pool

### ISSUE THREAD

**Issue by dancannon** [gocql/gocql#499]
We were using a custom connection pool which used [bitly/hostpool](https://github.com/bitly/go-hostpool), this allowed us to detect issues with any of our hosts and direct queries to other hosts in the cluster. 

Unfortunately a recent change (139a10f05ec6cf5cf66bda1aace1356b71fa3711) removed the ability to use custom connection pool which broke our ability to use this hostpool. We looked into using the new host/connection policies however with the current interface it is not possible as there is no way to return the result of the query to the hostpool.

Having this feature built-in to gocql could be useful as it should make the client much more resilient to failure. If this is not a possibility can you think of any other ways of implementing something similar given the current interface?

**Comment by Zariel** [comment]
What would need exposing to enable this? Would you consider contributing it as it sounds like a very useful addition to the pool.

**Comment by dancannon** [comment]
Yeah I have no problem with contributing a change. Are you against using the hostpool library or would you prefer having that code in gocql?

Regarding the actual implementation what do you think about updating `NextHost` to return a wrapped `HostInfo` that allows the host to be marked similar to how the hostpool library works (https://godoc.org/github.com/bitly/go-hostpool#HostPoolResponse)

**Comment by Zariel** [comment]
Can you not implement a host selection policy instead? But I guess you need to know if the query fails?

**Comment by dancannon** [comment]
Yeah exactly, you need to be able to tell your host selection policy the outcome of a given query and given the current interface that is not possible.

**Comment by Zariel** [comment]
How about this, I still need to figure out how to wire it back to the session and pool though.

```go
// HostSelectionPolicy is an interface for selecting
// the most appropriate host to execute a given query.
type HostSelectionPolicy interface {
	SetHosts
	SetPartitioner
	//Pick returns an iteration function over selected hosts
	Pick(*Query) NextHost

	// MarkError is called when an executed query returns an error
	MarkError(conn *Conn, qry *Query, err error)
	// MarkSuccess is called when an executed query does not return an error
	MarkSuccess(conn *Conn, qry *Query)
}
```

**Comment by dancannon** [comment]
A couple of points:

1. Do you really need separate `Mark` functions? Could you not just mark any queries as successful if there `err==nil`
2. This could be worked around but if we were to this interface we would not be able to use the hostpool library in its current form, however if we decide to inline the library into gocql then this won't be an issue.

What do you think?

**Comment by Zariel** [comment]
Why can't you use the bitly hostpool with the proposed interface? I guess you could just use a single mark function.

**Comment by dancannon** [comment]
You cant use the bitly hostpool because there is no way to mark a host given just the hostname. However I think the best solution would be to submit a PR to the project which adds the functions needed to support your suggested, if it is rejected for whatever reason it could always be forked into the gocql organization however I dont see that happening.

I will work on this tomorrow and submit a PR, thanks for the help so far.

**Comment by Zariel** [comment]
Ah yes, I guess you would either need a way to mark the host in the pool as bad via a hostname (which shouldn't be a terrible idea?) or to pass around a context on the query.

**Comment by dancannon** [comment]
I attempted to come up with a working solution here [dancannon/gocql](https://github.com/dancannon/gocql/tree/hostpool).

I decided to go with a solution that I think is more flexible than what we discussed but I am interested to see what you think. I also used the hailocab fork of the hostpool library as this allows you to change the hosts without changing the hostpool, this could be changed back but I think it would make the API a little more difficult to use.

**Comment by dancannon** [comment]
@Zariel have you had a chance to look at my branch? We have had to pin gocql to an older version so the sooner we can resolve this issue the better. Thanks

**Comment by Zariel** [comment]
I think this looks good, could you move it into gocql/policies, add some doc and submit as a PR?

**Comment by dancannon** [comment]
What do you mean by move into `gocql/policies`? Do you want me to create a new subpackage?

**Comment by Zariel** [comment]
actually ignore the bit about packages
