### ISSUE TITLE
Cannot create user defined function

### ISSUE THREAD

**Issue by korya** [gocql/gocql#500]
I'm trying to create a function with gocql:

```golang
query := `CREATE OR REPLACE FUNCTION uniq(state set<text>, val text)
  CALLED ON NULL INPUT RETURNS set<text> LANGUAGE java
  AS 'state.add(val); return state;'`;
err := session.Query(query).Exec()
```

I get the following error:

```
Unknown type in response to execute query (*gocql.schemaChangeFunction): [header version=[version=4 direction=RESP] flags=0x0 stream=6 op=RESULT length=62]
```

Is it expected behaviour?

As far as I can see https://github.com/gocql/gocql/commit/6b4a5e5a2c9fb456c2550fdc9398dfa4be68f854 has added support for UDF to `frame.go`, but it didn't add it to Conn::executeQuery() in `conn.go`. Was it done intentionally?

**Comment by Zariel** [comment]
No this looks like a bug, we should handle that response frame

**Comment by Zariel** [comment]
Thanks for the report

**Comment by korya** [comment]
This was fast. Thanks!
