### ISSUE TITLE
Gocql spamming "unable to get ring topology: gocql" under network partition

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#511]
I've noticed this recently as I've done a recent upgrade to gocql master on our fork. During a network issue, gocql can't get the ring topology and spams "unable to get ring topology: gocql" log messages.

Today I noticed that two machines had an outage, and gocql spammed the logs until the disk was full :laughing:. (it logged 9889 times a second!)

My guess is [controlConn.reconnect](https://github.com/gocql/gocql/blob/a64caf392c35f716d242c0eb5e13df5d33f42fc0/control.go#L64) is called excessively.

Some further sleuthing shows there was a [sleep](https://github.com/gocql/gocql/blob/a64caf392c35f716d242c0eb5e13df5d33f42fc0/control.go#L58) and it was removed (possible to prevent a sleep on successful reconnect?)

In any case, this function should probably be throttled - I have my own ideas on how to solve this, but some further sluething showed that there was some debouncing implemented that likely doesn't work.

**Comment by nemothekid** [comment]
Actually, it looks like I have an older version of [connect.go](https://github.com/ChannelMeter/gocql/blob/master/control.go) that I should have checked before opening this issue. Strangely, it has a sleep `time.Sleep(5 * time.Second)`, but as I mentioned I saw it called ~10,000 times a second.

**Comment by nemothekid** [comment]
Actually, my version doesn't even call `refreshRing` - seems like my [issue is here](https://github.com/ChannelMeter/gocql/blob/master/host_source.go#L108), when we fail to get the ring topology, we just continue.

**Comment by nemothekid** [comment]
Looks like the issue may have already been resolved; will just upgrade.

**Comment by Zariel** [comment]
I think its probably worth being able to register a logger, this log can be quite spammy under adverse network conditions.
