### ISSUE TITLE
Marshalling an empty list is throwing error

### ISSUE THREAD

**Issue by Gouthamve** [gocql/gocql#518]
Trying to marshal an empty list is throwing an obscure error: ```Not enough bytes to read a list```

I hope this is an easy fix as it is kind of essential for me.

CQL:

```cql
CREATE TYPE user (
    name text,
    phone text,
    email text,
    list list<text>
);

CREATE TABLE test.events_by_userid (
    userid text PRIMARY KEY,
    user frozen<user>
);
```
and GoLang:

```go
type user struct {
	Name  string   `cql:"name"`
	Phone string   `cql:"phone"`
	Email string   `cql:"email"`
	List  []string `cql:"list"`
}

testE := user{
	Name:  "goutham",
	Phone: "123456",
}

err = session.Query(`INSERT INTO events_by_userid (userid , user ) VALUES ( ?, ?)`, "goutham", testE).Exec()
if err != nil {
	log.Fatal(err)
}
```

throws ```Not enough bytes to read a list```.

**Comment by Gouthamve** [comment]
I think this error is being emitted by Cassandra and not gocql.

**Comment by Zariel** [comment]
This could be the driver not encoding the empty list correctly, I have a feeling I know what caused this.

**Comment by Zariel** [comment]
This is because cassandra is expecting collection types to be 0 length for empty, it does not have a concept of nil collections.
