### ISSUE TITLE
Panic Index out of range in Connect

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#519]
Index out of range.

```
panic: runtime error: index out of range

goroutine 32659 [running]:
github.com/channelmeter/gocql.Connect(0xc2082192c0, 0x11, 0xc2085de360, 0x7fd266046d20, 0xc208194120, 0x8, 0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/conn.go:190 +0x735
github.com/channelmeter/gocql.(*hostConnPool).connect(0xc208194120, 0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/connectionpool.go:398 +0xa2
github.com/channelmeter/gocql.(*hostConnPool).fill(0xc208194120)
	/go/src/github.com/channelmeter/gocql/connectionpool.go:333 +0x1cf
created by github.com/channelmeter/gocql.(*hostConnPool).Pick
	/go/src/github.com/channelmeter/gocql/connectionpool.go:260 +0xbc
```

**Comment by Zariel** [comment]
Whats the value of NumStreams?

**Comment by nemothekid** [comment]
Sorry for the terrible issue, I was trying to get things back up and just wanted to quickly document this error.

In this application, the cluster configuration's NumStreams is likely 0 meaning its probably going to the maximum for ProtoVersion 3.

I'm looking over the code now actually and not even sure how this could have come up. Also note that this happened after a network failure (been having a lot of these lately :()

**Comment by Zariel** [comment]
ouch, thanks ill take a look

**Comment by Zariel** [comment]
I have a feeling this is due to sharing conf config and mutating it.

**Comment by nemothekid** [comment]
That would be my guess as well, the fix could be simply just treating cfg as readonly and copying `NumStreams` as a threadlocal var

**Comment by Zariel** [comment]
yeah, that or passing by value.

**Comment by Zariel** [comment]
Im going to leave this open until I can make a test which proves that this was caused by #520
