### ISSUE TITLE
ORDER BY and a IN restriction error occurs

### ISSUE THREAD

**Issue by lylex** [gocql/gocql#522]
when execute the following code:

db.Query("SELECT * FROM emp WHERE empID IN (130,104) ORDER BY created_at DESC").Consistency(gocql.One).Iter().SliceMap()

Error occurs:

PANIC: Cannot page queries with both ORDER BY and a IN restriction on the partition key; you must either remove the ORDER BY or the IN and sort client side, or disable paging for this query

It should be supported according to the latest cql spec.

**Comment by Zariel** [comment]
Can you post the line the panic comes from? I think that might a Cassandra error?

**Comment by lylex** [comment]
Actually I did the panic explicitly. 

_, err := db.Query("SELECT * FROM emp WHERE empID IN (130,104) ORDER BY created_at DESC").Consistency(gocql.One).Iter().SliceMap()

err is a error, error message is "Cannot page queries with both ORDER BY and a IN restriction on the partition key; you must either remove the ORDER BY or the IN and sort client side, or disable paging for this query". Sorry for the confusion.

After some investigation, I found that gocql have a defaul pageSize. So when I execute these commands, gocql will by default add some paging cql to cassandra. So the error occurs. When I add the following in initialize:

session.SetPageSize(0) // try to turn off the default paging

It is ok for the query above. However, it should be done in the init of the cql session and removed paging forever. I have no idea whether it is save operation for all the sessions.

I think the "IN ... ORDER BY" is a common user scenario, so do you have any per-query setting about it or any other recommended solution?

**Comment by Zariel** [comment]
PageSize can be set on a per query basis by changing the query value, https://godoc.org/github.com/gocql/gocql#Query.PageSize

**Comment by lylex** [comment]
Yes, it works. Thanks a lot.
