### ISSUE TITLE
Panic recovery -> reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by silvinalucero** [gocql/gocql#523]
Panic recovery -> reflect: call of reflect.Value.Type on zero Value
/usr/local/go/src/runtime/panic.go:423 (0x42a6e9)
/usr/local/go/src/reflect/value.go:1664 (0x54facb)
/home/deploy/applications-kvsapi-slucero/src/github.com/gocql/gocql/marshal.go:194 (0x77d596)
/home/deploy/applications-kvsapi-slucero/src/github.com/gocql/gocql/marshal.go:66 (0x77babd)
/home/deploy/applications-kvsapi-slucero/src/github.com/gocql/gocql/conn.go:827 (0x75c2af)
/home/deploy/applications-kvsapi-slucero/src/github.com/gocql/gocql/session.go:437 (0x7a072d)
/home/deploy/applications-kvsapi-slucero/src/github.com/gocql/gocql/session.go:460 (0x7a0957)

**Comment by Zariel** [comment]
Thanks for the report
