### ISSUE TITLE
Panic in Pool.Pick

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#526]
Stack Trace:
```
[35m[2015-11-15T10:52:33.49Z] [GEARD] [geard.go:437] [CRITICAL] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:423 (0x4321f9)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:42 (0x4308b9)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x44770a)
	sigpanic: panicmem()
/go/src/github.com/channelmeter/gocql/connectionpool.go:188 (0x70456f)
	(*policyConnPool).Pick: conn = p.hostConnPools[host.Info().Peer].Pick(qry)
/go/src/github.com/channelmeter/gocql/session.go:429 (0x7463be)
	(*Session).executeBatch: host, conn := s.pool.Pick(nil)
/go/src/github.com/channelmeter/gocql/session.go:460 (0x746697)
	(*Session).ExecuteBatch: _, err := s.executeBatch(batch)
/go/src/github.com/channelmeter/geard/tasks/youtube/video.go:277 (0x5c3135)
```

I've been getting this during times of increased load, and when queries time out - also not sure what is nil in this situation `host`, `host.Info()` or `p.hostConnPools[host.Info().Peer]`.

I'm also at ad901edec6273959e31837afa3942b374efa2b5e, not sure if anything regarding this has changed since then.

**Comment by nemothekid** [comment]
It looks like 64eb2479f81d0adf1521cbf84318f5e78401b82f/#510 is hitting a similar issue I was.

**Comment by nemothekid** [comment]
I'll try applying #510, and reopen if I still have issues.

**Comment by nemothekid** [comment]
Reopening because I still hit the issue under contention.

```
panic: policy *gocql.tokenAwareHostPolicy returned no host info: {info:<nil>}

goroutine 137 [running]:
github.com/channelmeter/gocql.(*policyConnPool).Pick(0xc2085c7b90, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/channelmeter/gocql/connectionpool.go:195 +0x2f8
github.com/channelmeter/gocql.(*controlConn).reconnect(0xc208589ec0, 0x7ff7840eb601)
	/go/src/github.com/channelmeter/gocql/control.go:86 +0x190
github.com/channelmeter/gocql.(*controlConn).heartBeat(0xc208589ec0)
	/go/src/github.com/channelmeter/gocql/control.go:57 +0x186
created by github.com/channelmeter/gocql.createControlConn
	/go/src/github.com/channelmeter/gocql/control.go:29 +0x172
```

What should be done in this situation? Here is the function:

```go
func (p *policyConnPool) Pick(qry *Query) (SelectedHost, *Conn) {
	nextHost := p.hostPolicy.Pick(qry)

	var (
		host SelectedHost
		conn *Conn
	)

	p.mu.RLock()
	defer p.mu.RUnlock()
	for conn == nil {
		host = nextHost()
		if host == nil {
			break
		} else if host.Info() == nil {
			panic(fmt.Sprintf("policy %T returned no host info: %+v", p.hostPolicy, host))
		}

		pool, ok := p.hostConnPools[host.Info().Peer]
		if !ok {
			continue
		}

		conn = pool.Pick(qry)
	}
	return host, conn
}
```

Return a nil host? Sleep and retry?

**Comment by Zariel** [comment]
Bug here is that the host policy should be allowed to return nil host info
which was the previous behaviour. That if should be made into one check and
just break.

I'm in the process of refactoring the host discovery into an event based
one, the ring poller should return the last available hosts when it can't
connect.

**Comment by nemothekid** [comment]
My hunch is `host` is nil, and the nil comparison is failing because of the [nil interface{} comparison thing](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#nil_in_nil_in_vals)

I've hit this bug (w.r.t. expecting a nil value to be nil, but its not, its just a nil interface) before, looking at the code below:
```go
func (r *roundRobinHostPolicy) Pick(qry *Query) NextHost {
	// i is used to limit the number of attempts to find a host
	// to the number of hosts known to this policy
	var i uint32
	return func() SelectedHost {
		r.mu.RLock()
		defer r.mu.RUnlock()
		if len(r.hosts) == 0 {
			return nil
		}

		var host *HostInfo
		// always increment pos to evenly distribute traffic in case of
		// failures
		pos := atomic.AddUint32(&r.pos, 1)
		if int(i) < len(r.hosts) {
			host = &r.hosts[(pos)%uint32(len(r.hosts))]
			i++
		}
		return selectedRoundRobinHost{host}
	}
}
```

`len(r.hosts)` could be 0, and host is actually nil. Otherwise `r.hosts[(pos)%uint32(len(r.hosts))]` could be nil.

Lastly, I'm not sure what `i` is doing here, but if `i > len(r.hosts)` (we have walked all hosts) we end up with `selectedRoundRobinHost{nil}`, which would also cause the error I'm seeing. 

So it looks like we walk all the hosts (no host has `hostConnPools`, which could happen in a node network partition), and we return this garbage value.

What should be done here? Is there any way to fall `pool.fill`? Or return a `noavailablehosts` back to the application?

**Comment by Zariel** [comment]
Yep thats what I was thinking. Here I should be turned into an int, and if `i > len(hosts)` return nil explicitly. The connection pool should call `pool.fill` if the no host is returned.
