### ISSUE TITLE
Cassandra 3

### ISSUE THREAD

**Issue by maxtepkeev** [gocql/gocql#538]
Hi, I was just wondering, what is the status of cassandra 3 support for gocql, currently it doesn't seem to work, during the connection to cassandra the following error is returned:

```
failed to connect to 127.0.0.1:9042 due to error: not enough bytes to read header require 9 got: 8
```

**Comment by Zariel** [comment]
It should work with protocol 4, ill update the integration tests and check

**Comment by jdness** [comment]
Max, try adding

	cluster.ProtoVersion = 4

between your gocql.NewCluster.. and cluster.CreateSession().  Worked for me today. 

Jonathan

**Comment by maxtepkeev** [comment]
That was it, thanks Jonathan

**Comment by batflaps** [comment]
My code still pukes with same error, here's my code:
```go
package main

import "fmt"
import "log"
import "github.com/gocql/gocql"

var (
	name, sex string
	age int
)

func main() {
	// connect to the cluster
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Keyspace = "dbaccess"
	session, _ := cluster.CreateSession()
	defer session.Close()
	
	cluster.ProtoVersion = 4
	
	if err := session.Query("SELECT name, age FROM people WHERE name='doug'").Scan(&name, &age); 
	err != nil {
		log.Fatal(err)
	}
	fmt.Println(name, age)
}
```
Am I doing something obviously wrong? I'm running Cassandra 3.1.1

**Comment by Zariel** [comment]
Once the session is started the cluster config cant be changed, you need to set it with other config options, like the Keyspace.

**Comment by batflaps** [comment]
It worked! Thanks @Zariel . Here's my working code in case that helps anyone:
````go
package main

import "fmt"
import "log"
import "github.com/gocql/gocql"

var (
	name, sex, age string
)

func main() {
	// connect to the cluster
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.ProtoVersion = 4
	cluster.Keyspace = "dbaccess"
	session, _ := cluster.CreateSession()
	defer session.Close()
	
	if err := session.Query("SELECT name, age FROM people WHERE name='doug'").Scan(&name, &age); 
	err != nil {
		log.Fatal(err)
	}
	fmt.Println(name, age)
}
````

**Comment by arbarlow** [comment]
Hi, I've run into a similar problem and fixed it for my application but many tools like migrate and cqlr etc can't connect, can gocql detect the version and then use that?

**Comment by Zariel** [comment]
There is a ticket to do it, its possible but it is not yet implemented #540

**Comment by arbarlow** [comment]
@Zariel great! If you have some ideas where to start I can give it a go?

**Comment by Zariel** [comment]
@arbarlow moving discussion to #540, there is a further issue here that the driver should not rely on the protocol version to determine what queries to use, as we also have the nodes version which is a better indicator.
