### ISSUE TITLE
Auto detect protocol

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#540]
We should be able to auto detect what protocol to use by what the server responds with.

**Comment by Zariel** [comment]
I think the idea is that, the control connection sends the highest known protocol for an outgoing request, if the error is an invalid protocol response then use the returned protocol, otherwise the highest. This should only be done if the protocol is not set though.

**Comment by MalteJ** [comment]
+1

**Comment by bipin-nag** [comment]
Please do this. Libraries using gocql should not have to build this feature separately. I use cqlc which has incorrect way of detecting/upgrading protocol. Look at https://github.com/relops/cqlc/blob/9427a2081fb4f4910b0af8fc80d09c109b4f9815/generator/generator.go. It requires to connect at least once before upgrading. But that never happens with cassandra v3. Feel there needs to be a standard way and it is better solved at gocql level.

**Comment by Zariel** [comment]
The driver needs to connect once with the max value, and on error reconnect at a lower protocol. In reality applications should be hard coding their protocol version, as things like the V4 differences between 2.2 and 3.0 existing.
