### ISSUE TITLE
[Question] Any way to issue multiple queries with a single iter ?

### ISSUE THREAD

**Issue by jdness** [gocql/gocql#545]
Our web app needs to display hundreds of thousands of rows from a Cassandra 3 database query.  We page the results by using

```
cqlsession.Query(query).PageState(last_state).PageSize(rows_per_page).Iter()
```

We loop over the batch of rows with iter.SliceMap() and then record the iter.PageState() in the web cookie so the next page load can continue the query.  It works great!

However now I would like this web page to display results from two different queries.  Two materialized views on the same table (same column names, etc).  I would love to do something like this:

```
cqlsession.Query(`select * from table1_view1;select * from table1_view2;`).PageState(last_state).PageSize(rows_per_page).Iter()
```

However, that fails with an error that looks like this:

```
line 1:136 missing EOF at 'select' (...1 and remoteport = ?;[select] *...)
```

Any suggestions on how to make this work?  Thanks!

Jonathan

**Comment by Zariel** [comment]
That error is coming from Cassandra as the query is not valid syntax. It might be possible to implement an Iter which can merge 2 iters with the same columns, but this wouldnt work with PageState as the that is per query.

**Comment by jdness** [comment]
Okay thanks Chris.  That makes sense.  I will probably just build an array of iterators and loop over them instead of trying to do multiple queries with one iterator.
