### ISSUE TITLE
WillSwitchPage is always false

### ISSUE THREAD

**Issue by dopgm** [gocql/gocql#548]
Hi,

While iterator is correctly returning iter.PageState() for me = empty state on last pages,
for some reason iter.WillSwitchPage() is always false. I would expect it to become false only on the last page.

Thoughts?

Thank you!
D.

---
Go 1.5
gocql as of Dec 4
Cassandra 3.0

**Comment by Zariel** [comment]
Can you provide a test case example?

**Comment by dopgm** [comment]
Hi, @Zariel 
Here's my code (Go):

```go

 (...)
	query := cs.Db.Query(`SELECT foo,bar FROM posts WHERE user_id=foo`).PageState(state).PageSize(ipp)

	var p Post
	iter := query.Iter()

 (...)

	newState := iter.PageState()
	lastPageFlag := iter.WillSwitchPage()

 (...)
```

On any page my lastPageFlag remains false, while PageState correctly returns empty on the last one.

**Comment by Zariel** [comment]
Setting the PageState on a query will disable auto pagination, the `WillSwitchPages` indicates if auto pagination will switch to a new page (ie it has already fetched the next page). So in this case it will always return false.

**Comment by dopgm** [comment]
@Zariel 
Got it!
Thank yo for the explanation! Not an issue.

**Comment by Zariel** [comment]
No problem!
