### ISSUE TITLE
undefined: atomic.Value

### ISSUE THREAD

**Issue by tzach** [gocql/gocql#550]
I try to run the [driver example](https://gist.githubusercontent.com/beccam/0aa0c6fa28d9341fe32c/raw/4c38ce30edc0f8e46fccde4d458cf9d266a9f25c/GettingStarted.go)

and get the following results
```
$ go run ./example.go 
# github.com/gocql/gocql
../gocql/gocql/control.go:17: undefined: atomic.Value
```

My go version
```
$ go version
go version go1.2 linux/amd64
```

**Comment by Gouthamve** [comment]
I don't think go1.2 is supported. go1.4 and 1.5 are supported. I guess the atomic package in go1.2 doesn't have .Value

You could upgrade your go version.

**Comment by Zariel** [comment]
Gocql only supports the latest and previous Go versions, so at this time that is 1.4 and 1.5, to use Goqcl you will need to upgrade your Go versions as @Gouthamve points out.

**Comment by tzach** [comment]
Thanks @Gouthamve @Zariel 
Upgrading to Go 1.5 solve the issue.
