### ISSUE TITLE
Unmarshal'ing a list<frozen<map<text, int>>> type through custom unmarshal 

### ISSUE THREAD

**Issue by chitrakojha** [gocql/gocql#556]
Hi, 

I've a usecase where I store data in Cassandra as a list of maps. 

Is there a way to easily encode this into a []map[string]int in my custom unmarshal. 
I can implement my own Unmarshal logic if there's nothing more straightforward. 

Appreciate any help in this regard.

**Comment by Zariel** [comment]
The Marshaller should handle decoding into all Cassandra types, so if you allocate one and try to unmarshall into it should work. If it doesn't please open an issue with reproduction.
