### ISSUE TITLE
Unmarshal'ing a list<frozen<map<text, int>>> type results in "empty" map 

### ISSUE THREAD

**Issue by chitrakojha** [gocql/gocql#557]
Thanks @Zariel for the previous response. 

Here's my schema: 
```sql
CREATE TABLE test.table_foo (
    id text,
    size int,
    data list\<frozen\<map\<text, int\>\>\>,
    PRIMARY KEY (id)
)
```

Here's what I am doing in my code: 
```go
	var s []map[string]int


	if err := session.Query(`select data from table_foo
	where id=?`, "196070585").Consistency(gocql.One).Scan(&s); err != nil {
		log.Fatal(err)
	}
	fmt.Println(s)
```

This prints 
[map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[] map[]]

I've verified that data values do get returned in a byte format in the iterator, so it's essentially not empty.

**Comment by chitrakojha** [comment]
Additionally, this is the example data in one of the rows 
[{'21862': 9}, {'22154': 8}, {'11955': 6}, {'22208': 5}, {'22201': 4}, {'23368': 4}, {'21966': 4}, {'26213': 4}, {'25269': 4}, {'26331': 4}, {'32218': 4}, {'2420': 4}, {'13002': 4}, {'31134': 3}, {'21793': 3}, {'27247': 3}, {'23147': 3}, {'25460': 3}, {'22211': 3}, {'21795': 3}, {'23482': 3}, {'31140': 3}, {'6089': 3}, {'12044': 3}, {'23443': 3}, {'26414': 2}, {'27828': 2}, {'23403': 2}, {'31076': 2}, {'23237': 2}, {'12942': 2}, {'21794': 2}, {'26181': 2}, {'22955': 2}, {'12113': 2}, {'23099': 2}, {'25358': 2}, {'28689': 2}, {'26258': 2}, {'9966': 2}, {'11678': 2}, {'2373': 2}, {'23481': 2}, {'22225': 2}, {'25151': 2}, {'31933': 2}, {'4543': 2}, {'2649': 2}, {'22339': 2}, {'31807': 2}, {'3063': 2}, {'25981': 2}, {'21787': 2}, {'22209': 2}, {'25058': 2}, {'22664': 2}, {'30818': 2}, {'4789': 2}, {'22318': 2}, {'4018': 2}, {'21792': 2}, {'27246': 2}, {'29118': 2}, {'22368': 2}, {'21724': 2}, {'29646': 1}, {'21289': 1}, {'31463': 1}, {'30793': 1}, {'9073': 1}, {'23813': 1}, {'19714': 1}, {'26428': 1}, {'24948': 1}, {'11609': 1}, {'26252': 1}, {'23796': 1}, {'20712': 1}, {'29632': 1}, {'29100': 1}, {'10768': 1}, {'19719': 1}, {'1224': 1}, {'30581': 1}, {'10308': 1}, {'27328': 1}, {'13431': 1}, {'23485': 1}, {'30820': 1}, {'6559': 1}, {'20290': 1}, {'8714': 1}, {'24016': 1}, {'6563': 1}, {'5609': 1}, {'21852': 1}, {'529': 1}, {'27829': 1}, {'25047': 1}, {'22194': 1}]

**Comment by Zariel** [comment]
According to #558 it works correctly

**Comment by Zariel** [comment]
@chitrakojha as far as I can see this works on my end, can you give more details? Cassandra version, any errors on Cassandra side? What protocol version are you using?

**Comment by chitrakojha** [comment]
Thanks @Zariel  for the test. I emulated the test and saw the same error. 
I've the following version: 
Cassandra - 2.1.3

I am using the default protocol version. I am not sure what it is, maybe V2 ? How can I try with V3 ?

**Comment by chitrakojha** [comment]
@Zariel - thanks for the pointer. I was using protocol 2. 
I used P3 and this works perfect!
