### ISSUE TITLE
request: version pinning/release via http://gopkg.in

### ISSUE THREAD

**Issue by mikeatlas** [gocql/gocql#559]
Hello! 

We find the `godep` tool to be extremely frustrating when working with shared dependencies of numerous 3rd party libraries and our own multiple Go projects. Instead, we're pulling in forked versions of  projects as a way of pinning versions as a lame dependency management method, but it beats a lot of the issues we hit daily using Godep.

Gocql is one project we can't fork and build; the gocql `internal` packages prevent us from compiling or referencing it. True, we could run a `go get` each build, but would like to lock in a particular snapshot/working version of libraries all together without hitting this error:

```
$ go build
package gitlab.myserver.com/mycompany/go3p/gocql/gocql
    imports github.com/gocql/gocql/internal/lru: use of internal package not allowed
package gitlab.myserver.com/mycompany/go3p/gocql/gocql
    imports myserver.com/gocql/gocql/internal/murmur: use of internal package not allowed
package gitlab.myserver.com/mycompany/go3p/gocql/gocql
    imports github.com/gocql/gocql/internal/streams: use of internal package not allowed
```

As of Go 1.5, `internal` packages have _no_ ability to be whitelisted and are rejected by the `go` command for both GOROOT and GOPATH packages [(reference)](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit). 

So, if we are going to rely on gocql, it would be great to have a locked-in version to `go get` using the only method I'm aware of presently, `gopkg.in`'s service. How amenable is this project to pinning / releasing versions with that tool?

Thank you!
Mike

**Comment by martin-sucha** [comment]
It looks that in 2022 we don't need godep support as users can use Go modules instead. Closing in favor of #977 .
