### ISSUE TITLE
CreateSession fails if localhost resolves to "::1" ipv6 loopback address

### ISSUE THREAD

**Issue by bofabcd** [gocql/gocql#560]
_this works -_ cluster := gocql.NewCluster("**127.0.0.1**")
_this works only with ipv4 -_ cluster := gocql.NewCluster("**localhost**")
_this fails -_ cluster := gocql.NewCluster("**::1**")

**Comment by Zariel** [comment]
I think this is probably due to using `net.SplitHostPort` which requires IPv6 literals to be surrounded by [],

try using `[::1]`

**Comment by bofabcd** [comment]
I used localhost, but it resolved to::1 somewhere in gocql 

Brian Brown
bbrown@novetta.com
910-973-5943

**Comment by bofabcd** [comment]
This started happening when I switched from Go 1.4.2 to 1.5.2

**Comment by bofabcd** [comment]
With Go 1.4: localhost resolved as 127.0.0.1
With Go 1.5: localhost resolved as ::1

I guess I will change my config to use 127.0.0.1 instead of localhost

**Comment by Zariel** [comment]
Thats odd, ill look into this when I get the chance.

**Comment by bofabcd** [comment]
Has this been resolved?


Brian Brown
bbrown@novetta.com
910-973-5943

**Comment by Zariel** [comment]
Via #1000
