### ISSUE TITLE
TextMarshaler

### ISSUE THREAD

**Issue by mpmlj** [gocql/gocql#562]
Hi,

Please implement TextMarshaler.
Example of a use-case: https://github.com/istreamdata/orientgo/issues/52

Thank you!
D.

**Comment by Zariel** [comment]
For which types?

**Comment by mpmlj** [comment]
@Zariel 
My use case is uuid/timeuuid <-> string.

**Comment by mpmlj** [comment]
Awesome! Appreciate the prompt resolution, @Zariel ,

D.
