### ISSUE TITLE
Suspected TCP connection leak

### ISSUE THREAD

**Issue by DaveHasteSpringer** [gocql/gocql#565]
Apologies if this has already been logged (I cannot find an equivalent-looking open bug), or if I'm doing something stupid.

It looks as if the gocql library may leak TCP connections when repeatedly creating and closing sessions.

The following code reliably reproduces this problem, for me:

```
package main 

import (
	"github.com/gocql/gocql"
	"log"
	"time"
)

func main() {
	for {
		doit("cassandra-db-hostname")
		time.Sleep(time.Second)
	}
}

func doit(host string) {
	var releaseVersion string

	cluster := gocql.NewCluster(host)
	cluster.ProtoVersion = 4
	cluster.Keyspace = "system"
	cluster.Consistency = gocql.Quorum
	session, err := cluster.CreateSession()
	if err != nil {
		log.Printf("Error creating session on Cassandra host: %s (%v)\n", host, err)
		return
	}
	defer func() {
		session.Close()
		log.Printf("Session closed\n")
	}()

	err = session.Query(`SELECT release_version FROM local`).Consistency(gocql.One).Scan(&releaseVersion)
	if err != nil {
		log.Printf("Error querying version on Cassandra host: %s (%v)\n", host, err)
		return
	}

	log.Printf("Version: %v\n", releaseVersion)
}
```
Running this code (on OSX, or Ubuntu) results in an ever-increasing number of 'ESTABLISHED' TCP connections being created (verified using lsof), until the process runs out of file descriptors and starts experiencing problems.

The logged output confirms that each created session is being closed, so this looks a lot like a bug to me, unless I'm missing something?

**Comment by Zariel** [comment]
This looks interesting, all the drivers connections should be closed after the return from session.Close.

**Comment by Zariel** [comment]
@DaveHasteSpringer hi, I can't reproduce this, after running the test suite all connections to :9042 are closed, running the supplied program the same occurs.

**Comment by DaveHasteSpringer** [comment]
@Zariel That's strange. It's extremely reproducible for me, on at least two platforms!

I'll take another look at it, and maybe create a fresh Golang build environment in case it's a problem with my setup. I'll report back with my findings.

**Comment by DaveHasteSpringer** [comment]
@Zariel OK, I've managed to make some sense of this.

For my original report on 11th January, I was using the most recent commit to master (1dd55ddf77779788d00913b2962a1f995052117d). The file descriptor leak was certainly evident with that version (and is still reproducible using that version on a new clean system).

The latest code in master does not appear to exhibit this problem. After a bit of trial-and-error, it looks to me as if [this merge](https://github.com/gocql/gocql/commit/3b1e36f335e9a96610c1d6ebc26b74b7587d8d64) fixes the issue.
