### ISSUE TITLE
Creating a keyspace using gocql driver 

### ISSUE THREAD

**Issue by moadqassem** [gocql/gocql#566]
Hey all,

Sorry if my question looks a little bit dummy, but I have been looking inside the lib and I was looking for a method to create a keyspace if it doesn't exist.

So is there any implementation inside the gocql lib which creates a keyspce? 

Thanks.

**Comment by Zariel** [comment]
Gocql doesnt provide a direct way to do this, you also must connect the session to an already existing keyspace.

You can execute `CREATE KEYSPACE IF NOT EXISTS ...` as a normal query, we use this in the tests to setup and drop the keyspace, https://github.com/gocql/gocql/blob/1dd55ddf77779788d00913b2962a1f995052117d/cassandra_test.go#L91

**Comment by moadqassem** [comment]
Then what shall you do if you have to create integration tests using docker? it's kinda impossible to create the keyspace using only the driver.

**Comment by Zariel** [comment]
The gocql integration tests do this, have a method which is guarded by a `sync.Once` which does the keyspace manipulation then call it from each test that needs to use Cassandra. The method to create the keyspace can connect to the system keyspace, as the linked function does, just internally we use the control connection but it should work just fine using `session.Query`.

If you follow `createSession` from our tests you should see how it works, https://github.com/gocql/gocql/blob/1dd55ddf77779788d00913b2962a1f995052117d/cassandra_test.go#L258

**Comment by Zariel** [comment]
@moadqassem can I close this?
