### ISSUE TITLE
byte slice corruption in query object bind parameter

### ISSUE THREAD

**Issue by thedirtycolumbia** [gocql/gocql#567]
We recently updated our version of gocql to find that a bind parameter of type net.IP is being mutated before the execution of the query.

A gist of our test code is here: https://gist.github.com/thedirtycolumbia/678af7caf660962df509

We found that the ip parameter in the `check_alloc` and `check_free` queries are different if printed in the CheckQuery function (e.g. on line 2 of the test code gist) than they are after declaration (e.g. on line 37).

Running `git-bisect` reveals that our test breaks after d8a24ba3e6103220e570660a902a768dc84bb466

An example of what we would expect from printing query strings:

    Prepared query was: [query statement="SELECT COUNT(1) FROM alloc_ipv4_addrs WHERE addr = ?" values=[10.1.1.5] consistency=QUORUM]
    Prepared query was: [query statement="SELECT COUNT(1) FROM free_ipv4_addrs_by_location\n\t\t\t\t\tWHERE location = ? AND addr = ?" values=[us-west 10.1.1.5] consistency=QUORUM]
    Check query was: [query statement="SELECT COUNT(1) FROM alloc_ipv4_addrs WHERE addr = ?" values=[10.1.1.5] consistency=QUORUM]
    Check query was: [query statement="SELECT COUNT(1) FROM free_ipv4_addrs_by_location\n\t\t\t\t\tWHERE location = ? AND addr = ?" values=[us-west 10.1.1.5] consistency=QUORUM]

Here's what we're seeing after the change:

    Prepared query was: [query statement="SELECT COUNT(1) FROM alloc_ipv4_addrs WHERE addr = ?" values=[8.108.111.99] consistency=QUORUM]
    Prepared query was: [query statement="SELECT COUNT(1) FROM free_ipv4_addrs_by_location\n\t\t\t\t\tWHERE location = ? AND addr = ?" values=[us-west 8.108.111.99] consistency=QUORUM]
    Check query was: [query statement="SELECT COUNT(1) FROM alloc_ipv4_addrs WHERE addr = ?" values=[0.0.1.0] consistency=QUORUM]
    Check query was: [query statement="SELECT COUNT(1) FROM free_ipv4_addrs_by_location\n\t\t\t\t\tWHERE location = ? AND addr = ?" values=[us-west 0.0.1.0] consistency=QUORUM]

**Comment by Zariel** [comment]
Thanks for the report, will take a look

**Comment by Zariel** [comment]
Im trying to reproduce this and am struggling to, can you provide more of a runnable example which shows the behaviour? Is the IP in the example allocated by gocql? What are the table structures?

**Comment by thedirtycolumbia** [comment]
The IP addresses are all stored in a C* table like the one below:

    CREATE TABLE free_ipv4_addrs_by_location (
        location text,
        addr inet,
        PRIMARY KEY (location, addr)
    ) WITH CLUSTERING ORDER BY (addr ASC)

The IP in the example is selected from the free table and moved to the alloc table by the `allocateIPv4Address` function which returns the selected IP as a https://golang.org/pkg/net/#IP.

    CREATE TABLE alloc_ipv4_addrs (
        addr inet,
        location text,
        container timeuuid,
        PRIMARY KEY (addr, location)
    ) WITH CLUSTERING ORDER BY (location ASC)

**Comment by thedirtycolumbia** [comment]
The addresses we are now seeing in the executed query (`8.108.111.99` and `0.0.1.0 `) are never in the free table to begin with. We expect to see the address `10.1.1.5` after a single run of this test.

Our tests create a new keyspace each time they are run.

**Comment by thedirtycolumbia** [comment]
In case it is helpful, the query to select an IP address looks like this:

    q := `SELECT addr
                    FROM free_ipv4_addrs_by_location
                    WHERE location = ?
                    LIMIT 1`
    err = session.Query(q, location).Scan(&ip)
    // check for err, etc.

**Comment by Zariel** [comment]
Thanks, I can reproduce it. Annoyingly this is one which fails quickly without the race detector, but works with the race detector, awesome :D

**Comment by thedirtycolumbia** [comment]
Thank you! I pulled down these changes and our tests are all passing once again. : )
