### ISSUE TITLE
The current unmarshalling of tuples is incompatible with nested tuples e.g. map(tuple)

### ISSUE THREAD

**Issue by kristoiv** [gocql/gocql#572]
Because of the way gocql unmarshal's tuples into additional columns, it fails when the tuple is nested. In the example below we create a test keyspace and a table with a map-nested tuple of two integers.

This thread is meant as a place to discuss alternative implementations.

If you run this example you'll see something like:

``` go
cannot unmarshal tuple into *[]interface {}
```

``` go
package main

import (
    "fmt"
    "log"

    "github.com/gocql/gocql"
)

func main() {
    cluster := gocql.NewCluster("127.0.0.1")
    cluster.Consistency = gocql.One
    cluster.ProtoVersion = 4

    session, err := cluster.CreateSession()
    if err != nil {
        log.Fatalln(err)
    }

    // Drop testing keyspace
    if err := session.Query(`DROP KEYSPACE gocqldebugging_test;`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Create testing keyspace
    if err := session.Query(`CREATE KEYSPACE gocqldebugging_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Create table with tuple in it
    if err := session.Query(`CREATE TABLE gocqldebugging_test.test (id uuid PRIMARY KEY, myNonCustom map<uuid,frozen<tuple<int, int>>>);`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Insert some data into our table
    if err := session.Query(`INSERT INTO gocqldebugging_test.test (id, myNonCustom) VALUES (uuid(), {uuid():(1, 2),uuid():(3,4)});`).Exec(); err != nil {
        log.Fatalln(err)
    }

    var id gocql.UUID
    m := make(map[gocql.UUID][]interface{})
    if err := session.Query(`select id, myNonCustom from gocqldebugging_test.test`).Scan(&id, &m); err != nil {
        log.Fatalln(err)
    }

    fmt.Println(id, m)
}
```

**Comment by Zariel** [comment]
@kristoiv what sort of API makes sense for tuple unmarshalling? Type should be able to unmarshal into a single tuple column?

So far the best I can think of is `[]interface{}` or a list of anything, map would work as well.

**Comment by kristoiv** [comment]
I think a slice or an array makes the most sense. Sure you'll have to type assert it before using it but a map makes less sense since you won't have keys in the tuple anyway.

I guess the problem is how the unmarshalling happens now. I haven't studied the binary protocol enough to suggest an actual implementation, but as far as I understood the column will have nested values that could be handled (asserted) to their golang type, and then put into a []interface{} before it is returned.

I think all types should be possible to unmarshal from a tuple column since they can be nested in complex ways in CQL, and thus some developers are probably going to do so. I did when I wanted to add some quick pre-defined meta data to each value of a map in the userTable (e.g. UserTable->User->Groups(map)->Group(key=myGroup;value=[title, isAdmin, created]). I could do something like this today by nesting a map (Map(key=string, value=map(string, string)), but then every item has to have the same type.

**Comment by Zariel** [comment]
We can now use []interface, [...]interface{}, struct{} to handle tuples
