### ISSUE TITLE
Poor read/write performance with latest commit 496fdda

### ISSUE THREAD

**Issue by ttqin** [gocql/gocql#582]
Hi there,

We seem to be getting poor C* read and write performance after building against latest gocql/gocql, commit hash 496fdda0436cec5c0f0f361b34a686e501662d80. Reverting back to fe1bd1bc33e6a89c5cdbf0bf8847aea79fde19a2 seems to fix this issue, so the 4 PR's that have been merged in may have caused the issue.

read rate 100,000/s dropped to 4,200/s
write rate 10,000/s dropped to 600/s

I'm not sure what potential impact PR's #551 #577 have, nothing glaringly obvious.

cc @dancannon

**Comment by Zariel** [comment]
Thanks ill take a look at this, do you have any pprofs?

**Comment by Zariel** [comment]
@ttqin Ive been doing some benchmarking using pre prepared frames and so far I don't see such a large performance regression. My 4 core i5 macbook gives these numbers,

```
benchmark                        old ns/op     new ns/op     delta
BenchmarkSession_ReadPerf        597996        593589        -0.74%
BenchmarkSession_ReadPerf-2      435783        436608        +0.19%
BenchmarkSession_ReadPerf-4      501313        469419        -6.36%
BenchmarkSession_ReadPerf-8      512366        500448        -2.33%
BenchmarkSession_ReadPerf-16     576868        562769        -2.44%

benchmark                        old allocs     new allocs     delta
BenchmarkSession_ReadPerf        1974           1974           +0.00%
BenchmarkSession_ReadPerf-2      1974           1974           +0.00%
BenchmarkSession_ReadPerf-4      1975           1975           +0.00%
BenchmarkSession_ReadPerf-8      1976           1976           +0.00%
BenchmarkSession_ReadPerf-16     1976           1976           +0.00%

benchmark                        old bytes     new bytes     delta
BenchmarkSession_ReadPerf        209444        209449        +0.00%
BenchmarkSession_ReadPerf-2      210101        210073        -0.01%
BenchmarkSession_ReadPerf-4      211333        211262        -0.03%
BenchmarkSession_ReadPerf-8      212266        212099        -0.08%
BenchmarkSession_ReadPerf-16     212221        212312        +0.04%
```

This load is using `select * from system.schema_columns`. Can you give any more details on what sort of load you see such a drop in performance with.

**Comment by ttqin** [comment]
@Zariel apologies for the delay in replying. Unfortunately, I don't have any pprofs readily available.

The workload is doing large number of reads and then upserts of the same rows. Would you be able to modify your benchmark to try this?

**Comment by Zariel** [comment]
#615 and #607 should both improve read performance a fair amount, but im still unable to figure out what would cause such a large drop off in performance What Go version is being used?

**Comment by dancannon** [comment]
@Zariel I have finally managed to find some more time to look into this issue. I can now reliably reproduce it with a benchmark (I would share the code but it uses quite a bit of internal code, if I can't figure out anything else I will try to come up with a new test just using gocql). Essentially the test just executes many writes against a real cassandra cluster, I am also extending the length of the benchmarks with `-benchtime=10s`. 

Here are the results so far, I am also profiling these tests but have yet to find anything useful:
```
87cc185:
     300	  37795806 ns/op
ok  	package	13.220s
496fdda:
     200	  71651427 ns/op
ok  	package	32.723s
```

**Comment by dancannon** [comment]
Another update, setting `disableControlConn` to true seems to fix the performance issues (https://github.com/gocql/gocql/blob/master/session.go#L121). I have yet to figure out why this is though.

**Comment by Zariel** [comment]
Thats interesting. Have you looked cpu profiles for the 2 runs?

**Comment by dancannon** [comment]
@Zariel, I have had a look but couldnt see anything obvious, here are the svg outputs https://www.dropbox.com/sh/pax8d38eo2cfe12/AACPhwVXKAVpf5QFamrdLdrea?dl=0. Let me know if you would like any of the other outputs.

**Comment by Zariel** [comment]
That looks odd, the slow case seems to be spending a bunch of time doing `NewSession`. Have you tried with latest master?

**Comment by dancannon** [comment]
I just ran the benchmark with `master` and got the same result. I added the profiles to the dropbox directory with the `_master` suffix (this time the benchmarks ran with `-benchtime=30s`).

Also setting `disableControlConn` to true improved the performance again, strangely enough `NewSession` only runs once per benchmark so it shouldnt affect the results too much.

**Comment by dancannon** [comment]
Yet another update, setting `DisableInitialHostLookup` to true and commenting out everything in `refreshRing` also fixes the performance issues (both need to be done).

**Comment by Zariel** [comment]
Is it just `NewSession` being slow or is it also the queries? Looking at it newConnPool will block the whole connection pool whilst dialing where it shouldnt. We also duplicate calls to refreshRing unnecessarily, ill look into fixing these.

**Comment by Zariel** [comment]
Could you benchmark just `NewSession`? What sort of cluster are you running?

**Comment by dancannon** [comment]
I just ran some more benchmarks with the different parts of the query annotated.

```go
	// Setup session if not already connected
	start1 := time.Now()
	if err := e.init(); err != nil {
		return err
	}
	fmt.Println(1, time.Since(start1))

	// Load session
	start2 := time.Now()
	e.RLock()
	session, ks := e.session, e.ks
	e.RUnlock()
	fmt.Println(2, time.Since(start2))

	if session == nil {
		return fmt.Errorf("No open session")
	}

	// Prepare query
	start3 := time.Now()
	q := session.Query(stmt, params...)
	if opts.Consistency != nil {
		q = q.Consistency(*opts.Consistency)
	}
	fmt.Println(3, time.Since(start3))

	// Actually run the query
	start4 := time.Now()
	err := q.Exec()
	fmt.Println(4, time.Since(start4))
```

What I noticed was that the first query (when the session is still nil) was very slow and took multiple seconds.

```
1 2.025960814s
2 2µs
3 3µs
4 30.36304ms
```

Queries after this take much less time, however occasionally queries take around 5 times longer, I reverted to the previous hash and in that version the query times are stable at around 30ms.

```
1 235ns
2 151ns
3 812ns
4 161.967283ms

1 278ns
2 191ns
3 955ns
4 28.975792ms

1 155ns
2 159ns
3 799ns
4 155.171567ms

1 332ns
2 221ns
3 941ns
4 27.603106ms

1 183ns
2 162ns
3 757ns
4 27.786785ms

1 239ns
2 146ns
3 872ns
4 156.187168ms
```

I will benchmark `NewSession` but I think there is another issue here somewhere. The cluster I am testing this with is a 3 node cluster running Cassandra 2.24.

**Comment by dancannon** [comment]
Oh no.... I have found out why queries were being affected. I was wrong when I said it was a 3 node cluster as it is a multi-datacenter cluster with 3 nodes in each datacenter. So when gocql discovered the hosts it was discovering hosts in the datacenter that is in a different region...

Really sorry I wasted your time with this issue, hopefully this at least helps you speed up `NewSession` a bit.

**Comment by Zariel** [comment]
No worries, glad it wasn't a serious problem in the driver. Ill create some more tickets for the issues with refreshRing and NewSession. Thanks very much for the help!

**Comment by Zariel** [comment]
@dancannon Ive found an issue which would lead to adding hosts which dont pass the host filter, fixing.
