### ISSUE TITLE
HostFilter is useless

### ISSUE THREAD

**Issue by obeattie** [gocql/gocql#584]
The new `HostFilter` interface is – as far as I can tell – useless, as it is a [private attribute of `Session`](https://github.com/gocql/gocql/blob/master/session.go#L47). Can this be made public?

**Comment by obeattie** [comment]
Separately, I would like a mechanism to disable the automatic host discovery entirely. In our case, we know precisely which nodes we would like our services to connect to, and we don't want them doing discovery on their own. I believe this is made partially possible if `HostFilter` worked, but that doesn't prevent it executing the "discovery queries" in the first place.

**Comment by Zariel** [comment]
I intended to add the HostFilter interface but didnt get round to it. Ill open a separate issue to disable host discovery.
