### ISSUE TITLE
Error connecting to cassandra 3.0

### ISSUE THREAD

**Issue by mediocregopher** [gocql/gocql#594]
I get this error when trying to connect to a cassandra 3.0 instance with default configuration:

```
gocql: unable to control conn dial 127.0.0.1:9042: not enough bytes to read header require 9 got: 8
```

I didn't get this error previously, I believe I checked out gocql sometime last week and it was working fine until I pulled today.

Also, could I get some clarification on what cassandra versions are supported? The README states both that only up to 2.2.x is tested and that:

> we only test against the latest 3 major releases

Which is contradictory since the last major release was 3.0. Thanks, and let me know if there's anything I can do to help troubleshoot further.

**Comment by Zariel** [comment]
This is probably just due to needing to use protocol 4. We cant update the integration tests to test against cassandra 3 as it requires java 8 which we cant install in travis yet.

**Comment by mediocregopher** [comment]
Not sure if you meant 3 or 4 there, but setting `ProtoVersion = 3` did indeed fix it so thanks for setting me on the right path!
