### ISSUE TITLE
 "no connections available" error

### ISSUE THREAD

**Issue by bkeroackdsc** [gocql/gocql#609]
I have a web application which creates a global Session object during startup which the various HTTP handlers then use.

This application runs fine for a period of hours or days but then it starts throwing ``no connections available`` errors when trying to execute queries. I've tried increasing ``NumConns`` in ClusterConfig to  20 and ``SocketKeepalive`` to 30 seconds. This didn't seem to improve the situation. The only fix seems to be restarting the app.

Do session objects need to be periodically closed and refreshed? Or am I leaking connections somehow? I'm using ``session.Query(query).Scan()`` or ``MapScan()`` (not Iter) so nothing needs to be closed I don't think.

Any help would be appreciated. This is with the latest gocql master.

**Comment by nemothekid** [comment]
I saw a similar issue a couple days ago with Cassandra 3.2 using the latest code - my Cassandra databases were flapping, and services on newer-ish gocql code had the problem you described. However, after getting my cluster stable, I no longer see the errors. #596 might be related.

OTOH, you could also switch to the `pre-node-events` tree and see if you see the same issue (if you are getting this consistently, and you switch and the problems stop it would confirm the presence of bugs in the new event code). Remember to switch DiscoverHosts to true.

Also, Setting NumConns that high is a waste IMO.

**Comment by Zariel** [comment]
I think there may be some cases where the driver can never reconnect to the cluster if it doesn't get an event that a host went up.

**Comment by Zariel** [comment]
Also if you build with the tag `gocql_debug` it will log out all incoming events, which will be helpful in debugging this.

**Comment by crufter** [comment]
I am experiencing the same thing, once we start killing nodes in the Cassandra cluster one by one (as a sort of manual chaos monkey), we get this error.

We also use a single session created at service startup and reuse that everywhere.

**Comment by bkeroackdsc** [comment]
If it matters, in my case it's a single node C* "cluster".

**Comment by Zariel** [comment]
Working on a fix

**Comment by Zariel** [comment]
@bkeroackdsc @crufter @nemothekid if you see this again please reopen but I think it should be fixed, the control connection will now try to connect to the initial hosts and mark them as up if there are no available hosts to connect to.

**Comment by bkeroackdsc** [comment]
thanks @Zariel 

I'm deploying the fix today and will reopen if I run into the issue again.
