### ISSUE TITLE
String conversion/sanitization issue

### ISSUE THREAD

**Issue by mpmlj** [gocql/gocql#621]
Hi,

I'm storing a string "worst%25pa%24th%60ev%0dr-%2comg" via
b.Query(`UPDATE stories SET path = ? WHERE 	story_id = ?`, p.Path)  (part of a batch)

The string above is a result of QueryEscape() from the "net/url" package.

After save, the string appears differently In Cassandra:

was: "worst%25pa%24th%60ev%**0d**r-%2comg"
now: "worst%25pa%24th%60ev%**5cr**r-%2comg"

However, when doing insert directly via cqlsh, the string is correct/identical:
was: "worst%25pa%24th%60ev%0dr-%2comg"
now: "worst%25pa%24th%60ev%0dr-%2comg"

Please advise

Thank you!
D.

**Comment by Zariel** [comment]
What is the column type being inserted into?

**Comment by mpmlj** [comment]
@Zariel, "text".

**Comment by Zariel** [comment]
I'm unable to reproduce this locally, can you provide a test case which fails? This is what I used.

```go
func TestIssue621(t *testing.T) {
	cluster := createCluster()
	session := createSessionFromCluster(cluster, t)
	defer session.Close()

	if err := createTable(session, `CREATE TABLE gocql_test.Issue621 (
		id text PRIMARY KEY,
		value text)`); err != nil {

		t.Fatal(err)
	}

	const (
		key = "test"
	)

	value := "worst%25pa%24th%60ev%0dr-%2comg"

	err := session.Query("INSERT INTO Issue621(id, value) VALUES(?, ?)", key, value).Exec()
	if err != nil {
		t.Fatal(err)
	}

	var val string
	err = session.Query("SELECT value FROM Issue621 WHERE id=?", key).Scan(&val)
	if err != nil {
		t.Fatal(err)
	} else if val != value {
		t.Fatalf("expected to get value=%q got=%q", value, val)
	}
}
```

**Comment by mpmlj** [comment]
@Zariel 
Apologies, issue on my side. Appreciate your prompt response with a test!
