### ISSUE TITLE
Debugging "no connections available"

### ISSUE THREAD

**Issue by mediocregopher** [gocql/gocql#622]
Howdy! I'm currently setting up a client like so:

```go
        cc := gocql.NewCluster(cAddr)                                                                           
        cc.Keyspace = keyspace                                                                                  
        cc.ProtoVersion = 3                                                                                     
        cc.SocketKeepalive = 10 * time.Second                                                                   
                                                                                                                
        var err error                                                                                           
        cs, err = cc.CreateSession()                                                                            
        if err != nil {                                                                                         
            log.Fatalf("error connecting to cassandra: %s", err)                                                     
        }
```

This connection is then used by our api when handling requests. Randomly we'll see it return the error `no connections available`. Adding the `SocketKeepalive` seems to have helped with the problem, but it still happens occasionally. Subsequent requests to the api don't generate the error and go through successfully, so I guess the driver figures it out and makes more connections, but I'd still like to try and get rid of these errors if possible. Do you have any tips on how to debug this further, or what might be causing these errors?

**Comment by nemothekid** [comment]
See #609, which should/may have been fixed by #610. What commit version of the driver are you using?

**Comment by mediocregopher** [comment]
Thanks for the quick response! I'm not sure of the exact commit, but our build system does a fresh `go get -u` on every build, and the build was made about 3 days ago (1/29/2016), so that fix *should* have been in there.

Our "cluster" is actually only one node at the moment, if that affects anything at all, that other issue seems to have had something to do with nodes' connections to each other flapping which wouldn't be the case here.

**Comment by Zariel** [comment]
It could be that the pool trys to dial the host and fails. You can add logging to https://github.com/gocql/gocql/blob/84d36abe91cd4cc178592a546b6e3a1ec015a692/connectionpool.go#L537 to check what error and if the connection is closed.

You can also build with `gocql_debug` tag which will debug event frames coming in. If you have events enabled then the driver will detect the downed host via events and close the connection pool for it.

**Comment by Zariel** [comment]
Also if this is an intermittent problem for the cluster it might be worth adding a retry policy to retry the queries.

**Comment by mediocregopher** [comment]
Thanks, I'll try adding the logging in and see what comes up. Looking at the logs around that time I'm not seeing any other services having any troubles so I don't think it's a general packet loss issue or anything like that, but I guess we'll find out.

**Comment by Zariel** [comment]
@mediocregopher did you get anywhere?

**Comment by mediocregopher** [comment]
Well since rebuilding and redploying we haven't seen this issue at all again >_< I'm willing to close the issue, I can make a new one if it comes up again later.
