### ISSUE TITLE
Panic in connectionpool.go

### ISSUE THREAD

**Issue by jalkanen** [gocql/gocql#634]
Heya!

I'm seeing this, and I can't figure out what's going on - changing the HostSelectionPolicy seems to have no effect here.  Any ideas where to go debugging?

```
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:426 (0x42cf49)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:45 (0x42b5f9)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x44186a)
	sigpanic: panicmem()
/home/vagrant/go/src/github.com/gocql/gocql/connectionpool.go:201 (0x497f6d)
	(*policyConnPool).Pick: nextHost := p.hostPolicy.Pick(qry)
/home/vagrant/go/src/github.com/gocql/gocql/session.go:290 (0x4e3c1b)
	(*Session).executeQuery: host, conn := s.pool.Pick(qry)
/home/vagrant/go/src/github.com/gocql/gocql/session.go:801 (0x4e7069)
	(*Query).Iter: return q.session.executeQuery(q)
/home/vagrant/go/src/github.com/gocql/gocql/session.go:783 (0x4e6ead)
	(*Query).Exec: iter := q.Iter()
/vagrant/src/events.go:46 (0x4013a6)
	testFinalized: if err := session.Query("INSERT INTO events (id, user_id, type, result) VALUES (?,?,?,?)",

```

**Comment by Zariel** [comment]
What version of Go is this?

**Comment by Zariel** [comment]
Can you post a more fully panic trace? I need to see what is nil here as it must be the `policyConnPool` but cant confirm. Do you have something which reliably triggers this?

**Comment by jalkanen** [comment]
Sorry, I was in a bit of a hurry and left out important version info. This is occurring both on go 1.5.3 and go 1.6rc1 on Ubuntu 14.04 inside a Vagrant box against Cassandra 2.2.4.

I'll see if I can create a repro case.  The setup is fairly straightforward:

```
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Consistency = gocql.Quorum
	cluster.Keyspace = "monitoring"

	session, _ := cluster.CreateSession()

	defer session.Close()
```

**Comment by jalkanen** [comment]
*groan* Yes, this was actually a case of variable shadowing; I had an extra colon there - instead of "=" it's ":=" and this overrode my nice package variable which was hence an empty struct. However, it would be nice if session.Query() or Exec() checked that it has a valid Session before continuing. Now the error message is fairly confusing.
