### ISSUE TITLE
Read performance test

### ISSUE THREAD

**Issue by materespana** [gocql/gocql#639]
Hi Guys:

We are doing some performance test between Golang - Java and We notice that Java driver read performance is 4x more fast than Go driver. Here the information about the test:

Cassandra Schema:

CREATE KEYSPACE test WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 }

CREATE TABLE categories_stress_test (key text PRIMARY KEY, value text, version int, last_updated_truncated text, date_created timestamp, last_updated timestamp);

For testing We implement an API using gin-gonic web framawork that use cassandra like DB. We are doing queries with LocalOne consistency and the avg time of this queries in Java was 3ms rather than in Golang was 12ms. We notice too that Golang tests hava time spikes, here a little of access log:

[GIN] 2016/02/07 - 13:45:04 | 200 |   10.699396ms | 172.16.148.207:18263 |   GET     /containers/categories_stress_test/MLC134929
[GIN] 2016/02/07 - 13:45:04 | 200 |    19.67937ms | 172.16.148.207:18250 |   GET     /containers/categories_stress_test/MLV14887
[GIN] 2016/02/07 - 13:45:04 | 200 |   20.602219ms | 172.16.148.207:18248 |   GET     /containers/categories_stress_test/MLB29356
[GIN] 2016/02/07 - 13:45:04 | 200 |   20.505851ms | 172.16.148.207:18249 |   GET     /containers/categories_stress_test/MLB205135
[GIN] 2016/02/07 - 13:45:04 | 200 |   26.362305ms | 172.16.148.207:18243 |   GET     /containers/categories_stress_test/MLA339110
[GIN] 2016/02/07 - 13:45:04 | 200 |    2.643999ms | 172.16.148.207:18277 |   GET     /containers/categories_stress_test/MLB176878
[GIN] 2016/02/07 - 13:45:04 | 200 |   19.762425ms | 172.16.148.207:18258 |   GET     /containers/categories_stress_test/MLA17359
[GIN] 2016/02/07 - 13:45:04 | 404 |     4.24444ms | 172.16.148.207:18276 |   GET     /containers/categories_stress_test/MLM151233
[GIN] 2016/02/07 - 13:45:04 | 200 |    4.243693ms | 172.16.148.207:18278 |   GET     /containers/categories_stress_test/MLA121893
[GIN] 2016/02/07 - 13:45:04 | 404 |    19.47513ms | 172.16.148.207:18264 |   GET     /containers/categories_stress_test/MLC150984
[GIN] 2016/02/07 - 13:45:04 | 200 |    4.355704ms | 172.16.148.207:18282 |   GET     /containers/categories_stress_test/MCR50987
[GIN] 2016/02/07 - 13:45:04 | 200 |   20.143917ms | 172.16.148.207:18266 |   GET     /containers/categories_stress_test/MLA340902
[GIN] 2016/02/07 - 13:45:04 | 200 |   19.231485ms | 172.16.148.207:18267 |   GET     /containers/categories_stress_test/MLB134663
[GIN] 2016/02/07 - 13:45:04 | 200 |    2.793293ms | 172.16.148.207:18288 |   GET     /containers/categories_stress_test/MPT71034
[GIN] 2016/02/07 - 13:45:04 | 200 |    2.460949ms | 172.16.148.207:18293 |   GET     /containers/categories_stress_test/MLC159762
[GIN] 2016/02/07 - 13:45:04 | 200 |    3.628415ms | 172.16.148.207:18292 |   GET     /containers/categories_stress_test/MLU176420
[GIN] 2016/02/07 - 13:45:04 | 200 |    19.19791ms | 172.16.148.207:18271 |   GET     /containers/categories_stress_test/MLB208973
[GIN] 2016/02/07 - 13:45:04 | 200 |    9.966404ms | 172.16.148.207:18285 |   GET     /containers/categories_stress_test/MLA127443
[GIN] 2016/02/07 - 13:45:04 | 200 |    2.732705ms | 172.16.148.207:18301 |   GET     /containers/categories_stress_test/MCO166272
[GIN] 2016/02/07 - 13:45:04 | 200 |    5.561952ms | 172.16.148.207:18300 |   GET     /containers/categories_stress_test/MLA11234
[GIN] 2016/02/07 - 13:45:04 | 200 |   21.086949ms | 172.16.148.207:18279 |   GET     /containers/categories_stress_test/MLM134513
[GIN] 2016/02/07 - 13:45:04 | 200 |   19.511221ms | 172.16.148.207:18287 |   GET     /containers/categories_stress_test/MLB202746
[GIN] 2016/02/07 - 13:45:04 | 200 |    2.748697ms | 172.16.148.207:18309 |   GET     /containers/categories_stress_test/MLU137195
[GIN] 2016/02/07 - 13:45:04 | 200 |   19.231914ms | 172.16.148.207:18290 |   GET     /containers/categories_stress_test/MCO73526
[GIN] 2016/02/07 - 13:45:04 | 200 |   20.272818ms | 172.16.148.207:18291 |   GET     /containers/categories_stress_test/MLB160480
[GIN] 2016/02/07 - 13:45:04 | 200 |     2.77888ms | 172.16.148.207:18314 |   GET     /containers/categories_stress_test/MLU117805
[GIN] 2016/02/07 - 13:45:04 | 200 |   27.176181ms | 172.16.148.207:18296 |   GET     /containers/categories_stress_test/MLC140312
[GIN] 2016/02/07 - 13:45:04 | 200 |   40.288411ms | 172.16.148.207:18284 |   GET     /containers/categories_stress_test/MLU119178
[GIN] 2016/02/07 - 13:45:04 | 200 |   38.943594ms | 172.16.148.207:18315 |   GET     /containers/categories_stress_test/MLA336890
[GIN] 2016/02/07 - 13:45:04 | 200 |   46.994619ms | 172.16.148.207:18306 |   GET     /containers/categories_stress_test/MHN50488
[GIN] 2016/02/07 - 13:45:04 | 200 |   38.157254ms | 172.16.148.207:18317 |   GET     /containers/categories_stress_test/MLA82431
[GIN] 2016/02/07 - 13:45:04 | 200 |   49.587919ms | 172.16.148.207:18303 |   GET     /containers/categories_stress_test/MLA362058

You can see very different times, request with 2 or 3ms and request of 46ms.

Here our driver configuration:

Cluster := gocql.NewCluster(xxxx)
Cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())
Cluster.Consistency = gocql.LocalOne
Cluster.Port = xxxx
Cluster.Authenticator = &gocql.PasswordAuthenticator{xxxx, xxxx}
Cluster.Timeout = 500ms
session := Cluster.CreateSession()

and the test query:

select \* from categories_stress_test where key = ?;

Any ideas?

Regars.

**Comment by aquadrini** [comment]
Same issue here. Java driver is up to 5x faster, specially on reads. Our configuration is very similar to the  posted one.

**Comment by Zariel** [comment]
Thanks for the report, can you provide more information, namely

- Go version
- Client CPUs
- PProf svg if possible (cpu)

I would generally expect the Java driver to perform better due to the JVM and some other things.

**Comment by Zariel** [comment]
Setting GOGC to 800 gets me around 35% faster on my laptop, this is Go 1.6rc2

```
benchmark                       old ns/op     new ns/op     delta
BenchmarkSession_ReadPerf       470409        306853        -34.77%
BenchmarkSession_ReadPerf-2     287421        184061        -35.96%
BenchmarkSession_ReadPerf-4     263384        175334        -33.43%
```

**Comment by aquadrini** [comment]
I'm using Go 1.5.2, running Ubuntu 12.04 on a quad-core / 4GB virtual machine.

**Comment by Zariel** [comment]
@materespana can you run with `GODEBUG=gctrace=1`? Without any information like a pprof I cant really help, you will have to profile and figure out what is slow.

**Comment by Zariel** [comment]
Ive not confirmed but this is probably due to the TokenAwarePolicy, ill need to write a new benchmark to check that vs the RoundRobbin. Though performance should increase since #643

**Comment by Zariel** [comment]
@materespana can you try using protocol 4 and see if you see the same issue on master?
