### ISSUE TITLE
Default DiscoveryConfig settings leads to automatically trying to connect to all datacenters

### ISSUE THREAD

**Issue by robmccoll** [gocql/gocql#641]
Any chance the default could instead be changed to filter to the DC of the initial host list? The behavior of trying to connect across all DCs by default is a bit surprising.

**Comment by martin-sucha** [comment]
We now have a section in documentation that recommends using TokenAware host selection policy: https://pkg.go.dev/github.com/gocql/gocql#hdr-Data_center_awareness_and_query_routing I think that describes how to setup the client in sufficient detail.

We probably can't change the default as that would be a backward-compatibility breaking change. Please reopen if you think we should add something to the docs.
