### ISSUE TITLE
run Cassandra 3.x in CI

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#645]

**Comment by hgfischer** [comment]
Hi, I was just curious about what's the problem with Java 8 on Travis that is stopping you. I just found this: https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/

So in theory you just have to add this to your definition file:

```
jdk:
  - oraclejdk8
```

Isn't it enough?

**Comment by penberg** [comment]
@hgfischer AFAICT, that should be sufficient.

**Comment by Zariel** [comment]
AFAIK the `jdk` setting is only applied when language is java, though I think we now get Java 8 when running in the Trusty environment, and I think we have sudo so we can install all the packages again.
