### ISSUE TITLE
No available streams error after upgrading gocql

### ISSUE THREAD

**Issue by muirrn** [gocql/gocql#658]
We are running c\* 2.0.X so we only have 128 streams per connection. When all streams are in use, it looks like the old behavior was to block waiting for a new stream. The new behavior (via IDGenerator) is to return ErrNoStreams. One of our services makes a lot of queries very quickly (easily in the thousands). After upgrading gocql, the service gets an ErrNoStreams once it's kicked off 128 queries.

I think gocql should wait up to config.Timeout for an available stream rather than returning an error immediately. I don't see how my application can efficiently handle the exhausted streams situation since the only option as I see it is to retry queries in a busy CPU loop as long as you keep getting ErrNoStreams.

I looked at fixing this myself, but it seemed like introducing a channel into the IDGenerator would be prone to leaking goroutines or leaking streams, depending on how you implemented it. With some guidance, I would be happy to implement the solution.

As a side-note, we want to upgrade to 2.1.X (and get the 32K streams, which would probably alleviate this issue), but that might not be able to happen for some time.

**Comment by Zariel** [comment]
This is more likely the query execution is not trying hard enough to get a connection with streams available. There should be `NumConns * NumHosts * (127 - 1)` streams available to the application, which should be lots even on proto2. Is this easily reproducible?

**Comment by muirrn** [comment]
Yes, it happens every time I run my test program against our production ring. I will see if I can make a test case to reproduce it.

Trying different connections/different hosts would certainly improve things, but I still think it should block waiting for a stream if it can't get one. If you have a 3 node ring with the default 2 connections per-host, you have ~768 streams total which is still easily exhaustible, even if the query code is smarter and looks across connections for available streams.

**Comment by muirrn** [comment]
Here is a test case:

```
func TestProtocolV2StreamExhaustion(t *testing.T) {
	cluster := createCluster()
	cluster.ProtoVersion = 2

	session := createSessionFromCluster(cluster, t)
	defer session.Close()

	if err := createTable(session, "CREATE TABLE gocql_test.test_stream_exhaustion (id int, data text, PRIMARY KEY (id))"); err != nil {
		t.Fatalf("failed to create test_stream_exhaustion with err: %v", err)
	}

	query := session.Query("INSERT INTO test_stream_exhaustion (id, data) VALUES (?,?)", 351, "Calliphora-piously")
	if err := query.Exec(); err != nil {
		t.Fatalf("failed to insert with err: %v", err)
	}

	var wg sync.WaitGroup

	for i := 0; i < 1000; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()

			query := session.Query("SELECT data FROM test_stream_exhaustion WHERE id = ?", 351)
			if err := query.Scan(nil); err != nil {
				t.Error(err)
			}

		}()
	}

	wg.Wait()
}
```

Here is a diff I used to "fix" the problem and make the test pass (just to validate my test case, not a suggested fix). The round robin host selector returns nil if all the streams are exhausted, so I had to change to to pick a random conn in that case, so the change to keep retrying GetStream() would actually happen.

```
diff --git a/conn.go b/conn.go
index 5f40f78..56a47b3 100644
--- a/conn.go
+++ b/conn.go
@@ -504,10 +504,13 @@ var (

 func (c *Conn) exec(req frameWriter, tracer Tracer) (*framer, error) {
        // TODO: move tracer onto conn
-   stream, ok := c.streams.GetStream()
-   if !ok {
-           fmt.Println(c.streams)
-           return nil, ErrNoStreams
+ var (
+         stream int
+         ok     bool
+ )
+
+ for !ok {
+         stream, ok = c.streams.GetStream()
        }

        // resp is basically a waiting semaphore protecting the framer
diff --git a/policies.go b/policies.go
index 2d2ba26..d1922d8 100644
--- a/policies.go
+++ b/policies.go
@@ -7,6 +7,7 @@ package gocql
 import (
        "fmt"
        "log"
+ "math/rand"
        "sync"
        "sync/atomic"

@@ -545,5 +546,5 @@ func (r *roundRobinConnPolicy) Pick(qry *Query) *Conn {
                }
        }

-   return nil
+ return r.conns[rand.Intn(len(r.conns))]
 }
```

**Comment by muirrn** [comment]
Any comments? Would you be amenable to a PR similar to my patch above but with proper timeout handling and not using a busy loop to wait for an available stream?

**Comment by Zariel** [comment]
I would rather fix the underlying issue, I also dont think that waiting on a single conn is a good idea, the RoundRobbin pool could have a sync.Cond and wait for any conn to have a stream available, though that would be racy. Im not sure what a good solution to this is.

**Comment by muirrn** [comment]
What are you referring to as the "underlying issue"?

The available stream logic in the round robin conn selector is nice, but it's doing more stuff than the name "round robin" suggests. It seems like unexpected behavior that the "simple" round robin conn selector returns nil when there are in fact "up" conns. We could separate the available streams logic into a separate conn policy. We could make that conn policy wait for, and actually allocate the next available stream, thereby removing the race condition between waiting for a stream and claiming it. This "available stream" conn policy could take a secondary conn policy that it uses to pick a conn when multiple conns have available streams (e.g. could use round robin conn selection if multiple conns have available streams).

**Comment by muirrn** [comment]
Do you have any comments on my PR?

**Comment by Zariel** [comment]
Is this improved by #707 ?

**Comment by muirmanders** [comment]
#707 did improve things, but obviously you can still use up all your streams pretty easily with v2. We are upgrading our ring so we can probably just close this PR and not worry about it.
