### ISSUE TITLE
Error reporting broken in batches

### ISSUE THREAD

**Issue by shore** [gocql/gocql#662]
When cassandra returns an error for a query inside a batch, `executeBatch()` returns `&Iter{...}` that has err set to `nil`, even though the error message is available in the frame.  If the same queries are executed without a batch, an error is returned as expected for the query that is broken.

We discovered this when attempting to insert `nil` as cassandra type `inet`.  No error was reported, but the batch was not applied.

See https://github.com/gocql/gocql/blob/master/conn.go#L978 for the specific switch case.  Note that at this point in the code, err is known to be nil, as it hasn't been modified since the last check for it being nil at https://github.com/gocql/gocql/blob/master/conn.go#L948.  For the error case, it would be helpful to extract the error and stuff it into the error object before returning the iterator, thus allowing the error to be discovered when `iter.Close()` is called.

**Comment by Zariel** [comment]
Thanks for the report, filed a fix at #663

**Comment by shore** [comment]
fixes my test case.  close issue.
