### ISSUE TITLE
Handling ErrNoConnections

### ISSUE THREAD

**Issue by awdrius** [gocql/gocql#668]
Hi, I have multiple dockerized services running that push data to a certain cassandra tables. One of the instances tartes spouting tons of ErrNoConnections messages ("session has been closed") on a simple Query().Exec() call. Now I looked at where these errors could originate in a source code and it looks like it means that connection pool is exhausted (that is my interpretation).

The question is - how would one expect to handle such an error? Does it actually mean that connection to cassandra cluster is lost and one should recreate it?

**Comment by Zariel** [comment]
`session has been closed` error should only be thrown after `session.Close` has been called, `ErrNoConnections` comes from the connection pool not having any hosts which are `UP` to query.

**Comment by awdrius** [comment]
Thanks for clarifying it @Zariel 

So ultimately in my case I need to exit the process as it looks like live node detection did not work properly. 

Just to recap - I had 4 instances of the same binary executing INSERT queries against same cassandra cluster (3 nodes). 3 of the 4 running instances had no issues but 1 was returning ErrNoConnections. I'll try tracking it in case it happens again for a more specific repro steps if possible.

**Comment by Zariel** [comment]
That sounds like an issue, you can build with `gocql_debug` to debug events that are received.

**Comment by awdrius** [comment]
Oh, good to know I will try that and re-open this ticket with more details (if I get any). Thanks!
