### ISSUE TITLE
Marshal Varchar not parsing strings

### ISSUE THREAD

**Issue by dojodominator** [gocql/gocql#670]
It is possible to get a single quote into the marshal varchar function, which is then passed to cassandra. This causes the insert to not work as expected, and probably opens applications up to a sql injection style attack.
https://github.com/gocql/gocql/blob/master/marshal.go#L184

**Comment by dojodominator** [comment]
I have an update to this.  As it turns out, if the ' (single curved quote) character is encoded as the Windows-1252 character 145, which is outside of ascii, it causes the query to fail.

**Comment by Zariel** [comment]
what do you mean by 'not work as expected'? The queries are prepared before executing, and Cassandra should reject invalid queries not the driver.

**Comment by Zariel** [comment]
Strings are also defined as being utf-8 https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L904

**Comment by dojodominator** [comment]
Ah.  I missed that when reading through.  Thanks.  I had originally thought the issue was with strings not being properly escaped, but I was mistaken.
