### ISSUE TITLE
gocql does not seem to handle null values for collections types

### ISSUE THREAD

**Issue by IvanMalison** [gocql/gocql#673]
http://docs.datastax.com/en/drivers/java/2.2/com/datastax/driver/core/TypeCodec.html
 suggests that 
```
TypeCodec implementations should interpret null values and empty ByteBuffers (i.e. Buffer.remaining() == 0) in a reasonable way; usually, NULL CQL values should map to null references, but exceptions exist; e.g. for varchar types, a NULL CQL value maps to a null reference, whereas an empty buffer maps to an empty String. For collection types, it is also admitted that NULL CQL values map to empty Java collections instead of null references. In any case, the codec's behavior in respect to null values and empty ByteBuffers should be clearly documented.
```
but it seems that gocql does not handle correctly:
https://github.com/gocql/gocql/blob/1d518f410a870af312d2de5ac4fb49b3b08eba97/marshal.go#L953

Is there a reason for this?

**Comment by Zariel** [comment]
The framing protocol is what defines how to encode the types to and from Cassandra, which is located and the relevant part here https://github.com/apache/cassandra/blob/be20457c0d2583ea9e81a3000e9709aa6151d09c/doc/native_protocol_v4.spec#L813

The values are encoded as [bytes] which is an int n followed by n bytes, a negative value here for n indicates that the value is null in Cassandra, which will be handled. A collection of zero length will be encoded with a short m followed by that many values which are [bytes] again.

**Comment by IvanMalison** [comment]
But if I understand this correctly, there is also a concept of an empty value

```
For legacy compatibility reasons, note that most non-string types support "empty" values (i.e. a value with zero length).  An empty value is distinct from NULL, which is encoded with a negative length.
```

**Comment by IvanMalison** [comment]
From the doc that you linked
> For legacy compatibility reasons, note that most non-string types support
  "empty" values (i.e. a value with zero length).  An empty value is distinct
  from NULL, which is encoded with a negative length.

This ought to be handled

**Comment by Zariel** [comment]
Do you have an example that shows the erroneous behaviour? The marshaller checks that collections are empty or nil, the tests cover nil and empty collections, https://github.com/gocql/gocql/blob/733b8bc2648778c6f3f3aad3cc576ba9ad28eec8/marshal_test.go#L966

Also the framer handles [byte] with -1 length and returns a nil byte slice, https://github.com/gocql/gocql/blob/733b8bc2648778c6f3f3aad3cc576ba9ad28eec8/frame.go#L1554

**Comment by IvanMalison** [comment]
This happens with collections inside UDT types. gocql handles empty (as in containing 0 values) and nil correctly, but it does not handle values that were never present which will be returned a empty data buffers. It seems like this is something that can happen for legacy reasons.

All you need to do to replicate the issue is to insert a udt with a collection value with a nil value for the collection and then attempt to read it.

**Comment by Zariel** [comment]
Thanks for the report
