### ISSUE TITLE
Printing ffffffffffffffff under high concurrency

### ISSUE THREAD

**Issue by dax0** [gocql/gocql#674]
I'm seeing this weird issue where my log is printing ffffffffffffffff ffffffffffffffff if I write with high concurrency to Cassandra.  This is fixed by making NumConn incredibly high so I have a feeling it has something to do with the 128 concurrency queries per connection.  

Any ideas?

**Comment by Zariel** [comment]
Where is that log coming from?

**Comment by jbdeboer** [comment]
I see these log messages as well. As far as I can tell, they aren't affecting my application, though.

**Comment by dax0** [comment]
It's hard to tell where it comes from, it seems like a rogue fmt statement
somewhere

**Comment by Zariel** [comment]
they will be coming from https://github.com/gocql/gocql/blob/1e7d626b6238141ec0da7f6c4891276016e87704/conn.go#L512 will remove

**Comment by Zariel** [comment]
fixed in master, thanks very much!
