### ISSUE TITLE
Cannot create cluster/get host info with cassandra 1.2.8

### ISSUE THREAD

**Issue by Kimbsen** [gocql/gocql#675]
My app is trying to connect to a cassandra 1.2.8 cluster using go 1.6
and connects as follows. `hosts...` is 2 hosts, but there are 14 in the cluster

```
cluster := gocql.NewCluster(hosts...)
cluster.ProtoVersion = 1
cluster.CQLVersion = "3.0.0"
cluster.Keyspace = "keyspace"
session, err := cluster.CreateSession()
if err != nil {
    return nil, err
}
```

But i consistently get the following from err

`gocql: table: unable to fetch host info for ip: gocql: not enough columns to scan into: have 5 want 0`

Is 1.2.8 no longer supported? Or is there some workaround i can try.

**Comment by Zariel** [comment]
While not tested as part of the integration suite 1.2 should work, what is the schema for system.peers/system.local on 1.2?

**Comment by Eriken** [comment]
This is still an issue for us;
This snapshot works however:
https://github.com/Eriken/gocql-snapshot

I am unsure what commit this is.

**Comment by martin-sucha** [comment]
Cassandra 1.x is end-of-life now, closing.
