### ISSUE TITLE
Add net/context support

### ISSUE THREAD

**Issue by eandre** [gocql/gocql#676]
I often find myself writing code similar to this:

```go
	errc := make(chan error, 1)
	go func() {
		err := s.sess.Query("some query").Exec()
		errc <- err
	}()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-errc:
		return err
	}
```
or this:
```go
	type result struct {
		err     error
		present bool
	}
	rc := make(chan result, 1)
	go func() {
		var id string
		err := s.sess.Query("some query").Scan(&id)
		if err == gocql.ErrNotFound {
			rc <- result{present: false}
		} else if err != nil {
			rc <- result{err: err}
		} else {
			rc <- result{present: true}
		}
	}()

	select {
	case <-ctx.Done():
		return false, ctx.Err()
	case res := <-rc:
		return res.present, res.err
	}
```

It would be really useful if gocql supported use of `net/context` out of the box. There are a few ways one could possibly do this, each with their own advantages:
- Adding a `QueryCtx(ctx context.Context, stmt string, args ...interface{}) *Query` method to `Session`, that binds the context to the returned query.
- Adding a `BindCtx(ctx context.Context)` method to `Query`.
- Adding an overload for each method on `Query` that actually executes the query, that takes a `context.Context parameter`.

Would this be a useful addition? I would be happy to write the PR to accomplish any of these.

**Comment by Zariel** [comment]
This would be interesting. At what part of the driver would the Context be used in? What cases does it need to handle to integrate with net/context?

**Comment by eandre** [comment]
I am not 100% sure if I understand your questions. I have tried to answer them below, but let me know if you have more questions.

I am not sure where in the gocql driver this would internally be integrated. It would be nice if gocql could also notify Cassandra to cancel the query execution, but that is a nice-to-have. gocql could perhaps also use the cancellation to clean up its internal resources, but I am not sure to what degree that is possible, since I haven't investigated the source code very thoroughly.

As far as what to integrate with from net/context, the primary use case I have found so far is to provide cancellation (as demonstrated above). When the context is cancelled due to timeout or explicit cancellation, the `Query` would internally detect this by selecting on the `ctx.Done()` channel and return `ctx.Err()` immediately. This would make the code I wrote above much simpler and would require less boilerplate.

**Comment by eandre** [comment]
Gentle ping. :)

**Comment by eandre** [comment]
That's perfect, thank you for implementing it.

**Comment by Zariel** [comment]
No problem, it looks pretty useful
