### ISSUE TITLE
Iter() on SELECT * only returns one value?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#677]
Specs:
```
[cqlsh 5.0.1 | Cassandra 2.2.2 | CQL spec 3.3.1 | Native protocol v4]
go version go1.6 darwin/amd64
github.com/gocql/gocql master branch
```

My query is very simple: `SELECT * FROM tokens`, and I have 3 tokens.

The code is equally simple:
```
session, err := cass.CreateSession()
rowValues := make(map[string]interface{})

query := "SELECT * from tokens"
iter := session.Query(query).Iter()
for iter.MapScan(rowValues) {
    // Loop only happens once returning the first value.
}
```

Meanwhile, `cqlsh` returns all 3 values correctly.
```
cqlsh:pepper> select * from tokens;

 id                               | enabled
----------------------------------+---------
 holzNPrrK3BZDxGfOSP3yPjQaf-qYsux |    True
 59hODh3LrlEwLApV62TaipkcKHMM9eE6 |    True
 6osUzh5L-YAVYSI9Bg6Y8WT31taviyFs |    True

(3 rows)
```

This is my table schema, nothing fancy:
```
CREATE TABLE pepper.tokens (
    id text PRIMARY KEY,
    enabled boolean
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX tokens_enabled_idx ON pepper.tokens (enabled);
```

I must have missed something obvious here.

**Comment by bgreezy** [comment]
Have you considered using something like `for iter.Scan(&id,&enabled) {fmt.PrintLn(id,enabled)}` to see if  the results can be pulled from the database with a different function call? I have never used `iter.MapScan()` but it seems like it should work the way you have it called. I would double check that you can get them out using the regular scan. You could always add them to the map afterwards.

**Comment by didip** [comment]
@bgreezy Yes, mapping the scan to individual variable works as expected.
For now, that's the solution that works for me, I changed all `MapScan()` to regular `Scan()`.
I am starting to think that this is a bug on `MapScan()`.

**Comment by bgreezy** [comment]
I found an example in the gocql test directories. Try `session.Query(query).MapScan(rowValues)` Currently you are calling MapScan on the `Iter` object. The example of use on the Query object is in tuple_test.go

**Comment by kzcabstone** [comment]
@didip Not sure if you have solved this but answer seems to be here:
m := &map[string]interface{}{}
	for iter.MapScan(*m) {
		ret = append(ret, *m)
		m = &map[string]interface{}{}
	}
This worked for me and returned all rows.

**Comment by didip** [comment]
Interesting, so user have to re-initialize the map again.

For now, I am actually more satisfied with scanning individual variables because they are easy to spot in the code base.

I will give this a try again when I have the chance.

If you guys don't mind, I will close this ticket now.

**Comment by PhilipUa** [comment]
Use session.Query(query).Iter().SliceMap()
