### ISSUE TITLE
api: provide Next() bool / Scan() error methods instead of Scan() bool

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#681]
The current API uses Scan to to indicate that another row is available, and defers handling of scan errors the call of Close(), which is not always obvious. It also means that it is impossible to ignore unmarshalling errors during iteration.

This leads to things like #659

But I dont want to change the query api for fun.

Thoughts?

**Comment by nemothekid** [comment]
Why would you want to ignore unmarshalling errors? How often does that come up?

IMO, you would need a really good and widespread reason to change the API
