### ISSUE TITLE
FatalF from hailocab/go-hostpool X not in HostPool [ X X]

### ISSUE THREAD

**Issue by ekle** [gocql/gocql#686]
today i got a FatalF which stop my service: 
```host 172.10.210.14 not in HostPool [172.10.110.2 172.10.110.19]```
i'm using    1e7d626 
hostpool is e80d13c

gocql or it dependencies should never stop a go software.

**Comment by Zariel** [comment]
If there is an issue in the Gocql driver we can fix that, for issues in other projects please open tickets against those projects.

**Comment by ekle** [comment]
go-hostpool throws a Fatal error if a host is accessed which does not exist.
therefor i think gocql is making an invalid call.

**Comment by ekle** [comment]
i have this bug a few time a day now

**Comment by smira** [comment]
@ekle see also my PR: https://github.com/hailocab/go-hostpool/pull/4

I've stopped using hostpool in gocql for this reason

**Comment by Zariel** [comment]
The PR looks good, I had a look through the code and couldnt see anything obvious that would cause us to set at a host list which we dont have.

**Comment by smira** [comment]
@Zariel I believe it happened during discovery (with older gocql which was polling from `system.peers`) when host was going up (or probably down). `gocql` was reporting node healthy status before node got into hostpool. Something around this sequence of events. I don't have details unfortunately.

**Comment by ekle** [comment]
@smira what are you using instead of hostpool ?

**Comment by Zariel** [comment]
@ekle looking at the code the following can happen.
```
hostR := pick a host
// use hostR
// event, node for hostR is down
removeHostR from pools and policies
// query returns, make host as good/bad
hostR.mark(...)
// log.Fatalf
```

We can probably fix this our side

**Comment by Zariel** [comment]
@ekle @smira I have marked #689 to not close this issue, can you test that it does fix the issue you see?

**Comment by smira** [comment]
@Zariel I think `panic` is better than silently aborting process, but still something not acceptable in general.

**Comment by smira** [comment]
@ekle I'm using:

```
	clusterCfg.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())
```

**Comment by Zariel** [comment]
@ekle @smira is this fixed since #689?

**Comment by smira** [comment]
@Zariel thanks! I will schedule a test for it, but it would take some time on my side

**Comment by ekle** [comment]
looks like it is fixed. i didn't have this error anymore over the long weekend.

**Comment by Zariel** [comment]
Thanks for the report!

**Comment by smira** [comment]
I also did a test in the lab for several days, no problems so far.  Thanks @Zariel
