### ISSUE TITLE
Basic tutorial for gocql

### ISSUE THREAD

**Issue by tux21b** [gocql/gocql#69]
This issue is there to track topics that should be covered by a small tutorial, since they seem to cause confusion regularly:
- cluster setup (with code snippets for Cassandra 1.2 and 2.0)
- `Exec()` and `Scan()`
- iterating over columns
- iterating over columns in batches (Cassandra 2.0 only)
- dynamic columns (i.e. usage of `iter.Columns()`)
- Batches in Cassandra 1.2 (`Exec()` only) and Cassandra 2.0
- Usage of `ScanCAS`
- Usage of the marshal / unmarshal interface

**Comment by Dieterbe** [comment]
yes please :)
