### ISSUE TITLE
Massive timeouts during lightweight transactions.

### ISSUE THREAD

**Issue by mackeyja92** [gocql/gocql#690]
Frequently getting timeouts `Operation timed out - received only 0 responses` when attempting to many many lightweight transactions. My API is built to retry if the lightweight transaction fails because the `if` statement in the CQL is not met. However, I am getting a large amount of `time out`'s when running these. Mostly, in my testing they were fine, but in production it seems to be an issue where only about 1/3rd actually make it in C*. 

How can I fix this? 

Here is my config, mind the syntax might not be correct as I am copying some from our config file and replacing parsed variables, but this is essentially what it comes out to. 

	clusterConfiguration = &gocql.ClusterConfig{
		Hosts:                  ["10.10.85.11", "10.10.85.12", "10.10.85.13", "10.10.85.206", "10.10.87.21", "10.10.87.54"],
		CQLVersion:             "3.0.0",
		ProtoVersion:           2,
		Timeout:                10000 * time.Millisecond,
		Port:                   9042,
		NumConns:               2,
		Consistency:            gocql.ParseConsistency("LOCAL_QUORUM"),
		MaxPreparedStmts:       1000,
		MaxRoutingKeyInfo:      1000,
		PageSize:               5000,
		DefaultTimestamp:       true,
		MaxWaitSchemaAgreement: 60 * time.Second,
	}

Here is an example query

    UPDATE keyspace.table_name SET value = 15785, revision = 17 WHERE field1  = 'demo' AND date = 1458457200 AND field1  = 'demo_2' AND field3  = 'demo_3' AND field4  = 'demo_4' IF revision = 16

**Comment by Zariel** [comment]
Does your cluster span multiple DCs? By default the write for LWT will be done with Serial, try changing `SerialConsistency` on the query, ive never seen LWT's be that slow though.

**Comment by mackeyja92** [comment]
We are currently replacing our cluster with a new, higher performance, DC. However, it isn't ready yet so it is just sitting on the side lines. That is why I wanted everything set to LOCAL_QUORUM as this new DC is currently in a non-production ready state. I can change the query to be a LOCAL_SERIAL though, if that would help. 

Could host discovery be an issue here?

**Comment by Zariel** [comment]
It shouldn't be, a LWT does a Paxos transaction for all nodes which own the data, by default the consistency is Serial, which will do it for every node in each datacentre which is a replica for the key being updated, so this could cause it to be slow. Using LocalSerial will only do the transaction in a single datacentre

**Comment by mackeyja92** [comment]
Ok, we are phasing out the old DC this weekend so I will update next week and see if the issue has been resolved.

**Comment by mackeyja92** [comment]
Ok, I have migrated to the new DC and decommissioned the old DC. I am still experiencing this error but less frequently. Do you have any guidance on what else I can attempt to resolve this?

**Comment by Zariel** [comment]
For this you probably need to look at some monitoring in Cassandra, I doubt its the driver causing the timeouts. Are the keys well distributed or are many nodes concurrently updating the same key?

**Comment by mackeyja92** [comment]
The keys are well distributed. I am worried that the driver is returning a timeout before we actually hit the timeout duration. It is happening almost instantaneously but the timeout is set to 10 seconds.

**Comment by mackeyja92** [comment]
@Zariel, could you provide more insights on why it would be happening before the timeout period of 10 seconds? 

Is there more information I can give you that would be helpful in tracking this down? This is a growing problem for us and need to track down the root cause.

**Comment by Zariel** [comment]
I don't think the driver is doing anything odd which would cause timeouts,
the timeout error is more likely an internal Cassandra error. If you print
the error out with #+v you should see the code and error.

**Comment by mackeyja92** [comment]
Ok. I will leave this ticket open until I find a positive resolution though, if that is ok. 

I am currently testing different protocol versions to see if that will make a difference. Previously, and I don't know why, but we were using protocol version 2. I have upgraded the API to use use version 4 and moved to CQL 3.3 instead of 3.0. Testing both of those changes together today.

**Comment by mackeyja92** [comment]
I was able to fix the issue by setting the `SerialConsistency` on the `ClusterConfig` to `LocalSerial`. However, the issue returns when setting it back to `Serial`. We only have one DC now so they should essentially be the same. Would you still agree with your earlier assumptions that it is a configuration issue with our C* cluster?

**Comment by mackeyja92** [comment]
Switching to `ScanCAS` instead of using `Execute` seems to resolve this issue. Maybe provide better docs on which to use when? Beginner mistake. Thanks.

**Comment by zachbadgett** [comment]
Is there an explanation on why switching to ScanCAS fixes this problem? Exec and ScanCAS should do the same thing; both call `q.Iter()`.

**Comment by Zariel** [comment]
The CAS methods extract the first boolean param from the response which indicates applied, you could do it with Scan and pass in the boolean yourself

**Comment by zachbadgett** [comment]
Why did it fix his timeout problem?
