### ISSUE TITLE
gocql: connection closed waiting for response

### ISSUE THREAD

**Issue by derailed** [gocql/gocql#699]
Running into some issues with gocql 

Driver rev: 1st_gen_framing-383-g87cc185 -- 87cc1854b57c7a4d8f4ae1d0cc358ed6ecb0f8c3
Go: 1.5.1

I have a cassandra 2.1.13 cluster with 2 nodes and a reading rest api. When using ab perf with concurrency set to one all is peachy. However once I bump concurrency to 2 or more, I start seeing a few errors on my runs with gocql: connection closed waiting for response.
I do close the session after every request in a defer func. 

Any ideas if anyone ran into this issue before or things I can try out?

Thanks!

**Comment by derailed** [comment]
Did find another interesting tid bit. In the original scenario I pass into the ClusterConfig hosts [c1:p1,c2:p2,c3:p3] but if I switch to a load balancer and pass hosts = [lb:p1] instead my ab perf with concurrency test works. So thinking there might be an issue with letting the driver determine the host connection??

**Comment by Zariel** [comment]
The session is intended to live for the life of the application, creating a session is a relatively expensive operation, closing the session will close all open connections. The error you see is that one goroutine is executing a query and waiting for a response, another finishes and closes the session which closes the connection, cancelling the query.

**Comment by derailed** [comment]
Thanks for the clarification Chris! This somewhat explains what I am
experiencing but does not explain switching to using a load balancer as
besides the hosts config the code was the same. In my use case the
cassandra cluster will grow and shrink dynamically based on loads, hence
clients need to be aware and thought closing the session was a way to deal
with this requirement as on subsequent calls the cassandra cluster may look
differently ie h1,h2 -> h1,h2,h3 or even h1,h4,h5, h6. What is the best way
to deal with this scenario in gocql?

**Comment by Zariel** [comment]
gocql will listen for node events to indicate the nodes are joining/leaving the cluster and automatically add them to the pools

**Comment by derailed** [comment]
cool - does one need to configure it or it this behavior on by default?

**Comment by Zariel** [comment]
this is the default config
