### ISSUE TITLE
Scan()ning a time.Time value in a loop results in unexpected behavior

### ISSUE THREAD

**Issue by jtbandes** [gocql/gocql#704]
A change was made in #258 so that `unmarshalTimestamp` would no longer change the target variable's value if the timestamp received from Cassandra was null.

However, this encourages the following usage pattern:

``` go
var s string
var t time.Time
for iter.Scan(&s, &t) {
  // BAD: if the time column value was null,
  // then `t` still has the value from the *previous* row!
}
```

I'd like to recommend changing this, or people are going to accidentally write buggy code. Possible solutions:
- Revert to the old behavior (which, reading #258, sounds like it was epoch time 0, a.k.a. `1970-01-01 00:00:00`)
- Write `time.Time{}` to the variable (a.k.a. `0001-01-01 00:00:00`) so that it can be checked with `t.IsZero()`
- Simply don't support reading directly into `time.Time` variables. If `*time.Time` were used instead, then a `nil` value could be represented natively.

**Comment by Zariel** [comment]
the behaviour should be to set the value to empty if it is empty in Cassandra

**Comment by jtbandes** [comment]
The question is, what does "empty" mean for `time.Time`?

**Comment by Zariel** [comment]
empty for a value type would be `time.Time{}`

**Comment by Zariel** [comment]
This is another reason why I think #681 would be a better API

**Comment by nathj07** [comment]
I've just hit this bug while running unit tests - thankfully it was unit tests. This is really unexpected behaviour.

I would vote for 
> Write time.Time{} to the variable (a.k.a. 0001-01-01 00:00:00) so that it can be checked with t.IsZero()
As the solution. That to me makes the most sense. Is there any update on this issue? Anyone else have any further thoughts on it?
