### ISSUE TITLE
Gopkg Support

### ISSUE THREAD

**Issue by skeswa** [gocql/gocql#705]
I was surprised to discover that this repository has no Semver compliant version tags on it. I was wondering if that could be arranged.

**Comment by Ganners** [comment]
This would be useful, particularly as https://github.com/gocql/gocql/commit/f859eab0b61553a2f3f5aae1043da09755c9e37c breaks some of our legacy builds.

**Comment by skeswa** [comment]
I 100% agree. Especially given that using a real versioning scheme will
provide more information to users on how impactful any given change is.

**Comment by martin-sucha** [comment]
Closing in favor of #977
