### ISSUE TITLE
Unable to run go get github.com/gocql/gocql

### ISSUE THREAD

**Issue by subbu05** [gocql/gocql#711]
I don't see anything downloaded or process runs indefinitely.
Unable to get dependencies fot GOCQL

OS - Centos 6.6 64bit
golang 1.4
GOPATH and GOBIN are set correctly.

**Comment by Zariel** [comment]
try running with `-v`

**Comment by subbu05** [comment]
Same issue.
I don't see anything on the terminal.

**Comment by Zariel** [comment]
this works fine for me
