### ISSUE TITLE
"panic: runtime error: slice bounds out of range" when create session

### ISSUE THREAD

**Issue by chenziliang** [gocql/gocql#721]
Env is Cassandra 3.5, standalone, gocql is latest master build.

>[root@pvg-ta-super test]# cat test_gocql.go 
package main

>import (
	"github.com/gocql/gocql"
)

>func main() {
	// connect to the cluster
	cluster := gocql.NewCluster("super")
	cluster.Keyspace = "demo"
	session, _ := cluster.CreateSession()
        defer session.Close()
}`

Panic trace
>[root@super test]# go run test_gocql.go 
panic: runtime error: slice bounds out of range

>goroutine 24 [running]:
panic(0x6f2020, 0xc82000a090)
	/root/ken/go/src/runtime/panic.go:481 +0x3e6
github.com/gocql/gocql.readHeader(0x7f5a6e9d5488, 0xc82007c4e0, 0xc820080c78, 0x8, 0x8, 0x0, 0x0, 0xffffffffffffff00, 0x0, 0x0, ...)
	/root/ken/gocode/src/github.com/gocql/gocql/frame.go:358 +0x773
github.com/gocql/gocql.(*Conn).recv(0xc8200d4000, 0x0, 0x0)
	/root/ken/gocode/src/github.com/gocql/gocql/conn.go:448 +0x118
github.com/gocql/gocql.Connect.func1(0xc82007c600, 0xc8200d4000, 0xc82007c660, 0x7f5a6e9d6720, 0xc820083b00)
	/root/ken/gocode/src/github.com/gocql/gocql/conn.go:220 +0x71
created by github.com/gocql/gocql.Connect
	/root/ken/gocode/src/github.com/gocql/gocql/conn.go:230 +0x8d5
exit status 2`

**Comment by Zariel** [comment]
Thanks very much for the report!

**Comment by chenziliang** [comment]
Super. Thanks Zariel for the quick fix.
