### ISSUE TITLE
SetPartitioner never called on the HostSelectionPolicy

### ISSUE THREAD

**Issue by jncorpron** [gocql/gocql#724]
Looks like the call to SetPartitioner on the HostSelectionPolicy was lost in commit a04d2a5e3f4076edc106347f1624809c0733a1a1. The tokenAwareHostPolicy needs SetPartitioner to be called before it will be effective.

**Comment by Zariel** [comment]
The partitiononer is now maintained globally for sessions on the clusterMetadata, https://github.com/gocql/gocql/blob/master/ring.go#L100
