### ISSUE TITLE
Unsupported Protocol

### ISSUE THREAD

**Issue by mvbaffa** [gocql/gocql#729]
Hi,

I am trying to dial to a cassandra 3.2 server. I am receiving the error:
gocql: unable to dial control conn 10.152.20.212:9042: gocql: error on stream 0: Invalid or unsupported protocol version (2); the lowest supported version is 3 and the greatest is 4

How can I solve it

Thanks

**Comment by Zariel** [comment]
Update the config to use protocol 3 or 4

**Comment by mvbaffa** [comment]
Sorry but where is the config and what is the key.

Thanks

**Comment by Zariel** [comment]
https://github.com/gocql/gocql/blob/6c910921faab44389a426721cf57599fcd0a10d5/cluster.go#L53
