### ISSUE TITLE
Support for CQL 3.3 smallint and tinyint types

### ISSUE THREAD

**Issue by brtn** [gocql/gocql#733]
I want to use new types, especially tinyint and shortint, but they are not implemented in gocql at the moment AFAIK. Is there anybody working on this?

**Comment by Zariel** [comment]
The driver should nativly be able to handle reading and writing of tinyint and shortints

**Comment by brtn** [comment]
Wow, that was quick :) I also started to do this but you are faster than me, as expected.

Anyway, thank you @Zariel, I will use your work right away.
