### ISSUE TITLE
Improve retry policy

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#735]
Currently the retry policy will just attempt on a new host for each attempt, attempting at most `numberOfHosts` available in the pool.

We should provide an interface which allows more robust query retrying

**Comment by martin-sucha** [comment]
It is not clear what should be done with this issue. Is this related to https://github.com/gocql/gocql/pull/1082 or something else? @Zariel could you please clarify "more robust query retrying"?

**Comment by martin-sucha** [comment]
Closing in favor of #812
