### ISSUE TITLE
Questions about "no hosts available in the pool" error

### ISSUE THREAD

**Issue by mediocregopher** [gocql/gocql#739]
We recently did a rollout of a change across our cluster which necessitated going through each node, decommissioning it, and re-adding it as a new node with a new host ID. After doing that we started receiving `no hosts available in the pool` errors from our processes, and had to restart them. I'm guessing the driver has its internal idea of what the cluster looks like, and as we were dropping nodes out and putting new ones in that idea wasn't being updated.

We're using commit 1440c60 of gocql, which is a bit old, but I didn't see anything in the commit history since which might remedy this. There's a0223bbf, but I believe that wouldn't help here since these are ostensibly new nodes, not existing ones that were being restarted.

So my question is, is this a bug with gocql that it's not getting the new cluster topology? If not, what's the intended course of action for our app? Is there something we can do when we see this error to get it to re-retrieve the topology? Or should we just fatal and start over? Thanks!

**Comment by bkeroackdsc** [comment]
I'm seeing frequent ``no hosts available in the pool`` errors, without changing cluster topology at all. This is with a single-node "cluster".

**Comment by nemothekid** [comment]
@mediocregopher Your issue should be solved by node events (should be available since afd23f4ef235f528decbca56d0f558becdd65012) however I'm not too familiar with that side of the code base to comment. [events.go#174](https://github.com/gocql/gocql/blame/master/events.go#L159) should solve your use case and if its not working its probably a bug.

@bkeroackdsc If this is a single-node cluster, then doesn't that mean your single node is going down?

**Comment by mediocregopher** [comment]
We're definitely using a version which contains the node event logic (we're on 1440c60, which is like 3 months older). Is there anything which I can do to help debug the issue?

**Comment by bkeroackdsc** [comment]
Originally I thought the issue was due to gocql (a few months back I had issues with gocql running out of connections), but now it's looking like it was just instability on my Cassandra node.

**Comment by jsongHBO** [comment]
I have the same problem.  It's a single node cluster.  But I have 5 service nodes connected to Cassandra.  Only 1 service node encountered this issue, and was never able to INSERT again, while the other 4 worked fine.  So it not the cassandra node that has the issue.  BTW... the problematic node could SELECT from cassandra, not INSERT.
