### ISSUE TITLE
multiple memory leaks while host discovery breaks

### ISSUE THREAD

**Issue by balboah** [gocql/gocql#745]
There seem to be mutliple memory leaks triggering when cassandra nodes are terminated and new ones added.
GoCQL seem to still try some old host IPs while different services shows different memory leaks until restarted. Some profiles show these in particular:

Service A
```
      flat  flat%   sum%        cum   cum%
  891.18MB 92.62% 92.62%   891.18MB 92.62%  vendor/github.com/gocql/gocql.(*framer).writeQueryParams
...
vendor/github.com/gocql/gocql.(*Conn).exec

ROUTINE ======================== vendor/github.com/gocql/gocql.(*framer).writeQueryParams in vendor/github.com/gocql/gocql/frame.go
  891.18MB   891.18MB (flat, cum) 92.62% of Total
         .          .   1282:		f.writeShort(uint16(n))
         .          .   1283:		for i := 0; i < n; i++ {
         .          .   1284:			if names {
         .          .   1285:				f.writeString(opts.values[i].name)
         .          .   1286:			}
  885.84MB   885.84MB   1287:			f.writeBytes(opts.values[i].value)
         .          .   1288:		}
         .          .   1289:	}
         .          .   1290:
```

Service B
```
flat  flat%   sum%        cum   cum%
    5.03MB 26.66% 26.66%     5.03MB 26.66%  vendor/github.com/gocql/gocql.readHeader
       5MB 26.51% 53.17%        5MB 26.51%  reflect.Value.call
       4MB 21.21% 74.38%        4MB 21.21%  vendor/github.com/gocql/gocql.UUID.Time
    2.83MB 15.02% 89.40%     4.83MB 25.62%  vendor/github.com/gocql/gocql.(*Conn).releaseStream
       2MB 10.60%   100%        2MB 10.60%  vendor/github.com/gocql/gocql.UUID.Timestamp
         0     0%   100%     5.03MB 26.66%  vendor/github.com/gocql/gocql.(*Conn).authenticateHandshake
         0     0%   100%     9.03MB 47.87%  vendor/github.com/gocql/gocql.(*Conn).recv
         0     0%   100%     8.83MB 46.83%  vendor/github.com/gocql/gocql.(*controlConn).registerEvents
         0     0%   100%     8.83MB 46.83%  vendor/github.com/gocql/gocql.(*hostConnPool).HandleError
         0     0%   100%        4MB 21.21%  vendor/github.com/gocql/gocql.ParseConsistency

ROUTINE ======================== vendor/github.com/gocql/gocql.readHeader in vendor/github.com/gocql/gocql/frame.go
    5.03MB     5.03MB (flat, cum) 26.66% of Total
         .          .    359:     return frameHeader{}, fmt.Errorf("not enough bytes to read header require 9 got: %d", len(p))
         .          .    360:   }
         .          .    361:
         .          .    362:   head.stream = int(int16(p[2])<<8 | int16(p[3]))
         .          .    363:   head.op = frameOp(p[4])
         .          .    364:   head.length = int(readInt(p[5:]))
         .          .    365: } else {
         .          .    366:   if len(p) < 8 {
    5.03MB     5.03MB    367:     return frameHeader{}, fmt.Errorf("not enough bytes to read header require 8 got: %d", len(p))
```

Policy: `gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())`
Githash: 1440c60
Cassandra: 2.1.13

**Comment by balboah** [comment]
Probably related to https://github.com/gocql/gocql/issues/743

**Comment by Zariel** [comment]
What profiles are those? Inuse bytes?

**Comment by balboah** [comment]
Thats collected from `go tool pprof  http://localhost:6060/debug/pprof/heap`

**Comment by balboah** [comment]
The service eventually gets killed by linux due to memory usage when this is triggered

**Comment by Zariel** [comment]
Are there any goroutines that have been blocked for a while in gocql?

**Comment by Zariel** [comment]
I dont understand why there would be so much data in use when calling `writeBytes` as the data is just appended to the buffer, then eventually the buffer is flushed with the call to `finishWrite`. Kind of hard to diagnose.

**Comment by balboah** [comment]
Unfortunately I didn't enable blocked procedures profiling and didn't see anything in particular stacking up when looking at running goroutines. But perhaps the buffer flush never happens when gocql tries to connect to a cassandra that has been terminated? As it seem to be stuck on trying to connect to some non-existent IP according to netstat?

Tried to reproduce as an isolated test but couldn't so far.
Here is my small test if it helps anyone

```
package main

import (
	"flag"
	"testing"
	"time"

	"github.com/gocql/gocql"
)

var host string

func init() {
	flag.StringVar(&host, "host", "localhost:9042", "cassandra host to create cluster from")
	flag.Parse()
}

func session(host string) (*gocql.Session, error) {
	cluster := gocql.NewCluster(host)

	cluster.Consistency = gocql.Quorum
	cluster.Timeout = 30 * time.Second
	cluster.PoolConfig = gocql.PoolConfig{
		HostSelectionPolicy: gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy()),
	}
	cluster.RetryPolicy = &gocql.SimpleRetryPolicy{
		NumRetries: 3,
	}
	cluster.ProtoVersion = 3
	cluster.Compressor = &gocql.SnappyCompressor{}
	cluster.Keyspace = "test"

	return cluster.CreateSession()
}

func BenchmarkSession(b *testing.B) {
	s, err := session(host)
	if err != nil {
		b.Fatal(err)
	}
	s.Query(`CREATE TABLE IF NOT EXISTS foo (
  value uuid,
  PRIMARY KEY(value)
);`).Exec()
	b.ResetTimer()
	b.RunParallel(func(pb *testing.PB) {
		s, err := session(host)
		if err != nil {
			b.Fatal(err)
		}
		for pb.Next() {
			u, err := gocql.RandomUUID()
			if err != nil {
				b.Fatal(err)
			}
			if err := s.Query(
				"INSERT INTO foo (value) VALUES(?)", u,
			).Consistency(gocql.One).Exec(); err != nil {
				b.Fatal(err)
			}
		}
	})
}
```

The idea is to run 3 nodes locally and kill / re-join one of them with new hostname. However I didn't see the similar problem yet

**Comment by Zariel** [comment]
You should be able to see the gorouines in the /debug/pprof/goroutine?debug=2. The the write path is a write of a single byte slice to the connection, which has a deadline if the session has a timeout.

**Comment by marcusking01** [comment]
Is you're profile showing bytes allocated or bytes in use?  I've seen similar issues before with re-using the same buffer over and over and how it needs to allocate new memory when it grows as each time the slice needs to grow it doubles it's memory allocation.  Perhaps using bytes.buffer instead would work as there are operations to clear/shrink the bytes allocated

**Comment by Zariel** [comment]
`bytes.Buffer` uses a byte slice underneath so it would have the same effect. The `framers` should be recycled and reclaimed, if they are not that is a bug, the buffers they contain will stay around while they are used, so under high load I would expect framers to be recycled a lot, which will help reduce memory churn significantly.

I would be interested to see some in use profiles, in high loaded clients I would not be surprised to see a lot of memory in use in framers buffers, it would also be worth checking what amount of data is actually going over the wire as well.

**Comment by balboah** [comment]
I will probably try to reproduce again at some later time (but not high prio as it works as long as Cassandra does). Afaik it's not about getting stressed by being under too much load as the problem is small incremental increase over hours of time. It has been reoccurring when we've replaced / repaired Cassandra nodes with completely new instances (new IP, new id). Just didn't want to happen in my small isolated test outside of production.

and as I noticed the connection attempts to hostnames no longer existing, I'm suspecting that its somehow related to reconnection / pooling / discovery mechanisms

**Comment by balboah** [comment]
@Zariel Could you point me to where exactly framer write buffer is flushed? I don't see it in `finishWrite` as you mentioned

**Comment by balboah** [comment]
I still haven't been able to reproduce, and still far from understanding all the codebase. But a theory from reading the code so far:

Could it be that [query executor](https://github.com/gocql/gocql/blob/master/query_executor.go#L55) returns iterator after retrying a few times (with no error set), where the returned iterator contains the large framer(s), and that
[Iterator close](https://github.com/gocql/gocql/blob/master/session.go#L1113) lets the framer live on in memory by referencing it in this `framerPool`? If so, maybe the fix is to return errors in query executor when it retries?

This problem might then be enhanced because of a broken host discovery (see my earlier mentioning of continous connection attempts to hosts no longer existing) where it would trigger retries a lot.

I will try to verify this theory by triggering this query executor retry code.

**Comment by Zariel** [comment]
`framerPool` is a [sync.Pool](https://golang.org/pkg/sync/#Pool) and is collected at each GC.

**Comment by balboah** [comment]
Still have not been able to reproduce the problem :( I did however run into https://github.com/gocql/gocql/issues/739 every time I try to decommission and cycle all nodes one by one

**Comment by Zariel** [comment]
To debug this it would also be useful to have a list of the running goroutines and their current blocked time which are in gocql

**Comment by balboah** [comment]
I won't have access to the same setup again and were not able to reproduce, closing the issue
