### ISSUE TITLE
3.x Incompatible

### ISSUE THREAD

**Issue by umpc** [gocql/gocql#747]
While running cassandra 3.7.0, I get the following error when attempting to connect:
```
gocql: unable to create session: control: unable to connect to initial hosts: gocql: error on stream 0: Invalid or unsupported protocol version (2); the lowest supported version is 3 and the greatest is 4
```
How I am connecting:
```
cluster := gocql.NewCluster(ClusterAddr0)
cluster.Keyspace = keyspace
cluster.Consistency = gocql.Quorum

session, err := cluster.CreateSession()
```
I understand that the active developers cannot test this, so I will be reverting back to using an earlier version of cassandra. If someone would like more information, let me know.

EDIT: To follow up, the same error message was returned for every 3.x version that I tried, down to 3.1. Though for reference, I only checked odd-numbered versions because they are bugfixes for even-numbered releases.

**Comment by Zariel** [comment]
The error is saying that if does not support protocol 2, instead use
protocol 4

**Comment by harikt** [comment]
@Zariel 

Question from a person watching this repo. Not using, but just exploring for a use case.

> Invalid or unsupported protocol version (2); the lowest supported version is 3 and the greatest is 4

So doesn't it says version 3 and version 4 are supported ? Also I am not familiar with cassandra but wonder whether version 3 is supporting protocol version 3.

**Comment by Zariel** [comment]
Yes, in versions > 2.2.x it is recommended to use protocol 4

**Comment by harikt** [comment]
Thank you @Zariel .

**Comment by umpc** [comment]
I'd guessed that ```(2)``` was an error reference for this type of event because of the parentheses it's enclosed in.

That fixes it. Thank you @Zariel.
