### ISSUE TITLE
Questions about Host selection

### ISSUE THREAD

**Issue by mark-i-m** [gocql/gocql#760]
Hello,

I had questions about gocql's host selection.

I need to run some queries on the `system.local` and `system.peers` in order to get information about the state of the cassandra cluster while doing live schema migrations. I am using gocql to execute the required queries. However, due to cassandra's weak consistency model, I need to be able to use the same node for each query. I was wondering how to do this? I had a few vague notions, but I would appreciate any guidance:
- Some form of batching for read queries?
- Set `DisableInitialHostLookup` on the cluster config and provide only one host?
- Define a new discovery scheme?

Thanks,
Mark

**Comment by nemothekid** [comment]
I would set `DisableInitialHostLookup` and only provide one host. I'm not sure how well tested that path is so I would do a `SELECT hostid,broadcast_address FROM system.local` to make sure everything is working as described.

**Comment by mark-i-m** [comment]
Great!

Thanks for the quick answer :smile:
