### ISSUE TITLE
nil checks for interface types

### ISSUE THREAD

**Issue by robmccoll** [gocql/gocql#762]
There are a few places like this:
https://github.com/gocql/gocql/blob/master/conn.go#L321
where interface types are checked for nil.  There is really no point in doing this since the nil is likely of a different type than the base nil type (for example a nil *gocql.PasswordAuthenticator).

The only way to actually do this kind of nil check is through reflection:
https://play.golang.org/p/9x8_L_qWhC

**Comment by Zariel** [comment]
As far as I am aware it is logically the same as this, https://play.golang.org/p/ziYedmJTIw. The case you are talking about is when an interface value is assigned a nil struct, which this shouldnt be, I guess a user can implement an Authenticator which does this.
