### ISSUE TITLE
gocql API not conducive to testable code

### ISSUE THREAD

**Issue by mattgen88** [gocql/gocql#764]
Hi,

I've recently been using gocql for a project and I'm finding that writing testable code that is using gocql is quite difficult.

I am finding that the problem mostly stems around not implementing interfaces for things like gocql.Session and gocql.Query.

For example, you cannot create a session mock since Session.Query() returns a *gocql.Query, which is a concrete object

Also, you cannot create a mock of gocql.Query since chainable methods return *gocql.Query instead of an interface. Any mock that needs to return a reference to the object being used (e.g. gocql.Consistency()) is expected to return a concrete struct (*gocql.Query) so any mock that is implemented must also return that concrete object as it stands. 

Addressing this will break backwards compatibility, but allow for testable code to be written in the future. I do not have a PR to contribute, but only the statement of the issue.

As a work around, I had to create an interface and structs that implement and wrap the methods I use in gocql, but I cannot assert the correctness of the use of the library under that code.

**Comment by bkimble** [comment]
+1

**Comment by moxar** [comment]
+1

**Comment by primalmotion** [comment]
+1 this is utterly annoying

**Comment by fortytw2** [comment]
You should be "mocking" the behavior of `gocql` out at a slightly higher level than you may think. Try something along the lines of:

```go
type Datastore interface {
    GetUserByID(ctx context.Context) (*User, error0 
}

type CassandraStore struct {}
// implement methods here

type MockStore struct {}
// implement mock methods here
```

Then pass a `Datastore` throughout your application, creating it in/near your `func main`. This allows you to write unit tests using a `MockStore`, integration tests using the real cassandra store, and run for real with cassandra. https://github.com/matryer/moq may be helpful in generating the mock interface.

**Comment by Zariel** [comment]
And then in integration tests verify that the query and args are correct. I feel this is the best way and is how I've done it in the past.
