### ISSUE TITLE
Node discovery takes a very long time.

### ISSUE THREAD

**Issue by git-oca** [gocql/gocql#765]
Hi,

Not sure this is a bug or not, but node discovery seems to take a very long time (3 minutes or so) on my cluster (and even fail sometimes) way longer than what I'm used to using the java driver.
I did give a try to the "pre-node-events" which connect faster, but than seems to produce more error while reading the data.

I'm using Cassandra 2.1.11

I will be happy to help if I can but I don't know where to start...

**Comment by git-oca** [comment]
My cluster is running on Ubuntu 12.04.5 LTS

**Comment by git-oca** [comment]
This only occurs when I increase the cluster Timeout.

**Comment by Zariel** [comment]
Are you running in docker?

**Comment by git-oca** [comment]
Yes, running in docker.but after some more investigation, that may be my cluster that is causing the problem... I'm not sure right now...

**Comment by Zariel** [comment]
This is probably the same issue as #696
