### ISSUE TITLE
library logging output

### ISSUE THREAD

**Issue by mzuneska** [gocql/gocql#766]
I noticed that the gocql library logs in several different spots. For our production logging we prefer to log in json so random text output is at odds with this. Have there been any thoughts of removing the internal logging and bubbling up errors or allowing a logger to be injected?

**Comment by Zariel** [comment]
Id be happy to add a logger to cfg, what kind of logger are you thinking of?

**Comment by mzuneska** [comment]
Well we use https://github.com/Sirupsen/logrus which has the same api as the stdlib logger. I'd imagine any `log` that was injected in to  the `gocql` library would conform to the current set of methods on logger that `gocql` is using and no more than that. That much would be acceptable.

**Comment by Zariel** [comment]
Would having an interface like,

```go
type Logger interface {
   Println(string, ...interface{})
}
```

work?

**Comment by mzuneska** [comment]
I see both `log.Printf()` and `log.Println()` used in the library so it seems like to support the current code one would want
```go
type Logger interface {
	Printf(string, ...interface{})
	Println(...interface{})
}
```

**Comment by nathany** [comment]
Would it make sense to add the Logger to ClusterConfig? Something like this:

```go
type ClusterConfig struct {
    ....
    Log Logger
}
```

And default it to `log.New(os.Stderr, "", log.LstdFlags)`, which is the standard logger.

**Comment by nathany** [comment]
I've started on these changes in #803.

One question is whether or not gocql wants to limit its logging to `Printf` and `Println`?

**Comment by Zariel** [comment]
Hmm, im not sure, I can see cases where we would want to have some severity? Im not sure what is best practices here.

**Comment by nathany** [comment]
Nor am I. 

If gocql adopts something like logrus for severity levels, it would still be nice if users could configure it to do JSON for some.

What I'm currently struggling with is how to send all the logging through a ClusterConfig Log field rather than using a global.

**Comment by nathany** [comment]
A policy of only logging errors would avoid the need for severity levels, and may also remove some logging that may not really be necessary.

**Comment by mzuneska** [comment]
Taking a step back here I guess I'd ask what is the goal of logging in this library? 
- if it's for informational use for writers of the library I already see [what looks like a debug flag](https://github.com/gocql/gocql/blob/8fddba88e0d246cabfb37be496813a5c30979ad6/events.go#L94) and that could be used in more places.
- if it's for ideally for me as a user of this library then logging and not sending that message back in an error (as is most of the cases) severely limits what I can do with that condition
- if it's meant to just help me debug conditions but not report actual errors then I should be allowed to control how the logger writes the data and I believe it should be very restrictive. Looking to log severity levels of which none rise to the level of an error seems unnecessary. Also, there are many examples in the go standard library where `errors` is used to report state rather than exceptional cases.

As an aside I looked through `database/sql` and a postgres driver that implements that at `github.com/lib/pq` and neither logs anything that I could tell.

**Comment by nathany** [comment]
I agree with Mark's suggestion to take a step back and consider why gocql is logging where it does.

Meanwhile, my colleague @chris-skud pointed out a workaround to have gocql use [Logrus](https://github.com/Sirupsen/logrus) for JSON output.

```go
logger := logrus.New()
logger.Formatter = &logrus.JSONFormatter{}
// use logrus for standard log output:
log.SetOutput(logger.Writer())
```

Alternatively, if all logging is going through something like Logrus, the standard library logging can be discarded entirely with the following:

```go
log.SetOutput(ioutil.Discard)
```

**Comment by Zariel** [comment]
I agree, many of the logs help me debug issues for users, the debug flag I intended to use in cases where verbose logging was too obtrusive to run all the time and to assist in debugging travis testing issues.

**Comment by nathany** [comment]
I'm experimenting with log levels in Logrus. It's possible to set all standard library logging to a given level, such as info.

```
log.SetOutput(logger.WriterLevel(logrus.InfoLevel))
```

The result is that the current gocql logging is discarded if the LogLevel is set to warn or above. That may not be the best, because some logs from gocql are errors (like connection failures), but so far I can work around that by logging returned errors at a higher log level.

**Comment by mzuneska** [comment]
Thanks @nathany I'll try the workaround for now.

**Comment by sirupsen** [comment]
Great stuff, I've added this to the official READMe https://github.com/sirupsen/logrus/commit/080ca65fb5a85b6f2b42053b9a895d462ed0ddff
