### ISSUE TITLE
Support for Float from std package math/big

### ISSUE THREAD

**Issue by wienczny** [gocql/gocql#767]
Currently "big" types from c* are mapped using "gopkg.in/inf.v0". Please add support for the std library math/big

**Comment by Zariel** [comment]
Any particular reason? The decimal type in Cassandra are infinite precision decimals which are [encoded with a scale and an unscaled part](https://github.com/apache/cassandra/blob/824cb768d2aa45e1889653ab2c98cc0bc63e594e/doc/native_protocol_v4.spec#L859), as far as I am aware the `math/big` package does not support scaled/unscaled decimals.

**Comment by wienczny** [comment]
I need to convert to and from a swagger model. The model is generated using go-swagger which converts swagger "decimal numbers" to float64. The problem is that there is no easy conversion between those two.

**Comment by Zariel** [comment]
Are those floating point numbers or arbitrary precision decimals?

**Comment by wienczny** [comment]
Those values are regular javascript floating point numbers on the wire. I'm using java.lang.BigDecimal for calculations the client side though

**Comment by Zariel** [comment]
Then your losing precision over the wire, `gopkg.in/inf.v0` provides types which are compatible with `java.lang.BigDecimal`

**Comment by wienczny** [comment]
You are right. That's why I don't want to loose more precision converting values. Maybe new types will be added with https://github.com/OAI/OpenAPI-Specification/issues/607

**Comment by Zariel** [comment]
There is a proposal to a big decimal type to the standard library see golang/go#12127 but that wont solve the issue of the incompatible types you are encountering. I would recommend converting them to strings or such and then converting back to the decimal type. Unless you have any suggestions I don't see how to implement the decimal type in Cassandra with the types in `math/big`.
