### ISSUE TITLE
CCM Event tests are flaky in Travis

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#771]
We should add some hooks to the connection pool or session to detect events to test instead of using timeouts.

**Comment by nathany** [comment]
Does that refer to these (flaky) tests, or are these something else?

```
--- FAIL: TestUnpreparedBatch (1.00s)
	cassandra_test.go:429: count: expected 100, got 0
```

```
--- FAIL: TestStream0 (0.00s)
	conn_test.go:684: read tcp 127.0.0.1:41287->127.0.0.1:33392: read: connection reset by peer
```

build: https://travis-ci.org/gocql/gocql/builds/159111287

**Comment by Zariel** [comment]
No something else, those 2 are other flakes :(

**Comment by nathany** [comment]
Ok. I didn't see #789 at the time.

In this event test I don't see any timeouts -- I'm not sure why it fails sometimes.

```
--- FAIL: TestEventDiscovery (2.41s)
	events_ccm_test.go:25: status=map[node1:{State:UP Addr:127.0.0.1 Name:node1} node3:{State:UP Addr:127.0.0.3 Name:node3} node2:{State:UP Addr:127.0.0.2 Name:node2}]
	events_ccm_test.go:29: poolhosts=map[127.0.0.1:[filling=false closed=false conns=2 size=2 host=[hostinfo peer="127.0.0.1" port=9042 data_centre="datacenter1" rack="" host_id="3d8b84be-79ca-4cd3-9370-5af3b6b37f60" version="v2.0.17" state=UP num_tokens=256]]]
	events_ccm_test.go:33: did not discover "127.0.0.3"
	events_ccm_test.go:33: did not discover "127.0.0.2"
```

from: https://travis-ci.org/gocql/gocql/jobs/168777130

**Comment by nathany** [comment]
I don't understand why this is failing.

```
--- FAIL: TestEventNodeUp (57.38s)
	events_ccm_test.go:174: node not added after node added event
```

From what I see, cmd.Run is synchronously running `ccm start --wait-for-binary-proto` which says it will:

> Wait for the binary protocol to start

Yet there is a Sleep that apparently isn't enough? 

```go
// cassandra < 2.2 needs 10 seconds to start up the binary service
time.Sleep(15 * time.Second)
```

Perhaps a temporary fix would be a retry loop that polls every few seconds:

```go
start := time.Now()

for time.Since(start) < 60 * time.Second {
    // ...
    time.Sleep(5 * time.Second)
}
```

**Comment by Zariel** [comment]
Tbh I would rather mock out the event testing code to better isolate it and allow it to be more reliably testing something.

**Comment by Zariel** [comment]
Ive got some ideas to try and fix this but will skip them for now
