### ISSUE TITLE
Support for Async Write Queries/Bulk Insert

### ISSUE THREAD

**Issue by pwnsrma** [gocql/gocql#773]
I couldn't find anything similar to "executeAsync" , I have tried (unlogged) batches to insert 40k-50k records into a Cassandra table but this is not recommended  when batches contain updates/inserts for multiple partitions.
Insertion causing Cassandra to complain with ---
"Unlogged batch covering 23 partitions detected against table []. You should use a logged batch for atomicity, or asynchronous writes for performance."
Is anybody worked on this feature ?

Should I go with "go routines" or any recommendation on implementation of this ?

**Comment by Zariel** [comment]
Gocql provides under the synchronous API an asynchronous interface to Cassandra, as is recommended for libraries. A single request is written and flushed as soon as they come in, leading to under high load a lot of time spent is syscalls which is a known issue #383, it is an unfortunate side effect of leading to simpler code.

I've heard of people getting very good throughput but using many goroutines, an option is to use a pool of N goroutines to do writes to not overload the GC with many goroutines spawning/dying.

**Comment by pwnsrma** [comment]
@Zariel Thanks for the quick reply..!!
Will  test this with the Pool of goroutines.
