### ISSUE TITLE
driver using up a ton of memory during a large amount of reads

### ISSUE THREAD

**Issue by mediocregopher** [gocql/gocql#777]
We have a 60GB box and it has been running out of memory during large data processing jobs. I did a profile of our code and found that 55% of memory is being used inside gocql. Here's the output from pprof:

```
(pprof) top1
7.67GB of 13.83GB total (55.41%)
Dropped 329 nodes (cum <= 0.07GB)
Showing top 1 nodes out of 23 (cum >= 7.67GB)
      flat  flat%   sum%        cum   cum%
    7.67GB 55.41% 55.41%     7.67GB 55.41%  github.com/gocql/gocql.(*framer).readFrame
```

```
(pprof) list readFrame
Total: 13.83GB
ROUTINE ======================== github.com/gocql/gocql.(*framer).readFrame in /opt/TeamCityBuild/work/larry-1/8f528b9e3717e707/.deps/src/github.com/gocql/gocql/frame.go
    7.67GB     7.67GB (flat, cum) 55.41% of Total
         .          .    423:   }
         .          .    424:
         .          .    425:   if cap(f.readBuffer) >= head.length {
         .          .    426:           f.rbuf = f.readBuffer[:head.length]
         .          .    427:   } else {
    7.67GB     7.67GB    428:           f.readBuffer = make([]byte, head.length)
         .          .    429:           f.rbuf = f.readBuffer
         .          .    430:   }
         .          .    431:
         .          .    432:   // assume the underlying reader takes care of timeouts and retries
         .          .    433:   n, err := io.ReadFull(f.r, f.rbuf)
```

There's some other unrelated memory problems I have to deal with after that, but this is far and away the worst offender. 

I added a log message just above that make, and pretty much as soon memory starts being consumed it starts spewing:

```
2016/09/01 22:22:35 making head.length: 2799726
2016/09/01 22:22:35 making head.length: 2797306
2016/09/01 22:22:35 making head.length: 4255590
2016/09/01 22:22:35 making head.length: 4358834
2016/09/01 22:22:35 making head.length: 4253020
2016/09/01 22:22:35 making head.length: 4302867
2016/09/01 22:22:35 making head.length: 4298329
2016/09/01 22:22:35 making head.length: 4355676
2016/09/01 22:22:35 making head.length: 4342381
2016/09/01 22:22:35 making head.length: 4276774
2016/09/01 22:22:35 making head.length: 4261527
2016/09/01 22:22:36 making head.length: 2792650
2016/09/01 22:22:36 making head.length: 2798896
2016/09/01 22:22:36 making head.length: 2795337
2016/09/01 22:22:36 making head.length: 4351303
2016/09/01 22:22:36 making head.length: 4292330
2016/09/01 22:22:36 making head.length: 2795117
```

the number being the value of `head.length`.

I'm not sure what the exact bug is here, but it seems that if I'm just dumping data from cassandra there shouldn't be a net increase in memory used by driver itself, that should only happen if I was deliberately storing the data in memory in user space (which I'm not, I don't believe). Let me know if there's more info I could give to debug. This is all on latest master as of earlier today.

**Comment by Zariel** [comment]
The line that allocates the `readBuffer` in `readFrame` is used to copy data from the network connection so that it can be parsed, the connect them reads another frame whilst parsing happens on another goroutine. The reason it is copied is so that it frees up the connection for another frame to improve concurrency, parts of the buffer are then copied again into the individual types so that any data returned to the user does not point into this buffer. The `framer` which this buffer is attached to can be reused during requests.

In the profile you posted is it inuse memory or allocated memory?

**Comment by mediocregopher** [comment]
This ended up being an issue on our end, we were unmarshalling the data into a `[]byte` and then that was kept around for waaaaaay too long, and since that byte was allocated in gocql it looked like gocql had the leak. Sorry about that
