### ISSUE TITLE
marshal: alias for gocql.UUID type ?

### ISSUE THREAD

**Issue by ekle** [gocql/gocql#778]
hi,
is there a way to make an alias type for a uuid ?
I have uuids for different kinds of Ids and want the type-safty-system of golang to enforce this.
i tryed 

- User struct{ gocql.UUID }

and

-  type User gocql.UUID

but with both i get "can not marshal abc.User into uuid" 
i use the ids mostly as keys in cassandra map-fields.

**Comment by Zariel** [comment]
It should be possible to do

```go
type User gocql.UUID

func q(u User) {
   session.Query(gocql.UUID(u))
}
```

**Comment by ekle** [comment]
my UUIDs are mostly map-keys within structs. so this solution would require to duplicate all this structs and copy the data.
is there a way by implementing some Interfaces ? maybe Marshaler or UDTMarshaler ?

**Comment by Zariel** [comment]
In go 1.8 if aliases are added (which it looks like they will) this will be possible, but not until then. You could implement `MarshalCQL` which you just need to turn your UUID into a 16 byte value.
