### ISSUE TITLE
KeyspaceMetadata does not set protocol version and hence not useful for marshal 

### ISSUE THREAD

**Issue by samipshah** [gocql/gocql#779]
I am not really sure if this is a bug or its by design. However, what I am trying to do is when a session is started I fetch column information and while inserting data, I use that column information I retrieved from KeyspaceMetadata in Marshal function. The problem I face is Type.Version() in ColumnMetadata always returns 0 since the NativeType proto is not set in the metadata.go . Let me know if this is by design or a bug ? If a bug I can provide a patch.
.

**Comment by Zariel** [comment]
Looks like a bug

**Comment by cmlicata** [comment]
@Zariel, has this bug been resolved yet?  I'd like to patch it up if it hasn't.

**Comment by Zariel** [comment]
nope please go ahead

**Comment by cmlicata** [comment]
@Zariel, so I am struggling to figure out exactly where this issue resides because as far as I can see,  the `TypeInfo` struct, which obviously has the, `Version()` method exposed, is provided as part of the `ColumnMetadata`.  Any assistance with this issue would be greatly appreciated.

**Comment by Zariel** [comment]
There are TypeInfo created in https://github.com/gocql/gocql/blob/05df4896cf271375039b0645117594e861bde0d9/metadata.go#L836 in a few places which dont set the protocol version
