### ISSUE TITLE
Does gocql implement async writes?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#781]
I'd like to insert large volumes of things and I don't care about replays (i.e. if there are errors on some rows, keep going).

I've been seeing this in the log file:
```
2016/09/12 19:01:30 Unlogged batch covering 499 partitions detected against table [xyz]. You should use a logged batch for atomicity, or asynchronous writes for performance.
```

Furthermore, I cannot grep about async anywhere in the code base.

Got any pointers?

**Comment by nemothekid** [comment]
The gocql library exposes a synchronous API, and you can implement async on top of it with go primitives. By far the simplest is to use goroutines and channels, similar to http://labs.strava.com/blog/futures-in-golang/

What I do, which is pretty un-idiomatic is:

```go
import (
  "sync"
  "github.com/gocql/gocql" 
)

const MaxInflightRequests = 64
var inflightRequests = int32(0)
var inflightCond = sync.NewCond(&sync.Mutex{})
var errChanPool = sync.Pool{
	New: func() interface{} {
		return make(chan error, 1)
	},
}

func Exec(query string, args ...interface{}) chan<- err {
	r := errChanPool.Get()
	inflightCond.L.Lock()
	for atomic.LoadInt32(&inflightRequests) >= MaxInflightRequests {
		inflightCond.Wait()
	}
	atomic.AddInt32(&inflightRequests, 1)
	inflightCond.L.Unlock()
	go func() {
		e := session.Query(query, args...).Exec()
		atomic.AddInt32(&running, -1)
		inflightCond.Signal()
		r <- e
	}()
	return r
}

func foo() {
	// in code
	future := Exec("INSERT INTO table (foo, bar) VALUES (?,?)", bar, foo)
	// ...
	err := <-future
	errChanPool.Put(future)
	// etc
}
```

**Comment by didip** [comment]
I see, so there's nothing in the CQL protocol that differentiate sync vs async. Thanks!

**Comment by Zariel** [comment]
The message from Cassandra is referring to what I assume is the Java drivers async write feature (which is a little bit naughty?). Gocql provides a synchronous API over an asynchronous protocol which is the recommended way for Go libraries.

**Comment by pzentenoe** [comment]
> The gocql library exposes a synchronous API, and you can implement async on top of it with go primitives. By far the simplest is to use goroutines and channels, similar to http://labs.strava.com/blog/futures-in-golang/
> 
> What I do, which is pretty un-idiomatic is:
> 
> ```go
> import (
>   "sync"
>   "sync/atomic"
>   "github.com/gocql/gocql" 
> )
> 
> const MaxInflightRequests = 64
> var inflightRequests = int32(0)
> var inflightCond = sync.NewCond(&sync.Mutex{})
> var errChanPool = sync.Pool{
>     New: func() interface{} {
>         return make(chan error, 1)
>     },
> }
> 
> func Exec(query string, args ...interface{}) chan<- err {
>     r := errChanPool.Get()
>     inflightCond.L.Lock()
>     for atomic.LoadInt32(&inflightRequests) >= MaxInflightRequests {
>         inflightCond.Wait()
>     }
>     atomic.AddInt32(&inflightRequests, 1)
>     inflightCond.L.Unlock()
>     go func() {
>         e := session.Query(query, args...).Exec()
>         atomic.AddInt32(&running, -1)
>         inflightCond.Signal()
>         r <- e
>     }()
>     return r
> }
> 
> func foo() {
>     // in code
>     future := Exec("INSERT INTO table (foo, bar) VALUES (?,?)", bar, foo)
>     // ...
>     err := <-future
>     errChanPool.Put(future)
>     if (err != nil) {
>         panic(err)
>     }
>     // etc
> }
> ```
What its mean &running
