### ISSUE TITLE
Google Inc. in LICENCE?

### ISSUE THREAD

**Issue by nathany** [gocql/gocql#783]
Just curious as to why gocql uses the same three-clause license as Go with a non-endorsement clause mentioning Google?

>* Neither the name of Google Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

**Comment by Zariel** [comment]
This indeed looks odd a wrong (license was probably copied from the Go repo) and was done before my time, we should switch it out to a standard 3-clause BSD license.

**Comment by Zariel** [comment]
Thanks!
