### ISSUE TITLE
No result when select *?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#791]
Hi all, I am sure I miss something obvious here. I have a 4 nodes C* cluster for testing and this is my table:
```
CREATE TABLE IF NOT EXISTS stuff (
   id text PRIMARY KEY
);
```

and this is how I query it:
```
stuff := make([]string, 0)
query := fmt.Sprintf("SELECT * FROM stuff")

session, _ := cassandra.CreateSession()
defer session.Close()

// Changed this to gocql.One or gocql.Quorum, but no luck.
session.SetConsistency(gocql.One)

var id string

iter := session.Query(query).Iter()
for iter.Scan(&id) {
	stuff = append(stuff, id)
}
```

Super straight forward, almost hello world like.
On a single machine cluster, like a dev machine, I always get results.
But on my 4 hosts cluster, I get no results. Why is that?

`cqlsh` always returns the correct results. What gives?

**Comment by tendervittles** [comment]
What is your replication factor?

**Comment by Zariel** [comment]
Is there an error returned from CreateSession?

**Comment by didip** [comment]
Thank you for taking the time in looking at this issue, but apparently my Cassandra user has every single GRANT privileges except SELECT.

Thanks why. Sorry for wasting your time.
