### ISSUE TITLE
ScanCas expects more parameters on insert than defined

### ISSUE THREAD

**Issue by Highstead** [gocql/gocql#792]
When inserting a subset of the table columns with use of a light weight transaction the cassandra result returns the full set of cassandra column values.  This will then cause ScanCas() to fail due to a mismatch in columns.

This is perhaps not an issue with a driver, but is a result of how cassandra handles 'if not exists'.  I'll ponder this for a couple of days anyways.

### CQL
``` 
CREATE TABLE IF NOT EXISTS test.inserttest(
    key bigint,
    session_token text,

    foo text, 
    bar text,
PRIMARY KEY(key, event_date, session_token);

INSERT INTO test.inserttest(key, session_token, foo) VALUES (1, 'myToken', 'baz') IF NOT EXISTS;
```

### GoCql
```
....
if err := session.Query(`insert into test.inserttest(key, session_token, foo) VALUES (1, 'myToken', 'bez') IF NOT EXISTS;`).ScanCas(nil, nil, nil); err != nil {
  log.Println("Bummer");
}
```

Expected Result: 
No error

**Comment by Highstead** [comment]
This would be low priority as i suspect mapScanCas will function fine for my purposes.

**Comment by Zariel** [comment]
The annoying thing is that I suspect Cassandra is returning the whole row back (in a pretty annoying order too) regardless of columns inserted. Maybe raise a Cassandra bug? Not sure what can be done our side for this apart from using MapScanCAS.

**Comment by Highstead** [comment]
Yeah, i'm of the same opinion.  I'll close the Issue if i don't come up with anything in a day or so.

**Comment by Highstead** [comment]
Opened an issue on the Cassandra Jira.

**Comment by Zariel** [comment]
It would be nice to be able to specify the column order and columns to be returned in the query request, I may open a ticket for that.

**Comment by Highstead** [comment]
Cassandra feedback is 'will not fix, working as intended'
Jira ticket was: https://issues.apache.org/jira/browse/CASSANDRA-12691

Primarily the thought is 'what if someone is already using it like this'... which makes sense.  The more i think about it the more i suspect a scan specific to the fields returned is probably the way to go.

**Comment by Zariel** [comment]
The annoying thing from a user perspective is that the first time someone uses a CAS operation the returned columns are returned in an order that they dont expect. We should be able to specify the column return order in the query somehow.
