### ISSUE TITLE
How SliceMap or MapScan are supposed to be used with paginated results?

### ISSUE THREAD

**Issue by hgfischer** [gocql/gocql#815]
Hi,

I'm doing a small program that will read random Cassandra tables, with varying schemas, so It seems SliceMap or MapScan could be what I need, but I'm not finding much info about them.

Is SliceMap going to load all the rows into memory? Or it's just a page of it? If it's just a page, how am I supposed to iterate with this API?

**Comment by hgfischer** [comment]
Hello,

Could you give me any points about this, please?

**Comment by Zariel** [comment]
MapScan works like a normal iterator, SliceMap returns every row as a map per row.
