### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by janajri** [gocql/gocql#816]
Hey there, we noticed that recent builds have been segfault-ing with the specific stacktrace -- I'll add more info as soon as I know more.

10/28/2016 4:47:46 PMpanic: runtime error: invalid memory address or nil pointer dereference
10/28/2016 4:47:46 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9a8b7d]
10/28/2016 4:47:46 PM
10/28/2016 4:47:46 PMgoroutine 42714 [running]:
10/28/2016 4:47:46 PMpanic(0xbcfc60, 0xc42000c090)
10/28/2016 4:47:46 PM	/usr/local/go/src/runtime/panic.go:500 +0x1a1
10/28/2016 4:47:46 PMcontainer/list.(*List).MoveToFront(0xc420cb0a20, 0xc4217c7170)
10/28/2016 4:47:46 PM	/usr/local/go/src/container/list/list.go:169 +0x4d
10/28/2016 4:47:46 PMgithub.com/gocql/gocql/internal/lru.(*Cache).Get(0xc42096da20, 0xc428533650, 0x6f, 0x0, 0xc42890f798, 0x3)
10/28/2016 4:47:46 PM	/go/src/github.com/gocql/gocql/internal/lru/lru.go:81 +0x8d
10/28/2016 4:47:46 PMgithub.com/gocql/gocql.(*preparedLRU).execIfMissing(0xc42096da40, 0xc428533650, 0x6f, 0xc42890f880, 0x0, 0xce8200)
10/28/2016 4:47:46 PM	/go/src/github.com/gocql/gocql/prepared_cache.go:51 +0x68
10/28/2016 4:47:46 PMgithub.com/gocql/gocql.(*Conn).prepareStatement(0xc420f2dea0, 0x0, 0x0, 0xce82a7, 0x5e, 0x0, 0x0, 0x0, 0x7f4d96eabe10, 0x0)
10/28/2016 4:47:46 PM	/go/src/github.com/gocql/gocql/conn.go:686 +0x12e
10/28/2016 4:47:46 PMgithub.com/gocql/gocql.(*Conn).executeQuery(0xc420f2dea0, 0xc4286c4c00, 0xc437259de0)
10/28/2016 4:47:46 PM	/go/src/github.com/gocql/gocql/conn.go:769 +0x149
10/28/2016 4:47:46 PMgithub.com/gocql/gocql.(*Query).execute(0xc4286c4c00, 0xc420f2dea0, 0x10d7c20)
10/28/2016 4:47:46 PM	/go/src/github.com/gocql/gocql/session.go:739 +0x35

**Comment by i** [comment]
This was introduced by: https://github.com/gocql/gocql/commit/3d6a7fbdbdb2f4fcd679cd7846a56986f4ee44c7

It needs to be rolled back ASAP.

**Comment by nemothekid** [comment]
Looks like the [LRU's Get Operation isn't Read Only](https://github.com/gocql/gocql/blob/master/internal/lru/lru.go#L23).

**Comment by janajri** [comment]
@i yup, does seem so -- we pulled an older commit and have been fine. Thansk for the quick action here -- closing this out.

**Comment by Zariel** [comment]
As the LRU moves the read value from the front of the list this requires a write lock.

https://github.com/gocql/gocql/blob/2e915f92d7783579c51937e238dc5307c8f00505/internal/lru/lru.go#L81

**Comment by Zariel** [comment]
Thanks for the report as well
