### ISSUE TITLE
Iter().MapScan() and "can not unmarshal X uuid into gocql.UUID"

### ISSUE THREAD

**Issue by hgfischer** [gocql/gocql#822]
Hello, 

first of all, thanks for this package!

I'm getting this error from inside a Iter().MapScan(), Iter().Scan() call:

```can not unmarshal X uuid into gocql.UUID```

I was trying to understand the reason and I found the code at https://github.com/gocql/gocql/blob/734b8e8dfe75f153dbeac49fac906e677b1d0a0a/marshal.go#L1412

I'm not sure what is the expected behaviour here, but since the `value.(type)` is not a pointer to a `gocql.UUID`, the switch is passing through. Could it be a counter effect of the MapScan usage?

I've changed the line 1412 a bit to return `%#v` for both columns and this is what I got:

```
can not unmarshal X gocql.NativeType{proto:0x4, typ:12, custom:""} into gocql.UUID{0x68, 0xa1, 0x55, 0xe2, 0x20, 0x80, 0x42, 0xec, 0xb2, 0xff, 0x21, 0x1b, 0xb7, 0x2d, 0xeb, 0xfa}
```

**Comment by hgfischer** [comment]
It looks like is an issue with `MapScan()` because when I do the following, I never hit this issue:

```
	columns := iter.Columns()
	values := make([]interface{}, len(columns))
	for i, column := range columns {
		values[i] = column.TypeInfo.New()
	}
	for iter.Scan(values...) {
		for _, v := range values {
			log.Printf("%T = %v\n", v, v)
		}
		fmt.Println()
	}
	if err = iter.Close(); err != nil {
		log.Fatalln(err)
	}
```

**Comment by hgfischer** [comment]
Hi,

I've prepared a way to reproduce the issue here: https://github.com/hgfischer/gocql-debug/

Just be sure you have all dependencies and do a `make all`. This will create a VM with Cassandra 2.2 and run `main.go` that will show the issue.

You can see that MapScan always get the first row, but fails in the next one. Seems to be that it is related to a reused map or buffer.

**Comment by hgfischer** [comment]
If I don't reuse the map where MapScan() will store the results, then there is no issue. It is a workaround to initialise this map with a new `map[string]interface{}` after every iteration but this creates a lot of garbage and it will not scale well.

**Comment by vrischmann** [comment]
[This](https://github.com/gocql/gocql/blob/master/helpers.go#L261-L265) is the problem. Using your test environment, I logged the content of values after the for loop, I got this:

    2016/11/22 21:50:03 value: 00000000-0000-0000-0000-000000000000
    2016/11/22 21:50:03 value: 0xc42000c420
    2016/11/22 21:50:03 value: 0xc42000c430
    2016/11/22 21:50:03 value: &[]
    2016/11/22 21:50:03 value: 0xc42000c439
    2016/11/22 21:50:03 value: 0xc42002e020
    2016/11/22 21:50:03 value: 0xc42000c458
    2016/11/22 21:50:03 value: 0xc42000c464
    2016/11/22 21:50:03 value: 0xc42000c480
    2016/11/22 21:50:03 value: 0xc42000c490
    2016/11/22 21:50:03 value: 0xc42000c4b0
    2016/11/22 21:50:03 value: 0001-01-01 00:00:00 +0000 UTC
    2016/11/22 21:50:03 value: 00000000-0000-0000-0000-000000000000
    2016/11/22 21:50:03 value: 0xc42000c4f0
    2016/11/22 21:50:03 value: 0xc42002e030
    2016/11/22 21:50:03 map[t_uuid:2af09814-5385-432f-bbb4-67428c5fc5ed t_boolean:false         t_decimal:23989.8059 t_double:24897.8967 t_timestamp:1970-01-01 03:45:11 +0000 UTC     t_varchar:CDtfZs8aGbaAJssF49GbTWjXC049VDzH t_varint:1215     t_ascii:alyqKzmtyNLQxmc6KO8KrMUbDPDTl7Tg t_blob:[83 219 142 84 165 211 242 123 2 218 0 215     8 22 236 251 106 26 196 229 244 33 217 182 120 17 76 109 51 240 153 47] t_inet:44.41.188.200     t_text:RxDzgowqbGDEil4ZhvDoGXAn6hNCMAPo t_float:25806.988 t_int:10785     t_timeuuid:cbdcb740-b0f3-11e6-ac0e-55b3569f6b5a t_bigint:20354]
    2016/11/22 21:50:03 value: 2af09814-5385-432f-bbb4-67428c5fc5ed
    2016/11/22 21:50:03 value: alyqKzmtyNLQxmc6KO8KrMUbDPDTl7Tg
    2016/11/22 21:50:03 value: 20354
    2016/11/22 21:50:03 value: [83 219 142 84 165 211 242 123 2 218 0 215 8 22 236 251 106 26 196     229 244 33 217 182 120 17 76 109 51 240 153 47]
    2016/11/22 21:50:03 value: false
    2016/11/22 21:50:03 value: 23989.8059
    2016/11/22 21:50:03 value: 24897.8967
    2016/11/22 21:50:03 value: 25806.988
    2016/11/22 21:50:03 value: 44.41.188.200
    2016/11/22 21:50:03 value: 10785
    2016/11/22 21:50:03 value: RxDzgowqbGDEil4ZhvDoGXAn6hNCMAPo
    2016/11/22 21:50:03 value: 1970-01-01 03:45:11 +0000 UTC
    2016/11/22 21:50:03 value: cbdcb740-b0f3-11e6-ac0e-55b3569f6b5a
    2016/11/22 21:50:03 value: CDtfZs8aGbaAJssF49GbTWjXC049VDzH
    2016/11/22 21:50:03 value: 1215
    2016/11/22 21:50:03 can not unmarshal X uuid into gocql.UUID


So, at the second call the map is not cleared and the loop above will use the map elements and put them in `rowData.Values`, then it won't work.

I'm not sure what the loop here is supposed to do, removing it entirely makes `MapScan` work correctly, but it's entirely possible I'm missing something.

@hgfischer if you want to reuse the map, you can instead `delete` each key from your map after processing your row, then it works

**Comment by hgfischer** [comment]
Yes, using delete, or creating new maps on each interaction is a fix, but not ideal. Instead of generating a lot of memory garbage, I've decided to work around and don't use MapScan() because of this.

IMHO iteration variables should be always reused, and MapScan is not working this way right now. People using it might notice huge performance improvements with large collections of data, if this is fixed in MapScan.

I don't know how to fix it for now, but I would do it if I knew.
