### ISSUE TITLE
TokenAwarePolicy is broken for Cassandra 2.2

### ISSUE THREAD

**Issue by i** [gocql/gocql#827]
Cassandra 2.2 drops the `*_aliases` fields from the `system.schema_columnfamilies` table.

The current implementation of the token aware policy reads this table in order to derive routing keys. This results in falling back to the backup host selection policy on 100% of queries.

**Comment by Zariel** [comment]
This should only cause a fallback when not using proto v4 though as it should be the primary key from the prepared info. This falls into the mess that is supporting the various metadata versions that different cassandra versions support, it needs refactoring and improving.
