### ISSUE TITLE
CQL date type is not supported?

### ISSUE THREAD

**Issue by olegabr** [gocql/gocql#828]
I have a field of type `date` in my CQL table. When I try to insert data in this table from my `gocql` code, I have this error:

```
can not marshal time.Time into custom(org.apache.cassandra.db.marshal.SimpleDateType)
```

I've tried to use string representation since CQL docs states that `date - Date string, such as 2015-05-03` but has similar error:

```
can not marshal string into custom(org.apache.cassandra.db.marshal.SimpleDateType)
```

How to deal with date type from `gocql` code?

**Comment by Zariel** [comment]
That should marshal, ill take a look

**Comment by Zariel** [comment]
Yep it appears they are not implemented for marshal/unmarshal. Time is trivial, date is not so obvious. Ill need to add some tests before I can add these.

**Comment by evildecay** [comment]
The latest has been supported

**Comment by Zariel** [comment]
thanks

**Comment by olegabr** [comment]
the commit https://github.com/gocql/gocql/commit/bdbe7c9b943cfd07dfeccccbaa04071ae7ce22b6 is very good, but no tests were added for the new functionality added.

**Comment by evildecay** [comment]
@olegabr Yes, test file will be added later.
