### ISSUE TITLE
Can I pass my own tls.Config?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#830]
Based on the code base here: https://github.com/gocql/gocql/blob/9395dd748fc5af1bca332eb778f01dc80577a3b2/connectionpool.go, it looks like I cannot pass my own `*tls.Config`.

If so, can I have a feature request for user to be able to pass their own `*tls.Config`?

The use case is so that user can have the ultimate control over the TLS settings. Example:

```
tlsConfig := &tls.Config{
    MinVersion:               tls.VersionTLS12, // Enforce TLS 1.2 only
    CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
    PreferServerCipherSuites: true,
    CipherSuites: []uint16{
        tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
        tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
        tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
        tls.TLS_RSA_WITH_AES_256_CBC_SHA,
    }, // Custom CipherSuites
    RootCAs:            myOwnPool,
    ClientSessionCache: tls.NewLRUClientSessionCache(512), // Caching settings
}
```

**Comment by robusto** [comment]
Yes, look at the SslOpts field that is exposed in ClusterConfig. "tls.Config" is exposed as an anonymous field:

https://github.com/gocql/gocql/blob/9395dd748fc5af1bca332eb778f01dc80577a3b2/cluster.go#L52
https://github.com/gocql/gocql/blob/9395dd748fc5af1bca332eb778f01dc80577a3b2/conn.go#L82

Example:
```
yourTlsConfig := &tls.Config{...}

cluster := gocql.NewCluster(hosts...)
cluster.SslOpts.Config = yourTlsConfig
sess, err := cluster.CreateSession()
...
```

Related PR: https://github.com/gocql/gocql/pull/414

**Comment by didip** [comment]
Ah! Perfect. Thank you for the quick response.
