### ISSUE TITLE
no response received from cassandra within timeout period

### ISSUE THREAD

**Issue by clanstyles** [gocql/gocql#835]
I wrote an app to transfer our 80 GB MySQL cluster to Cassandra. It takes some time because of the restructuring of the data.It seems that no matter how many times I try it, eventually it always "crashes" with 
"no response received from cassandra within timeout period". Once this happens, the process will hang forever. It wont add any more data. I can see in OpsCenter that no more writes happen, and the app itself isn't outputting anything more.

I'm using the latest version of the driver. I did see that there were some other tickets made about this issue. I made sure that the current version has the close on the channel.

See: https://github.com/gocql/gocql/issues/664

**Comment by Zariel** [comment]
Can you look at the goroutines in use and see if any are stuck in gocql? Infact if you can provide all the stacks of code in gocql that would be helpfull looking into this.

**Comment by clanstyles** [comment]
How can I give you this? The process is still running.

**Comment by Zariel** [comment]
If you have net/pprof handlers installed you can grab them there, otherwise if you can kill it with ABRT and it will stop and dump stacks.

**Comment by clanstyles** [comment]
I don't have net/pprof setup. If I have to, I'll cause the issue again after setting up handlers for it. 
kill -ABRT <pid> and kill -6 both don't stop the process.

**Comment by clanstyles** [comment]
Alright, I got the data out of it.

It looks like it's leaking Go routines.

```
goroutine 1891329 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1885363 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1891349 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1891087 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1890951 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1890691 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1891243 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e

goroutine 1886201 [chan send, 1395 minutes]:
main.main.func1(0xc82008e8c0, 0xc82014e230, 0xc82014e2a0, 0xc82002e090, 0xc8201a0180)
        ......cmd/transfer/client.go:87 +0x15b
created by main.main
        ......cmd/transfer/client.go:89 +0xa3e
```

**Comment by Zariel** [comment]
None of those have any frames in `gocql`, were any of the snipped frames in `gocql`?

**Comment by clanstyles** [comment]
The amount of those overflowed and the buffer of the terminal goofed it.
Let me write it to file.

**Comment by Zariel** [comment]
@clanstyles any update?

**Comment by ttaranov** [comment]
I've noticed that if I change cassandra's batch_size_warn_threshold_in_kb to a higher value (batch_size_warn_threshold_in_kb: 10), errors like this timeout above disappear. It makes me wonder whether the inserted record(s) is too large?

**Comment by mjoshiNetElastic** [comment]
I am hitting this issue consistently on my setup.CreateKeySpace  ne
Create table for UUIDKeyMap Name 
Create table for UUIDKeyMap Name failed with error: gocql: no response received from cassandra within timeout period
InstantiateDbIf: connect to session failed with err  gocql: no response received from cassandra within timeout period
This happens only on one of my machine. The same code works fine on another setup just fine.. Any help to help debug this will be appreciated. 
Thanks.

**Comment by Zariel** [comment]
@mjoshiNetElastic check the logs on cassandra
