### ISSUE TITLE
Support UNSET values in Prepared Statements

### ISSUE THREAD

**Issue by nemosupremo** [gocql/gocql#861]
A useful feature ([CASSANDRA-7304](https://issues.apache.org/jira/browse/CASSANDRA-7304)) in 2.2.0+ is to treat `null` values as unset in prepared statements (the difference here is that sending a `null` in a prepared statement is the equivalent to a DELETE - which causes tombstones, unset just treats it as you not having set anything at all). I'm looking to start work on PR, but I don't think I can get to it soon, so I just opened an issue instead.

**Comment by Zariel** [comment]
From what I can tell this just requires sending -2 instead of -1 for null values. How would the user indicate that it should send "unset" instead of "nil", we could add a type? `gocql.UnsetCol` which got marshalled to `-2` which would be relatively clean

**Comment by nemothekid** [comment]
If we follow the Python driver, there are two methods we would implement

1. A custom type (like `gocql.UnsetCol`).
1. A session level setting that treats all `nil`s as `gocql.UnsetCol`/`-2`.

Going with 1 would be good, but when I last looked at it, the when we write the bytes to the connection we assume if the byte array is nil, we will always write -1.

**Comment by nemothekid** [comment]
Maybe the fix could be added here - https://github.com/gocql/gocql/blob/5e9bfab8b94dac35b012c8bd39953e928299a86d/frame.go#L1326

Something like -
```diff
if n := len(opts.values); n > 0 {
	f.writeShort(uint16(n))
	for i := 0; i < n; i++ {
		if names {
			f.writeString(opts.values[i].name)
		}
+              if (opts.values[i].unset) {
+		     f.writeBytesButNullIsNeg2(opts.values[i].value)
+              } else {
+                    f.writeBytes(opts.values[i].value)
                }
	}
}
```

**Comment by anshulr** [comment]
Any Updates on this ?
