### ISSUE TITLE
Compile Error: r.hp.SetHosts undefined

### ISSUE THREAD

**Issue by ychen11** [gocql/gocql#865]
go version: 1.7.4 Linux/amd64

I imported gocql, and tried to compile my project, it threw the compile error:
```
../vendor/github.com/gocql/gocql/policies.go:402: r.hp.SetHosts undefined (type hostpool.HostPool has no field or method SetHosts)
```

Not just line 402, but also 425 and 444

**Comment by vrischmann** [comment]
You probably need to update your vendored copy of `github.com/hailocab/go-hostpool`

**Comment by ychen11** [comment]
@vrischmann I tried the latest bitly/go-hostpool and also hailocab/go-hostpool.
Same error, could you please post the so-called updated hailocab/go-hostpool?

**Comment by ychen11** [comment]
Here is my folder directory:
```
vendor/github.com/gocql/gocql/
vendor/github.com/hailocab/go-hostpool/
```
I checked the go-hostpool, it has an interface HostPool, and also HostPool has SetHosts method.
BUT: It throws the error I mentioned on the top, is there anything wrong?

**Comment by vrischmann** [comment]
If that's the case I would try to delete your `$GOPATH/pkg` directory, or `$GOPATH/pkg/path/to/your/project` directory if you don't want to remove everything. Then try to recompile your project.

**Comment by ychen11** [comment]
@vrischmann Thanks, that works.
