### ISSUE TITLE
DNS request timeout appears skip moving on to next node and returns nil session

### ISSUE THREAD

**Issue by bgreezy** [gocql/gocql#873]
We use an internal DNS server, but as you can see from the picture when it was misconfigured to go out to Google DNS at 8.8.8.8, the gocql connector couldn't resolve the domain name and it didn't go on to any other node, it just returned a nil session which crashed the program, I put in a piece of code to continue trying to re-establish the session to force it to use a different node, but I figured this was a fix that could be incorporated into the gocql package itself. Here is some code that maybe could generate the error again if you correctly create a domain that could be resolved and a domain that couldn't be resolved on your DNS server. 

`var cluster *gocql.ClusterConfig`
`cluster = gocql.NewCluster("domainthatdoesexist.mynetwork","domainthatdoesntexist.mynetwork")`
`session, err := cluster.CreateSession()`

![screen shot 2017-03-10 at 1 48 52 pm](https://cloud.githubusercontent.com/assets/14946747/23808623/80f21aaa-0598-11e7-933a-b6a7013bcb61.png)

**Comment by leighmcculloch** [comment]
I'm seeing the same behavior. If one of the my nodes drops off DNS inconveniently around the time I'm creating a new session, I get:

```
gocql: unable to create session: lookup [hostname]: no such host
```

For consistency with the Java library it should treat an inability to lookup like a timeout connecting to the host and move on to other nodes. This happens regardless of the consistency value I provide, so even if I provide `gocql.One` it still happens.

**Comment by Zariel** [comment]
Here we should ensure that we can connect to at least 1 of the supplied hosts, we will discover the rest later.
