### ISSUE TITLE
retry does not work if the request fails

### ISSUE THREAD

**Issue by zhixinwen** [gocql/gocql#893]
In queryExecutor:executeQuery
```
for hostResponse := hostIter(); hostResponse != nil; hostResponse = hostIter() {
                    ###......
		iter = qry.execute(conn)
                ......
}
```
The loop would try the next host until any of the host works, but if
`qry.execute(conn)`
times out due to network issue, the rest of the retries would not work. The qry.context has used all of the time in the first call.

Overall, if the request fails on "context deadline exceeds" err, then the rest of the retry would return immediately without doing anything. Since retry mainly works for network issue, retry in gocql is breaking.

**Comment by Zariel** [comment]
This is #812

**Comment by zhixinwen** [comment]
Close issue due to duplicate
