### ISSUE TITLE
Fetching records from Cassandra table in realtime using PageState

### ISSUE THREAD

**Issue by akshaydeo** [gocql/gocql#900]
I am writing a small ETL system in Golang, which involves writing an extractor for Cassandra. I am using gocql (https://github.com/gocql/gocql) as Cassandra driver. 

**Problem Statement**

The problem statement I am trying to solve is, to fetch batch of records from a predefined table in cassandra. Along with that, I want to keep record of till what I have read the records, so when there are newer records, I'll use the last stored state and resume reading the records.

**Implementation details**

Steps I am following:

1. My library creates a metadata table in the cassandra to save the state of the page.
2. In the start, it fetches the current state of the page saved in the metadata table. 
3. Then the library fires a query : 

        iter = c.cassandra.GetSession().Query(c.getQuery()).PageState([]byte(c.LastPageState)).PageSize(c.RecordLimit).Iter()

In a gist, this fires `SELECT * from %s ALLOW FILTERING` with the page state I get from the iterator and page size that is defined as batch size in confog.
4. Then, it iterates through the result set and push the records one by one on a channel.
5. At the end, it stores the latest 
         
    c.LastPageState = string(iter.PageState())
    c.savePageState(utils.Base64([]byte(c.LastPageState)))
6. Go To step 3 after a certain delay

**Passing test case**

1. I add 100 records into a table in Cassandra
2. Then I start my extractor, it fetches all the 100 records in a batch of 10 or even in odd number batches without any duplicates.

Table definition:
    
    err = c.Exec("CREATE TABLE test1 (data int, time_added timestamp, PRIMARY KEY(data, time_added)) WITH CLUSTERING ORDER BY (time_added ASC)")

Data I add:

    for i := 0; i < ENTRY_COUNT; i++ {
			err = c.Exec("INSERT INTO test1 (data, time_added) VALUES (?,?)", i, time.Now())
			Expect(err).NotTo(HaveOccurred())
		}

**Failing test case**
1. I add 100 records as described above.
2. Then I fetch them back as described above.
3. Then I again add 100 new records.
4. Now it could just extract next 2 records and keeps on getting 0 records for next select query.

Let me know if something is not clear from the question, I would be happy to amend it in whichever way is required

**Comment by akshaydeo** [comment]
Source code for extractor and test cases
https://gist.github.com/akshaydeo/65dacbb8276e0645715469ada4a82078

**Comment by ColDog** [comment]
We are also having trouble with GoCQL page state. We are getting inconsistent return values with page state and cannot reliably page through results. We send the page state through our api base64 encoded and return it to the backend. The paging only works around 80% of the time however.

**Comment by Zariel** [comment]
There shouldnt be anything odd going on in the driver, the value is returned just like a query result which is passed out. PageState is only valid for an identical query and values, are you sure values or columns arnt changing?
