### ISSUE TITLE
unexpected authenticator "com.datastax.bdp.cassandra.auth.DseAuthenticator"

### ISSUE THREAD

**Issue by gmflau** [gocql/gocql#909]
I am using gocql with my DataStax Enterprise 5.1 release and I ran into this "unexpected authenticator "com.datastax.bdp.cassandra.auth.DseAuthenticator" issue.  When I reviewed the code, it looks like DseAuthenticator is one of the supported authenticators -
 https://github.com/gocql/gocql/blob/05df4896cf271375039b0645117594e861bde0d9/conn.go#L31 .

Is there anyone can verify this?  Thanks!

**Comment by penberg** [comment]
@gmflau Are you sure you were using an up-to-date version? The issue was fixed in https://github.com/gocql/gocql/issues/882, and reading the code, it should work fine.
