### ISSUE TITLE
Is there any plan for implementing a DCAwareRoundRobinPolicy?

### ISSUE THREAD

**Issue by freedom1989** [gocql/gocql#913]
I am trying to build a multi-datacenter Cassandra cluster. According to the [guide(procedure 1)](http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsAddDCToCluster.html), it asks me to use `DCAwareRoundRobinPolicy`. 

the `DCAwareRoundRobinPolicy` will try to query the hosts within the local datacenter. if no available hosts in local datacenter, the client will query remote hosts in remote datacenter.

my goal is to make sure that the clients only connect to the hosts in the existing datacenter before the new datacenter is ready.

I didn't find `DCAwareRoundRobinPolicy` in gocql implementation. so is there any plan to implement it? or is there any alternative solution that I can achieve my goal?

**Comment by didip** [comment]
I happen to need this feature as well

**Comment by freedom1989** [comment]
I found an alternative solution instead of `DCAwareRoundRobinPolicy`:    
```
cluster.HostFilter = gocql.DataCentreHostFilter("local_datacenter_name")
```
this ensures that the request goes to the datacenter you specified.    

although, an implementation of `DCAwareRoundRobinPolicy` is better, I think.

**Comment by Tigraine** [comment]
I just stumbled over this myself.. I was expecting much better latencies but found that my nodes in europe still connected to the US C* nodes and incurred an absurd amount of latency

**Comment by Tigraine** [comment]
Thanks @freedom1989 - I implemented a CloudSnitch like functionality in my client to detect the local DC and now my latencies went from ~200ms to around 10ms ..

**Comment by zaddok** [comment]
Where is the documentation for how to use the  DCAwareRoundRobin policy?

**Comment by Zariel** [comment]
https://godoc.org/github.com/gocql/gocql#DCAwareRoundRobinPolicy which can be set in the poolconfig in the cluster config https://godoc.org/github.com/gocql/gocql#ClusterConfig
