### ISSUE TITLE
'no response received from cassandra [...]' when modifying the schema

### ISSUE THREAD

**Issue by dsmontoya** [gocql/gocql#914]
I intermittently get `gocql: no response received from cassandra within timeout period` when use... 
``` golang
session.Query(query).Exec()
```
to modify the schema.

It can be reproduced by running the following docker-compose:
```
git clone https://github.com/dsmontoya/issues.git && cd issues/gocql/no-response/
docker-compose up --build
```

Cassandra Version: 3.0.13

**Comment by CodingMinds** [comment]
I'd say this is more an Cassandra than an gocql thing.
I guess creating a keyspace is really specific task in your application so maybe it's a valid solution to increase timeout for this specific query.

Something like
```golang
const cCBootstrapTimeout time.Duration = 3 * time.Second
const cCDefaultTimeout time.Duration = 600000000 * time.Nanosecond // 600ms from https://github.com/gocql/gocql/blob/master/cluster.go#L48

// [...]
cluster.Timeout = cCBootstrapTimeout
sessionKeyspace, err := cluster.CreateSession()
if err != nil {
  log.Fatalf("Error creating Cassandra session: %s", err)
}
defer sessionKeyspace.Close()
log.Println("Cassandra session created")
err = sessionKeyspace.Query(`CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1}  AND durable_writes = true`).Exec()
if err != nil {
  log.Fatalf("Error creating Cassandra keyspace: %s", err)
}
log.Println("Keyspace 'ks' created")

// Set default timeout
cluster.Timeout = cCDefaultTimeout
```

See also https://stackoverflow.com/a/31896970/3824339

**Comment by Zariel** [comment]
We explicitly set the timeout when doing keyspace creation to be massive when running tests in Travis as I have personally seen this take a very long time. The driver will also wait for schema agreement between the nodes, but I'm not sure thats counted for the timeout.
