### ISSUE TITLE
it is different between production and development in count  execution,why?

### ISSUE THREAD

**Issue by sunvim** [gocql/gocql#919]
cql = "select count(id) from dsf_deal where id = 'web_static' "
	if whereCql != "" {
		cql = cql + whereCql
	}
	cql = cql + limitSql
	log.Infof("cql[%s]\n", cql)
	cntIter := session.Query(cql).Iter()

	for cntIter.Scan(&totalNums) {
		log.Info(totalNums)
		upsRet.TotalNums = totalNums
	}
	defer cntIter.Close()

the above code work well in development, but bad in production, the value of the variable "totalNums" is nil, then totalNUms' s value is 0, actually the right value is 275,why?

**Comment by Zariel** [comment]
Check the error on the iterator which is returned from `Close()`. Please provide more reproduction steps.
