### ISSUE TITLE
Why hostIter() is called twice on every loop inside queryExecutor?

### ISSUE THREAD

**Issue by didip** [gocql/gocql#924]
This is the line: https://github.com/gocql/gocql/blob/master/query_executor.go#L25

The code is introduced in this commit: https://github.com/gocql/gocql/commit/a04d2a5e3f4076edc106347f1624809c0733a1a1

If I am reading the code correctly, if I have an even number for Replication Factor (i.e. 2), then it's possible to land on the same host again in the next iteration.

Am I thinking about this correctly?

**Comment by Zariel** [comment]
What do you mean? It's up to the host selection policy to return hosts, each returned host will be attempted.
