### ISSUE TITLE
On multi DC, with LOCAL_ONE consistency level on read, gocql frequently returns empty results.

### ISSUE THREAD

**Issue by didip** [gocql/gocql#925]
The setup:

* 2 DC

* gocql opens `LOCAL_ONE` session to its own local DC. The cluster config also uses `gocql.DataCentreHostFilter` to pick up the local nodes.

* The query is very simple: `SELECT * FROM table where primary_key='example'`

I cannot replicate this using Python driver or cqlsh, but gocql will frequently returns empty results very quickly (within 0.2 seconds).

**Comment by Zariel** [comment]
Can you show some code which executes the query please.

**Comment by didip** [comment]
After looking at it more, the problem exists somewhere else.

Sorry for wasting your time.
