### ISSUE TITLE
Not able to connect to Cassandra with latest available version. 

### ISSUE THREAD

**Issue by akhiltiwari16** [gocql/gocql#927]
Hello, 

I did latest checkout and started facing connection issues with cassandra. Though it works fine with older version (the one that I checked out around 6 months ago). 

Error is: 

```
2017/06/28 11:00:28 gocql: unable to dial control conn <ip_address>: gocql: no response to connection startup within timeout
2017/06/28 11:00:28 [Directory Listing]: Could not connect to cassandra cluster: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout
```

Cassandra: 3.9
Go: 1.7 .3

**Comment by Zariel** [comment]
Im unable to reproduce this with 3.9 locally, can you post the cluster config and describe the cluster config
