### ISSUE TITLE
gocql failed to connect to Cassandra in Travis CI

### ISSUE THREAD

**Issue by hsluoyz** [gocql/gocql#929]
https://travis-ci.org/casbin/cassandra-adapter/jobs/248833341

**Comment by Zariel** [comment]
Could you try with the latest commit please.

**Comment by hsluoyz** [comment]
Hi @Zariel ,

The error remains the same: https://travis-ci.org/casbin/cassandra-adapter/jobs/248833341

**Comment by Zariel** [comment]
I was able to reproduce locally, this seems to only affect 2.0.x and I no longer remember what the changes to the system tables were between these versions so I hope this is now fixed. Can you try and reproduce and confirm. And FYI, I would update the version of Cassandra you test against :)

**Comment by hsluoyz** [comment]
Hi @Zariel ,

The error has been fixed when I restart the build:)

My testbed is Travis CI. So the version of Cassandra is not controlled by me. I didn't see its version in the printed log of Travis page either. Thanks for your support!
