### ISSUE TITLE
More than 1 connection being created to a cassandra server on creating a session.

### ISSUE THREAD

**Issue by nupurbansal8** [gocql/gocql#933]
When creating a cassandra connection in go, I am using the following connection variables:
     cluster.Consistency = gocql.LocalOne
The cluster right now consists of only one node.

On creating a session, I check connections through netstat command and see that 3 connections have been created to the cassandra server.
Why are there 3 connections instead of 1 ??

**Comment by Zariel** [comment]
LocalOne is the consistency, the driver will use NumConns * NumberOfHosts + 1 connections
