### ISSUE TITLE
Same query taking too long on consequent hits

### ISSUE THREAD

**Issue by nupurbansal8** [gocql/gocql#949]
For the same query, I am getting variable execution time on a cassandra cluster.
The variation is very vast. For 1 hit it is taking 3ms while for next hit it is taking 42ms.

What can be the possible reason ?

**Comment by Zariel** [comment]
Network issues? Garbage collection in Go? Garbage collection in Java? Disk contention in cassandra? Cassandra process suspended?  Cassandra cpu overloaded? Compaction in Cassandra? TCP message buffering? Cassandra threadpools busy?
