### ISSUE TITLE
Support tracing

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#951]
Placeholder issue to support tracing via opentracing

**Comment by Multiply** [comment]
Is this on the roadmap, or something you'd consider taking PRs for?

**Comment by Zariel** [comment]
Yes

**Comment by nightlyone** [comment]
The people behind opentracing and opencensus now work together on a [new, unified open telemetry standard](https://opentelemetry.io/about/) and stated they will obsolete opentracing as well as opencensus when that work is done. 

Given those new develeopments, I would suggest NOT adding either of opentracing and opencensus to gocql and instead keep the APIs open enough to implement it outside of this package to lower future maintenance efforts.

**Comment by martin-sucha** [comment]
Closing this issue.

Opentracing integration can be implemented outside the main gocql package with the observer interfaces already  (https://github.com/gocql/gocql/pull/1466#issuecomment-663908807) and there are many different integrations that could be made.

Those may be in a separate gocql-contrib repo (if such repo will be created).
