### ISSUE TITLE
Why is multiple IPs sent as arguments to NewCluster method in the example?

### ISSUE THREAD

**Issue by lazercorn** [gocql/gocql#962]
The docs says "The supplied hosts are used to initially connect to the cluster then the rest of the ring will be automatically discovered."

so technically one IP is enough, but why is multiple IPs sent as arguments to NewCluster method in the example?

`cluster := gocql.NewCluster("192.168.1.1", "192.168.1.2", "192.168.1.3")
`

**Comment by kf6nux** [comment]
A couple reasons:

1. Nodes go down, and we'd like the ability to connect to the cluster even if one of the nodes is down.
2. If you are connecting via some proxy/port-forwarder and don't have access to the nodes' broadcast addresses, then you'd want to list all the proxies/port-forwarders there and use:
```golang
	cluster.DisableInitialHostLookup = true
	cluster.IgnorePeerAddr = true
```
