### ISSUE TITLE
Read performance difference between GoCQL and PHP drivers

### ISSUE THREAD

**Issue by ankit2806** [gocql/gocql#965]
Cassandra Version: 2.1

GoCQL Version: 1.7

Task Implemented:
We have 2 datacenters with 5 nodes on each DC. We have alse set the DCAwareRoundRobinPolicy for both the PHP and GoCQL drivers. We are reading data from the cassandra database using SELECT statement based on the WHERE condition. The expected result will be a single row data fetched from millions of rows.

Expected Result:
The performance of the GoCQL driver is better than the PHP driver.

Actual Result:
The PHP driver was executing the statement under 10ms and the same statement is takinng 25ms with GoCQL driver. It appears GoCQL is slower.

Is there any solution to improve the performance of GoCQL driver?

**Comment by Zariel** [comment]
What do you reasonably expect me to be able to do? There is nothing in this ticket which has a reproducible step, nor does it describe or provide any information about the nature of the app running queries (or Cassandra for that matter). I can't just magically find and fix issues in the driver on the premiss that it 'is slower than X'.

I suggest you do some profiling of your application, figure out where the latency is coming from and then decide if there is likely to be an issue in gocql and not elsewhere, a good place to start is here [0].

Are you sure that the environment is the same for go and php versions? Are there more queries/second in the go version?

[0] https://blog.golang.org/profiling-go-programs

**Comment by penberg** [comment]
The PHP driver is actually a small wrapper on top of the C++ driver so I fully expect it to be fast. But as @Zariel points out, there's nothing actionable in this issue and the best course of action is to profile your application (together with gocql driver) to see what the bottleneck is.
