### ISSUE TITLE
regression:

### ISSUE THREAD

**Issue by mrwonko** [gocql/gocql#968]
### What version of Cassandra are you using?

2.1.13

### What version of Gocql are you using?

066e974c166d59aa2d3aee45b234d8c21c631180

### What did you do?

For testing purposes we have a docker container of Cassandra. Using Docker for Mac I forward its port 9042 to my host to make it locally accessible. I then try to connect to it from gocql using localhost:9042.

### What did you expect to see?

Before 77431609f517cb41ee9afdcdd373561c4d935316 I was able to connect to Cassandra and make requests.

### What did you see instead?

I now get this error on `ClusterConfig.CreateSession()`:

> no connections were made when creating the session

It works when I set DisableInitialHostLookup, but I'm not sure if that's a thing I should do?

---

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`

  I can't get nodetool to connect, depending on the port I use I get either `EOFException: 'null'` or `SocketTimeoutException: 'Read timed out'`
- output of `SELECT peer, rpc_address FROM system.peers`

      cassandra@cqlsh> select peer, rpc_address from system.peers ;
      
       peer | data_center | host_id | preferred_ip | rack | release_version | rpc_address | schema_version | tokens
      ------+-------------+---------+--------------+------+-----------------+-------------+----------------+--------
      
      (0 rows)
- rebuild your application with the `gocql_debug` tag and post the output
  
  > 2017/09/07 14:20:23 gocql: Session.handleNodeUp: ::1:9042
2017/09/07 14:20:25 unable to dial "172.17.0.2": dial tcp 172.17.0.2:9042: i/o timeout
2017/09/07 14:20:25 gocql: Session.handleNodeDown: 172.17.0.2:9042
2017/09/07 14:20:25 gocql: Session.handleNodeUp: 172.17.0.2:9042
2017/09/07 14:20:27 unable to dial "172.17.0.2": dial tcp 172.17.0.2:9042: i/o timeout
2017/09/07 14:20:27 gocql: Session.handleNodeDown: 172.17.0.2:9042

**Comment by Zariel** [comment]
Please see #964

**Comment by Zariel** [comment]
Sorry the issue is #946
