### ISSUE TITLE
float32 only returns 5 decimal places

### ISSUE THREAD

**Issue by robertyoung81** [gocql/gocql#978]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.0

### What version of Gocql are you using?
Latest

### What did you do?
SELECT query on a column of type float

### What did you expect to see?
full precision value: 37.38996124267578

### What did you see instead?
5 decimal precision: 37.38996

---

I queried the same cluster from a node.js application (using cassandra-driver), and it returned the value with full precision.

**Comment by Zariel** [comment]
float column in cassandra is a 32 bit float, change your column type to double.
