### ISSUE TITLE
Gocql timeout when the startIndex is higher. But when the timeout is increased we get back result.

### ISSUE THREAD

**Issue by PratikshyaMishra** [gocql/gocql#981]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
cqlsh 5.0.1 | Cassandra 3.0.11.1485 | DSE 5.0.5 | CQL spec 3.4.0 | Native protocol v4

### What version of Gocql are you using?
did git pull for the commit id commit 4e73f1fe43d75fb706c292f295121f9eada14e90

### What did you do?
The tables in our database have over 100k records. We queried the table to get records with a higher start index (startIndex = 20000).

### What did you expect to see?
We expected to see some result set to be returned. 

### What did you see instead?
Gocql time out error
---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
Can you debug this more your side? You should see timeouts in the cassandra logs for long queries, if not enable that feature. There is nothing in this ticket which is actionable or indicates an issue with the driver and is significantly more likely to be an issue with the cluster or the data distribution.

**Comment by PratikshyaMishra** [comment]
Hi Chris,

I debugged it and could not find any Cassandra log that was related to this
error. The clash query with higher startIndex is working fine. I also used
the python Cassandra library and was able to fetch records with higher
startIndex within seconds. But with goCQl I am seeing this error.

Thanks
Pratikshya

**Comment by Zariel** [comment]
In that case can you share a reproducing schema + query?

**Comment by PratikshyaMishra** [comment]
**Schema:**
CREATE TABLE staff (
    id text PRIMARY KEY,
    "externalId" text,
    meta frozen<meta>,
    "staffInfo" frozen<staffInfo>,
    "comapnyId" text,
    solr_query text,
    subscriptions list<text>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX staff_solr_query_index ON staff (solr_query) USING 'com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex';

CREATE TYPE staffInfo (
    "staffName" text,
    "staffId" text,
    email text
);

CREATE TYPE meta (
    "staffType" text,
    created text,
    "lastModified" text,
    location text
);

**QUERY:**
SELECT "id", "meta", "staffInfo", "comapnyId", "subscriptions", "externalId"  FROM staff where SOLR_QUERY = '{"q":"*:*", "start": 15000}' LIMIT 100;

**Comment by Zariel** [comment]
I don't have access to DSE so I can't help, does it reproduce with normal tables?

**Comment by martin-sucha** [comment]
There is no actionable information in this issue. I don't have access to DSE either. This issue is old, so I'm closing it. If you still can reproduce with the latest gocql version, please reopen and provide detailed steps to reproduce. One thing that would help would be to capture network traffic between client and server and compare what is different between Python driver and gocql.
