### ISSUE TITLE
Issue with LWT -- "if not exists"

### ISSUE THREAD

**Issue by kkrishna** [gocql/gocql#995]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

[cqlsh 5.0.1 | Cassandra 2.1.15.1423 | CQL spec 3.2.1 | Native protocol v3]
one Cassandra cluster with 3 nodes.

### What did you do?
We are using the cassandra feature of `IF NOT EXIST` clause during the insertion of the row. When multiple goroutines are trying to insert, we are observing that often multiple goroutines are succeeding at a time while ONLY one should have succeeded. 
Sample code and log are attached.
[lwtsample.gz](https://github.com/gocql/gocql/files/1412878/lwtsample.gz)
schema for lwt is as follows:
```
desc testlock
CREATE KEYSPACE testlock WITH replication =
{'class': 'NetworkTopologyStrategy', 'USC1': '3'}
AND durable_writes = true;
CREATE TABLE testlock.paas_lock (
tenant text,
namespace text,
pool text,
created timestamp,
owner text,
uuid text,
PRIMARY KEY ((tenant, namespace, pool))) 
```

### What did you see instead?
Here is the log from sample code. you'd notice that goroutine 6 and 5 both got lock once it was released by 27. Only one should have succeeded. Have anyone faced this before; Is there anything amiss in code? :

```
go run main.go 
2017/10/16 11:00:31 CassandraDB: endpoint(10.180.52.46:9042), keyspace(testlock)
2017/10/16 11:00:31 CassandraDB: timeout(600ms), retry(&{NumRetries:3})
2017/10/16 11:00:38 lockobj: &{Tenant:test Ns:mkr Pool:PATCH_POLICY Owner: Uuid:27 Created:2017-10-16 11:00:35.13594583 -0700 PDT Success:false}
2017/10/16 11:00:38 lock: &{Tenant: Ns: Pool: Owner: Uuid: Created:0001-01-01 00:00:00 +0000 UTC Success:false}
2017/10/16 11:00:38 got lock 27
2017/10/16 11:00:38 released lock 27
2017/10/16 11:00:39 lockobj: &{Tenant:test Ns:mkr Pool:PATCH_POLICY Owner: Uuid:6 Created:2017-10-16 11:00:35.134512416 -0700 PDT Success:false}
2017/10/16 11:00:39 lock: &{Tenant: Ns: Pool: Owner: Uuid: Created:0001-01-01 00:00:00 +0000 UTC Success:false}
2017/10/16 11:00:39 got lock 6
2017/10/16 11:00:39 lockobj: &{Tenant:test Ns:mkr Pool:PATCH_POLICY Owner: Uuid:20 Created:2017-10-16 11:00:35.135152313 -0700 PDT Success:false}
2017/10/16 11:00:39 lock: &{Tenant: Ns: Pool: Owner: Uuid: Created:0001-01-01 00:00:00 +0000 UTC Success:false}
2017/10/16 11:00:39 lockobj: &{Tenant:test Ns:mkr Pool:PATCH_POLICY Owner: Uuid:5 Created:2017-10-16 11:00:35.13465921 -0700 PDT Success:false}
2017/10/16 11:00:39 lock: &{Tenant: Ns: Pool: Owner: Uuid: Created:0001-01-01 00:00:00 +0000 UTC Success:false}
2017/10/16 11:00:39 got lock 5
```

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment]
Is this the issue that is being discussed on #265 ? My understanding is that if Cassandra doesn't support client side timestamps with LWT then it should either ignore them or error out, this could be a Cassandra bug but we can work around it.

**Comment by kkrishna** [comment]
@Zariel  Not sure if this is same as #265 related to client side timestamp. Will try out #996 fix. Any debugging suggestions, in case if issue still exists?

**Comment by Zariel** [comment]
Are you running into something like http://datanerds.io/post/cassandra-no-row-consistency/? I verified locally that doing LWT works correctly from the driver standpoint and #996 does not cause or solve any issues.

**Comment by Zariel** [comment]
I can't replicate any issue by hammering different LWT queries, closing.
